import type { FeelingsContext } from '../card-feelings-extended'

// Cups suit: Ace through King (14 cards)
export const CUPS: Record<string, FeelingsContext> = {
  'ace-of-cups': {
    uprightLong: `The Ace of Cups as feelings is one of the most tender cards in the deck. It describes a heart that has only recently begun to open, often surprising the person it belongs to. They are not yet performing love in any practised way — what they feel is rawer and less defended than that. A spring has been released in them, and it is running toward you with something close to wonder.\n\nWhen this card surfaces in a feelings reading, the other person often feels a quality of newness about you that they cannot quite explain in words. You may be the first person in some time who has reached the soft layer beneath their composure. There is admiration, but it is the affectionate, slightly disbelieving kind, not the calculating kind. They may not have told you everything they feel — partly because the feelings themselves are still unfolding, partly because to name them too soon would risk frightening the thing itself. But what is happening internally is real, and it is unmistakably moving toward you rather than away.\n\nThis is also the card of overflowing capacity. The querent may sense, accurately, that the other person has a great deal of love available — for them, but also more broadly. There is no hardness here, no withholding, no calculation about whether you have earned access. The Ace of Cups gives because giving is what an open heart does. The most honourable response is to receive without immediately interrogating what it means or where it is going. Some feelings need a season of being held lightly before they can declare themselves.`,
    reversedLong: `The Ace of Cups reversed as feelings describes a heart that wants to open but currently cannot. The capacity for love is there — the cup itself is intact — but it has been turned over, and what would otherwise flow toward you is being held back. This is rarely a conscious cruelty. Far more often it is the work of old protections still doing their job long after the original danger has passed, or grief that has not yet finished its work in them.\n\nThe person you are asking about may genuinely care for you and still be unable to let that caring surface in ways you can feel. They may withdraw at the exact moments you most need them to step forward. They may speak warmly when prompted and then disappear into themselves for days. The signal is mixed because the inner state is mixed: feeling is present, but the channel through which it would reach you is closed. Sometimes they themselves do not quite know what is in the cup, only that something prevents them from offering it.\n\nThere is also a possibility that what once flowed has temporarily run dry. Burnout, depression, an unresolved loss elsewhere in their life, or simple emotional exhaustion can all produce this reversal without indicating anything specific about you. The card asks you to resist the temptation to take the closure personally or to flood them with feeling in the hope of forcing a response. Neither approach tends to work. The vessel rights itself when it is ready, and you cannot accelerate that process by reaching into it. Holding your own ground steadily, without either pursuing or punishing, is the only response that respects what is actually happening.`,
    howTheyFeel: `Right now they feel something that has caught them slightly off guard. There is genuine tenderness when they think of you, and the tenderness arrives before the analysis — which is significant, because it means the feeling is preceding the story they will eventually tell themselves about it. They may not have words yet, and pressing them for words may push the feeling back underground.\n\nThere is also a quality of hope here that they may not have felt in some time. You represent, to them, a possibility they had quietly stopped expecting. That is a lot of weight for a new connection to carry, so they may protect it by going quiet at intervals — not because they have changed their mind, but because they are trying not to overwhelm what is still delicate. Receive this for what it is rather than asking it to be more declarative than it can yet be. The signal is strong even when the volume is low.`,
    feelingsFaqs: [
      {
        q: 'What does the Ace of Cups mean as someone\'s feelings for me?',
        a: 'The Ace of Cups as feelings describes a heart freshly open toward you, often in ways that have surprised the person themselves. They feel tenderness, hope, and a quality of newness they cannot quite explain. The card suggests genuine emotional movement rather than infatuation or fantasy; what they feel has the soft, unguarded quality of a spring just beginning to flow. They may not have said much yet because the feelings themselves are still unfolding, but the direction of those feelings is clearly toward you. This is one of the more sincere cards to draw in a feelings question.',
      },
      {
        q: 'Is the Ace of Cups a yes for love?',
        a: 'Yes. The Ace of Cups is among the strongest affirmative cards for love in the deck. It signals emotional opening, the beginning of a heart-led connection, and the genuine availability of feeling on the other side. It does not guarantee a particular outcome — no card does — but it tells you the conditions for love are present and active. If you are asking whether someone has real feelings for you, whether a new connection has emotional substance, or whether a relationship has room to deepen, the Ace of Cups answers with quiet, sincere yes.',
      },
      {
        q: 'What does the Ace of Cups reversed mean as feelings?',
        a: 'The Ace of Cups reversed as feelings describes feelings that exist but cannot currently reach you. The other person\'s heart is not closed permanently — the capacity is intact — but it is turned over, blocked by old protections, grief, exhaustion, or unprocessed material from elsewhere in their life. They may genuinely care and still be unable to express that caring in ways you can receive. The reversal is rarely a verdict that nothing is there; it is a diagnosis that the channel is currently obstructed. The honest response is patience without pursuit, and steady self-respect rather than escalation.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Ace of Cups, the feelings run deeper than passing interest. This is not a card of curiosity or attraction alone; it is a card of genuine emotional opening. What they feel may still be inarticulate, and they may not yet know where it is going, but the caring itself is real. The Ace of Cups very rarely accompanies a casual or surface-level feeling. If this card has come up for them, you can trust that whatever is happening internally has substance, even if external behaviour has not yet caught up with what the heart already knows.',
      },
    ],
  },
  'two-of-cups': {
    uprightLong: `The Two of Cups as feelings is the card of genuine mutual recognition. The person you are asking about feels met by you in a way that is rare in their experience. There is a quality of equality to what they feel — neither of you towering over the other, neither chasing nor being chased — and that balance is itself part of why the feeling is so distinct from previous attachments. They do not just want you; they want what happens in the space between you.\n\nThis card carries a particular kind of sincerity. The other person is not playing a role, not performing romance, not strategically managing the connection. What they feel is the warmth of being seen and the relief of being able to see in return without flinching. They may use the word soulmate or kindred or simply find themselves saying out loud that this feels different. Even if they have not said any of this to you, they are saying it to themselves.\n\nThere is also a quality of present-moment commitment in this card. The Two of Cups is not about distant future fantasies; it is about the live exchange happening right now. They feel safe enough with you to drop some of their habitual defences. They notice their own behaviour around you and find that they like who they are in your presence. Whatever its future shape, the current feeling between you has the unmistakable character of a meeting between equals who actually want to meet. That is far less common than the romantic imagination suggests, and it is worth recognising for what it is.`,
    reversedLong: `The Two of Cups reversed as feelings describes a connection in which the mutuality has slipped. The other person may still feel something, but the symmetry that gave the bond its particular quality has tilted. One of you is now pouring more than the other; one of you is reaching while the other has quietly withdrawn. They may be aware of the imbalance and uncertain how to address it, or they may be participating in it without yet noticing what has happened.\n\nThere is sometimes an unspoken disappointment underneath this reversal. Something you said or did, or something they expected and did not receive, has changed the temperature without being named. They may still care, but the caring is now braided with hesitation, hurt, or quiet resentment that they have not yet brought into the open. Alternatively, they may have discovered that their own values, rhythms, or capacities do not match yours as closely as the initial attraction suggested, and the feeling is cooling not from antagonism but from honest recalibration.\n\nIn other readings this card reversed can describe a connection that was never quite as mutual as it appeared. The chemistry was real, but on closer acquaintance one of you is more invested than the other, and the gap is becoming visible. They may feel guilty about not matching your level of feeling, which can make them less rather than more available — guilt tends to produce avoidance rather than honesty. The card asks you to read the situation without flattering yourself or yielding to despair. Mutuality cannot be willed into existence; it can only be acknowledged where it actually is, or its absence honestly named.`,
    howTheyFeel: `Right now they feel the rare sensation of recognition. You strike them as someone they could be honest with, which is not a small thing in their world. When they are with you, something about their usual self-presentation softens, and they find themselves more present than they typically allow.\n\nThere is also a felt sense of safety that they may not be naming out loud. You do not require them to perform; you do not seem to want a version of them that is not actually them. That gives the connection an unusually clean quality. Whatever else they may be working through privately, when they think of you the predominant feeling is warmth — not the volatile, anxious warmth of new infatuation, but the steadier warmth of having met someone who fits. They are not always going to know what to do with that. Give them room to discover the connection at their own pace rather than asking it to declare itself prematurely.`,
    feelingsFaqs: [
      {
        q: 'What does the Two of Cups mean as someone\'s feelings for me?',
        a: 'The Two of Cups as feelings describes a sense of genuine mutual recognition. They feel met by you in a way that stands out from previous connections, and there is a quality of equality and safety to the bond that they have not always experienced. They are not playing a role; what they feel is sincere and live in the present rather than projected into fantasy. Even if they have not articulated it to you, internally they are noting that this connection feels different — more honest, more balanced, more like meeting someone rather than chasing or being chased.',
      },
      {
        q: 'Is the Two of Cups a yes for love?',
        a: 'Yes, and it is one of the most affirmative cards in the deck for a love question. The Two of Cups specifically signals mutuality — not one-sided feeling, not unrequited attraction, but a genuine meeting between two people who are drawn to each other on equal terms. It tells you the chemistry is real, the recognition is shared, and the foundation for a deeper relationship is present. Pulling this card in a love reading is usually an indication that what you are sensing on the other side is actually there, not imagined.',
      },
      {
        q: 'What does the Two of Cups reversed mean as feelings?',
        a: 'The Two of Cups reversed as feelings indicates that the mutuality has slipped. The connection may still hold real feeling, but the symmetry has tilted — one of you is investing more, or an unspoken disappointment has cooled the temperature without being named. Sometimes the reversal describes a connection that was never as mutual as it appeared, and the gap is now becoming visible. They may still care, but the caring is now braided with hesitation or quiet guilt. The card asks for an honest reading of where the balance actually lies rather than insisting on the symmetry the bond once had.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Two of Cups, this is far more than interest. They feel a level of recognition and safety with you that they rarely experience, and the caring is genuine and reciprocal in nature. This is one of the few cards that specifically rules out the lopsided dynamic of surface attraction or one-sided feeling; the Two of Cups is by definition about mutuality. They care, and what they feel runs deeper than the bare attraction that would show up under cards like the Knight of Cups or Page of Cups. Trust the depth this card describes.',
      },
    ],
  },
  'three-of-cups': {
    uprightLong: `The Three of Cups as feelings carries a particular warmth that is often misread as superficial. The person you are asking about feels genuinely delighted by you — but the delight is woven through with friendship, ease, and the company of others. They associate you with joy. When they think of you, they think of the times you laughed together, the gatherings where you both came alive, the conversations that felt like celebration rather than effort. That is no small thing. In their inner landscape you are filed under things that make life lighter, and that is a category many people lose touch with in adulthood.\n\nThere is sometimes a softness about whether the feeling is romantic or affectionate that the upright Three of Cups can leave unresolved. They may not yet be sure themselves. What they are sure of is that you are someone they want in their life, someone they want their other people to meet, someone who has already passed the social tests that closed-off people use to keep most others at distance. They have invited you in. Whether that invitation eventually unfolds into something specifically romantic depends on other cards and on what you both want.\n\nWhat is unmistakable is that the feeling is generous and outward-facing. They want to share their life with you in the broader sense — their friends, their celebrations, their good news, their everyday joys. This is not the obsessive, closed-circuit feeling of infatuation; it is the more spacious feeling of wanting to bring you into a bigger world. Many lasting relationships begin in exactly this register. The card is gentler than the more dramatic love cards, but in its quiet way it points to genuine affection and the early forms of belonging.`,
    reversedLong: `The Three of Cups reversed as feelings introduces social complication into the picture. Their feelings for you may be real, but the surrounding context has become noisy. Friends, family, or wider community pressures are influencing how they feel — or how they feel allowed to feel — and the result is a kind of static that obscures what would otherwise be straightforward warmth. They are not entirely free with you because they are not entirely free in their own social world.\n\nThis reversal sometimes points to a third party whose presence is altering the dynamic. That third party need not be a romantic rival in any conventional sense; it could be a close friend who disapproves, an ex who has not entirely departed, a family member whose opinion carries weight, or a colleague whose interference has tangled what would otherwise be simpler. The other person feels something for you and feels something for the other relationships pulling at them, and at present they have not been able to integrate the two. The hesitation you may be reading is rarely about you personally.\n\nIn other readings the reversal describes feeling that has thinned through overexposure or social performance. Perhaps the early connection was made in a celebratory setting that did not survive translation into more private, sober encounters. Perhaps drinking culture, group dynamics, or the desire to be liked led one of you to perform a version of yourself that does not match daily reality. They may now feel a quiet uncertainty about whether what they liked is actually there in plainer light. The card asks both of you to test the connection in quieter contexts rather than legislating from the festive version of yourselves.`,
    howTheyFeel: `Right now they feel a warmth toward you that has a sociable, open quality to it. You are someone they are pleased to think of, someone they would happily run into, someone who has already crossed several internal thresholds without having to do anything strategic. When they imagine spending time with you, the image usually involves other people — a meal with friends, a group setting, an event — rather than only the two of you alone.\n\nThat is not a sign of lukewarmness; for them it is a sign of genuine inclusion. The people they bring into their wider life are the people they are letting in properly. You may sometimes wish the feeling were more focused or declarative than it currently is, and over time it may become so. For now, what they feel is the gentle, real affection that lives in shared good times. Receive it as the early form of belonging that it is. Pressing it to be more pointed too early can stiffen what would otherwise unfold naturally.`,
    feelingsFaqs: [
      {
        q: 'What does the Three of Cups mean as someone\'s feelings for me?',
        a: 'The Three of Cups as feelings describes warm, sociable affection. The other person genuinely enjoys you, associates you with joy and celebration, and has begun to include you in their wider social life. The feeling is sincere even if it has not yet declared itself as specifically romantic — they may not be sure themselves, and that uncertainty is honest rather than evasive. What is clear is that you have crossed several internal thresholds and been welcomed into the part of their world reserved for people who lighten their life. Many lasting relationships start in exactly this register.',
      },
      {
        q: 'Is the Three of Cups a yes for love?',
        a: 'Yes, but a gentler and more sociable yes than the more focused love cards. The Three of Cups affirms genuine affection and warm feeling, and it suggests the social conditions for a relationship are favourable — friends and community are likely to support the bond rather than undermine it. It does not always indicate the laser focus of a single-minded romance; it indicates a love supported by a broader life. For a long-term partnership this register is actually a strong sign. For a question about whether something specifically romantic is brewing, watch the surrounding cards for confirmation.',
      },
      {
        q: 'What does the Three of Cups reversed mean as feelings?',
        a: 'The Three of Cups reversed as feelings points to social or third-party complications shaping the connection. Their feelings may be real but currently entangled with the influence of friends, family, or someone else in the picture whose presence is muddying the water. The reversal can also describe a connection forged in festive or performative settings that has not quite translated into quieter daily life. They are not necessarily withholding feeling on purpose; the surrounding noise is making integration difficult. Look at whether the bond holds up in sober, private contexts as well as social ones.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the Three of Cups upright, they care — though the caring has a friendly, inclusive quality rather than the consuming focus of a more intense card. Do not mistake the warmth of this card for surface interest. It indicates someone who has chosen to include you in their genuine life, which is one of the more meaningful forms of caring that exists. The relationship may not feel as feverish as some, but feverishness is not always a marker of depth. The Three of Cups describes affection that tends to mature well over time.',
      },
    ],
  },
  'four-of-cups': {
    uprightLong: `The Four of Cups as feelings is one of the more uncomfortable cards to draw, because it describes a person who is not currently feeling what you might hope they feel — not from active dislike, but from inward absorption. They have turned their attention away from the offer of connection, often without quite realising they have done so. You may be standing in front of them holding something real, and they are looking past it because their gaze is fixed somewhere else: an old wound, a private dissatisfaction, a comparison they cannot quite shake.\n\nThe other person may genuinely register that you are there, may even be intellectually aware that what you offer is valuable, and yet feel nothing in particular when they think of you. This can be especially painful to receive because the absence is not personal in the usual sense; it is a generalised emotional flatness that happens to include you. They are not actively rejecting you. They are not feeling much of anything, and the not-feeling has become so habitual that they have stopped noticing it as a problem.\n\nSometimes this card describes a person caught in nostalgia or comparison — measuring you against a previous love, a fantasy partner, or an idealised version of what should have been by now. The cup being offered is real and good. They are simply not in a state to receive it. Pushing harder or trying to wake them up with grand gestures tends to confirm them in their distance rather than soften it. The card asks for an honest reckoning. Either their attention will turn naturally, in which case the connection is still possible, or it will remain elsewhere, in which case you are being shown something true rather than punished. Either way, more striving on your part will not produce what only their own readiness can.`,
    reversedLong: `The Four of Cups reversed as feelings is gentler, and frequently more hopeful, than the upright version. The figure who had been gazing inward is beginning to look up, and what they see is increasingly likely to include you. The fog of self-absorption is lifting. Apathy that had settled over their emotional life is starting to break apart, and the cup being offered — which had been there all along — is finally registering.\n\nThis often shows up when someone is emerging from a period of emotional withdrawal, depression, overwork, or grief. They have been hard to reach not because they did not care but because they had very little internal energy available for anyone. Reversed, the Four of Cups says the worst of that phase is passing. They are becoming available again. They are starting to notice what is in front of them. Their feelings for you, which may have been muted or invisible, are beginning to surface as the underlying flatness gives way.\n\nIn other readings the reversal points to recognition arriving belatedly. They may suddenly understand what you have been offering, or who you have been to them, in a way they had previously missed. This is not always a triumphant moment; it can be sober. They may feel some regret that they did not see it earlier, some uncertainty about whether the same offer is still on the table. The card asks for a measured, honest response from your side. You are not obliged to wait indefinitely for someone to wake up, but if you have been waiting and this card appears, the waking is happening now. What you do with it depends on what you actually want and what you have left to give.`,
    howTheyFeel: `Right now they feel a kind of flatness that they may not even be naming as flatness. The feelings you might hope they were having are not absent because of anything you have done; they are absent because something in them has gone quiet. They are wrapped up in their own preoccupations, and your offer of connection has been arriving in a room where no one is fully present to receive it.\n\nThis is hard to sit with. The temptation is to read their distance as a verdict and to escalate — more contact, more effort, more attempts to be seen. Almost none of that helps. What this card describes is not solved by being pursued; it tends to be deepened by it. The more honest response is to step back, hold your own life with care, and let them either come up for air on their own or remain where they are. You will know more in time. For now, the kindest reading is that this is information, not punishment. They are not feeling much, and that is the truth of where they are.`,
    feelingsFaqs: [
      {
        q: 'What does the Four of Cups mean as someone\'s feelings for me?',
        a: 'The Four of Cups as feelings describes emotional withdrawal and inward absorption. The other person is not actively rejecting you so much as failing to register what you offer because their attention is turned elsewhere — into nostalgia, dissatisfaction, comparison, or a private flatness they have not addressed. They may know intellectually that you are valuable to them and still feel little of anything when they think of you. The absence is rarely personal in the usual sense; it is a generalised emotional muting that happens to include you. The card asks for honest reading rather than escalation on your part.',
      },
      {
        q: 'Is the Four of Cups a yes for love?',
        a: 'No, generally. The Four of Cups upright signals apathy, distraction, or emotional withdrawal on the part of the person being asked about, which makes it a difficult card for romantic prospects in the short term. It does not pronounce a permanent verdict — the situation can shift, especially if other cards in the reading suggest movement — but on its own it indicates that they are not currently in a state to engage with what you are offering. The most honest reading is to take the no as information about now, not necessarily forever, and to act accordingly.',
      },
      {
        q: 'What does the Four of Cups reversed mean as feelings?',
        a: 'The Four of Cups reversed as feelings is generally hopeful. It indicates that the other person\'s withdrawal is ending. They are beginning to look up from whatever has been absorbing them, and you are increasingly likely to be visible to them again. Sometimes this shows up as someone emerging from depression, grief, or overwork; sometimes as a belated recognition of what they had previously failed to see. The card asks for patience without pursuit. The opening is real but fragile; let it unfold rather than rushing in to capitalise on it. What returns at its own pace tends to stay.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the Four of Cups upright, neither caring nor interest is the dominant note — apathy is. The other person may have cared at some point, may care again later, but right now their emotional attention is elsewhere. Reading this card as either a yes to caring or a no to interest oversimplifies what is actually happening. They are checked out. Until that changes, attempts to determine whether they secretly care will mostly produce frustration. Wait for the picture to clarify rather than projecting feeling into a vacuum. The honest answer for now is that the lights are dim and you cannot read by them.',
      },
    ],
  },
  'five-of-cups': {
    uprightLong: `The Five of Cups as feelings describes a person standing in grief, with their back to whatever good remains. The feelings they are having about you, or about the situation between you, are filtered through loss. They are mourning something — possibly the relationship as it once was, possibly a previous love whose ghost has not departed, possibly an idealised future that has not materialised — and the mourning is occupying so much of their inner field that little else can be felt cleanly.\n\nIt is important not to misread this card as proof that they do not care. Often the grief is precisely about you, or about the version of you and the relationship they had hoped for. Disappointment lives close to love in the emotional anatomy; we do not grieve what we did not value. What this card tells you is that the predominant feeling on their side right now is sorrow — and sorrow has a tendency to obscure everything else. Even genuine warmth is hard to access from inside it.\n\nThe person you are asking about may be fixated on what has gone wrong, on apologies that did not arrive, on hopes that did not come through. They may struggle to see the cups still standing — the affection, the possibility, the ground that is still under their feet. They are not yet ready to turn around. Asking them to do so prematurely tends to deepen the grief rather than lift it. What is needed is time and gentleness. Whether the grief eventually opens into renewed feeling or into clear-eyed release depends on what they choose to do with the cups they are not yet looking at.`,
    reversedLong: `The Five of Cups reversed as feelings marks a quiet turning. The grief that had defined the inner landscape is loosening, and the person you are asking about is beginning to lift their gaze. Slowly, often without announcement, they are noticing what remains rather than only what was lost. The cups still standing — including, often, whatever they feel for you — are coming back into view.\n\nThis reversal frequently appears when someone has been processing a previous heartbreak, betrayal, or major disappointment, and is finally surfacing. The feelings they had buried or could not access are beginning to flow again. They may feel a tentative, fragile hope that they have not allowed themselves in some time. With this often comes a softer sense of you, less filtered through whatever ghost had been occupying their interior. They are starting to see you in the present rather than through the residue of the past.\n\nIn other readings the reversal speaks to a willingness to repair what felt damaged. They may feel some regret about how they have been showing up — withdrawn, bitter, preoccupied — and a genuine wish to bring more of their actual warmth into the connection now that the worst of their grief has passed. The card does not promise restoration of what was; it promises the beginning of something more honest. Receive the returning feeling without rushing it to declare more than it can yet sustain. What is genuinely emerging will keep emerging if it is given room.`,
    howTheyFeel: `Right now they feel weighted by something that may or may not be about you directly. There is grief in them, and it is shaping what they can and cannot offer at the moment. When they think of you, the feeling that arises is often coloured by disappointment — either about what has been lost between you, or about something else in their life that you are now indirectly carrying.\n\nThis does not mean they have stopped caring. It means the caring is currently surrounded by mourning, and they cannot easily reach the parts of themselves where warmer feelings live. They may withdraw at moments when you would expect closeness, fall silent when you have asked for honesty, dwell on what went wrong rather than what is still possible. Read this as the inward turn of a person processing loss rather than as a final statement of how they feel about you. Give them, and yourself, more time than feels comfortable. When grief is given its room, it eventually moves. When it is rushed, it tends to stay.`,
    feelingsFaqs: [
      {
        q: 'What does the Five of Cups mean as someone\'s feelings for me?',
        a: 'The Five of Cups as feelings describes a person filtering everything through grief or disappointment. The mourning may be about you, about the relationship as it had been, or about a separate loss that is currently colouring their entire emotional life. Either way, sorrow is occupying so much of their inner field that warmer feelings — which may still be there — cannot easily reach the surface. They are fixated on what has gone wrong and not yet able to see the cups still standing behind them. The feeling toward you is real but heavily filtered by what feels lost.',
      },
      {
        q: 'Is the Five of Cups a yes for love?',
        a: 'Not in its upright form. The Five of Cups signals grief, disappointment, and the inward turn that mourning requires, none of which favour the emergence of new love or the lively continuation of an existing one. It does not preclude love in the longer term — many relationships move through this card and come out the other side — but for the immediate question of whether love is flowing freely now, the answer is generally no. The card asks for honesty about the grief rather than pretending it is not shaping what is currently possible.',
      },
      {
        q: 'What does the Five of Cups reversed mean as feelings?',
        a: 'The Five of Cups reversed as feelings indicates that the grief is lifting and warmth is beginning to return. The other person is starting to see what remains rather than only what was lost, and you are increasingly likely to be visible in that returning view. There may be some tentative regret about how they have been showing up, and a quiet wish to bring more of their actual feeling into the connection now that they are emerging from sorrow. The card is hopeful but fragile. The returning feeling will keep returning if it is given room rather than pressed for declarations.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the Five of Cups, caring is almost certainly present — grief tends to confirm rather than deny the value of what is being grieved. The complication is that their caring is currently obscured by sorrow, and they may struggle to express it in ways you can recognise. Read this card as evidence that you matter to them, not as a sign that you do not. The harder question is what they will be able to offer once the grief has had its season. That depends partly on them and partly on what you are willing to wait through. The feeling is real; the timing is uncertain.',
      },
    ],
  },
  'six-of-cups': {
    uprightLong: `The Six of Cups as feelings carries a sweetness that is hard to fake. The person you are asking about feels a quality of safety with you that they associate with their younger, less defended self. You bring out something in them that adulthood often buries — the capacity for ordinary kindness, for play, for being tender without immediately worrying how it will be received. Whatever else is happening in their life, when they think of you, the felt sense is gentle.\n\nThis card often points to a sense of familiarity that goes beyond how long you have known each other. They may feel that you have known them for longer than the calendar allows, or that being around you reminds them of home in some unspecified way. For some people this manifests as a literal connection to the past — an old friendship rekindled, a former love returning, a person from an earlier chapter coming back into focus. For others it is the felt resonance with someone they have not actually known before but who registers, somehow, as known.\n\nThe affection here tends to be uncomplicated by the sharper edges of attraction or strategy. They are not playing a game with you. They are not performing a sophisticated version of love. What they feel is closer to the warmth of a long, easy friendship — sometimes alongside romantic feeling, sometimes as the heart of it. Many relationships built on this card have unusual staying power, precisely because the feeling underneath is more like deep affection than fevered passion. Trust the gentleness rather than demanding it convert into a louder register. Loud is not the same as deep.`,
    reversedLong: `The Six of Cups reversed as feelings introduces a more complicated relationship with the past. The other person may still feel something for you, but their feelings are tangled with comparisons, idealisations, or attachments that do not quite belong in the present. They may be measuring you against a previous love, holding on to a version of the relationship as it once was rather than as it is now, or fixated on a romantic narrative formed when they were much younger and not yet able to evaluate it.\n\nThis reversal sometimes shows up when an old flame is in the picture in some form — perhaps actively communicating with them, perhaps simply living vividly in their imagination. You may be aware of this, or you may not, but their inner landscape is more crowded than they have admitted. The feelings they have for you are real, but they are not the only feelings competing for attention in their heart. Until they take responsibility for that, the connection between you cannot quite settle into the present.\n\nIn other readings the reversal speaks to inherited patterns shaping their behaviour in ways they have not yet examined. Early attachment templates, family dynamics, and childhood wounds are showing up uninvited in how they feel about you. They may withdraw when intimacy deepens, recreate a familiar dynamic from their family of origin, or seek in you a parent they did not have. None of this is conscious cruelty; most of it is unconscious. The card asks for compassion without pretending the patterns are not there. Genuine adult connection requires that both people eventually grow past the templates they inherited, and the work cannot be done on someone else\'s behalf.`,
    howTheyFeel: `Right now they feel an unusual warmth around you that is hard to explain rationally. Something in your presence loosens a quality they do not get to experience often — a sweetness, a lack of defensiveness, an ease that reminds them of an older, less guarded self. Whether they have told you this or not, internally they are noting that being with you feels safe in a particular way that is not very common in their adult life.\n\nThere may also be a sense that they have known you longer than the actual timeline supports. People sometimes use words like familiar, or comfortable, or like home for this feeling, even when there is no objective basis for it. Receive this as the genuine compliment it is. They are not telling you they are thrilled in the dramatic sense; they are telling you that around you they can finally exhale. For many people, the relationships built on this register turn out to be the ones that hold up over time.`,
    feelingsFaqs: [
      {
        q: 'What does the Six of Cups mean as someone\'s feelings for me?',
        a: 'The Six of Cups as feelings describes a gentle, familiar warmth. The other person feels safe with you in a way that brings out a younger, less defended version of themselves. There is a quality of recognition that often exceeds how long you have actually known each other — you feel like home to them, even when they cannot quite explain why. The feeling is tender rather than feverish, and it tends to be uncomplicated by the sharper edges of attraction or strategy. Many lasting relationships are built on this register, even if it lacks the drama that imagination might prefer.',
      },
      {
        q: 'Is the Six of Cups a yes for love?',
        a: 'Yes — a sweet, gentle, and often understated yes. The Six of Cups affirms that the connection has the qualities of genuine affection, safety, and a familiar warmth that often forms the backbone of lasting love. It may not predict fireworks; what it predicts is the kind of relationship that holds up over time precisely because it is built on something steadier than fireworks. For a question about whether something real is brewing, the Six of Cups is reassuring. For a question about whether it will be dramatic, it is silent.',
      },
      {
        q: 'What does the Six of Cups reversed mean as feelings?',
        a: 'The Six of Cups reversed as feelings indicates a complicated relationship with the past that is shaping how they feel toward you now. They may be comparing you to a previous love, holding onto an idealised version of the relationship as it once was, or carrying childhood patterns into the bond without yet examining them. An old flame may also be in the picture, either literally or imaginatively. Their feelings for you are real, but currently not the only feelings competing for attention. The card asks for compassion without pretending the complication is not there.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Six of Cups, the caring is clear and tender. This is not a card of casual interest; it describes feelings that have crossed into genuine affection, often with a quality of being known and accepted. The caring may not always express itself in dramatic ways — the Six of Cups is gentler than that — but the depth is real and durable. If you are looking for an answer about whether something genuine is there, this card affirms it. The connection has the markers of affection that tend to mature rather than fade.',
      },
    ],
  },
  'seven-of-cups': {
    uprightLong: `The Seven of Cups as feelings describes a person whose inner landscape is crowded with possibilities, fantasies, and competing images that they have not yet sorted out. They may feel a great deal — for you, for someone else, for several possibilities at once — but the feelings have not been distilled into anything they can stand behind. What you sense from them is a kind of shimmering: warmth one day, distance the next, intensity followed by withdrawal, with no obvious pattern connecting the shifts.\n\nThis is not necessarily dishonesty, though it can feel that way from the outside. More often it is honest confusion. They are seeing several versions of the future at once, and several versions of you, and several versions of who they would be in different scenarios, and they have not yet committed to one over the others. The fantasy can be so vivid that it interferes with their ability to engage with the actual person in front of them. You may sometimes feel that they are responding to an idea of you rather than to who you actually are, and you may be right.\n\nThis card can also indicate that they are pursuing several connections simultaneously, or that they are still considering options they have not disclosed. The feelings they have for you are real but not exclusive. Until they make a choice — and the Seven of Cups is famous for being a card of indecision — you cannot expect their feelings to organise themselves into something stable. The honest response is to take the situation as it is, name what you actually need, and decline to be one of the cups in their array indefinitely. Sometimes the act of refusing to remain in the fog clarifies things for them in ways that all their internal deliberation has failed to do.`,
    reversedLong: `The Seven of Cups reversed as feelings marks a clearing of the fog. The person you are asking about is beginning to sort through their options, fantasies, and competing desires, and to settle on what they actually want. The feelings they have for you, which may have been one of many shimmering possibilities, are starting to come into focus. They are seeing you more clearly — less filtered through projection or fantasy — and what they see is increasingly being received with intention rather than dispersed across other distractions.\n\nThis reversal often shows up when someone has been deliberating for too long and has finally tired of their own indecision. They are ready to choose. Whether they choose you or not depends on other cards, but the choosing itself is happening. The advantage of this card is that whatever they conclude tends to come with more commitment than the upright version could ever sustain — because they have actually decided rather than drifted.\n\nIn other readings the reversal speaks to the loss of illusion. They may have been holding onto a fantasy about someone else, or about an idealised version of you, that has now lost its hold. The disappointment of that disillusionment can clear the way for genuine feeling toward what is actually present. You may benefit from this, or you may discover that what they had been projecting onto you was incompatible with who you really are. Either way, the air is becoming clearer, and clearer air permits better feeling. The card invites you to be present to the person they are becoming rather than the one they had been pretending to be.`,
    howTheyFeel: `Right now they feel many things at once, and they have not yet figured out which of those things is the actual feeling. When they think of you, they feel one set of emotions; when they think of other possibilities, they feel another set. This is genuinely confusing for them, and the confusion is sometimes mistaken from the outside for coldness or game-playing. More often it is simply an unfinished interior process.\n\nWhat you may be sensing is the inconsistency of someone who has not made up their mind. They might be warm and present on Tuesday and unreachable on Friday, not because their feelings have changed but because a different fantasy has temporarily taken centre stage. Trying to read their feelings for you in this period is like trying to read a book through a kaleidoscope; the underlying text is there, but the colours keep shifting. The wisest stance is to wait for the picture to settle without contorting yourself to hold their attention. What is real will still be real once the fog clears. What is not will reveal itself for what it always was.`,
    feelingsFaqs: [
      {
        q: 'What does the Seven of Cups mean as someone\'s feelings for me?',
        a: 'The Seven of Cups as feelings describes a heart crowded with options, fantasies, and competing possibilities. They may feel a great deal — for you, for someone else, for several scenarios at once — but they have not yet sorted out which feeling is real and which is projection. What you sense from them tends to shift in ways you cannot quite track. This is more often honest confusion than deliberate game-playing, but the effect on the receiving end can be exhausting. Until they make a choice, their feelings cannot organise themselves into anything stable.',
      },
      {
        q: 'Is the Seven of Cups a yes for love?',
        a: 'Generally no, or at best a maybe. The Seven of Cups signals fantasy, indecision, and the failure to choose, none of which support the kind of clarity that real love requires. It does not preclude love eventually emerging — many relationships pass through this card en route to something more settled — but in its current state, the conditions are not stable enough to answer yes. The card asks you to be honest with yourself about whether you are being pursued by the actual person in front of you or by an idea they have spun about you. The difference matters.',
      },
      {
        q: 'What does the Seven of Cups reversed mean as feelings?',
        a: 'The Seven of Cups reversed as feelings indicates that the fog is lifting. They are beginning to sort through their options, set aside illusions, and choose what they actually want. The feelings they have for you, if real, are starting to come into clearer focus and may be approached with more intention. The reversal can also describe the collapse of an idealised version of someone else, which clears the way for genuine feeling toward what is actually present. Whatever the case, clearer air permits better feeling. The card asks both of you to engage with the real rather than the projected.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the Seven of Cups, the honest answer is that they themselves do not yet know. They may be interested in several things at once, attracted to fantasies as much as to people, and unable to distinguish reliably between the two. The caring may be present, but it is mixed with so much else that you cannot read it cleanly from outside. Trying to determine whether their feelings for you are genuine while they are still in this scattered state will mostly produce frustration. Wait for the picture to clarify rather than projecting depth into a state that is mostly fog.',
      },
    ],
  },
  'eight-of-cups': {
    uprightLong: `The Eight of Cups as feelings is sober and quiet. The person you are asking about has begun to feel that what is between you, or what they have been carrying more broadly, no longer feeds them in the way they need. This is rarely a sudden conclusion. It is the felt result of a long period of quiet inventory, in which they have noticed the gap between what they wanted and what they actually have, and have decided — perhaps without fully articulating it — that they cannot continue.\n\nThe feelings here are not absent. Often they are still real, even tender. The eight cups standing behind the figure are not nothing; they represent what was built, what was felt, what mattered. The figure walks away not because they have stopped caring but because caring has stopped being enough. Something in them is being called toward a different kind of life, and they cannot remain where they are without betraying that call. This can be very hard for the person being left to hear, because it feels nothing like rejection — and yet the practical outcome is similar.\n\nFor those still in the relationship, this card can describe a partner who is mentally already walking. They may not have said anything yet. The conversations have grown shorter; the eyes look further away; a quietness has entered the room that was not there before. They are not contemplating drama; they are contemplating departure. Sometimes the departure can still be averted, but only by addressing what has actually grown hollow — not by pleading, not by performing, but by being willing to have the conversation that has not yet been had. Often the card simply names what is already in motion. Allowing the truth of it does more good than resisting.`,
    reversedLong: `The Eight of Cups reversed as feelings describes the more complicated terrain of someone who knows something is wrong but cannot yet bring themselves to leave it. They may feel resigned, stuck, or quietly desperate. They are aware that what they have is not enough, but the act of walking away requires a courage they do not yet have. So they stay, and the feelings begin to take on a heaviness that affects everything else they touch.\n\nAlternatively, this reversal can describe a return — someone who walked away once and is now circling back. The feelings they had buried when they left are resurfacing, sometimes with regret. They may not have been able to find what they were looking for elsewhere, or they may have realised that what they left was more valuable than they had recognised at the time. The card asks you to read this with care. Returns can be honest reckonings, or they can be the resumption of an old pattern that did not work the first time and will not work the second time either.\n\nIn other readings the reversal speaks to someone who fears moving on. They feel the call to leave — a relationship, a habit, a chapter — and cannot answer it because the alternative feels too daunting. Their feelings for you are now entangled with this avoidance. They may use the connection as something to hide behind rather than something to genuinely inhabit. This is hard on both of you. The card asks for clarity about whether what is being offered is real engagement or quiet stalling. Neither one is a moral failing on their part, but you deserve to know the difference rather than discover it later.`,
    howTheyFeel: `Right now they feel a quiet emptiness that may not match what is visible on the surface. They are still showing up, still going through the rituals of connection, and inside they are aware that something has gone hollow. When they think of you, the feeling that surfaces is often complicated — affection braided with weariness, gratitude braided with quiet dissatisfaction. They are not yet sure whether what they are weary of is the relationship itself, their own state, or some larger pattern they cannot quite name.\n\nIf they are in the middle of this card, they may not say much about what they are feeling. The Eight of Cups is a card of inward reckoning before outward decision. They are walking through their own interior, looking at what they have built and asking whether it still serves the person they are becoming. The honest response from your side is to give them the room they are asking for, even when it costs you. Forcing the conversation often delays the conclusion they need to reach on their own. Whatever decision emerges from this will be more honest than one extracted from them prematurely.`,
    feelingsFaqs: [
      {
        q: 'What does the Eight of Cups mean as someone\'s feelings for me?',
        a: 'The Eight of Cups as feelings describes a quiet, sober conclusion that what they have been holding — possibly the relationship itself, possibly something broader — no longer feeds them. The feelings may still be real, often even tender, but caring has stopped being enough. They are being called toward a different kind of life and cannot remain where they are without betraying that call. The departure is rarely dramatic; it is felt before it is named. If you have been sensing that they are mentally already walking, this card often confirms what your intuition has been registering.',
      },
      {
        q: 'Is the Eight of Cups a yes for love?',
        a: 'No, generally. The Eight of Cups is a card of leaving, even when the leaving is sorrowful rather than bitter. It indicates someone moving away from what they had, in search of something they have not yet been able to name. For an active relationship question, this typically points to ending or significant transition rather than continuation. It does not always mean the relationship is over forever — some couples walk through this card and find each other again in a changed form — but for the immediate question of whether love is going to continue smoothly as before, the answer is sober rather than affirmative.',
      },
      {
        q: 'What does the Eight of Cups reversed mean as feelings?',
        a: 'The Eight of Cups reversed as feelings describes someone who senses they should walk away but cannot yet bring themselves to do so, or someone who has walked away once and is now circling back. There may be resignation, fear of moving on, or genuine reconsideration. The reversal asks you to read carefully whether the return is honest reckoning or the resumption of an old pattern. Neither possibility is a moral failing, but the difference matters. They may be staying out of fear or returning out of regret — both are real, but they call for different responses from you.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the Eight of Cups, caring is usually present and almost never the issue. The complication is that caring has not been enough to make them stay or to make the connection work in its current form. This is one of the more painful readings because it tells you the affection is real and the departure is also real. They are not leaving because they did not care; they are leaving because caring did not turn out to be sufficient. That truth is harder to receive than indifference would have been, but it is also more honest. Let it land for what it is.',
      },
    ],
  },
  'nine-of-cups': {
    uprightLong: `The Nine of Cups as feelings is one of the more flattering cards to draw in a feelings question. The person you are asking about feels genuinely pleased with you. When they think of you, what arises is satisfaction — the felt sense that something they had wished for is, in fact, present in their life. You make them happy in ways that are concrete enough to notice and stable enough to count on. This is the card sometimes called the wish card, and in feelings questions it often indicates that you are, quietly, a wish of theirs come true.\n\nThe contentment here is not the breathless intensity of new infatuation. It is something steadier — the warm, slightly disbelieving recognition that the connection between you matches what they had hoped for, rather than disappointing it. They feel emotionally well around you. Their nervous system relaxes in your presence. They may catch themselves smiling for no obvious reason after a conversation with you, or noticing that their general life satisfaction is higher in the periods when you are close.\n\nThere is sometimes a quality of gratitude in this card that does not get talked about enough. They are aware, on some level, that what they have with you is rare. They may not yet have said so out loud — happiness is sometimes harder to articulate than complaint — but they are noting it internally. The card invites you to receive this fully rather than testing it or assuming it is too good to be true. Some people sabotage their own contentment by refusing to believe in it. If this card has come up for them, the feeling is real, and refusing to trust it is its own kind of harm.`,
    reversedLong: `The Nine of Cups reversed as feelings describes a more uncomfortable satisfaction — one that has either curdled into entitlement, gone hollow, or never quite matched what they had hoped for in the first place. The person you are asking about may have what they thought they wanted and still feel restless. They are getting their wishes met on the surface and finding that the meeting has not produced the contentment they expected. Sometimes this is about the relationship itself, sometimes about a wider pattern of seeking that has not yet found what would actually nourish.\n\nThis reversal can describe feelings that are more about self-image than about you. They may enjoy what the connection says about them, what it provides them, what they get to feel about themselves when you are in their life, more than they enjoy the actual person you are. This is a subtle and unflattering reading, and not every Nine of Cups reversed deserves it, but the pattern is common enough to consider. The card asks you to notice whether their satisfaction with you is genuinely about you, or about the role you are filling in their psychic economy.\n\nIn other readings the reversal speaks to dissatisfaction that has crept in despite favourable circumstances. They may have everything they thought they wanted and feel quietly unhappy anyway, which is confusing for them and confusing for you. The dissatisfaction often points to something inside them that the relationship cannot solve — a longing for meaning, or for self-knowledge, that no external person can supply. The fairest response from your side is not to try to be more, but to recognise that what they need is not something you can provide by amplifying yourself. Some discontents have to be addressed at their actual source.`,
    howTheyFeel: `Right now they feel a quiet, settled pleasure in your presence. They may not always be able to articulate it, and they may sometimes downplay it from habit, but the felt experience is that you make their life better. Their mood lifts when they think of you. Their daily life is materially happier in the periods when you are close.\n\nThis is not the loud, agitated feeling of new attraction. It is something more grown — the recognition that what they have with you matches, or even exceeds, what they had quietly been hoping for. They may not have told you any of this. Happiness, oddly, is often harder to articulate than its opposite. But internally they know. When they imagine the version of their life in which you remain present, that version looks good to them, and they want it to keep going. Trust the satisfaction this card describes. It is a quieter signal than some, but quieter does not mean weaker.`,
    feelingsFaqs: [
      {
        q: 'What does the Nine of Cups mean as someone\'s feelings for me?',
        a: 'The Nine of Cups as feelings describes genuine contentment with you. The other person feels emotionally well around you in ways that are concrete and noticeable. Their life is materially happier when you are close, and they may quietly recognise that what they have with you matches what they had hoped for. This is sometimes called the wish card, and in a feelings question it often means you are, in their inner life, a wish fulfilled. The satisfaction may not announce itself loudly — settled happiness is quieter than infatuation — but it is real and durable.',
      },
      {
        q: 'Is the Nine of Cups a yes for love?',
        a: 'Yes — and a confident, settled yes rather than a feverish one. The Nine of Cups affirms emotional satisfaction, contentment, and the felt sense that the connection is meeting a real need rather than producing complication. For love questions, this card is one of the more reassuring outcomes available. It indicates not just that feelings exist, but that those feelings are accompanied by the wellbeing that signals a healthy bond. If you are asking whether something is going well, the Nine of Cups says yes, and asks you to receive that yes rather than testing it.',
      },
      {
        q: 'What does the Nine of Cups reversed mean as feelings?',
        a: 'The Nine of Cups reversed as feelings indicates a more troubled satisfaction. The person may have what they thought they wanted and still feel restless, or their pleasure in the connection may be more about self-image than about you specifically. The reversal can also describe contentment that has gone hollow, or pleasure tipping toward entitlement. The card asks you to look honestly at whether their satisfaction is genuine and rooted in who you actually are, or whether it is about a role you are filling for them. The distinction matters more than it first appears.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Nine of Cups, the caring is clear, settled, and genuinely felt. This is not a card of casual interest; it describes someone whose life is meaningfully better because you are in it, and who recognises that fact even if they do not always articulate it. The caring may not be dramatic, but drama is not the same as depth. The Nine of Cups tends to indicate the kind of feeling that survives ordinary life rather than flaring and dying. If you are looking for confirmation that something real and grounded is there, this card provides it.',
      },
    ],
  },
  'ten-of-cups': {
    uprightLong: `The Ten of Cups as feelings is among the most affirming cards in the deck. The person you are asking about feels a deep and integrated love for you that includes their wider life — their family, their long-term hopes, their sense of what a good life looks like. They do not just feel attraction or affection; they feel that you belong in the picture of the life they actually want to build. This is significant because many people can feel attracted to someone they would never include in their broader vision. The Ten of Cups says the opposite: they feel you and the life they hope for are aligned.\n\nThe emotional quality here is settled and warm in a way that includes a future. They imagine you in domestic moments, in family gatherings, in the long unfolding of years. Whether or not they have said this out loud, internally they are already including you in plans that have not yet been spoken. This is not the urgency of new love but the deeper warmth of love that has found its home. Their feelings have moved past the stage of wondering whether you are right; they have arrived at the recognition that you are.\n\nThere is also a quality of pride in this card. They feel proud to be connected to you, proud to introduce you to the people who matter to them, proud of the relationship as something they would be happy to have witnessed by the rest of their life. This is rarer than the romantic imagination suggests. Many connections are kept compartmentalised; the Ten of Cups describes a connection allowed to integrate. Receive that for what it is. The feelings here are mature, generous, and genuinely directed toward a shared future rather than toward a private fantasy.`,
    reversedLong: `The Ten of Cups reversed as feelings describes a gap between the picture they had hoped for and the reality they are now sitting with. The other person may have wanted the kind of love this card represents, and may still want it, but something in the actual relationship is not matching the vision. The disappointment may be subtle. Outwardly, things may look broadly fine. Inwardly, they are aware of a quiet ache between the dream of what could have been and the daily texture of what is.\n\nThis reversal often shows up when family dynamics or external pressures are interfering with the connection. Perhaps their family does not approve, perhaps yours does not, perhaps obligations elsewhere are making it hard for you to be a real priority in their life. The feelings between you may be genuine and still be tangled with circumstances that prevent the relationship from feeling whole. They may withdraw at moments because the friction has worn them down, not because they have stopped caring.\n\nIn other readings the Ten of Cups reversed speaks to disharmony at home. They may be carrying the strain of a difficult family of origin, or the strain of trying to build a life that looks like the Ten of Cups when the materials they actually have do not yet permit it. Their feelings for you can become entangled in this larger struggle, sometimes unfairly. The honest response from your side is to look at whether the obstacles to the picture are external and addressable, or internal and structural. The first kind can shift with effort. The second kind requires either acceptance or a different vision altogether. Pretending the gap is not there rarely closes it.`,
    howTheyFeel: `Right now they feel a love for you that includes their wider life. When they imagine the future, you are in it — not as a vague abstraction but as a specific, settled presence. They have, internally, already made the move from wondering whether you fit to recognising that you do. They may not have told you this in so many words, partly because such recognitions are sometimes harder to articulate than smaller ones, but the inner stance is firm.\n\nThere is also a quality of arrival in what they feel. They are not chasing, not auditioning, not strategising. They are at rest in your direction, with the kind of warmth that wants ordinary days as much as extraordinary ones. The emotional climate around you is mature, generous, and integrated with the life they actually want to live. If you have been wondering whether what they feel is real, this card is unusually unambiguous. Receive it. The Ten of Cups does not appear without there being something genuine for it to describe.`,
    feelingsFaqs: [
      {
        q: 'What does the Ten of Cups mean as someone\'s feelings for me?',
        a: 'The Ten of Cups as feelings describes a deep, integrated love that includes their vision of a wider life. They do not just feel attraction; they feel that you belong in the future they actually want to build. The emotional quality is settled and warm rather than urgent, and the feeling extends to family, long-term hopes, and the kind of life they imagine living. This is a card of mature love rather than infatuation, and it indicates feelings that have moved past wondering and arrived at recognition. Pulling this card is one of the strongest affirmations of genuine emotional commitment available.',
      },
      {
        q: 'Is the Ten of Cups a yes for love?',
        a: 'Yes — emphatically, and with a long-term flavour that few other cards match. The Ten of Cups affirms love that is integrated with the rest of life rather than kept in a private corner. It indicates emotional alignment, shared future-orientation, and the kind of harmony that endures rather than flaring. For questions about whether a relationship has lasting potential, this card is one of the clearest yeses in the deck. It does not promise that nothing will ever be difficult, but it does promise that the underlying feeling has the right shape for a real life together.',
      },
      {
        q: 'What does the Ten of Cups reversed mean as feelings?',
        a: 'The Ten of Cups reversed as feelings indicates a gap between the picture of love they had hoped for and the reality they are currently inhabiting. The feelings may still be present, but disharmony — sometimes from family or external pressures, sometimes from misalignment in values or daily life — is preventing the connection from feeling whole. They may withdraw at moments because the friction has worn them down rather than because they have stopped caring. The card asks you to look at whether the obstacles to the picture are external and addressable, or structural and requiring honest reckoning.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Ten of Cups, they care in the most integrated possible sense. This is not casual interest; it is love that has made room for you in the broader life. They have included you in their long-term imagination, and that act of inclusion is one of the more telling signals available. If you are looking for proof that the feelings are deep, durable, and oriented toward shared future rather than private fantasy, this card provides it. The depth here is genuinely rare, and worth receiving without scepticism.',
      },
    ],
  },
  'page-of-cups': {
    uprightLong: `The Page of Cups as feelings describes a heart that is still young in its emotional expression, regardless of the person\'s actual age. The feelings are real but tender, exploratory, and sometimes uncertain of their own shape. The other person may not have done a great deal of this before — falling for someone in the way they are falling for you, allowing themselves to be vulnerable with this particular kind of openness, considering what it would mean to act on what they feel. There is a freshness here that is genuinely sweet and slightly unguarded.\n\nThis card often shows up when someone is in the early stages of a feeling they are not yet ready to declare. They may communicate in small gestures — a thoughtful message at an unexpected hour, an awkward but sincere compliment, a creative offering — rather than in direct emotional language. They feel romantic, and the feeling itself surprises them. Pages are not always confident about how to handle what they hold, and you may sense some shyness or hesitancy alongside the genuine warmth.\n\nFor those in established relationships, this card can describe a partner who feels newly inspired, or who is rediscovering a softer, more open mode of being with you. They are feeling tender. They are open to the imagination of love, to playful gestures, to the kind of small romantic acts that often get crowded out of long relationships. This is genuine and worth honouring. Pages are easy to underestimate because they are not the dramatic court cards, but the feeling they describe — fresh, sincere, willing to be surprised — is one of the most authentic forms of love available to anyone.`,
    reversedLong: `The Page of Cups reversed as feelings describes immaturity, escapism, or emotional volatility on the part of the person you are asking about. They may feel real things for you, but they have not yet developed the capacity to handle those feelings well. The result is a stop-start quality in which they advance when it suits them and retreat when it asks something of them. They are not deliberately playing games; they are simply not yet emotionally equipped for what they are reaching toward.\n\nThis reversal often appears when someone is hiding from the seriousness of what they feel. They may communicate in unreliable patterns — warm at certain hours, distant at others — because the feeling itself is more than they know what to do with. They may use fantasy, drink, distraction, or other people as ways of managing the intensity, which leaves you on the receiving end of behaviour that does not quite add up. Their care may be real, but their capacity to express it consistently is not.\n\nIn other readings the reversal speaks to feelings that have not been examined and are therefore being acted out rather than understood. They may project childhood material onto you, expect you to mother them, romanticise you in ways that have little to do with who you actually are, or recoil when you fail to match the fantasy. None of this is sustainable. The card asks for honest reading of whether what they offer matches what an adult connection requires. Sometimes the answer is that they will grow into the relationship if given time and space; sometimes it is that you are being asked to do their emotional development for them, which is a request you are entitled to decline.`,
    howTheyFeel: `Right now they feel something genuinely tender that they do not quite know how to express. When they think of you, the emotion is sweeter and softer than the version they manage to communicate. There is a gap between what they feel inside and what they manage to send out, and the gap is making them more hesitant than the feeling itself would warrant.\n\nThey may reach toward you in small, sometimes awkward ways — a thoughtful message, a creative gesture, an unexpected piece of openness — and then retreat as if startled by their own boldness. Read this for what it is rather than reading it as inconsistency. They are not toying with you; they are negotiating with their own inexperience or shyness. The feeling is real, the warmth is sincere, and the volume is simply lower than they wish it could be. If you can hold the unfolding patiently, what is emerging often grows into something more confident. If you press too hard for declaration too soon, the timid heart tends to close again.`,
    feelingsFaqs: [
      {
        q: 'What does the Page of Cups mean as someone\'s feelings for me?',
        a: 'The Page of Cups as feelings describes a tender, exploratory, often youthful quality of emotion. The other person feels something genuine but is still figuring out how to express it. They may communicate in small, sometimes awkward gestures rather than direct emotional language, and there can be a sweet hesitancy alongside the warmth. This is not the confident declaration of a more developed card, but it is sincere — perhaps more sincere than louder expressions might be. They are surprised by their own feeling and are negotiating with that surprise as they reach toward you.',
      },
      {
        q: 'Is the Page of Cups a yes for love?',
        a: 'Yes, but a gentle and developing one. The Page of Cups affirms emotional openness, sincere feeling, and the beginning of a heart-led connection, while indicating that the relationship is still in an early or tentative phase. The yes here is hopeful rather than triumphant; it suggests that something real is starting, but that the form it will eventually take is not yet settled. For a question about whether feelings are present, this card answers yes. For a question about whether the relationship is already mature and established, the answer is that you are still in the early chapters.',
      },
      {
        q: 'What does the Page of Cups reversed mean as feelings?',
        a: 'The Page of Cups reversed as feelings indicates emotional immaturity, escapism, or volatility on the part of the person you are asking about. They may feel real things but lack the capacity to handle those feelings consistently, producing a stop-start quality that is genuinely confusing to receive. They are usually not playing games deliberately; they are reacting to feelings that are bigger than their current emotional skills. The card asks you to look honestly at whether what they offer matches what an adult connection requires, and to decline politely if you are being asked to do their developmental work for them.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Page of Cups, the caring is real but young. They feel something tender, and the feeling is sincere rather than calculated, but it has not fully matured into the steady commitment of a more developed card. You may sense the gap between what they feel and what they can yet express. This does not invalidate the caring; it just describes the stage they are in. Pages can grow into confident hearts if given time and patience. The question is whether the pace of their development matches what you need from the connection now.',
      },
    ],
  },
  'knight-of-cups': {
    uprightLong: `The Knight of Cups as feelings is the card of the romantic — the suitor on horseback offering the cup, the dreamer in love with love, the heart that pursues beauty with sincere intent. The person you are asking about feels romantically drawn to you in a particular, idealising way. They imagine you in soft focus. They want to make grand gestures, or at least the more elegant equivalents available to them. They are not embarrassed to be moved; they want to be moved, and you are the one moving them.\n\nThis card carries a real, even old-fashioned, romantic sincerity. They are not performing love cynically. They genuinely feel pulled toward you with the kind of sweep that comes from the imaginative, emotional side of their nature. Knights of Cups can write the message, make the journey, send the flowers, propose the trip — they like the language of love and they use it without self-consciousness. Inside they feel warmed by you in ways they enjoy feeling and do not particularly want to manage away.\n\nThere is one note of caution worth holding. The Knight is in motion; he is still on his quest. The feelings he describes are sincere but not yet settled. He may pursue beautifully and then need to leave for some other beautiful thing on the horizon. This is not necessarily bad faith — knights are designed to ride — but it is worth recognising. The romance you are receiving is genuine. Whether the romance will mature into staying depends on him, on you, and on what each of you wants the bond to become. Receive the beauty of what is offered without yet asking it to commit to permanence.`,
    reversedLong: `The Knight of Cups reversed as feelings introduces a more complicated relationship to romantic feeling. The Knight\'s sincerity may be intermittent, performative, or undermined by moodiness, jealousy, or unrealistic expectations. The person you are asking about may pursue you intensely and then withdraw without warning. They may idealise you when they are inspired and find you disappointing the moment you fail to match the fantasy. The feelings are present, but the relationship with those feelings is unsteady.\n\nThis reversal often appears when someone is in love with the idea of being in love more than with the actual person they are courting. They want the high, the rush, the romantic narrative — and when daily reality fails to provide those continuously, their interest flags. They may then reach for a new infatuation, returning to you when the new one disappoints. This can be exhausting on the receiving end, and it is one of the patterns the reversed Knight most reliably describes.\n\nIn other readings the reversal speaks to a partner whose moods drive the temperature of the relationship in unpredictable ways. They feel intensely when they feel, but the feelings shift in ways you cannot anticipate or stabilise. Jealousy, sulking, or grand gestures used to manipulate rather than to celebrate can all appear here. The honest reading is to notice whether the romance you are receiving has substance beneath it or whether it is mostly performance. The Knight of Cups reversed asks you to be unromantic, briefly, in order to see clearly. What you decide to do with that clarity is up to you.`,
    howTheyFeel: `Right now they feel a wash of romantic sentiment when they think of you. You stir the imaginative, idealistic side of their nature, and they enjoy the stirring. They may compose messages to you in their head before they send them. They may imagine scenes — a particular dinner, a particular walk, a particular conversation — and look forward to making them real. Their feelings for you have a quality of being savoured, almost privately, before they are expressed.\n\nThere can also be a slight performance in this register, not because they are insincere but because they like the language of love and they reach for it readily. Receive what they offer with appreciation rather than scepticism, but keep your own footing. The Knight of Cups can be intoxicating to be on the receiving end of, and the intoxication can sometimes obscure the question of whether the connection has the durable, daily substance that lasting relationships eventually require. The feeling is real. Time will tell whether it is also enduring.`,
    feelingsFaqs: [
      {
        q: 'What does the Knight of Cups mean as someone\'s feelings for me?',
        a: 'The Knight of Cups as feelings describes a sincere, romantic, idealising attraction. The other person feels drawn to you in a way that they enjoy savouring — they imagine you in soft focus, want to make gestures, and are not embarrassed to be moved. The sentiment is genuine and unfeigned, and it carries the particular quality of someone in love with the experience of love itself. The note of caution is that knights are in motion: the feelings are real but not yet settled. Receive the romance for what it is without yet asking it to commit to permanence.',
      },
      {
        q: 'Is the Knight of Cups a yes for love?',
        a: 'Yes, with an asterisk. The Knight of Cups affirms genuine romantic interest, sweet pursuit, and the energy of someone actively moving toward you with heart-led intent. For a question about whether feelings are present and being directed in your direction, the answer is clearly yes. The asterisk is that the Knight is on a journey, and the journey is not yet over. The romance is sincere; the question of whether it will mature into staying depends on what unfolds. Take the yes for what it says, and stay curious about what comes next.',
      },
      {
        q: 'What does the Knight of Cups reversed mean as feelings?',
        a: 'The Knight of Cups reversed as feelings describes unstable, moody, or over-idealising romantic feeling. The pursuit may be intermittent, the sincerity uneven, and the interest dependent on the high of the romantic narrative rather than on the actual person being pursued. Jealousy, sulking, or pursuit that fades when daily life fails to match the fantasy can all appear here. The card asks you to look honestly at whether what you are receiving has substance beneath the gestures, or whether the gestures themselves are the whole thing. Both are possible, and the difference matters.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Knight of Cups, the feeling is somewhere between caring and interested in a particular way — it is romantic interest with genuine warmth. They are drawn to you, and the drawing is sincere, but caring in the deeper sense of long-term commitment has not necessarily arrived yet. This is the card of a sweet, real pursuit rather than the card of settled love. Whether interest matures into deeper care depends on what each of you brings to what is being built. The feelings now are honest. The question of permanence is still open.',
      },
    ],
  },
  'queen-of-cups': {
    uprightLong: `The Queen of Cups as feelings describes a person — or a personality archetype — who feels deeply, intuitively, and with great emotional intelligence. When the Queen of Cups appears as the other person\'s feelings for you, what they offer is empathic, attuned, and quietly attentive in ways you may not always notice. They feel you. They register your moods, your unspoken concerns, the small shifts in your tone of voice. Their feelings for you are inseparable from the depth with which they pay attention to who you actually are.\n\nThis is not a card of dramatic declaration. The Queen of Cups loves through listening, through presence, through the steady availability of her emotional warmth. She may not say it loudly. She may not need to. What she feels for you tends to express itself in the quality of how she shows up — in remembering what you said three weeks ago, in noticing when something is off, in holding space without trying to fix. The feelings are mature and grounded in genuine care for your wellbeing rather than in fantasy about who you might be for her.\n\nThere is also a strongly intuitive quality to her feeling. She may know things about you that you have not told her. She may sense when you need her before you have realised it yourself. This can be remarkable to receive, and it can also be a great deal — being seen this clearly is intimate in a way that some people find unsettling. Trust the depth she offers. The Queen of Cups, when she gives her heart, gives it with genuine emotional substance. Few cards in the deck describe more reliable feeling.`,
    reversedLong: `The Queen of Cups reversed as feelings describes the shadow side of emotional depth — overwhelm, codependency, insecurity, or feeling that has tipped into something less healthy than the upright version. The other person may feel for you intensely, but the intensity is no longer well-regulated. They may absorb your moods rather than holding their own ground in the face of them. They may need you in ways that are difficult to sustain, or they may withdraw when their own feelings become too much for them to manage.\n\nThis reversal often appears when emotional intelligence has not been matched by emotional self-care. The Queen of Cups reversed feels everything and has not yet learned how to feel without drowning. As a result, her care for you can come braided with anxiety, neediness, or a quiet manipulation that uses emotional sensitivity as a tool rather than a gift. None of this is necessarily conscious. She may genuinely believe she is being loving when she is, in fact, being depleting. The dynamic can become exhausting for both of you.\n\nIn other readings the reversal points to feelings that are real but obscured by the person\'s own unresolved material. They may project feelings onto you that belong to earlier figures in their life. They may struggle to distinguish between their own emotions and the emotions they are picking up from you. The honest response is to hold compassion for the depth of what they feel while declining to be responsible for managing it. Queens at their best know themselves; the reversed Queen of Cups is still learning what is hers and what is not. The work cannot be done on her behalf, but you can refuse to enable patterns that prevent it.`,
    howTheyFeel: `Right now they feel you in a way that few other people in your life probably do. They register what is happening for you without being told, and they hold what they register with care. When you have been struggling, they feel something soften in them in your direction. When you have been well, they share in it quietly. They love through paying attention, and the attention is real.\n\nThis is not always announced. The Queen of Cups can love deeply without saying so loudly, and you may sometimes wish she would put more of what she clearly feels into spoken words. But the feeling is there, woven through her behaviour, present in the texture of how she shows up. You can rely on what she offers. The depth she brings is not performative; it is the actual shape of her interior. Receive it as the rare gift it is, and let yourself be seen by someone who has the capacity to see clearly. Many people never meet someone with this register; if she has appeared in your life, what she feels is genuine.`,
    feelingsFaqs: [
      {
        q: 'What does the Queen of Cups mean as someone\'s feelings for me?',
        a: 'The Queen of Cups as feelings describes deep, attuned, intuitive emotional connection. The other person feels you in a way few people do — they notice the small shifts, register the unspoken, and offer their care through quiet attention rather than loud declaration. The feelings are mature, grounded, and woven through the way they actually show up in your life. This is not a card of dramatic confession but of substantial, dependable love. They may not always say it; they live it. The depth here is genuine and worth trusting.',
      },
      {
        q: 'Is the Queen of Cups a yes for love?',
        a: 'Yes, and a particularly substantive one. The Queen of Cups affirms emotional depth, genuine attunement, and the kind of love that pays attention rather than performs. For questions about whether someone truly understands you and feels for you with real care, this card is one of the strongest yeses available. It does not predict drama; it predicts the slow, sustaining nourishment of being held by someone with real emotional intelligence. For a long-term love question, that nourishment matters more than most other markers.',
      },
      {
        q: 'What does the Queen of Cups reversed mean as feelings?',
        a: 'The Queen of Cups reversed as feelings describes emotional overwhelm, codependency, or sensitivity that has not been matched by self-knowledge. The feelings are real, often intense, but the regulation is poor. The person may absorb your moods, project unresolved material onto you, or use emotional attunement as a tool rather than a gift. None of this is necessarily conscious cruelty; it is more often the shadow of depth that has not yet learned its own boundaries. The card asks for compassion paired with clear limits about what is yours to carry.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright Queen of Cups, the caring is unmistakable and deep. This is not a card of casual interest; it describes someone who attends to your inner life with genuine attention and offers their feelings with substance. You may sometimes wish the declarations were louder, but the depth of what is actually there is far greater than performative love ever produces. The Queen of Cups gives her heart with real care for your wellbeing. If she has come up for someone in your life, what they feel for you is dependable and grown.',
      },
    ],
  },
  'king-of-cups': {
    uprightLong: `The King of Cups as feelings describes emotional maturity — feelings that have been felt, examined, and integrated into a steady character. The person you are asking about feels for you with the kind of grown warmth that does not flare and collapse. He has been through enough of his own emotional terrain to know what genuine love looks like, and what he feels for you sits inside that hard-won knowing. He is not infatuated; he is committed at the level of his feeling, even if he has not yet articulated commitment at the level of his words.\n\nThis card carries a particular dignity in love. The King of Cups does not perform his emotions, but they are present. He offers steadiness, patience, and the kind of presence that does not become destabilised by your bad days. He has the capacity to hold complicated feelings — yours and his own — without collapsing into them. When he loves, he loves with the calm of someone who has earned the right to. He is not afraid of intimacy; he has practised it long enough to be comfortable inside it.\n\nThere is something quietly reassuring about being the object of King of Cups feeling. You may not get fireworks. You will, however, get the steady, generous, emotionally available presence of a person who has done his own work. He will listen well. He will not punish you for vulnerability. He will, in fact, make space for it. If you are uncertain whether what he feels is real, this is the wrong question; the King\'s feelings are nothing if not real. The truer question is whether you can receive the particular grown register of his love, which is gentler and more dependable than the louder versions you may have previously known.`,
    reversedLong: `The King of Cups reversed as feelings describes emotional mastery that has gone wrong in one of several recognisable ways. The mature steadiness can curdle into suppression, with feelings held so tightly they cannot reach you. The diplomatic patience can shade into emotional manipulation, in which apparent calm masks pressure and control. The depth can become moody, with the person retreating into long silences that the people around him are forced to navigate.\n\nThis reversal often appears when someone has the surface markers of emotional maturity without the inner work to back them up. He looks calm and grown, but the calm is a performance over considerable unprocessed feeling underneath. You may sense the gap between how he presents and what is actually moving in him. The pressure of that gap sometimes leaks out as coldness, as judgement, or as the slow weight of disapproval delivered through silence rather than direct speech.\n\nIn other readings the reversal describes feelings that exist but are being deliberately withheld. He may be afraid of the vulnerability required to express them, may feel that revealing what he feels would put him at a disadvantage, or may simply have learned, somewhere along the way, that strong feelings are dangerous to admit. The card asks you to read carefully whether the warmth that should be there is being conserved out of caution or genuinely depleted. The first is workable, with patience and gentle invitation; the second is information you would do well to receive clearly rather than romanticise.`,
    howTheyFeel: `Right now they feel a settled affection for you that does not need to announce itself. The feelings are present, mature, and steady. When they think of you, what arises is a kind of warmth that has already made peace with the complications of caring about another person. They are not panicking. They are not strategising. They are quietly committed to what they feel, even if they have not yet said so in plain language.\n\nThis can sometimes be hard to read from outside. The King of Cups does not need to perform his feelings, which means the absence of performance can be mistaken for the absence of feeling. It is not. What he offers is the deeper register: presence, patience, dependability, and the kind of emotional availability that holds steady through ordinary days as well as dramatic ones. If you have been waiting for the loud declaration, you may wait some time. If you have been receiving the quieter, more substantial signals — the consistent showing up, the calm in difficult moments, the felt sense of being held — you are already in the presence of love that knows itself.`,
    feelingsFaqs: [
      {
        q: 'What does the King of Cups mean as someone\'s feelings for me?',
        a: 'The King of Cups as feelings describes mature, integrated emotional warmth. The other person feels for you with the steady, examined love of someone who has done his own work and knows what genuine feeling looks like. He does not perform his emotions, but they are present and dependable. He offers patience, presence, and the kind of emotional availability that does not destabilise in the face of ordinary difficulty. The feelings here are quiet rather than dramatic, but they are deeper and more reliable than louder registers tend to be. Trust the steadiness as the love it is.',
      },
      {
        q: 'Is the King of Cups a yes for love?',
        a: 'Yes — and a particularly substantive yes for long-term love. The King of Cups affirms emotional maturity, steady warmth, and the capacity to love someone through the realities of daily life rather than only the highs. For questions about whether someone can actually hold a real relationship, with all that entails, this is one of the strongest cards in the deck. The yes is calm rather than feverish, but calmness here is a feature rather than a limitation. It indicates love that has the inner resources to last.',
      },
      {
        q: 'What does the King of Cups reversed mean as feelings?',
        a: 'The King of Cups reversed as feelings describes emotional mastery gone wrong — suppression, manipulation, or moodiness masquerading as depth. The feelings may be real but withheld; the apparent calm may mask unprocessed material underneath. Sometimes the reversal describes someone who has learned to perform maturity without doing the inner work to back it up, and the gap leaks out as coldness, judgement, or silent disapproval. The card asks for honest reading of whether the warmth is being conserved out of caution, which is workable, or genuinely depleted, which is information.',
      },
      {
        q: 'Do they care about me or are they just interested?',
        a: 'With the upright King of Cups, they care, and the caring is mature, grounded, and durable. This is not a card of casual interest; it describes someone whose feelings have been examined, integrated, and committed to. The expressions may be quieter than the more dramatic cards would produce, but the substance is far greater. The King of Cups does not invest emotionally in connections he does not value. If this is his register toward you, the depth is real, and the steady presence he offers is one of the more meaningful forms of love available.',
      },
    ],
  },
}
