import type { FeelingsContext } from '../card-feelings-extended'

// Major Arcana part 2: The Hanged Man through The World (cards 12–21)
export const MAJOR_2: Record<string, FeelingsContext> = {
  'the-hanged-man': {
    uprightLong: `The Hanged Man as feelings describes someone who is genuinely suspended in their experience of you — not avoiding it, not deciding against it, but living inside a quiet pause where they are seeing the connection from an angle they had not previously considered. They feel the importance of what is unfolding, and they are also unwilling to rush it into a shape it is not ready to take. This is rarely the cool indifference it can sometimes look like from the outside. It is more often a person trying to honour the genuine weight of what they are feeling by not making premature declarations about it. They want to understand what is happening between you before they speak it.

Just below the surface, there is real tenderness and a willingness to be changed by you. The Hanged Man is the card of conscious surrender, and as feelings it almost always points to someone who has, in some quiet way, already let down a defence they had been holding for some time. They may not have articulated this yet, even to themselves, but the inner shift has occurred. What looks like passivity is actually receptivity. They are letting the connection work on them rather than trying to work on it. This kind of openness, when it is genuine, tends to produce slower but considerably deeper feeling than the more performative versions of interest.

What they are open to right now is mostly perspective — yours, theirs, the relationship's. They are interested in how you see things, what you have learned, what you have come to believe through your own difficult chapters. There is also a willingness to wait that is not the same as indifference; they would rather move at a pace that allows real understanding than rush to a conclusion that turns out to be hollow. If you can resist the urge to demand certainty from them prematurely, what is forming is likely to be something they take seriously and remember.`,
    reversedLong: `The Hanged Man reversed as feelings most often describes someone caught in a stalled pattern around you — feelings that have not been processed, decisions that have not been made, an internal limbo they have been inhabiting for considerably longer than is healthy. They may still care about you in some real way, but the caring is no longer producing motion. They are circling the same thoughts about the connection, deferring the same conversation, and quietly hoping the situation will resolve itself without their having to risk anything definitive. It will not. The longer they hover in this suspension, the more the connection itself begins to take on the quality of indecision rather than genuine relationship.

There is also a particular kind of martyrdom this position surfaces — a willingness to endure a situation indefinitely, framed internally as patience or loyalty, that has actually become a way of not facing what they already know. They may feel stuck rather than free, sacrificed rather than committed. The feelings are real but they have curdled into something heavier than affection — closer to attachment held in place by fear of the alternative. They may not be able to articulate any of this clearly even to themselves, and if you ask directly about their feelings you are likely to receive answers that sound thoughtful but never quite resolve into anything you can act on.

Underneath, there may also be quiet resentment that they have not voiced. Resentment toward you for the position they feel themselves to be in, resentment toward themselves for not having chosen more clearly, resentment toward the situation for refusing to declare its own shape. None of this is necessarily fatal to the connection, but it does mean that what they currently feel is not a clean signal you can rely on. The pause they have been in has stopped producing insight and started producing inertia. Real movement, if it comes, will require one of you to genuinely break the suspension rather than continuing to hope it ends on its own.`,
    howTheyFeel: `Right now, they feel something for you that is real, but suspended. You are present in their thoughts more than they have probably admitted, and you have produced a shift in how they see things that has not yet translated into words or action. The pause is not the absence of feeling — it is the way feeling looks when someone is genuinely trying not to force it into a shape before it is ready. They are watching, listening, and quietly recalibrating their understanding of the connection rather than rushing to declare anything.

What this means practically is that demanding clarity from them at this moment is likely to produce either a partial answer they will later have to revise, or a defensive retreat. The kinder and more useful approach is to allow the suspension to do its work while you stay grounded in your own life. If something is genuinely forming, it will become clearer with time. If the pause has become avoidance, that too will become visible. Either way, the answer is forming. Your part is to remain honest with yourself about what you want and patient enough to let the situation reveal what it actually is.`,
    feelingsFaqs: [
      {
        q: 'What does The Hanged Man mean as feelings?',
        a: `The Hanged Man as feelings describes someone who is genuinely paused in their experience of you — not indifferent, not retreating, but suspended in a state of conscious consideration. They are seeing the connection from an angle they had not previously taken, and they are unwilling to rush to a conclusion that the situation has not yet earned. Underneath, there is usually real tenderness and a willingness to be changed by what is unfolding. The pause can look like passivity from outside but is more often receptivity — letting the connection work on them rather than forcing a premature resolution. Patience tends to be rewarded here.`,
      },
      {
        q: 'Is The Hanged Man a yes for love?',
        a: `The Hanged Man is not quite a yes and not quite a no — it is a "not yet" that is more hopeful than it sounds. In love readings, the card almost always points to a genuine pause rather than rejection, and the pause is often productive even when it is uncomfortable to sit inside. If you can tolerate the suspension without forcing a premature decision, what tends to emerge on the other side is sturdier than the rushed yes would have been. The card rewards patience and honest waiting. People who treat it as encouragement to slow down rather than as a verdict usually find it works in their favour.`,
      },
      {
        q: 'What does The Hanged Man reversed mean as feelings?',
        a: `The Hanged Man reversed as feelings most often describes someone stuck in a stalled pattern around you — caring in some real way, but unable to convert the caring into motion or clarity. They have been circling the same thoughts, deferring the same conversation, and quietly hoping the situation will resolve itself without their having to risk anything definitive. There may also be unspoken resentment and a martyrdom dynamic where they feel sacrificed rather than committed. The feelings are genuine but no longer produce a clean signal. Real movement will usually require one of you to break the suspension rather than wait for it to end on its own.`,
      },
      {
        q: 'Do they have feelings for me when The Hanged Man appears?',
        a: `Almost always yes, but the feelings are inhabiting a particular kind of stillness. The Hanged Man as feelings is rarely about absence of feeling; it is about feeling that has not yet found a form. They are thinking about you, considering you, and quietly reorienting around you, but they have not yet translated any of this into the language of declaration. If you can tolerate the ambiguity without forcing a premature answer, you tend to receive a more honest and more durable response than impatient questioning would produce. Their hesitation is rarely about you specifically; it is usually about the depth of what they are feeling.`,
      },
    ],
  },

  'death': {
    uprightLong: `Death as feelings describes someone moving through a profound transformation in their relationship with you, or in themselves, that is changing the entire texture of what they feel. Something they used to feel about the connection has genuinely ended, and something new is becoming possible in its place. This is rarely cold or rejecting. More often it is the experience of an old version of the bond falling away — the casual phase ending and something more serious arriving, or the surface-level attraction giving way to a deeper recognition, or an old wound finally healing enough to allow real intimacy. The card asks you to trust that the ending is in service of something more honest.

There is often a quietness about this kind of feeling because it is genuinely consequential. They are not in the early flush of attraction where everything is being broadcast outward; they are inside the slower work of becoming someone who can actually meet you. They may have less to say about it than the upright card suggests, simply because what is moving in them is too large for casual conversation. What they feel is sturdy rather than performative, and it tends to be expressed through quality of attention, follow-through, and a willingness to show up over time rather than through declarations.

What is also worth understanding is that Death as feelings often arrives at a threshold. They are letting go of who they were in order to meet you as who they are becoming, and the letting go has its own weight. Old patterns, old beliefs about love, old protective postures — these are being released, and the release is rarely entirely comfortable even when it is welcome. If you can give them room to grieve what they are releasing while also receiving what they are now able to offer, the connection that emerges tends to be considerably more honest than what came before. They are not playing at love. They are clearing the ground for it.`,
    reversedLong: `Death reversed as feelings most often describes someone clinging to an old version of the connection that has, in some essential way, already ended. They may still be performing the role they used to play — attentive, present, available — but the living current that once made the role meaningful has quietly departed. They cannot quite acknowledge this, and so the relationship continues in form while emptying in substance. It is one of the more painful dynamics to be on the other side of, because nothing obvious is wrong; there is just the slow recognition that the warmth has gone somewhere else and neither of you is quite naming it.

There can also be the inverse pattern: feelings frozen in a previous chapter that no longer exists. They are still emotionally inhabiting how things were six months or two years ago, still telling themselves the story they were telling then, still measuring the present against a past that is no longer accurate. This is a kind of emotional stuckness rather than rejection, but the effect on you is similar — you cannot reach the person they have become because they have not allowed themselves to become anyone new since the chapter they are still inside. Their feelings about you are about who you both were, not who you are now.

Underneath this, there is usually fear of endings — the fear that letting one phase die means losing everything, when in fact it would only mean honouring what has run its course and allowing what is genuinely alive to develop. Death reversed asks for honesty that neither of you has been able to offer yet. Until that honesty arrives, the feelings they have for you will remain entangled with what has already passed, and you will struggle to receive anything clean from them. Real care, if it is still there, will require one of you to name the ending before the new beginning can take its actual shape.`,
    howTheyFeel: `Right now, they are inside a real transformation in how they feel about you. Something is ending — perhaps an old way of holding back, perhaps a previous understanding of the connection, perhaps a defensive pattern that has been quietly limiting them — and something more honest is forming in its place. This is not a casual or surface-level shift. What they feel is becoming more substantial, less performative, and more capable of meeting you where you actually are. The transition has its own weight, and they may be quieter or more thoughtful than usual as they move through it.

What this means for you is that you are unlikely to receive the easy reassurance you might want, but what you receive instead tends to be more durable. Their attention has changed quality. Their follow-through has become more deliberate. The connection itself is being rebuilt on different ground. If you can hold steady while they finish releasing what needs to be released, what becomes available on the other side is usually considerably more honest than whatever was there before. They are not pulling away. They are clearing space.`,
    feelingsFaqs: [
      {
        q: 'What does Death mean as feelings?',
        a: `Death as feelings describes someone moving through a genuine transformation in how they relate to you — an old version of the connection ending so that something more honest can take its place. This is rarely cold or rejecting; it is more often the experience of a casual phase deepening, a surface attraction giving way to real recognition, or an old protective pattern finally relaxing enough to allow real intimacy. The feelings tend to be quieter than the upright card might suggest, because what is moving in them is too substantial for casual conversation. What they feel is sturdy and expressed through quality of attention rather than declarations.`,
      },
      {
        q: 'Is Death a yes for love?',
        a: `Death is a yes for love, but a particular kind of yes — the kind that involves real transformation rather than easy continuation. The card almost never points to literal endings of the heart-stopping variety; it points to the necessary endings that make deeper love possible. If you are willing to allow what needs to end to actually end — old patterns, surface dynamics, defensive postures — what tends to emerge is considerably more honest than what came before. The card rewards the willingness to move through transition rather than around it. Most lasting love includes several Death passages along the way.`,
      },
      {
        q: 'What does Death reversed mean as feelings?',
        a: `Death reversed as feelings most often describes someone clinging to a previous version of the connection that has, in some essential way, already ended — still performing the old role while the living current has quietly departed. It can also describe feelings frozen in a chapter that no longer exists, where they are still relating to who you both were rather than who you have become. Underneath is usually fear of endings and an inability to honour what has run its course. Until that honesty arrives, the feelings they have for you will remain entangled with what has passed, and you will struggle to receive anything fully alive from them.`,
      },
      {
        q: 'Are they interested in me when Death appears as feelings?',
        a: `Yes, but in a particular way — the interest is real and significant, but it is moving through transformation rather than sitting in easy attraction. They are letting go of something old to make room for something more honest with you, and the letting go has its own weight. What you may notice is more depth and less performance, more substance and less fluency, more quiet attention and fewer obvious signals. If you can read the deeper signal rather than waiting for the flashier one, you will see that the interest is there and is becoming more serious rather than less. Trust the slower texture.`,
      },
    ],
  },

  'temperance': {
    uprightLong: `Temperance as feelings describes someone whose feeling for you is patient, integrated, and genuinely balanced. They are not in a state of frantic infatuation, nor are they holding back from the connection; they are inhabiting the middle ground where real intimacy actually develops. What they feel is steady. They are letting the relationship breathe at its own pace, and they trust that what is forming between you does not need to be forced into a particular shape on a particular timeline. This kind of feeling is sometimes harder to read than the louder versions because it does not produce dramatic signals, but it is considerably more durable than the alternatives.

There is also a quality of integration in how they hold the connection. They are blending what they want from a partnership with what they understand about you — adjusting, accommodating, finding the natural rhythm rather than insisting on one of their own. They have probably been thinking about how their life and yours might fit together, not in the urgent way of someone trying to lock something down, but in the considered way of someone genuinely wanting to build something that works for both of you. They are willing to wait for the right time, the right pace, the right depth of mutual readiness.

What this often produces in practice is a feeling of safety. They do not flood you with intensity and then disappear; they do not run hot and cold; they do not require you to manage their emotional weather. The temperance they bring to the connection is itself a form of love, though it can take a while to recognise as such if you are accustomed to more dramatic forms of attention. If you can meet them in this measured place rather than reading the absence of drama as absence of feeling, what develops between you tends to be unusually grounded. They are showing up for you in the way that actually allows real intimacy to take root.`,
    reversedLong: `Temperance reversed as feelings describes someone whose feelings for you have fallen out of their natural balance — usually in one of two directions. Either they are over-investing in the connection too quickly, trying to accelerate intimacy that has not yet had time to genuinely form, or they are holding so much back that they have become emotionally unavailable to a connection that is actually trying to develop. Both patterns produce the same underlying problem: an inability to inhabit the patient middle in which real feeling actually grows. What they feel is real, but the way they are holding it has tipped into extremes.

There is also a particular impatience this position surfaces. They may be trying to force the relationship to declare itself before either of you has had time to really know what is forming. The push for a particular commitment, the demand for a particular pace, the insistence on a particular shape — all of these can be expressions of feelings that have lost their footing. Alternatively, they may be running hot and cold, swinging between intense closeness and chilly retreat, never quite settling into a rhythm that the connection can sustain. You may find yourself reactive rather than responsive in their company, which is usually a sign that the temperance has gone.

Underneath, there is often anxiety they have not named — about being chosen, about not being chosen, about whether the connection is what they wanted it to be, about whether they want what they thought they wanted. None of this is necessarily fatal to the bond, but it does mean that what you are currently receiving from them is not a clean signal. The work, if it is theirs to do, is restoration of flow — usually through doing less rather than more, allowing interactions to breathe at their own pace, and resisting the urge to force shape on something still finding itself. Until that happens, the feelings will continue to swing rather than settle.`,
    howTheyFeel: `Right now, they feel something steady for you — something that does not need to announce itself loudly to be real. The temperance they are bringing to the connection is itself a sign of how seriously they are taking it. They are not interested in dramatic gestures that cannot be sustained; they are interested in building something that can. What they feel is quietly integrated into their daily life rather than compartmentalised as a separate intensity, and you may notice that you appear in their thinking in small, consistent ways rather than only in big declarations.

For you, the medicine is to meet them in this measured place. If you have been reading the absence of drama as absence of feeling, consider whether what you are actually receiving is something better — the steady, undefended attention of someone who is genuinely available. Allow the pace they are offering to be enough. The slower rhythm is doing real work, and what tends to develop on this kind of foundation is considerably sturdier than the fast-burning alternatives. Trust the texture, even when your nervous system is asking for more obvious reassurance.`,
    feelingsFaqs: [
      {
        q: 'What does Temperance mean as feelings?',
        a: `Temperance as feelings describes someone whose feeling for you is patient, integrated, and genuinely balanced — neither in frantic infatuation nor holding back, but inhabiting the middle ground where real intimacy develops. What they feel is steady rather than dramatic, and they are letting the relationship breathe at its own pace. There is often a quality of integration in how they hold you, blending their wants with what they understand about you. The temperance itself is a form of love, though it can be harder to read than louder versions of feeling. If you meet them in this measured place, what develops tends to be unusually grounded and durable.`,
      },
      {
        q: 'Is Temperance a yes for love?',
        a: `Temperance is a steady yes for love — not the fast-burning kind that tends to flare and exhaust itself, but the patient kind that actually has the capacity to last. The card describes the alchemy by which two people genuinely come to fit each other, and it almost always points toward connections that develop sustainably over time. If you can accept that the yes comes with a pace of its own rather than the urgency you might prefer, the card rewards you generously. The relationships that Temperance describes tend to be quietly remarkable in their durability, even when they look unspectacular from outside.`,
      },
      {
        q: 'What does Temperance reversed mean as feelings?',
        a: `Temperance reversed as feelings describes someone whose feelings for you have fallen out of their natural balance — either over-investing too quickly, trying to accelerate intimacy that has not had time to form, or holding back so much that they have become emotionally unavailable. They may be running hot and cold, swinging between intense closeness and chilly retreat. Underneath, there is usually anxiety they have not named about the connection or about themselves. What you are receiving is not a clean signal. The remedy is patience and reduction of intensity rather than more effort — though that is rarely what either of you wants to hear.`,
      },
      {
        q: 'Do they love me when Temperance appears as feelings?',
        a: `Temperance suggests that what they feel for you is genuine, considered, and increasingly integrated into their actual life. Whether the word "love" applies depends on where the connection is in its arc — Temperance does not insist on the timeline of declaration. What the card does insist on is that the feeling is real and that it is being held with care rather than urgency. They are not playing games and they are not in retreat; they are letting the bond develop at the pace that allows it to actually take root. The love, when it is named, tends to be sturdy precisely because it was not rushed into being.`,
      },
    ],
  },

  'the-devil': {
    uprightLong: `The Devil as feelings describes a powerful, magnetic, sometimes obsessive pull — the kind of charge that overrides rational thought and makes the other person feel like a necessity rather than a choice. This is not the gentle warmth of Temperance or the steady recognition of Death; it is closer to the gravitational compulsion of an attraction they cannot easily set down. They want you in a way that has weight, and the wanting is partly outside their conscious control. There is real desire here, real intensity, and a sense that the connection holds something important even if it also feels a little overwhelming.

What sits just below the surface is usually a more complicated picture. The Devil rarely points to clean, simple attraction; it tends to surface where chemistry has tangled with other things — old wounds, projections, fantasies about being saved or completed by another person, longings that go back further than this particular connection. They may be projecting onto you qualities you partly have but partly do not, and the projection itself is part of what generates the heat. The intensity feels significant because, for them, it is — but the significance is not always entirely about you. Some of it is about what you represent to parts of them they have not yet examined.

What they feel is real, and it deserves to be respected rather than dismissed. But the card also asks you to look carefully at whether the dynamic between you serves both of your fuller selves or whether it primarily serves the parts of you that are looking for completion outside themselves. The most charged connections are not always the most nourishing, and the most nourishing are not always the most charged. If the Devil is the dominant tone here, expect the pull to be strong and the texture to be complicated. The honest question is not whether they want you — they do — but whether what is forming between you is the connection you actually want to be inside, or one that primarily replays an older pattern you have not yet outgrown.`,
    reversedLong: `The Devil reversed as feelings most often describes someone becoming aware of an unhealthy pattern in how they have been feeling about you, and beginning, sometimes painfully, to release it. The compulsive intensity is loosening. The chains they had not previously seen are becoming visible, and the visibility itself is the beginning of being able to remove them. This is generally a hopeful position, but it is rarely comfortable. What they are seeing may include their own projections, their own dependencies, their own use of the relationship to avoid something more difficult in themselves. They are not necessarily falling out of feeling for you; they are falling out of the particular distorted shape the feeling has taken.

There is also the version of this position where they are recovering from feelings that had become a form of self-betrayal. Perhaps they had been ignoring real incompatibility because the charge was too strong to set aside. Perhaps they had been accepting treatment they should not have accepted because they were afraid of losing the connection. Perhaps they had been performing a role with you that was not really who they are. The reversal often catches them in the moment of recognising this — the moment of beginning to want themselves back. What they feel for you is changing shape as that recovery proceeds, and the new shape may be more honest but also less intense than what came before.

Underneath, the work they are doing is real, and it usually requires support. Therapy, recovery communities, trusted friends — the structures within which honest shadow work actually proceeds. If you care about them, the most useful thing you can offer is patience with the unevenness of their process and respect for the boundaries they are beginning to find. The relationship that emerges on the other side of this passage, if there is to be one, will not be the same as what was there before. It will probably be quieter, more deliberate, and considerably more sustainable. But it will arrive only if both of you are willing to release what was running on compulsion in favour of what can run on genuine choice.`,
    howTheyFeel: `Right now, they feel a strong pull toward you — strong enough that they may not be entirely in control of it. The Devil as feelings is rarely subtle. There is desire, intensity, and a kind of weight to your presence in their thoughts that they have not been able to easily set down. Whether this is a yes you should welcome depends on what is fuelling the charge: real recognition, or projection; genuine compatibility, or the replay of an older pattern. The intensity itself is not the answer to that question. It is the question.

What this means practically is that you can probably trust the intensity is real, but the meaning of the intensity needs honest examination on both sides. The Devil rewards the people who are willing to look at what is actually happening between them rather than getting swept up in the heat. If you can stay grounded in your own life while the connection develops, and if you can ask honestly what the relationship is doing to you as well as for you, the answer that emerges tends to be considerably more useful than the answer the chemistry alone would produce. Heat is information, not destiny.`,
    feelingsFaqs: [
      {
        q: 'What does The Devil mean as feelings?',
        a: `The Devil as feelings describes a powerful, magnetic, often compulsive pull — desire that overrides rational thought and makes the other person feel like a necessity rather than a choice. There is real intensity, real wanting, and a sense that the connection holds something important. Underneath, the picture is usually more complicated: projections, old wounds, fantasies of completion, longings that predate this connection. What they feel is real, but the heat is rarely entirely about you alone. The card asks honest examination of whether the dynamic serves both of your fuller selves or whether it primarily replays an older pattern you have not yet outgrown.`,
      },
      {
        q: 'Is The Devil a yes for love?',
        a: `The Devil is a yes for intense desire, but not necessarily a yes for sustainable love. The card almost always describes a powerful pull, but it also surfaces the shadow side of attraction — compulsion, dependency, the parts of love that are partly about something other than the actual person. Whether this is the love you actually want depends on what the charge is built on. If there is real compatibility underneath the heat, the Devil can describe a genuinely passionate connection. If there is mostly projection, the connection tends to be costly. Read the card as invitation to look closely rather than as simple endorsement.`,
      },
      {
        q: 'What does The Devil reversed mean as feelings?',
        a: `The Devil reversed as feelings most often describes someone becoming aware of an unhealthy pattern in how they have been feeling about you, and beginning to release it. The chains they could not previously see are becoming visible. They are not necessarily falling out of feeling for you; they are falling out of the particular distorted shape the feeling had taken. This is generally hopeful but rarely comfortable, and the work it requires is real. The relationship that emerges on the other side tends to be quieter, more deliberate, and considerably more sustainable — if both of you are willing to release what was running on compulsion.`,
      },
      {
        q: 'Are they obsessed with me when The Devil appears as feelings?',
        a: `Yes, often quite literally. The Devil as feelings can describe genuine obsession — they think about you constantly, struggle to set you down, and feel the pull as something close to compulsion. This is flattering to receive and also worth examining carefully. Obsession is not the same as love, and the connections that begin with this intensity often need significant work to mature into something sustainable. If you find the dynamic returns to you with the same charge, treat the heat as information rather than verdict. What you do with the information matters more than the intensity itself.`,
      },
    ],
  },

  'the-tower': {
    uprightLong: `The Tower as feelings describes an emotional state that is in genuine upheaval — feelings that have either suddenly arrived with force or have been suddenly clarified by something that disrupted the previous picture. They may be in the middle of a real shock about how they feel toward you, or about something else in their life that is now reshaping their capacity to feel anything cleanly. Whatever the trigger, the structures they were previously operating inside have given way, and what they feel right now is unfiltered, urgent, and not entirely under control. This is not a steady signal. It is the lightning before the new sky.

What sits underneath the disruption is often a feeling that has been wanting to surface for some time and that finally has the conditions to do so. The Tower does not usually destroy what was actually working; it collapses what was built on false foundations. As feelings, this often means the polite version of how they thought they felt about you is falling apart, and something more honest — sometimes far stronger, sometimes far more uncertain — is being revealed. They may be surprised by the force of what is moving in them, and they may not yet know what to do with it. The honesty of the moment is the gift, even when the form of the gift is uncomfortable.

What they are open to is realer contact than they were able to offer before. Performances, pretences, and managed presentations have been disrupted; what is left is whatever was underneath. This can produce raw, urgent connection, but it can also produce confusion, because the new feelings have not yet had time to integrate. If you can meet them with steadiness while they are inside this passage, the connection that emerges tends to be more honest than what was there before. Tower moments rarely allow people to keep pretending. What is left after the dust settles is usually the truth of what they actually feel.`,
    reversedLong: `The Tower reversed as feelings most often describes a slow-burn revelation rather than a sudden one — feelings about you that have been gradually surfacing through small cracks, near-conversations, and the accumulating sense that something is not quite right with the previous arrangement. They may be trying to delay the reckoning, holding the structure together with increasingly desperate maintenance, but the foundations have already begun to give way. What they feel is in the process of changing, and they have probably been minimising this even to themselves for considerably longer than is sustainable.

There is also the post-Tower version of this position, where a disruption has already happened and what the reversal describes is the aftermath. The shock has occurred, the revelation has been spoken, and now they are sitting inside the dust, trying to figure out what to do with what has been revealed. Feelings in this state are often heavy, tender, and slow to find their shape. They may be exhausted by what has been disrupted and not yet able to imagine what comes next. None of this is the same as not feeling; it is feeling in a particular kind of recovery.

Underneath, the work the card asks is honesty about what the previous structure was actually holding. If they had been telling themselves a particular story about the connection, the Tower reversed often catches them in the moment of being unable to keep telling it. This is uncomfortable for both of you, but it is genuinely useful. What you receive on the other side, if you are still in contact when the dust settles, tends to be a considerably more accurate picture of what they actually feel — including parts that the previous structure had not allowed them to acknowledge. Slow Tower work is harder than the sudden version, but it tends to leave more usable rubble behind.`,
    howTheyFeel: `Right now, they are inside genuine emotional disruption around you. Something has shifted, or is shifting — either suddenly or through a slower accumulation of small revelations — and what they feel is not the controlled signal you might prefer. They may be surprised by their own reactions, struggling to articulate what is moving in them, or trying to hold a structure together that has already begun to fail. This is not stable territory. It is also not necessarily bad territory; the Tower's gift, even when it arrives as feelings, is the destruction of what was not actually working in favour of what might.

For you, the medicine is steadiness without pressure. Tower moments are rarely the right time to demand declarations; what you receive will probably not yet have settled into a form they can stand behind. If you can hold space without rushing to interpret what is happening, the picture tends to clarify on the other side of the disruption. What emerges is often more honest than what was there before, even when the process of getting there is uncomfortable. Trust the clearing, even before you can see what is being cleared for.`,
    feelingsFaqs: [
      {
        q: 'What does The Tower mean as feelings?',
        a: `The Tower as feelings describes a state of genuine emotional upheaval — feelings that have either suddenly arrived with force or have been suddenly clarified by something disruptive. The previous structures they were operating inside have given way, and what they feel right now is unfiltered and not entirely under control. Underneath the disruption is usually a feeling that wanted to surface for some time and finally has the conditions to do so. The honest version of how they feel about you is becoming visible, sometimes uncomfortably. What is left after the dust settles is usually the truth of what they actually feel, which is the gift of the card.`,
      },
      {
        q: 'Is The Tower a yes for love?',
        a: `The Tower is rarely a clean yes or no for love; it is a clearing of whatever was not actually true between you so that what is true can be seen. If the connection was built on something real, the Tower tends to reveal that solidity even as it destroys the surrounding pretence. If the connection was built on illusion, the Tower tends to reveal that too. The card rewards honesty rather than maintenance. People who treat the disruption as information about what is actually there usually find the eventual answer more useful than people who try to rebuild the old structure exactly as it was.`,
      },
      {
        q: 'What does The Tower reversed mean as feelings?',
        a: `The Tower reversed as feelings most often describes a slow-burn revelation rather than a sudden one — feelings about you that have been gradually surfacing through small cracks and accumulating disquiet. They may be trying to delay the reckoning, holding the previous structure together with increasingly desperate maintenance. It can also describe the aftermath of a Tower moment that has already happened, where they are sitting inside the dust and trying to figure out what comes next. The card is not easier than the upright version; in some ways it is harder because the discomfort is sustained over time.`,
      },
      {
        q: 'Do they have strong feelings when The Tower appears?',
        a: `Almost always, yes — though the strength is the strength of disruption rather than the strength of settled emotion. Tower feelings are intense because something significant is being revealed, destroyed, or restructured, not because the affection has stabilised into something predictable. They may not yet know what to do with what they feel, and they may produce signals that contradict each other while the dust is settling. Trust that the intensity is real without rushing to read it as a final verdict. The card's work tends to be clarifying even when it is uncomfortable, and the picture usually settles into something more honest than what came before.`,
      },
    ],
  },

  'the-star': {
    uprightLong: `The Star as feelings describes a quiet, hopeful, healing kind of feeling — the warmth that arrives after a long difficulty and asks to be received gently. They feel something tender for you, and the tenderness is connected to a larger sense that things in their life are becoming possible again. You are part of a season of renewal for them, whether or not either of you would have used that language. What they feel is not the heat of new attraction or the urgency of compulsion; it is closer to the slow return of faith — in themselves, in connection, in the future. This kind of feeling tends to be sturdier than its quietness might suggest.

There is also a quality of inspiration in how they hold you. You bring out something in them they had perhaps stopped expecting to feel — a willingness to be hopeful, a capacity for vulnerability, a sense that real intimacy is genuinely possible rather than only theoretical. They may be more themselves around you than they have been in some time, and this is not a small thing. Healing of any depth requires the safety to be honest, and the Star as feelings often indicates that you have become a presence in which that safety is available. They are not performing for you. They are letting themselves be seen.

What they are open to is unhurried real connection. They are not in a rush to define the bond into a particular shape; what they value is the quality of presence that the two of you have been able to create together. Star feelings tend to develop into the kind of relationships people describe years later as having been deeply formative — not because of dramatic moments, but because of the steady, healing texture they were able to inhabit. If you can receive this without demanding it be louder than it is, what is forming between you is likely to be one of the more genuinely nourishing connections of your life.`,
    reversedLong: `The Star reversed as feelings describes someone whose capacity for hope around you has dimmed, often because of disappointments that have nothing directly to do with you. Previous relationships may have left them more guarded than they realise. Recent difficulties in their life may have eroded their general faith in good things continuing. The accumulated weight of waiting for a connection to feel safe again may have produced a tiredness that is now expressing itself in their relationship with you. What they feel is not necessarily absent; it is muted, fenced in, or held at a careful distance that is more protective than rejecting.

There is also the version of this position where they are inside a more direct disillusionment with the connection itself. Something they had hoped about you, the relationship, or the future has not held up to closer examination, and the loss of that particular hope is colouring everything else they feel. This is rarely permanent, but it is real. They may be in the process of recalibrating what is actually available between you, and the recalibration carries some grief — for what they had imagined, for what they had begun to count on, for the version of the connection they thought they were inside.

Underneath, what often needs honest attention is whether the dimming is about something repairable or about a more fundamental mismatch that has finally become visible. The Star reversed does not always say the connection is over; sometimes it says the connection has been carrying expectations it was never going to fulfil, and that releasing those particular hopes is what will allow what is actually possible to take its real shape. What the card asks is honest engagement with what has dimmed and why. Forced positivity will not restore the light. Honest reckoning with what has been worn down, often supported by therapy or genuine rest, sometimes does.`,
    howTheyFeel: `Right now, they feel something gentle and hopeful for you — a feeling that has more to do with healing than with heat. You have become associated with a kind of safety they may not have felt in some time, and the safety itself is producing tenderness. They are not rushing. They are not performing. They are letting the connection do its slow work, and what is forming is unusually sturdy beneath its quiet surface.

For you, the medicine is to receive the gentleness without demanding it become louder. Star feelings rarely announce themselves dramatically, and reading the quietness as absence would be a mistake. If you can meet them in the unhurried, healing pace they are offering, what develops tends to be one of the more genuinely nourishing connections available to either of you. Trust the quality of presence more than the visibility of declaration. The light is real, even when it is the kind that shines without effort.`,
    feelingsFaqs: [
      {
        q: 'What does The Star mean as feelings?',
        a: `The Star as feelings describes a quiet, hopeful, healing kind of feeling — the warmth that arrives after long difficulty and asks to be received gently. They feel something tender for you that is connected to a larger sense of renewal in their life. You bring out a willingness in them to be hopeful again, to be vulnerable, to believe real intimacy is actually possible. The feelings are not loud, but they tend to be sturdier than their quietness suggests. What they are open to is unhurried real connection, and what develops on this foundation often turns out to be one of the more nourishing relationships of either of your lives.`,
      },
      {
        q: 'Is The Star a yes for love?',
        a: `The Star is a beautiful yes for love — not the fastest yes, but one of the most honest. The card describes feelings that are healing, hopeful, and quietly substantial, and the relationships it points to tend to be unusually nourishing in the longer run. If you can receive the slower pace without forcing more drama into it than it needs, what develops is the kind of love that genuinely makes both people better. The card rewards trust in the quality of presence over the quantity of declaration. Connections under the Star are usually the ones people are grateful for years later.`,
      },
      {
        q: 'What does The Star reversed mean as feelings?',
        a: `The Star reversed as feelings describes someone whose capacity for hope around you has dimmed — often because of disappointments that have nothing directly to do with you, but sometimes because something specific to the connection has not held up to closer examination. They may be more guarded than they realise, or more tired than they have admitted. The feelings are usually still there, but muted or protectively fenced. The card asks honest engagement with what has worn down the light, and recognition that forced positivity will not restore it. Real reckoning, often supported by rest or therapy, sometimes does.`,
      },
      {
        q: 'Do they love me when The Star appears as feelings?',
        a: `The Star is one of the more gentle and genuine indicators of real, healing love. Whether the word "love" applies in its declared form depends on where the connection is in its arc, but what the card describes is almost always the substance from which lasting love is made — safety, hope, honest vulnerability, and the quiet sense of being genuinely seen. They feel something real for you, and what they feel tends to deepen rather than fade with time. If they have not yet named it as love, what they feel is very often what love actually is before it finds the language for itself.`,
      },
    ],
  },

  'the-moon': {
    uprightLong: `The Moon as feelings describes a state that is genuine but heavily occluded — feelings present, but seen through fog, projection, dream, and unprocessed material from older parts of the psyche. They feel something for you, often something significant, but they are not currently able to see it clearly. Old fears, unresolved patterns, and unconscious associations are colouring how they read the connection, and the colouring may be more powerful right now than the actual signal underneath. What they feel may oscillate considerably depending on which inner weather is dominant on a given day.

There is also a quality of dream-like intensity to this kind of feeling. The Moon often produces emotion that feels almost archetypal — bigger than the literal facts of the relationship, charged with symbolism, animated by parts of them that are usually beneath waking awareness. This can be magnetic to receive but also unstable to rely on. Some of what they feel for you is real; some of it is projection of qualities you do not actually possess; some of it is their own unresolved material trying to find a hook in the present. Disentangling these strands is genuinely difficult, especially while inside the experience.

What they are open to is mostly what their unconscious permits, which may not be what their conscious mind would choose. They may be drawn to you and frightened of you in roughly equal measure, attached to you and unable to articulate why, present in some moments and elsewhere in others. None of this is necessarily evidence of bad faith. It is more often evidence of feeling that has not yet found its own clarity. If you can stay grounded in your own life while the Moon does its work, and resist the temptation to demand certainty from a person who currently has none to give, what eventually clarifies on the other side tends to be more honest than what could be reported at the height of the fog.`,
    reversedLong: `The Moon reversed as feelings most often describes a clearing of confusion — for better or for worse. The fog that has been distorting how they see you is beginning to lift, and what is becoming visible may be a relief or it may be unwelcome. Sometimes the reversal reveals that the fears they had been carrying about the connection were unfounded, and what they feel is actually steadier than they had been able to recognise. Sometimes it reveals the opposite — that the idealisation they had been carrying was not sustainable, and the actual person and connection are less than the dream had been suggesting. Either way, the picture is sharpening.

There is also the version of this position where they are integrating projections they had been making onto you. The Moon at its most distorting often turns the other person into a screen onto which old material is being cast; the reversal often catches the moment of recognising this. Some of what they had been feeling intensely was about you, and some of it was about earlier figures, earlier wounds, earlier patterns that had found you as a hook. As this becomes visible, the feelings recalibrate. They may feel less than they thought they did, or differently from how they had been describing it, or in a more honest way that is harder to summarise.

Underneath, the work is genuine recalibration. They are coming back to a more accurate read of the connection, which is good news in the longer run even when the immediate adjustment is uncomfortable. What you receive from them during this passage may be quieter, less certain, more measured. This is not necessarily withdrawal; it is more often a person who has stopped seeing you through distortion and is now trying to figure out what they actually see. Give the clarification time to settle. Reactive decisions made at the height of the recalibration tend not to age well, but the picture that emerges once the fog has fully lifted is usually one you can both work with honestly.`,
    howTheyFeel: `Right now, what they feel toward you is real but unclear — to them, and probably to you. The Moon brings a kind of dreamy intensity that resists tidy summary. They may be drawn to you in ways they cannot fully articulate, frightened by their own depth of response, or projecting onto you a mixture of who you actually are and who old material has primed them to expect you to be. The feelings are not fake. They are simply not yet clean enough to trust as a final read.

For you, the medicine is patience and groundedness. Do not demand declarations from a person who genuinely does not yet know what they are inside. Do not match their fog with fog of your own. Stay in your own life, keep your own discernment intact, and let the lunar phase complete its work. What clarifies on the other side tends to be more honest and more usable than anything available during the cloudiest stretch. Your steadiness, in the meantime, is a gift to both of you — it gives them something stable to find their way back to as the fog lifts.`,
    feelingsFaqs: [
      {
        q: 'What does The Moon mean as feelings?',
        a: `The Moon as feelings describes a state that is genuine but heavily occluded — feelings present, but seen through fog, projection, dream, and unprocessed older material. They feel something for you, often something significant, but they are not currently able to see it clearly. Old fears, unresolved patterns, and unconscious associations are colouring how they read the connection. Some of what they feel for you is real; some is projection; some is their own unresolved material seeking a hook. Disentangling the strands is difficult while inside the experience, and demanding clarity from them now usually produces an answer neither of you can trust.`,
      },
      {
        q: 'Is The Moon a yes for love?',
        a: `The Moon is rarely a clean yes or no for love; it is a "not while the fog is this thick." The card asks for patience and honest work rather than declarations. Real feelings are present, but they are tangled with material that needs to be sorted before the answer becomes reliable. People who try to push the card for a verdict usually receive something that contradicts itself within weeks. People who allow the lunar phase to complete its work — often with the support of honest conversation, time, or therapy — tend to find the answer that emerges on the other side is more durable than the answer the fog would have produced.`,
      },
      {
        q: 'What does The Moon reversed mean as feelings?',
        a: `The Moon reversed as feelings most often describes a clearing of confusion — for better or for worse. The fog that had been distorting how they see you is beginning to lift, and what is becoming visible may be reassuring (fears unfounded) or unwelcome (idealisation deflating). They may be integrating projections they had been making onto you, and the feelings are recalibrating as a result. What you receive during this passage may be quieter and more measured, which is not necessarily withdrawal. The picture that emerges once the fog has fully lifted is usually one you can both work with honestly, even if the immediate adjustment is uncomfortable.`,
      },
      {
        q: 'Are they confused about their feelings when The Moon appears?',
        a: `Almost always, yes. The Moon as feelings is one of the clearest indicators that the other person genuinely does not yet know what they feel — or rather, that what they feel is too tangled with other material to be reported reliably. They may oscillate between contradictory signals, struggle to articulate what is moving in them, or describe the connection differently on different days. None of this is necessarily bad faith. It is the actual texture of unresolved feeling. The kindest response is patience and your own groundedness while they sort through what is theirs and what is older material seeking expression.`,
      },
    ],
  },

  'the-sun': {
    uprightLong: `The Sun as feelings describes the kind of warmth that is simply, unmistakably good. They feel light around you. Being with you, or thinking about you, brightens their day in a way that is not complicated, not conditional, and not performed. This is the most uncomplicated positive card in the deck when it appears in feelings questions, and it usually means what it appears to mean. They are happy when you are present in their life, and the happiness is real rather than rehearsed. There is joy here, and the joy is being attributed in significant part to you.

There is also a quality of genuine seeing in how they hold the connection. The Sun's light makes things visible as they actually are, and as feelings this often means they are seeing you clearly and being delighted by what they see. They are not idealising you, not projecting, not falling for a version of you that you cannot sustain — they are responding to who you actually are with warmth and recognition. This is rarer than it sounds, and it is one of the most genuinely valuable foundations a connection can have. You are being received rather than imagined.

What they are open to is the full expression of the bond. They are not holding back, not playing strategic games about pace, not protecting themselves through measured doses of attention. They want more of you, more often, and they tend to be relatively transparent about this. The connection feels easy because, for them at this moment, it actually is. If you can match the openness rather than pulling back into more guarded patterns, what develops is generally one of the more straightforward and joyful connections either of you will have. The Sun is not subtle, and that lack of subtlety is the gift.`,
    reversedLong: `The Sun reversed as feelings describes warmth that is genuinely present but is being dimmed by something — insecurity, exhaustion, a residual habit of distrust, or a quiet difficulty allowing themselves the full receipt of what the connection is actually offering. The feelings are there. The light is real. But something keeps interfering with their ability to fully inhabit it. They may find themselves second-guessing what they receive from you, or doubting that they deserve the ease they are encountering, or unable to enjoy the connection without some small inner voice asking what is going to go wrong.

There is also the particular pattern of performed happiness this position surfaces. They may be presenting brightness to you because they want the relationship to feel good, while their actual interior texture is more complicated than they are letting you see. This is not usually conscious deception; it is more often the inability to bring difficulty into a connection they want to keep light. Over time, this kind of management produces a flatter rather than fuller bond, because the real person is being filtered before they reach you. The light becomes performed, and you start receiving the performance instead of the warmth.

Underneath, the work is allowing the joy to actually land. The Sun reversed often catches someone who has not yet learned to trust simple goodness — to receive love without bracing for its withdrawal, to enjoy ease without expecting it to cost them later, to inhabit happiness without immediately measuring its sustainability. None of this is your problem to fix, but it is useful to understand. If you can stay open and grounded in your own real warmth, you give them a steady source they may, over time, learn to actually receive. What is dimming the Sun in their feelings is usually older than the connection itself.`,
    howTheyFeel: `Right now, they feel something warm and uncomplicated about you — assuming the card is upright. Being with you is good. Thinking about you is good. The connection is producing the kind of easy joy that genuine compatibility tends to produce, and they are inclined to want more of it rather than less. There is no hidden agenda or strategic withholding; what you are receiving is more or less what is actually there. This is the most straightforwardly positive feelings card in the deck.

For you, the medicine is to receive the warmth without complicating it. If you have been waiting for some twist that makes the goodness less trustworthy, the Sun is asking you to consider that the goodness might just be the goodness. Match their openness with your own. The connections that take root under the Sun are often the steady, joyful ones that quietly become the most important relationships of a person's life. Let it be as good as it actually is.`,
    feelingsFaqs: [
      {
        q: 'What does The Sun mean as feelings?',
        a: `The Sun as feelings describes the kind of warmth that is simply, unmistakably good. They feel light around you, happy in your presence, and genuinely delighted by who you actually are. There is no idealisation or projection — they are responding to the real you with real warmth, which is one of the most valuable foundations a connection can have. They are not holding back, not playing strategic games about pace, not protecting themselves with measured doses of attention. What you receive from them is unusually transparent, and the joy is being attributed in significant part to you. It is the most straightforwardly positive feelings card in the deck.`,
      },
      {
        q: 'Is The Sun a yes for love?',
        a: `The Sun is one of the most enthusiastic yeses in the entire deck for love. It describes feelings that are warm, transparent, genuinely happy, and grounded in real recognition rather than fantasy. Connections under the Sun tend to be straightforwardly joyful and often quietly become the most important relationships of either person's life. The card rewards openness and matched warmth; it does not require strategy or careful management. If you have been waiting for a clearer signal than the Sun, you will probably wait a long time. Let the goodness be as good as it actually is.`,
      },
      {
        q: 'What does The Sun reversed mean as feelings?',
        a: `The Sun reversed as feelings describes warmth that is genuinely present but is being dimmed by something — insecurity, exhaustion, residual distrust, or a quiet difficulty allowing themselves the full receipt of what the connection is offering. The feelings are there; the light is real; but something keeps interfering with their ability to fully inhabit it. There can also be performed happiness, where they present brightness while the actual interior is more complicated. The work, if it is theirs to do, is allowing the joy to actually land. The dimming is usually older than the connection itself.`,
      },
      {
        q: 'Do they love me when The Sun appears as feelings?',
        a: `The Sun is one of the strongest indications in the deck that real, uncomplicated love is in play. Whether they have named it yet depends on where the connection is in its arc, but what the card describes is almost always the genuine substance of love rather than its less reliable precursors. There is warmth, recognition, joy, and the willingness to be openly happy in your presence. These are not the materials of infatuation or projection. They are the materials of real partnership. If the Sun is appearing repeatedly, take it at its face value — the love is genuinely there, and it is the durable kind.`,
      },
    ],
  },

  'judgement': {
    uprightLong: `Judgement as feelings describes someone who is being called, often quite forcefully, to reckon with what they actually feel about you and what they want to do about it. The card often appears at moments of significant emotional clarification — they have been hearing an inner call about the connection that they can no longer easily ignore, and the call is now producing a kind of pressure for honest acknowledgement. They may be in the process of forgiving something that needed forgiving, or releasing an old story about the relationship that had been quietly limiting them, or finally allowing themselves to recognise the depth of what has been forming.

There is also a quality of awakening to how they hold the connection. Things that had been present but unacknowledged are becoming undeniable. Feelings that had been filed away under other labels — friendship, curiosity, complication — are revealing themselves as something more significant. They are seeing the relationship in a different light than before, and the new light is asking for response rather than passive observation. This is the trumpet of the upright card sounding in feelings territory, and it is rarely a quiet experience for the person hearing it.

What they are open to is the larger version of what is possible between you. They are being asked to rise to the connection rather than play small around it, and many of them are answering the call. This can produce significant moves — declarations they had been postponing, commitments they had been hedging, conversations they had been avoiding. If you have been waiting for them to step into something realer, Judgement is often the card that catches the moment of stepping. What they feel is being clarified, and the clarification tends to favour honesty over comfort. Be ready for the directness when it arrives.`,
    reversedLong: `Judgement reversed as feelings most often describes someone hearing an inner call about you but actively avoiding it. They know what they feel, or they nearly know — but engaging with the knowledge would require them to act on it, and acting on it would require facing things they have been deferring. So the call gets reframed as distraction, the feelings get downgraded as confusion, the conversation that wants to happen gets postponed indefinitely. What is operating underneath is a reluctance to fully reckon with their own experience of the connection, often because the reckoning would imply changes they are not yet willing to make.

There is also the particular shadow of harsh self-judgement this card surfaces. They may be carrying guilt or shame around the relationship — about past behaviour, about how they handled something, about their own perceived inadequacy as a partner — that is functioning as an obstacle to present feeling. Rather than working through it honestly, they have been trying to manage it by minimising the connection or by performing a version of themselves that the guilt cannot reach. None of this is necessarily about you. It is about an internal verdict they have been refusing to either acknowledge fully or release, and the refusal is foreclosing on what could otherwise be happening between you.

Underneath, the work the card asks is honest reckoning without self-violence. If they could look at what they actually feel without the inner critic immediately weighing in, the picture would probably be clearer and more workable than they currently fear. But Judgement reversed describes the difficulty of doing this work alone, and many people in this position require support — therapy, honest friendship, time, a willingness to face the call rather than continue avoiding it. Until the reckoning happens, what they offer you will continue to be partial, hesitant, and complicated by material that has very little to do with the actual relationship. Patience is reasonable; indefinite waiting probably is not.`,
    howTheyFeel: `Right now, they are hearing an inner call about you. Whether they are answering it depends on where they are in the larger work the card describes — but the call itself is real, and what they feel is in the process of being clarified rather than continuing in its previous half-formed state. Something is asking them to recognise what is actually present between you and to choose, honestly, how to respond. This is consequential territory. Decisions made under Judgement tend to be the kind people remember years later as turning points.

For you, the medicine is to remain honest with yourself about what you want and to give them the chance to rise to the call without forcing the moment. If they are in the upright version of the card, you will probably hear from them in a more direct, more decided way than before. If they are in the reversed version, you may need to gently insist on the conversation that has been deferred for too long. Either way, your steadiness with your own truth is the appropriate posture. Judgement rewards the people who are willing to be honest about what they actually feel and want, and that begins with you.`,
    feelingsFaqs: [
      {
        q: 'What does Judgement mean as feelings?',
        a: `Judgement as feelings describes someone being called, often forcefully, to reckon with what they actually feel about you and what they want to do about it. They are hearing an inner call about the connection that they can no longer easily ignore. Feelings filed away under other labels are revealing themselves as something more significant. They are being asked to rise to the connection rather than play small around it, and many of them are answering. This can produce significant moves — declarations, commitments, conversations they had been postponing. What they feel is being clarified, and the clarification tends to favour honesty over comfort.`,
      },
      {
        q: 'Is Judgement a yes for love?',
        a: `Judgement is generally a yes for love, but a particular kind of yes — one that involves real reckoning rather than easy continuation. The card describes feelings being clarified and called toward genuine commitment, and the decisions made under it tend to be the kind that mark turning points in people's lives. If you are prepared to meet the directness the card produces with your own honesty, what develops is usually substantial. The card rewards both people being willing to actually rise to what is being asked. It is less a yes to the comfortable version of love than a yes to the real one.`,
      },
      {
        q: 'What does Judgement reversed mean as feelings?',
        a: `Judgement reversed as feelings most often describes someone hearing an inner call about you but actively avoiding it. They know what they feel, or nearly know, but engaging would require action they are not ready for. The call gets reframed as distraction; the feelings get downgraded as confusion; the conversation that wants to happen gets postponed. There may also be harsh self-judgement, guilt, or shame about the relationship that is functioning as an obstacle to present feeling. Until the reckoning happens, what they offer you will be partial and hesitant. Patience is reasonable; indefinite waiting probably is not.`,
      },
      {
        q: 'Are they thinking about me when Judgement appears?',
        a: `Yes, often considerably more than they have let on. Judgement as feelings frequently surfaces when someone has been quietly reconsidering the relationship and is now arriving at a clearer understanding of what they want. You have been in their thoughts in a more deliberate, more reflective way than usual. They may have been working through old material, reframing past chapters, or coming to a more honest view of what has been forming between you. Whether they have spoken any of this aloud yet depends on where they are in their process, but the inner activity is real. Expect, in the upright version, a more direct communication than you have previously received.`,
      },
    ],
  },

  'the-world': {
    uprightLong: `The World as feelings describes a sense of genuine arrival in their experience of you. They feel complete in the connection, integrated in their feeling for you, and at home in what has been forming between you. This is not the early excitement of new attraction or the agitation of unsettled desire; it is closer to the quiet, grounded satisfaction of having found something that fits. They are not still searching while they are with you. The connection feels whole, and the wholeness is being attributed in significant part to who you are and what the two of you have been able to create together.

There is also a quality of completed integration in how they hold the bond. Old patterns that might have interfered with real intimacy have been worked through enough not to dominate. Previous chapters have been allowed to close. The feeling they are bringing to you is not weighed down by unresolved material from elsewhere; it is the genuine current of what is alive between you in the present. This is rarer than it sounds. Most people bring more unfinished business to their relationships than they realise, and the World indicates someone who has done enough of the work to actually be available.

What they are open to is the full expression of the connection at its completed scale. They are not hedging, not waiting to see if something better comes along, not protecting themselves against eventual disappointment. They are ready to commit to what is actually here, often in ways that are explicit and structural — building a life together, formalising the partnership, weaving themselves into your future and you into theirs. If you can meet them in this fullness, what develops tends to be the kind of connection people describe years later as having been the genuine landing place after a long journey of looking. The World, in feelings, is the card of arrival.`,
    reversedLong: `The World reversed as feelings describes a connection at the threshold of meaningful completion or deepening that is not quite stepping through. They feel something significant for you and are close to genuinely arriving in the bond, but something is holding them back from the final step. Sometimes this is perfectionism — the relationship is "almost right" and they are waiting for it to become entirely right before they fully commit. Sometimes it is unfinished business from elsewhere that has not yet been completed enough to allow real arrival. Sometimes it is the simple human fear of stepping into something that asks for the full version of themselves.

There is also the version of this position where they are genuinely at the end of a chapter but cannot quite acknowledge the ending. The relationship has run a meaningful course, the cycle has reached its natural completion, and yet they continue to hover at the threshold rather than name what has actually happened. This is rarely cruelty; it is more often grief that has not yet found its language, or fear of what comes next, or the difficulty of admitting that something genuinely beautiful has reached its end. The feelings are still there, but they belong to a chapter that needs to close before either of you can fully move forward.

Underneath, the work the card asks is honesty about the final step. If you are at a threshold of deepening, what specifically is preventing the step into the next phase? If you are at the threshold of completion, what would the dignified ending look like, and what conversations are needed to allow it? The World reversed almost never suggests that the connection is meaningless or that the feelings are fake. It suggests that something is suspended at the doorway, and that the suspension itself is more costly than the actual movement would be. Indefinite hovering rarely produces the clarity that genuine engagement with the threshold does.`,
    howTheyFeel: `Right now, they feel something integrated and substantial for you — feelings that have arrived, or are very close to arriving, at their full shape. The World is the card of completion, and as feelings it almost always indicates someone who has done enough of their own work to actually be available to you, and who recognises in the connection something they have been moving toward for a long time. There is satisfaction here, and groundedness, and the quiet relief of finding what genuinely fits.

For you, the medicine is to receive the arrival without complicating it. If the card is upright, what they feel is sturdy and ready for the full version of partnership. If the card is reversed, what they feel is real but suspended at a threshold; the question is what specific step remains to be taken to allow genuine arrival. Either way, the connection is at a significant moment, and the way you meet it matters. The World does not appear casually. When it shows up in feelings, it is signalling that something meaningful is either fully here or asking to be allowed to fully arrive.`,
    feelingsFaqs: [
      {
        q: 'What does The World mean as feelings?',
        a: `The World as feelings describes a genuine sense of arrival in their experience of you — feelings that are integrated, complete, and at home in what has been forming between you. They are not still searching while they are with you; the connection feels whole, and the wholeness is being attributed in significant part to who you are. They have done enough of their own work to actually be available, and they are ready to commit to what is here, often in explicit, structural ways — building a life together, formalising the partnership, weaving their future into yours. The World, in feelings, is the card of arrival, and it tends to mean what it appears to mean.`,
      },
      {
        q: 'Is The World a yes for love?',
        a: `The World is one of the most affirmative yeses in the deck for love. It describes a connection that has reached, or is reaching, the kind of completion that allows real partnership. The feelings the card indicates tend to be integrated, durable, and ready for commitment rather than still in the early formative stages. Connections under the World are often the ones people describe years later as the genuine landing place after long searching. If you have been waiting for a definitive sign of readiness, the World is one of the clearest you can receive. Allow the arrival to be as real as it actually is.`,
      },
      {
        q: 'What does The World reversed mean as feelings?',
        a: `The World reversed as feelings describes a connection at the threshold of meaningful completion or deepening that is not quite stepping through. They feel something significant for you but something is holding them back from the final step — perfectionism, unfinished business elsewhere, fear of what full commitment would ask. It can also describe a chapter at its natural end that has not yet been honestly named. The card almost never suggests the feelings are fake; it suggests something is suspended at the doorway. The work is identifying what specific step remains and what has been keeping it untaken. Indefinite hovering tends to cost more than actual movement would.`,
      },
      {
        q: 'Do they love me when The World appears as feelings?',
        a: `Yes, in a particularly grounded and arrived sense. The World as feelings is one of the strongest indicators in the deck that real, fully integrated love is in play — love that has done its inner work, completed its previous chapters, and is ready to commit at scale. Whether they have named it yet depends on where the connection is in its arc, but what the card describes is almost always the substance of mature, durable love rather than its earlier, less reliable stages. If the World is appearing repeatedly in feelings questions about this person, take it at face value. The love is genuine, and it is the kind that lasts.`,
      },
    ],
  },
}
