import type { FeelingsContext } from '../card-feelings-extended'

// Major Arcana part 1: The Fool through Justice (cards 0–11)
export const MAJOR_1: Record<string, FeelingsContext> = {
  'the-fool': {
    uprightLong: `When The Fool appears as feelings, it points to something fresh and uncalculated stirring in the other person — a curiosity about you that has not yet decided what shape it wants to take. They feel light when they think of you. There is a flicker of possibility, a sense that something interesting could begin here, and importantly they have not yet built up the protective storylines that usually accompany attraction. The feelings are pre-narrative. They are not yet asking what this is or where it is going; they are simply enjoying the small lift you bring into their day.

Underneath that lightness, there is often a genuine readiness for a new chapter. Whatever was occupying their emotional life before — an old relationship still being processed, a long period of self-protection, a season of just getting on with it — has begun to loosen its grip. You have arrived at a moment when they are unusually open, and the openness itself is part of what they are feeling. That is why the energy can feel both intense and weirdly weightless at the same time.

The honest caveat is that this openness has not yet had to survive contact with much reality. The Fool's emotions are real, but they are also untested. The person feels drawn rather than committed, intrigued rather than certain. Hold the warmth without rushing to define it. If what they feel is genuine, it will keep arriving in less abstract forms; if it is only the bright start of nothing in particular, that will also become clear. For now, they feel something quite simple — alive in your direction.`,
    reversedLong: `The Fool reversed as feelings points to emotions that have either curdled into anxious hesitation or skidded into reckless extremes. The most common pattern is a person who senses something genuine toward you and immediately starts negotiating with themselves about whether it is safe to feel. There is interest, but it is being held behind a wall of pre-emptive doubt — old hurts, half-finished stories with previous people, a quiet fear of being naive again. What they feel is real, but they are not letting themselves be moved by it because being moved feels exposing in a way they are not ready for.

The other expression is more chaotic: feelings that spike without grounding, intense one week and absent the next. They are excited by the idea of you without being entirely in the relationship with the actual you, and the gap between fantasy and reality keeps producing whiplash. This is not duplicity so much as immaturity around their own emotional life. They have not learned to stay with a feeling long enough to let it become something durable, so what arrives as enthusiasm tends to drift, return, drift again.

Beneath both patterns is usually a fear of getting it wrong. The reversed Fool is the heart that wants to leap and has been taught — by parents, by ex-partners, by past mistakes — that leaping is dangerous. So what they feel for you keeps surfacing and being talked out of itself. Take it as information rather than verdict. If you matter to them, the wobble will eventually settle into something more honest, often when they have done some private work you will not be there to witness.`,
    howTheyFeel: `When this card shows up to describe how someone feels about you, the texture is light, curious, and slightly nervous in a pleasant way. You are not a settled topic in their head yet — you are a question they keep finding themselves drawn back to. They think of you in unguarded moments and feel a small lift, a sense that something nice could happen, without yet knowing exactly what they want that something to be. There is real warmth here, but it is the warmth of a beginning, not the gravity of a long-standing love.

If The Fool reversed surfaced instead, the picture is the same draw with more friction. They feel something, and then they catch themselves feeling it, and then they retreat a little, and then they come back. Try not to read every wobble as disinterest. With this card the wobble is part of the feeling itself — a person letting themselves want something and not quite trusting that the wanting is allowed.`,
    feelingsFaqs: [
      {
        q: 'What does The Fool mean as feelings?',
        a: `The Fool as feelings describes a fresh, uncalculated draw toward you. The person feels light when you cross their mind, curious about where this might go, and emotionally readier than they have been in some time. The feelings are real but pre-narrative — they have not yet decided what to call the connection, and they are not running it through their usual filters. There is openness, mild excitement, and a sense of possibility without much pressure. It is one of the warmer cards to receive about another person's emotions, as long as you remember that warmth at the start of something is not the same as commitment.`,
      },
      {
        q: 'Is The Fool a yes for love or feelings?',
        a: `As a feelings reading, The Fool leans yes but in a specific register: yes, they are open; yes, they feel something fresh; yes, they would step toward you given the right opening. It is not the certain yes of a deeply settled love — it is the willing yes of a new beginning. That distinction matters. Treat it as encouragement to be present and curious rather than as a guarantee of where the connection will land. If you let it unfold honestly, The Fool's optimism tends to mature into something more durable; rushing to lock it down too early is the thing that most often dissipates the energy.`,
      },
      {
        q: 'What does The Fool reversed mean as feelings?',
        a: `The Fool reversed as feelings usually points to genuine interest that is being held back by hesitation, old hurts, or chaotic timing. The person feels something but does not entirely trust the feeling — they may have been burned before, may not be sure they are ready, or may be oscillating between enthusiasm and retreat without quite knowing why. It is rarely about you personally. It is almost always about an unresolved relationship with their own openness. Read it as feelings under construction rather than feelings withheld. The work, if there is work, is theirs to do.`,
      },
      {
        q: 'Does The Fool mean they are interested in me?',
        a: `Yes — The Fool surfacing as someone's feelings about you generally indicates real interest, expressed in a light and curious key rather than a heavy declarative one. They are drawn to you, they feel something fresh when you appear, and they are unusually open to whatever might come next. The catch is that their interest is still finding its shape, so it can look unsettled from the outside. Trust the warmth, give it room to develop, and resist the urge to demand definitions before the feelings have grown into themselves. The interest is there; what matters now is the texture of what you build with it.`,
      },
    ],
  },

  'the-magician': {
    uprightLong: `The Magician as feelings describes a focused, intentional attraction. When this card surfaces to name another person's emotions toward you, it points to feelings that have crystallised enough to become directed. They are not drifting around the idea of you; they are choosing you, in some quiet way, and the choosing has started to shape how they show up. The Magician is the card of will applied to desire, which means the person is no longer simply curious about you — they have begun to gather their attention, their words, and their plans into something pointed in your direction.

There is often a sense of capability in this energy. They feel that they could actually build something with you, and that confidence is part of what they feel. The Magician is not the dreamy attraction of someone hoping things will work out; it is the more grounded sense of someone who knows how to make things happen and has decided that you are worth the effort. Practically, this can show up as initiative — they reach out, they remember details, they create occasions to see you — and emotionally, it shows up as a sense of clarity about what they want from the connection.

The honest note is that The Magician's energy is most beautiful when intention is matched by integrity, and the card asks the same of both people in a connection. If their feelings are real, expect to see consistency between what they say and what they do. If you only see one of those, the card is naming something closer to its shadow form. Watch the whole pattern, not the polished moments. When it is genuine, this is one of the more powerful "as feelings" cards you can receive — somebody who feels strongly enough to act, and skilled enough to act well.`,
    reversedLong: `The Magician reversed as feelings is a difficult card to read kindly, because at its core it describes a gap between presentation and substance. The most common pattern is a person whose attention toward you is curated rather than genuine. They are skilled at producing the appearance of interest — the right words, the timely message, the charm that arrives precisely when you are about to step back — and what is missing is the inner reality those gestures are supposed to express. They may feel something, but the feeling is mostly about managing your perception of them rather than letting themselves be seen as they actually are.

A softer reading is that they have real feelings and are simply not letting any of it land. The talent for connection is there, the desire is there, and yet some combination of fear, distraction, or unworked-through history keeps them performing instead of arriving. You may have noticed that conversations with them can feel a bit two-dimensional, as though you are getting a polished version rather than the person inside it. This is rarely cynical. More often it is a habit of self-protection that has hardened into a style, and they may not even realise they are doing it.

The harsher reading is worth naming because it is sometimes true: feelings being deployed strategically, attention being given as leverage, charm being used to keep you available without offering much in return. Trust the pattern over the moments. If their words consistently overshoot their actions, if every clarifying conversation produces a smooth resolution that nothing actually follows, the card is telling you something. The Magician reversed in feelings is asking you to look for the substance underneath the signal — and to take seriously what you find, or do not find.`,
    howTheyFeel: `When this card describes how someone feels about you, there is genuine intention in the air. They have moved past wondering about you and into wanting you, and that wanting has begun to organise their behaviour. You are on their mind in a way they have decided to do something with. There is confidence in the feeling — not arrogance, but the quiet sense that they could build something good with you if the timing and the openness are there.

If the reversal showed up instead, read the picture more cautiously. Their feelings may be real, but the way they are being expressed is doing more work for their image than for the connection itself. Watch what they actually do over a few weeks, not just what they say in a single sparkling conversation. The Magician's gift, in either orientation, is the capacity to direct energy toward a chosen end — and your job is to figure out, honestly, what end they have actually chosen.`,
    feelingsFaqs: [
      {
        q: 'What does The Magician mean as feelings?',
        a: `The Magician as feelings indicates a focused, intentional attraction. The person is not just curious about you — they have begun to direct their attention, time, and actions toward the connection. There is confidence in what they feel and capability behind it; they sense that something real could be built with you, and they are willing to do the work it would take. This is one of the more decisive "as feelings" readings you can receive. When it is genuine, expect to see consistency between what they say and what they do — the card is most beautiful when intention and integrity move together.`,
      },
      {
        q: 'Is The Magician a yes for love?',
        a: `As a feelings reading, The Magician usually points to yes — with the important caveat that this card is about deliberate action rather than fated romance. They are interested, they have decided to act on the interest, and they have the skill to do so well. Look for follow-through. If their attention is matched by behaviour over time, this is one of the more substantial yeses in the deck. If it is all surface and no substance, you are looking at the reversed expression. The card asks you to read the whole pattern honestly rather than reacting to single moments of charm.`,
      },
      {
        q: 'What does The Magician reversed mean as feelings?',
        a: `The Magician reversed as feelings often signals a gap between presentation and substance. Either the person is performing interest without letting the real feeling land, or they are using attention strategically rather than offering it honestly. Sometimes the feelings are real but their habit of self-protection turns them into curated displays; sometimes the dynamic is more cynical. The way to tell is consistency over time. If words and actions track together, you are likely looking at someone working through old fears. If they consistently overshoot or misalign, the card is naming something you should take seriously.`,
      },
      {
        q: 'Does The Magician mean they love me or are interested in me?',
        a: `Yes — The Magician as someone's feelings about you generally indicates real, intentional interest. It is not the floating curiosity of a beginning; it is the directed energy of a person who has made some kind of internal decision about you and started acting on it. Whether that interest is yet love depends on how long the connection has been forming and what other context surrounds the reading. What is clear is that you are not an idle thought to them. They feel something pointed and active, and they are putting at least some of their will into the connection. Trust the pattern of their behaviour to tell you the rest.`,
      },
    ],
  },

  'the-high-priestess': {
    uprightLong: `The High Priestess as feelings describes emotions that are deep, real, and largely unspoken. The person feels something significant toward you, but the feeling is happening in a register beneath their usual vocabulary — they may not yet have words for it, and they may not yet be ready to share what they do have. This is not coldness or withholding so much as the natural quiet of feelings that have not been processed into language. The High Priestess sits between the pillars holding what cannot yet be said, and her appearance as someone's emotions toward you means that there is genuine inner content even if very little of it is reaching the surface.

There is often an intuitive recognition in this energy. They sense something about you — a familiarity, a depth, a feeling that you are different from the people they usually encounter — and the recognition itself is part of what they feel. They may not be able to explain why you matter, but they know that you do, and the knowing has the quality of something arrived at rather than worked out. That is precisely why the feelings can be hard to read from outside: the person is registering you through channels they themselves do not fully trust or articulate.

The honest texture is patience. The High Priestess does not rush, and feelings carried in her current tend to take their own time to surface. If you push for clarity too early, you may find them retreating further into their inner world rather than meeting you in shared language. Let things unfold. Pay attention to the quiet signals — the way they remember small things, the moments of unexpected attentiveness, the long looks that say more than the brief sentences. The feelings are present and substantial; they simply do not announce themselves the way other cards' feelings do.`,
    reversedLong: `The High Priestess reversed as feelings points to emotions that have been suppressed, distorted, or hidden — either from you or from the person themselves. The most common pattern is feelings that the person is refusing to acknowledge fully. They sense something toward you and they keep talking themselves out of taking it seriously, often because acknowledging it would mean having to act on it, and acting on it would mean exposing parts of themselves they prefer to keep private. The intuitive knowing is there; it is being overridden.

A different reading is more concerning: feelings that are being deliberately concealed, perhaps because they are entangled with circumstances you do not have full visibility on. Another relationship, an unresolved situation, a context that makes their emotions inconvenient to express openly. The reversed High Priestess is the classic card of the partially hidden picture, and when she surfaces as someone's feelings, it sometimes means there is more going on than has been shared with you. This does not always indicate dishonesty in the active sense, but it does mean that the full story has not yet arrived.

The third pattern is internal suppression: a person whose own intuition is telling them something about the connection — sometimes positive, sometimes ambivalent — and who is refusing to consult it because the answer would be inconvenient. They may be in a mental loop, reasoning about you in ways that override what they actually feel. None of these patterns are necessarily fatal, but all of them require honesty to resolve, and honesty is exactly what the reversed Priestess is asking for. Trust your own quiet sense of the situation as much as you trust the words you are being given; with this card, your intuition is often more accurate than the explicit narrative.`,
    howTheyFeel: `When The High Priestess describes someone's feelings about you, the picture is quiet but full. There is real depth in what they feel — possibly more than they have shown, possibly more than they have admitted to themselves — and the feelings are arriving through channels that do not always translate cleanly into conversation. They sense something significant about you, even if they have not found the words for it yet. You may be a recurring thought, a quiet pull, a person they have not stopped considering even when they have been silent.

If the reversal showed up, treat the silence with more care. Either they are keeping something deliberately, or they are refusing to look at what they feel, or there is context you do not yet have. Listen to your own intuition about the connection alongside their explicit signals. The High Priestess always asks for genuine inner consultation, and her message in either orientation is the same: trust what you sense, not just what you are told.`,
    feelingsFaqs: [
      {
        q: 'What does The High Priestess mean as feelings?',
        a: `The High Priestess as feelings describes deep, real emotions that the person has not yet put into words. They sense something significant about you — often something they themselves cannot quite explain — and the feeling is moving in registers underneath their usual conversation. It is rarely cold; it is simply quiet. Patience and attention to small signals will tell you more than direct interrogation will. If you push for premature definition, the energy tends to retreat. Let the connection unfold and watch the unspoken indicators: the lingering glance, the remembered detail, the moments of presence that do not need announcing.`,
      },
      {
        q: 'Is The High Priestess a yes for love?',
        a: `As a feelings reading, The High Priestess is closer to a thoughtful "maybe with depth" than a clean yes or no. Real feeling is present, but it is in a stage of inner gestation rather than expressed commitment. The person is feeling something genuine, but they are also not ready to declare it, and rushing them past that stage usually backfires. Read this card as encouragement to be patient and attentive rather than as a green light to push for clarity. What the Priestess promises is depth, not speed. If you can stay with the quiet long enough, what is forming underneath has a good chance of becoming substantial.`,
      },
      {
        q: 'What does The High Priestess reversed mean as feelings?',
        a: `The High Priestess reversed as feelings usually signals that something is being hidden, suppressed, or unconsulted. Either the person is refusing to look honestly at what they feel toward you, or they are deliberately keeping aspects of their situation private, or there is unresolved context you do not have full access to. Your own intuition is unusually important under this card — the explicit narrative may not be the most reliable source of information. Trust the quiet sense in your own body about the connection. The reversed Priestess almost always indicates that the full picture has not yet been shared, and the honest move is to attend to what you genuinely sense.`,
      },
      {
        q: 'Does The High Priestess mean they have deep feelings for me?',
        a: `Often yes, but the depth is held inwardly rather than shown openly. The High Priestess as someone's feelings about you usually points to genuine, significant emotion — sometimes more than the person has expressed, sometimes more than they have even acknowledged to themselves. The catch is that depth of feeling does not always translate into visible behaviour with this card. They may think of you often without telling you. They may treasure small interactions in ways you would not guess from the outside. If you want to know how much they feel, watch what surfaces in quiet moments rather than what gets said in performative ones.`,
      },
    ],
  },

  'the-empress': {
    uprightLong: `The Empress as feelings is one of the warmest cards to receive about another person's emotions toward you. It describes a love that is generative, nurturing, and rooted in genuine care for who you are as a whole person. The feelings are abundant rather than scarce — they are not holding back, not measuring themselves, not waiting to see whether you deserve them. The person feels softly drawn to you in a sustaining way; thinking of you produces something close to warmth in their chest, and being with you produces a sense of having returned somewhere good.

There is sensuality in this energy as well, in the deepest sense of the word: an appreciation of you as embodied, particular, real. They are not in love with an idea of you. They are drawn to the specific way you laugh, the small habits, the texture of your presence. The Empress turns the abstract into the concrete and the conceptual into the felt, and that shift is part of what they are experiencing. They want to take care of you, to feed you, to make room for you in the rhythms of their life. The wanting comes from fullness rather than need.

A small honest note: The Empress's warmth can sometimes outpace structure. The feelings are real and abundant, but they do not always organise themselves into the kind of clear commitments that other cards represent. The person may love you without yet knowing how to fit that love into the rest of their life, especially if there are existing obligations, projects, or unfinished personal work in their world. Trust the warmth, and let practical clarity arrive in its own time. What is being offered here is genuine nourishment. Receive it without anxious analysis; the analysis can come later, if it needs to come at all.`,
    reversedLong: `The Empress reversed as feelings points to a disrupted current of nourishment between the person and you, or within their own life more broadly. The most common pattern is feelings that are present but depleted — they care about you, but they have so little to give right now that the care cannot quite reach you in its full form. Often the depletion has nothing to do with you. They are over-stretched at work, exhausted by family obligations, dealing with their own unresolved health or emotional matters, and the warmth that would normally flow toward you is being absorbed by everything else they are trying to hold.

A second pattern is feelings that have become functional rather than alive. They are still committed, in some sense; they still think of you; they still consider you part of their life — but the sensual, generative quality has faded. Things have become slightly perfunctory between you, perhaps without either of you naming it. This is not the dramatic crisis of conflict; it is the quieter crisis of warmth quietly going offline. The Empress reversed in this expression is asking whether the relationship is genuinely nourishing both of you or merely operating.

The harder reading is worth naming: care that has crossed from nurture into smothering, or affection that comes with strings. They may feel something real for you and express it in ways that crowd, control, or unconsciously demand reciprocation. This is less common than the depletion pattern, but it does appear, especially in relationships where one person is doing significantly more emotional labour than the other. Whatever the specific expression, the card is naming a circuit in need of repair. The feelings are not necessarily gone — they are simply not flowing well, and honest attention to why is the work.`,
    howTheyFeel: `When this card describes how someone feels about you, the energy is full, warm, and oriented toward your wellbeing. They want good things for you. They notice you in particular and specific ways — your tastes, your moods, your body, your story — and they want to add to your life rather than extract from it. There is real love here, and it is the kind of love that wants to feed, hold, and grow alongside you. You are not a project to them; you are a person they would like to take genuine care of.

If The Empress reversed surfaced instead, the warmth is still likely present, but something in the flow has been disrupted. They may care and be unable to show it well right now, or the connection may have lost some of its sensuality without either of you naming the drift. Treat the diagnosis as workable. The Empress, even reversed, is rarely a card of absent feeling. She is more often a card of feeling that needs the right conditions to surface again.`,
    feelingsFaqs: [
      {
        q: 'What does The Empress mean as feelings?',
        a: `The Empress as feelings describes a warm, abundant, nurturing love. The person feels genuinely drawn to you as a whole human being — your specifics, your body, your daily rhythms — and the draw is sustaining rather than anxious. They want to take care of you, to share their life with you in tangible ways, to add to your wellbeing. There is also sensuality in this energy: an appreciation of you as physically present and particular. It is one of the more nourishing "as feelings" cards in the deck. Receive it without rushing it; The Empress works in slow, generative time rather than in declarations.`,
      },
      {
        q: 'Is The Empress a yes for love?',
        a: `As a feelings reading, The Empress is a strong yes for love itself, and a softer yes for the structural questions around it. Their feelings are real, abundant, and oriented toward your wellbeing. Whether those feelings have yet organised themselves into the specific commitments you might be hoping for is a separate question — The Empress is wonderful with warmth and less precise with logistics. Trust the love, and give the practical shape of the relationship time to develop. What is being offered here is nourishment of a high quality. The rest tends to follow when the conditions are right.`,
      },
      {
        q: 'What does The Empress reversed mean as feelings?',
        a: `The Empress reversed as feelings usually points to genuine care that is currently struggling to flow well. Most often the person is depleted by other parts of their life and has less to give than they would like; sometimes the warmth between you has quietly become functional rather than alive; occasionally the care has crossed into smothering or comes with hidden conditions. In nearly every case, the feelings themselves are not absent — the conditions for expressing them have eroded. The work is to diagnose which condition has been neglected, in them or between you, and to bring honest attention to repairing it.`,
      },
      {
        q: 'Does The Empress mean they love me?',
        a: `Often yes — The Empress is one of the more genuine love-indicating cards when she appears as someone's feelings about you. The love she describes is not the dramatic infatuation of newer connections; it is the warmer, more sustaining affection of a person who genuinely wants to be in your life in a nourishing way. They see you in particular, they want to care for you, and they feel something close to home when you are present. If you have been wondering whether the feeling is real, this card is a strong indication that it is — provided the rest of the spread does not significantly contradict it.`,
      },
    ],
  },

  'the-emperor': {
    uprightLong: `The Emperor as feelings describes emotions that are steady, protective, and quietly committed. The person feels something durable toward you — not flashy, not performative, but solid in a way that has begun to organise their sense of the future. You are no longer a tentative thought; you are a structure in their life that they want to honour and build around. The Emperor's love is the love of someone who takes the idea of partnership seriously and who would rather demonstrate the feeling through reliability than through grand declarations.

There is often an element of protectiveness in this energy. They want to make sure you are alright. They notice your stress, they think about your security, they file away the practical details of your life in ways that quietly shape their decisions. This is not always the warmest-feeling kind of love from the outside — The Emperor can be reserved, sometimes slow to express what he feels in romantic language — but it is one of the most dependable. Their feelings have built themselves into how they show up rather than how they speak, and the showing up is consistent.

The honest texture is patience with the way the feelings express themselves. If you are looking for poetry, this card may disappoint; if you are looking for a person who will be there when it matters, the card is encouraging. There may also be a desire for clarity about the relationship's shape — they tend to feel safer when commitments are defined, expectations are clear, and the partnership has a recognisable form. This is not control so much as the way they organise care. When The Emperor's energy is healthy, it is the steady ground that lets other, lighter forms of love flourish on top of it.`,
    reversedLong: `The Emperor reversed as feelings points to a confused or imbalanced relationship with power inside their emotions toward you. The most common pattern is feelings that have tipped into control or rigidity. They care about you, but the caring has begun to express itself as managing — wanting to direct your choices, define the relationship unilaterally, set the terms of how care is given and received. This can range from the heavy-handed to the subtle, but the through-line is the same: their love is real and their love is also doing more administrative work than relational work.

A different and equally common pattern is emotional reserve so pronounced that it functions as withholding. They may feel something durable toward you and refuse, or fail, to soften it into anything visible. Affection arrives in a register so muted that you have to interpret it, and the interpretation gets exhausting. Sometimes this is old conditioning around vulnerability; sometimes it is genuine inability to access the emotional range a real partnership requires. Either way, what they feel is not reaching you in a form you can receive, and that disconnect is itself a problem.

A third reading worth naming is the absence of structure where structure was implicitly promised. Feelings that should have settled into commitment have remained suspended — they care, they say so, and yet they refuse to define the relationship in any way that would actually obligate them. This is The Emperor's authority used in reverse: keeping the benefits of partnership without consenting to its responsibilities. The card is asking you to look honestly at how their feelings are being expressed. Real authority in love is in service of the relationship, not in charge of you, and an Emperor unwilling to be either of those is offering something quite hollow.`,
    howTheyFeel: `When this card describes how someone feels about you, the texture is steady, protective, and largely demonstrated through behaviour. They are not a person of dramatic declarations. They are a person who keeps appointments, remembers your birthday, notices when something is wrong, and quietly arranges for things to be alright. Their feelings have woven themselves into their habits, and the habits are how the love shows up. If you can read the unflashy signals, there is a lot here.

If The Emperor reversed appeared instead, watch the shape of the care more carefully. Are their feelings expressed as support, or as control? Is the steadiness present, or is it actually withholding wearing the costume of stoicism? The reversed Emperor still cares — usually — but the way the caring is being expressed has gone wrong somewhere, and naming the specific dysfunction is what allows the connection to either heal or be honestly let go.`,
    feelingsFaqs: [
      {
        q: 'What does The Emperor mean as feelings?',
        a: `The Emperor as feelings describes steady, protective, structurally serious emotions. The person feels something durable for you and tends to express it through reliability rather than declarations — keeping commitments, noticing practicalities, organising parts of their life around the idea of you. It is not always the warmest-feeling card from outside, but it is one of the most dependable. If you can read undramatic signals, the love here is real and quietly substantial. Expect commitment-readiness and a desire for the relationship to have clear shape; this is how Emperor energy organises its care, and it is rarely an accident when it appears.`,
      },
      {
        q: 'Is The Emperor a yes for love?',
        a: `As a feelings reading, The Emperor is usually a yes — the kind of yes that takes itself seriously. They feel something stable for you and are prepared, in principle, to back the feeling with structure. The caveat is that their expression of love tends to be steady rather than effusive, so if you are reading every gesture for romantic intensity you may underestimate what is actually present. Trust the consistency. If their actions are reliable over time and the relationship is moving toward definition rather than away from it, the yes is real, even if it does not announce itself in the language you expect.`,
      },
      {
        q: 'What does The Emperor reversed mean as feelings?',
        a: `The Emperor reversed as feelings usually signals a distortion of how care is being expressed. Either their feelings have tipped into control or rigidity, or they are so reserved that affection rarely reaches you, or they want the benefits of partnership without accepting its responsibilities. Real feeling is often still present, but the way it is being expressed is not serving the relationship. The diagnostic question is whether their authority in love is in service of you and the partnership, or whether it is busy managing, withholding, or evading. Loosen where they have gripped, commit where they have evaded — those are the directions of repair.`,
      },
      {
        q: 'Does The Emperor mean they are serious about me?',
        a: `Yes — The Emperor is one of the strongest indicators in the deck that someone is taking you seriously. He surfaces when feelings have moved past curiosity or infatuation and into the territory of intended commitment. They are thinking about you in a long-term way; they are organising their decisions with you in mind; they would prefer the relationship to have a defined and recognisable shape. The expression may be quieter than you would like, but the substance is there. If you have been wondering whether you are something real to this person, The Emperor's appearance suggests strongly that you are.`,
      },
    ],
  },

  'the-hierophant': {
    uprightLong: `The Hierophant as feelings describes emotions that are values-driven and oriented toward something durable. The person is not simply attracted to you — they sense that you share, or might share, the deeper things that matter to them. There is a recognition in this energy of compatibility at the level of meaning rather than just chemistry. They feel that you could fit into the long shape of their life, that your values seem to track with theirs, and that a relationship with you would honour rather than disrupt the things they hold sacred.

There is often a traditional cast to the feelings as well. They are thinking of the relationship in established frameworks — partnership, commitment, perhaps family, perhaps marriage — and the framework is part of what feels safe to them about you. This is not necessarily conventional in a stale sense; it is more that they want what they feel to be recognisable and supported by the structures they trust. They may also be drawn to your steadiness, your principles, the way you carry yourself in the world. You feel like someone they could introduce to the people whose opinions matter to them.

The texture of these feelings is patient and somewhat formal. The Hierophant does not rush, and the person experiencing this energy is likely to want the relationship to develop in a way that feels appropriate, deliberate, and honourable. They may prefer to define what is happening before they let themselves feel everything they could feel. If you read this as coolness, you may misjudge. The reserve is part of the respect. When The Hierophant's feelings are real, they tend to deepen rather than fade, and they tend to result in something that lasts.`,
    reversedLong: `The Hierophant reversed as feelings is a more complicated card. The most common pattern is feelings that are in tension with the frameworks the person normally lives inside. They may genuinely care about you and simultaneously feel that this connection does not fit the script their family, faith, culture, or earlier life had written. The friction is internal as much as external. Their emotions and their inherited templates are not aligned, and they have not yet found the courage or the clarity to choose between the two.

A second reading is a values misalignment between you that has not been honestly examined. The Hierophant is fundamentally about shared deeper meaning, and reversed he can describe feelings that exist in spite of significant differences rather than because of resonance. They may enjoy you, feel drawn to you, and quietly suspect that you want different things from life. Without honest conversation, this mismatch tends to surface eventually, often after one or both of you has invested more than the gap can comfortably hold.

A third pattern worth naming is rebellion-driven attraction: feelings that are partially fuelled by the fact that you do not fit what they were raised to want. This can be liberating in early stages and brittle later, because the energy of rejecting an old template is not the same as the energy of building something genuine. The reversed Hierophant in any of these expressions is asking you to take seriously the question of whether your values actually match. The feelings may be real, and they may also need much more honest examination than either of you has yet given them. Build on resonance, not on novelty.`,
    howTheyFeel: `When The Hierophant describes how someone feels about you, the energy is grounded in shared values and oriented toward something lasting. They are thinking of you in terms that include the long-term. You feel like a person whose life could fit alongside theirs, whose principles seem to align with their own. The feelings are warm in a stable rather than dramatic way, and they tend to express themselves through commitment-readiness rather than intensity.

If the reversal showed up, hold the picture more carefully. They may feel something for you and simultaneously feel that the relationship is in tension with the rest of their life, or that your values are quietly different from theirs. None of this means the connection is doomed; it does mean that the next stage of the relationship will require honest conversation about what each of you actually wants from a life, and whether those wants line up enough to build on.`,
    feelingsFaqs: [
      {
        q: 'What does The Hierophant mean as feelings?',
        a: `The Hierophant as feelings indicates values-aligned, commitment-oriented emotions. The person senses that you share, or might share, the deeper things that matter to them, and the recognition is part of why you feel safe to them. There is often a traditional cast to the feelings — they are thinking of partnership, perhaps marriage or family, perhaps long-term shared life — and the framework itself is part of what feels right. The energy is patient, deliberate, and respectful. If you can read the unrushed signals, there is something durable forming, often something they hope will last.`,
      },
      {
        q: 'Is The Hierophant a yes for love?',
        a: `As a feelings reading, The Hierophant leans yes in a particular register — yes to commitment, yes to the long form of love, yes to building something recognisable rather than something improvisational. They are taking the connection seriously and want it to develop in a way that honours both your principles. The caveat is that the energy is deliberate rather than spontaneous, so if you are looking for fireworks you may need to recalibrate. What the Hierophant offers is depth that earns itself over time. If that matches what you actually want, this is a strong card to receive.`,
      },
      {
        q: 'What does The Hierophant reversed mean as feelings?',
        a: `The Hierophant reversed as feelings usually points to genuine feelings in tension with frameworks. Either the person cares about you and the relationship does not fit the script they were raised with, or your underlying values are quietly different and the difference is being papered over, or part of the attraction is fuelled by the rebellion of not fitting an old template. In all cases, honest conversation about what you each actually want from a life is the work. The feelings may be real; the question is whether the foundation underneath them is built on resonance or merely on novelty and proximity.`,
      },
      {
        q: 'Does The Hierophant mean they want a serious relationship with me?',
        a: `Often yes — The Hierophant is one of the more commitment-indicating cards in the deck. He surfaces when someone is considering you in long-term, structurally serious terms, often including marriage, family, or the kind of shared life that requires real alignment of values. They feel something for you that they want to be permanent, and they are willing to take the slow road to make sure it can be. If you have been wondering whether they take the relationship seriously, this card is a strong indication that they do, provided the broader spread does not contradict it significantly.`,
      },
    ],
  },

  'the-lovers': {
    uprightLong: `The Lovers as feelings is one of the strongest cards in the deck for genuine romantic emotion. When this card surfaces to describe another person's feelings toward you, it points to a connection that feels significant, almost recognised — as though something in them has identified you as a person who actually matters, not just as a person who is currently around. The feelings have moved past attraction into a deeper resonance: a sense that you align with them in ways that go beneath surface compatibility, and that being with you would require them to be more themselves rather than less.

There is often a decisional quality in this energy. The Lovers describe not only love but the choice of love, and the person feeling this card is in some way choosing you — or feeling that they are being asked to choose you. This can be conscious or quietly unconscious, but it tends to organise their inner life around the question. They are aware that you matter; they are aware that this awareness has implications; they are aware that ignoring it would be a kind of betrayal of something true. The intensity is real, and it is not casual.

A small honest note: The Lovers' energy can also surface uncertainty. The card sometimes describes a person standing at a meaningful choice point, feeling drawn to you and simultaneously aware of what choosing you would cost or commit them to. This is not the same as ambivalence. It is the gravity of real feeling, which always carries some weight of decision with it. If the card surfaces this way, the feelings are no less genuine — they are more so, which is precisely why the question of what to do with them feels significant rather than light.`,
    reversedLong: `The Lovers reversed as feelings describes a connection that is meaningful and out of balance. The most common pattern is real feelings that exist in conditions which are making them difficult to honour. They care about you, perhaps deeply, but something in their life — another relationship, a values conflict, an unworked-through history, the demands of a particular circumstance — is keeping the feelings from settling into something honest. They may be torn rather than uninterested, and the being-torn is the texture of what they feel.

A second pattern is misalignment between you that has surfaced and not yet been resolved. The Lovers is a card of values, and reversed she can describe feelings that exist despite genuine differences in what each of you actually wants from love, from life, from each other. Sometimes this is workable through honest conversation; sometimes it is genuinely incompatible. The card is not predicting which, but it is naming that the difference is real and needs to be looked at rather than romanticised away.

The harder reading is worth naming: avoidance of a choice that requires being made. They feel something for you and they have been refusing to take responsibility for what those feelings imply, often because doing so would require difficult action in some other part of their life. The reversed Lovers is sometimes the card of the person who keeps feeling but never deciding, and the indecision is its own answer. Take the feelings seriously, take the situation seriously, and notice whether they are actually moving toward you over time or simply feeling something at a distance without ever stepping into it. The honest verdict tends to surface in behaviour, not in declarations.`,
    howTheyFeel: `When The Lovers describes how someone feels about you, the texture is significant, resonant, and value-laden. You are not casual to them. There is a sense in their inner life that you matter, that the connection is something rather than nothing, and that they have begun to register you as a person whose presence has weight in their life. The feelings often include both warmth and a kind of inner quiet recognition — they know that you are different.

If The Lovers reversed surfaced, the same significance is present, complicated by imbalance. They feel something real and they are tangled with it — either because circumstances make the feelings difficult, or because values do not quite match, or because they are avoiding the choice that the feelings imply. In either orientation, the depth is genuine. What differs is whether that depth has yet found honest ground to land on.`,
    feelingsFaqs: [
      {
        q: 'What does The Lovers mean as feelings?',
        a: `The Lovers as feelings indicates significant, values-resonant romantic emotion. The person feels that you matter to them in a way that is not casual — there is a recognition, sometimes almost a sense of inevitability, that the connection means something. The feelings often include both warmth and a quiet gravity; they are aware that what they feel has implications, and that awareness is part of the emotion itself. It is one of the strongest "as feelings" cards in the deck. Receive it as genuine, and remember that depth of feeling often carries the weight of decision along with it — that weight is not a problem, it is the nature of real love.`,
      },
      {
        q: 'Is The Lovers a yes for love?',
        a: `As a feelings reading, The Lovers is a strong yes — yes to love, yes to resonance, yes to the kind of connection that is built on alignment rather than convenience. They feel something for you that has moved past attraction into recognition. Whether the external circumstances are clear is a separate question; the card sometimes surfaces during meaningful choice points, and the choice can involve real complication. But on the question of whether the feeling itself is real, The Lovers is among the clearest yeses you can receive. The work, if there is work, is what to build with that yes in the conditions you actually have.`,
      },
      {
        q: 'What does The Lovers reversed mean as feelings?',
        a: `The Lovers reversed as feelings usually indicates genuine emotion in difficult circumstances. Either the feelings exist alongside complicating factors — another relationship, a values gap, a hard timing — or there is a meaningful misalignment between you that has not been honestly addressed, or they are avoiding the decision that the feelings imply. The depth is generally real. The question is whether the situation is workable, and whether they are willing to move toward you in concrete ways rather than just feeling at a distance. Watch behaviour over time. The honest answer tends to surface in action rather than in declarations.`,
      },
      {
        q: 'Does The Lovers mean they love me?',
        a: `Often yes — The Lovers is one of the most genuine love-indicating cards when it appears as someone's feelings about you. It surfaces when emotions have moved past attraction into a deeper recognition that you matter, that you align with something important to them, that you are someone whose presence has weight in their life. Whether they have yet found the words for that feeling, and whether circumstances allow it to be expressed cleanly, is a separate question. But on the existence of the feeling itself, this card is one of the strongest indications you can receive. They feel something real for you.`,
      },
    ],
  },

  'the-chariot': {
    uprightLong: `The Chariot as feelings describes determined, focused emotion. The person has decided, in some quiet inner way, that you are worth pursuing — and the pursuit has become organised. They are not drifting around the idea of you; they are moving toward you with intention. The feelings have a directional quality, a sense of momentum, that distinguishes this card from the softer or more contemplative emotional cards in the deck. They feel something for you, and the feeling has begun to translate into action.

There is often confidence in this energy. They believe they can make a relationship with you happen, and the belief is part of what they feel. The Chariot is the card of will applied successfully to obstacles, which means the person is likely undeterred by complications — whether external (distance, busy schedules, competing demands) or internal (their own hesitations, old patterns). They have set their sights on you and are willing to do the work the situation requires. This can feel exhilarating and slightly overwhelming, depending on how much momentum they are bringing.

The honest texture is that The Chariot moves fast and likes to be in motion. The feelings are real and focused, but they may not yet have done the slower work of getting to know you in ways that less directional cards represent. Their emotion is energetic rather than contemplative, and the energy may at times outpace genuine emotional knowledge. None of this makes the feelings less authentic — but it does mean that the relationship's depth will need to keep pace with its speed. If they care, they will slow down enough to let the connection become something more than momentum. That slowing is one of The Chariot's quieter teachings, and worth watching for.`,
    reversedLong: `The Chariot reversed as feelings describes emotions that are scattered, blocked, or moving in too many directions at once. The most common pattern is a person who feels something for you but has not been able to organise the feeling into coherent action. They want to pursue you and they keep getting distracted, derailed, or paralysed by competing demands. The intention is there; the execution keeps faltering. This can look from outside like inconsistency, and the inconsistency is exhausting to be on the receiving end of, but it is more often a sign of internal disarray than of false feeling.

A second pattern is aggression or impatience. The Chariot's healthy momentum has tipped into pushing — wanting things to happen on their timeline rather than the relationship's natural pace, getting frustrated when you do not respond on cue, treating you as a goal to be achieved rather than a person to be met. This is rarely premeditated cruelty. It is more often immaturity around their own desire: feelings turned into a kind of campaign rather than allowed to be feelings.

A third reading is the loss of direction entirely. They felt something at one point, the feelings have become diffuse, and now they are not sure what they want from you or from love generally. This is the card of the suspended pursuit, the campaign that has stalled, the person who is no longer sure why they were pursuing anything in the first place. None of these expressions necessarily mean the feelings are gone; they do mean that something in the person's relationship with their own desire has gone off-track, and watching honestly whether they regain coherence is more useful than waiting for declarations.`,
    howTheyFeel: `When The Chariot describes how someone feels about you, the energy is determined, intentional, and pointed in your direction. They have made some kind of inner decision about you and have begun acting on it. There is real momentum here. You are not a passive consideration; you are the goal they are organising their effort around. The feelings carry confidence and a sense of wanting to move things forward concretely.

If the reversal showed up, the picture is the same direction with the wheels coming off. They may still feel something for you, but the feelings are scattered, blocked, or impatient in ways that produce friction. Watch whether they regain coherent direction over time. The Chariot, even reversed, is rarely a card of absent feeling — it is more often a card of feeling that has temporarily lost its road. Either it finds the road again, or it slows into something more honest, or it dissipates.`,
    feelingsFaqs: [
      {
        q: 'What does The Chariot mean as feelings?',
        a: `The Chariot as feelings indicates determined, focused, intentional emotion. The person has decided you are worth pursuing and has begun directing real energy toward the connection. The feelings carry momentum, confidence, and a sense of wanting to move things forward — they are not contemplative but directional. It is one of the more decisive "as feelings" cards in the deck. Receive it as genuine intent, and remember that intensity sometimes outpaces the slower work of getting to know you. If the feelings are real, the speed will eventually settle into something that can sustain itself.`,
      },
      {
        q: 'Is The Chariot a yes for love?',
        a: `As a feelings reading, The Chariot is a strong yes — particularly on the question of whether the person is willing to act on what they feel. They are not waiting around. They have made some kind of inner commitment to pursue the connection and are bringing real energy to it. The caveat is that pace and depth are different things, and the card describes momentum more than it describes contemplative readiness. If their intention holds up over time and they slow down enough to actually meet you, this is one of the more substantial yeses you can receive. Watch for the pace to mature into substance.`,
      },
      {
        q: 'What does The Chariot reversed mean as feelings?',
        a: `The Chariot reversed as feelings usually points to emotions that have lost their road. The person may feel something genuine and be unable to organise it coherently — scattered, blocked by competing demands, or pushing in ways that produce friction rather than progress. Sometimes the feelings have become diffuse and they no longer know what they want; sometimes they have tipped into impatience or aggression. The feelings are rarely absent, but their expression is off. The question is whether the person can find their way back to coherent intention, and whether you want to be involved while they figure that out.`,
      },
      {
        q: 'Does The Chariot mean they are pursuing me?',
        a: `Yes — The Chariot is one of the clearest pursuit-indicating cards in the deck. When it appears as someone's feelings about you, it almost always means they are actively moving toward you in some way, even if the movement is not yet fully visible to you. They have decided you are worth their attention and effort, and they are bringing real intention to the connection. If you have been wondering whether their interest is serious enough to act on, this card strongly suggests it is. The remaining question is whether their pace matches the depth you actually want to build.`,
      },
    ],
  },

  'strength': {
    uprightLong: `Strength as feelings describes a love that is patient, warm, and quietly resilient. The person feels something for you that has the steadiness of mature affection — not the spike of infatuation, not the urgency of pursuit, but the warmer kind of care that has settled in and intends to stay. There is gentleness in this energy. They are not trying to overwhelm you, control the pace, or perform their interest; they are simply present with what they feel, allowing it to develop in its own time.

There is often a sense of acceptance in this card's emotional register. They see you, including the parts that other people might find difficult, and they are not put off by what they see. This is not the same as idealisation — Strength does not look away from the harder material. It looks at it and chooses warmth anyway. Their feelings have a quality of "yes to the whole of you", which can be genuinely moving to be on the receiving end of, especially if you have been used to relationships where being fully seen felt unsafe.

The honest texture is that Strength's emotional energy is sometimes mistaken for passivity. The person may not push for definitions, may not pursue intensely, may not produce dramatic gestures, and from outside this can look like restraint or even reluctance. It is more accurately patience. They are confident enough in what they feel that they do not need to prove it through performance. If you can read the quieter signals — the consistency, the gentle attention, the warmth that does not waver — there is real love here, and it is the kind of love that tends to last.`,
    reversedLong: `Strength reversed as feelings describes emotions complicated by self-doubt, fear, or suppressed reactivity. The most common pattern is a person who genuinely cares about you and does not trust their own capacity to handle what the caring would require. They may feel inadequate, unsure whether they have the emotional skills the relationship needs, or quietly afraid of the vulnerability that letting themselves fully feel something would bring. The result is a love that keeps shrinking from its own size, expressing itself in muted forms because the full expression feels too exposing.

A second pattern is suppressed reactivity surfacing in ways neither of you fully understands. They feel something for you, and they also have emotional material — fear, jealousy, old hurt, unprocessed anger — that they are not letting themselves look at. The unfelt material does not stay unfelt; it leaks. It shows up as moods, as small distances, as inexplicable reactions to things that did not seem to warrant them. The reversed Strength card is the card of the unintegrated shadow inside the warm heart, and the integration is genuinely difficult work that takes time.

A third reading is the absence of inner steadiness, which can produce feelings that feel intense one day and gone the next. Without the grounded resilience that the upright card represents, emotions become harder to hold. They may love you on Tuesday and feel uncertain by Friday, not because of anything you did, but because their internal weather is unstable. This is not bad faith; it is unworked-through self. The card is asking, gently but firmly, for the person to do the inner work of building genuine resilience. If they will, the feelings tend to clarify. If they will not, the relationship will be limited by what they have not yet built.`,
    howTheyFeel: `When Strength describes how someone feels about you, the energy is warm, patient, and genuinely accepting. They like you in a settled way. They are not in a hurry, not anxious about where this is going, not performing their interest — they are simply with what they feel and content to let it develop. There is gentleness in their attention, and there is also a quiet resilience: they are not easily put off, not easily destabilised, not easily talked out of what they feel.

If Strength reversed surfaced, read the same warmth complicated by inner instability. They may care and not trust their capacity to handle it, or have unworked-through emotional material that keeps leaking into the connection, or experience the feelings as more changeable than feels comfortable. The love is usually still real. What is missing is the inner ground that would let it become reliable, and only they can build that.`,
    feelingsFaqs: [
      {
        q: 'What does Strength mean as feelings?',
        a: `Strength as feelings describes warm, patient, accepting emotion. The person likes you in a settled way and is content to let the connection develop in its own time. There is gentleness in their attention and quiet resilience underneath it — they are not easily destabilised by small things, not in a rush to define what this is, not anxious about your reciprocation. They see you, including the harder parts, and choose warmth anyway. It is one of the more emotionally mature "as feelings" cards in the deck, even if its quietness can be mistaken for restraint. Read the consistency rather than the volume.`,
      },
      {
        q: 'Is Strength a yes for love?',
        a: `As a feelings reading, Strength is a yes in a particularly gentle register. They feel something real for you and have the patience and resilience to let it grow without forcing the pace. This is not the dramatic yes of cards like The Lovers or The Chariot; it is the steadier yes of a person who genuinely cares and is willing to wait for the relationship to find its honest shape. If you are able to value calm warmth over intensity, the answer this card gives is one of the better ones you can receive. Trust the steadiness; it tends to last.`,
      },
      {
        q: 'What does Strength reversed mean as feelings?',
        a: `Strength reversed as feelings usually indicates genuine emotion complicated by self-doubt, fear, or suppressed reactivity. The person may care about you and not trust their own capacity to handle what the caring requires; they may have unworked-through material that leaks into the connection as moods or small distances; they may experience their own feelings as more unstable than is comfortable. The love is generally still real. What is missing is the inner ground to make it reliable, and that ground is theirs to build. Be kind, but do not mistake their wobble for your problem to fix.`,
      },
      {
        q: 'Does Strength mean they love me?',
        a: `Often yes — Strength when it surfaces as someone's feelings about you describes warm, accepting affection that includes the whole of you. It is not always the most demonstrative kind of love, but it tends to be one of the more genuine. They feel something for you that has the quality of settled care: the willingness to be patient, the capacity to accept your harder parts without flinching, the quiet resilience that does not need to keep proving itself. If the love expresses itself more in steady presence than in dramatic gestures, do not undervalue it. This is the kind of love that tends to be there.`,
      },
    ],
  },

  'the-hermit': {
    uprightLong: `The Hermit as feelings describes emotions that are real, deep, and currently being processed in private. The person feels something for you, and the feeling has become significant enough that they need solitude to make sense of it. This is not withdrawal from you specifically — it is a turn inward to consult what is actually happening in them, which they cannot do well in the noise of constant contact. The Hermit's energy is the energy of someone working out something important, and you are likely part of what they are working out.

There is often a sense of seriousness in this card's emotional register. They are not feeling something light or casual. The fact that they have needed to retreat in order to think clearly suggests that the connection has weight — perhaps more weight than they were prepared for. They may be examining what they want from love, whether this is the right time for them to pursue it, what a relationship with you would actually require of them. The reflection is genuine and it is taking time, which is exactly what The Hermit's work always requires.

The honest texture is patience and trust in space. The Hermit does not respond well to being pulled out of the cave before he has finished his thinking. If you can hold the connection lightly while they do their inner work, what emerges is usually clearer and more honest than what would have emerged had they been pressured to declare themselves prematurely. The feelings are real. They are simply going through the slower process that real feelings sometimes need in order to become coherent. If you can wait without needing the waiting to be performed, this card often resolves into something quite genuine.`,
    reversedLong: `The Hermit reversed as feelings points to a retreat that has gone too far or in the wrong direction. The most common pattern is feelings that have curdled into emotional isolation — the person cares about you and has used solitude not for reflection but for avoidance. The cave that was supposed to be a place of inner work has become a place of hiding, and the longer they stay there, the harder it gets to come out. They may genuinely want connection and simultaneously be unable to take the steps that would create it, locked in a loop of inward retreat that no longer serves anyone, including them.

A second pattern is loneliness disguised as independence. They feel something for you and they have built such a fortified life around their solitude that letting you in feels like a structural threat. Their protective patterns have become a personality, and the personality cannot accommodate the kind of vulnerability the relationship would require. This is not coldness exactly. It is more the calcification of habits that once protected them and now keep them from the very thing they say they want.

A third reading is the refusal to look honestly at what they feel. The Hermit's lamp is supposed to illuminate, and reversed it points to a person who has gone into solitude and is not actually doing the inner work the solitude was meant for. They are stewing rather than reflecting, isolating rather than integrating, avoiding rather than examining. None of these patterns necessarily mean the feelings are absent. They do mean that the inner work the situation requires is not currently happening, and the relationship will be limited by that until it does.`,
    howTheyFeel: `When The Hermit describes how someone feels about you, the energy is real, contemplative, and currently turned inward. They feel something significant and are taking time alone to understand what it actually is. You may experience this as distance, and from one angle that is what it is — but the distance is not rejection. It is the quiet of a person working something through. The Hermit's love often emerges from the cave clearer and more honest than it went in, provided he is given the time the work requires.

If The Hermit reversed surfaced instead, the same retreat is present without the productive inner work. They may be isolating, avoiding, or refusing to examine what they feel. The feelings are likely still there. What is missing is their willingness or capacity to engage with them. Be honest about how long you can wait for someone whose retreat has stopped serving anyone.`,
    feelingsFaqs: [
      {
        q: 'What does The Hermit mean as feelings?',
        a: `The Hermit as feelings describes genuine emotions being processed in private. The person feels something significant for you and has turned inward to understand what it actually is. This is not rejection or coldness — it is the inner work that meaningful feelings sometimes require before they can be expressed clearly. The Hermit's love tends to emerge from solitude more honest than it went in, but the solitude itself is part of the process. Patience is asked. If you can hold the connection lightly while they do the reflection, what surfaces afterward is usually worth the wait.`,
      },
      {
        q: 'Is The Hermit a yes for love?',
        a: `As a feelings reading, The Hermit is more of a "yes, in time" than an immediate yes. The person feels something real but needs the space of solitude to know what to do with it, and that space cannot be rushed without distorting the very thing it is meant to produce. If you can wait without forcing definition, the answer that eventually emerges is typically thoughtful and honest. If you cannot wait, that is its own legitimate answer too. The card asks you to be patient with their pace and clear about your own.`,
      },
      {
        q: 'What does The Hermit reversed mean as feelings?',
        a: `The Hermit reversed as feelings usually indicates a retreat that has gone too far or stopped being productive. The person may care about you and be using solitude as avoidance rather than reflection; they may have built such a fortified independence that letting you in feels structurally impossible; they may be in the cave without doing any of the inner work the cave was meant for. Feelings may still be present, but the engagement required to act on them is not. Watch how long the pattern continues. Some retreats are temporary; others become permanent, and the difference matters for what you choose to do.`,
      },
      {
        q: 'Does The Hermit mean they are losing interest?',
        a: `Not necessarily — The Hermit's distance is usually inward turn rather than diminishing interest. The person is taking time alone because what they feel is significant enough to require thinking through, not because they have stopped feeling anything. The misinterpretation that the card means rejection is one of the most common mistakes people make with it. That said, the distance can be hard to sit with, and your patience has its limits. Watch the behaviour over time. If they emerge with clarity, the feelings tend to be real. If the retreat continues indefinitely, the answer is in the duration itself.`,
      },
    ],
  },

  'wheel-of-fortune': {
    uprightLong: `The Wheel of Fortune as feelings describes emotions that are in motion. The person's feelings toward you are shifting — usually in your favour — and the shift carries the quality of something larger than either of you driving the change. They may be discovering things about you that are reorganising how they had previously thought about the connection, or finding that their own internal weather has changed in ways that make you newly significant in their life. Whatever the specific mechanism, what they feel is not static; it is on a turn, and the turn is moving toward you.

There is often a sense of timing in this energy. The feelings have become available now in a way they were not available before, whether because of changes in their circumstances, completion of an earlier chapter, or simply the inner readiness that comes when something has run its course. They may feel that meeting or reconnecting with you has the quality of fate — not in a mystical sense necessarily, but in the sense that the situation seems to have arranged itself in their favour, and you are part of the arrangement.

The honest texture is that what the Wheel gives can also turn. The feelings are real and the current is favourable, but the same card warns gently against treating any particular emotional season as permanent. The right response is to receive what is being offered now without trying to lock the cycle in place. If the feelings continue to deepen as the wheel keeps turning, what is forming has real durability; if the season changes, that too is part of how the card works. Move with the current rather than trying to stop it. The luck this card brings tends to favour those who can ride it lightly.`,
    reversedLong: `The Wheel of Fortune reversed as feelings describes emotions caught in resistance, stagnation, or unlucky timing. The most common pattern is feelings that are present but stuck — the person cares about you and cannot seem to make any progress on what to do with the caring. The wheel is not turning. Circumstances they cannot easily change keep blocking the natural development of the connection: a difficult job, a complicated existing situation, geographic distance, life logistics that refuse to align. The feelings exist, and the conditions for expressing them are not currently available.

A second pattern is resistance to a change that wants to happen. They feel something for you and the feeling implies a shift in their life they are not ready to make — leaving a different relationship, abandoning a familiar pattern, accepting a new chapter that would disrupt arrangements they have grown comfortable with. The Wheel reversed is the card of clinging to the previous turn even as the universe is asking for the next one. The clinging is not always conscious; sometimes it shows up as repeated bad timing, missed openings, or the strange recurrence of obstacles that always seem to surface just as the relationship was about to move forward.

A third reading is a genuine downturn — feelings that have entered a difficult phase for reasons neither of you fully control. This is not necessarily fatal. The wheel turns. What feels stuck now will not be stuck forever, and feelings carried through a difficult season often emerge clearer and more honest than they were before. The work, if there is work, is to avoid forcing what cannot yet move. The Wheel teaches patience with timing, in either orientation. The right action in a stuck season is usually less than you think.`,
    howTheyFeel: `When The Wheel of Fortune describes how someone feels about you, the energy is in motion and the motion is largely favourable. Their feelings are turning toward you in ways that may surprise both of you — perhaps because circumstances have shifted, perhaps because their internal readiness has changed, perhaps because of some confluence neither of you would have predicted. There is often a sense of right timing here. You are arriving in their life at a moment when they are unusually available to feel something genuine.

If the reversal surfaced, the picture is the same dynamic stuck. Their feelings may be present but unable to move, blocked by circumstances or by their own resistance to the changes the feelings imply. The wheel will turn again, almost always. The question is whether you can wait through the stuck season or whether you need to move on while it lasts. Either is legitimate; the card simply names the timing honestly.`,
    feelingsFaqs: [
      {
        q: 'What does The Wheel of Fortune mean as feelings?',
        a: `The Wheel of Fortune as feelings describes emotions in motion and usually moving in your favour. The person's feelings toward you are shifting, perhaps significantly, in ways that may feel almost timed or fated. There is a sense of right timing in this energy — the feelings have become available now in a way they were not before. Receive the current without trying to lock it in place; what the Wheel gives can also turn, and the feelings tend to deepen most reliably when the turning is allowed to keep happening naturally rather than forced into permanence prematurely.`,
      },
      {
        q: 'Is The Wheel of Fortune a yes for love?',
        a: `As a feelings reading, The Wheel of Fortune leans yes — particularly on the question of whether something significant is happening or about to happen in the emotional dynamic. The wheel is turning in a direction that favours the connection, and the person feels it. Whether the resulting relationship lasts depends on what you build with the favourable season, which is a different question than the card answers. The yes here is about the current moment's momentum. Use it wisely; do not assume it is permanent until it has had time to demonstrate that it is.`,
      },
      {
        q: 'What does The Wheel of Fortune reversed mean as feelings?',
        a: `The Wheel reversed as feelings usually indicates emotions caught in stuck timing, resistance, or unlucky circumstance. The feelings may be real and unable to move — blocked by external obstacles, by resistance to a needed change, or by a genuine downturn in the connection's seasons. The wheel turns. What is stuck now does not stay stuck forever, but the patience required can be considerable. The honest question is whether you can wait through the stuck phase and what you need to take care of yourself in the meantime. Forcing the wheel rarely works; riding it does.`,
      },
      {
        q: 'Does The Wheel of Fortune mean they will come back?',
        a: `Often yes, especially when the card surfaces upright. The Wheel of Fortune is one of the cards most associated with the return of energies, opportunities, and connections that had previously moved away. If you are asking about a person who has been absent, the card frequently indicates that circumstances are shifting in a direction that brings them back into your life — though it does not guarantee the form the return will take. Hold the possibility lightly. The cycle is more often kind to those who can wait without clinging than to those who try to summon the wheel prematurely.`,
      },
    ],
  },

  'justice': {
    uprightLong: `Justice as feelings describes emotions that are clear, fair, and rooted in honest evaluation. The person has looked at the connection and is responding to what they actually see, rather than to a fantasy of who you are or a projection of who they want you to be. Their feelings have integrity. They are not exaggerated, not understated, and not contingent on you performing a particular version of yourself; they are calibrated to the real you, and they have arrived at whatever weight is honest for the situation.

There is often a sense of accountability in this energy. They are aware of what they are feeling and willing to take responsibility for it. They will tell you the truth when asked, even if the truth is more complicated than a simple declaration of love. They are also weighing the relationship honestly — what it has been, what it is, what it could be — and adjusting their feelings to match. This can feel cooler than the more romantic cards in the deck, but it is also one of the most reliable indicators that what you are dealing with is real. Justice does not flatter; she also does not lie.

The honest texture is that Justice's feelings tend to be proportional to what has actually been built between you. If the connection has been deepening, her response will deepen; if there has been imbalance or unresolved material, her response will reflect that too. The card sometimes surfaces when a relationship is at a point of honest accounting — what each of you has contributed, what has gone unspoken, what needs to be addressed for the connection to continue cleanly. Take the clarity she offers as a gift. It is the foundation that real long-term feeling needs in order to last.`,
    reversedLong: `Justice reversed as feelings describes emotions that are distorted by unfairness, dishonesty, or refusal of accountability. The most common pattern is feelings that exist in conditions of meaningful imbalance — one of you is contributing significantly more than the other, and the imbalance is being papered over rather than addressed. The person may care about you and not want to look at how much you have been carrying, because looking would imply having to change. Their feelings are real and they are also operating in a way that benefits them at your quiet expense.

A second pattern is feelings entangled with dishonesty. They may be hiding something material — about their own situation, about their previous history, about their actual intentions — and the hidden material is shaping the feelings in ways neither of you can address until it surfaces. Sometimes the dishonesty is to themselves first; they have not been honest with themselves about what they feel or what they are doing, and that internal misalignment leaks into the relationship as ambiguity, inconsistency, or quiet evasion of the questions that actually matter.

A third reading is the refusal to take responsibility for impact. They may feel something for you and consistently avoid accountability for the parts of the relationship that have hurt or confused you. They explain, they justify, they sidestep — anything to avoid the simple admission that something they did has consequences they need to own. The reversed Justice card asks you, gently, to take what you are sensing seriously. If something feels unfair or dishonest in the connection, your perception is probably accurate. Real feelings, in the long run, require honest ground; without it, what is being built has limits the card is naming clearly.`,
    howTheyFeel: `When Justice describes how someone feels about you, the energy is clear, fair, and honest. They feel what they feel, no more and no less, and they are willing to tell you the truth about it. There is real integrity in their emotional response. You are not being idealised, and you are not being undervalued — you are being seen and responded to accurately. The texture may feel cooler than some of the more romantic cards, but the substance is reliable.

If Justice reversed surfaced, the picture is less clean. Their feelings may exist in conditions of imbalance, dishonesty, or unresolved accountability. They may care about you and still be operating in ways that quietly disadvantage you, or hiding something material, or avoiding responsibility for how their behaviour has landed. Trust your sense of what feels unfair. The reversed card is almost always asking for honest accounting, and what feelings remain after that accounting is what is actually real.`,
    feelingsFaqs: [
      {
        q: 'What does Justice mean as feelings?',
        a: `Justice as feelings describes clear, fair, and proportionate emotion. The person is responding to who you actually are rather than to a fantasy of you, and their feelings carry real integrity. They will tell you the truth when asked, weigh the connection honestly, and adjust their response to match what has genuinely been built between you. This is one of the more reliable "as feelings" cards in the deck, even though its tone can feel cooler than the more romantic options. Justice does not flatter, but she also does not lie. What she offers is the honest foundation that lasting feeling needs.`,
      },
      {
        q: 'Is Justice a yes for love?',
        a: `As a feelings reading, Justice is a conditional yes — yes if the relationship has been built honestly and fairly, less of a yes if it has not. The card is calibrated to truth rather than to romance. Where there has been mutual contribution and genuine alignment, the feelings she describes are real and proportionate. Where there has been imbalance or unaddressed material, she will name the gap rather than smooth it over. Take the honesty as encouragement rather than discouragement; what survives Justice's scrutiny tends to be sturdy in ways that less honest connections cannot match.`,
      },
      {
        q: 'What does Justice reversed mean as feelings?',
        a: `Justice reversed as feelings usually points to emotions complicated by unfairness, dishonesty, or refusal of accountability. The feelings may be real and still operate in ways that quietly disadvantage you; the person may be hiding something material; they may consistently avoid responsibility for how their behaviour has landed. Your sense of what feels unfair is generally accurate under this card. Take the perception seriously rather than reasoning it away. Honest accounting is the only way through; what feelings survive that accounting are the ones that actually have a future, and they are worth the work it takes to get there.`,
      },
      {
        q: 'Does Justice mean they are being honest about their feelings?',
        a: `Upright, generally yes — Justice as someone's feelings about you usually indicates that what they say tracks with what they feel. They are not exaggerating, not minimising, and not hiding the relevant material. If they have told you they care, they care; if they have expressed limits, the limits are real. This is one of the more straightforward cards to receive in that sense. Reversed, the reading flips: their stated feelings may not match the underlying reality, and your task is to weigh the behaviour as much as the words. In either orientation, Justice is the card that rewards clear-eyed honesty over preferred interpretations.`,
      },
    ],
  },
}
