import type { FeelingsContext } from '../card-feelings-extended'

// Pentacles suit: Ace through King (14 cards)
export const PENTACLES: Record<string, FeelingsContext> = {
  'ace-of-pentacles': {
    uprightLong: `The Ace of Pentacles as feelings is the quiet beginning of something they want to build with you, not just feel about you. Unlike the more declarative Aces, this one rarely arrives with fanfare. The other person is noticing a stable warmth — the sense that you are someone they could plan around, share resources with, introduce to their actual life. The feeling is not yet love in the operatic sense; it is the early, sober recognition that you might be worth investing in. Pentacles people show affection by giving real things — time, money, attention, practical help — and at the Ace stage this is just starting to take shape.\n\nIf you are wondering whether their feelings are serious, this card answers gently in the affirmative. They are not playing. They are slowly opening a door, testing whether the foundation will hold weight. Expect small, concrete signals rather than romantic monologues — a remembered preference, a meal cooked, an offer to fix something, a careful check-in about your schedule. Each of these is, in Pentacles language, a love letter. The error many querents make is dismissing these gestures as mere kindness. They are not mere. They are how this person says everything they cannot yet say.\n\nThe card also suggests their feelings are tied to a real-world context they can sustain. They are not fantasising about you from a distance. They are quietly imagining whether their actual life — bills, habits, calendar, family — has room for you. If you want to honour the energy of this card, meet it in kind. Be reliable. Show up. Let your interest land as something they can touch.`,
    reversedLong: `The Ace of Pentacles reversed as feelings describes affection that has not been given a foundation, or feelings that are present but cannot translate into the practical commitments that would make them real. The other person may genuinely care about you and still be unable to organise their life around that caring. Plans are vague. Promises are made and quietly missed. The feeling exists somewhere inside them — you are not imagining it — but it has not been planted in soil where it can grow.\n\nSometimes this reversal signals that they are not yet ready for the kind of grounded partnership their feelings would require. Money is unsettled, their living situation is unstable, an old relationship still has hooks in them, or they simply have not done the inner work to know how to be a partner. The affection is real; the infrastructure is missing. Other times the card warns of a more uncomfortable truth — that what looks like feeling on their side is mostly comfort, convenience or routine, and would not survive any real test. Look at the surrounding cards to tell which version is here.\n\nFor the querent, the advice is sobering rather than bleak. Stop reading their warmth as commitment. Watch what they do with money, time and follow-through, because in Pentacles language those are the feelings. If those signals are weak, the affection — however genuine it may be — is not yet capable of building a life with you. You are not required to wait indefinitely for someone to translate emotion into action. The Ace reversed asks you to honour your own need for tangible reality, even when their words are warm.`,
    howTheyFeel: `Right now they feel a quiet, steady interest in you that they may not have fully voiced. There is a sense of "this could be real" rather than fireworks, and they are testing it slowly — noticing how you behave, whether you keep small promises, how you handle ordinary life. They want to invest, but Pentacles people invest only after they have looked at the ground. Expect them to be measured rather than effusive.\n\nDo not mistake their lack of romantic declaration for a lack of feeling. They are likely thinking about you more than they are saying, and what they say will tend to be practical — offering help, suggesting plans, noticing small details about your life. If you can meet them with similar groundedness rather than pressing for grand statements, the feeling on their side will deepen. They are slow, but if their version of love takes root, it tends to last.`,
    feelingsFaqs: [
      {
        q: 'What does Ace of Pentacles mean as feelings?',
        a: 'It means their feelings for you are quietly serious and oriented toward something real. They are not yet declaring love, but they are beginning to imagine you in their actual life — schedule, finances, future. The affection is grounded rather than fiery. Expect them to express it through reliability, practical help, remembered details and small acts of investment rather than poetic monologues. For Pentacles people, those gestures are the feelings. Treat each one as a sentence in a love letter they are slowly writing. The pace is slow on purpose; what is being built is meant to last.',
      },
      {
        q: 'Does the Ace of Pentacles mean they want a serious relationship?',
        a: 'Usually yes, though "serious" here means stable rather than dramatic. They are not chasing an intense fling. They are testing whether you could become part of an ordered, sustainable life. If you want a partner who will plan, show up and contribute concretely, this card is a good sign. If you want someone who will sweep you off your feet with words, you may need to recalibrate. The Ace of Pentacles person commits slowly and then keeps committing. Their version of romance is the kind that pays bills on time and remembers your prescription refill date.',
      },
      {
        q: 'Are their feelings genuine if Ace of Pentacles appears?',
        a: 'Yes, and in a particularly trustworthy way. Pentacles feelings are slow to ignite but slow to leave. The Ace stage means they are still in the early, careful phase of recognising what they feel, so do not expect grand confessions yet. Watch their behaviour instead. Are they consistent? Do they remember the small things? Do they offer practical help without keeping score? Each of those is a yes. If you press for verbal declarations too early, you may rush a process that, left to its own rhythm, would become one of the steadier loves you have known.',
      },
      {
        q: 'How does Ace of Pentacles describe new feelings between two people?',
        a: 'It describes a new connection that is taking root in real soil rather than in fantasy. The two of you are beginning to share practical reality — meals, schedules, plans, perhaps money or living space — and the feelings are growing alongside that shared ground rather than ahead of it. This is not the dizzying start of a Cups romance, and it does not need to be. The Ace of Pentacles favours connections that feel ordinary in the best sense — calm, reliable, embodied. If you can let it stay that ordinary, it tends to mature into something quietly extraordinary.',
      },
    ],
  },

  'two-of-pentacles': {
    uprightLong: `The Two of Pentacles as feelings describes someone who cares about you and is also juggling a great deal of other life. Their affection is real but their attention is fragmented. Work, family obligations, money pressures, perhaps the unfinished edges of a previous relationship — all of these are spinning in the air at once, and you are one of the balls they are trying to keep aloft. The card is not saying you are unimportant to them. It is saying their bandwidth is currently smaller than their feelings.\n\nThis often manifests as inconsistency that has nothing to do with you. They are warm one week and quiet the next, present at dinner and distracted on the phone, full of plans they cannot quite execute. The temptation is to read this as ambivalence, but in Pentacles language it more often reads as overload. They want to give you more; they have not yet figured out how to make the time. If you can resist the urge to take their busyness personally, you will see the feeling more clearly underneath.\n\nThe card also carries a quiet warning. Two of Pentacles people are skilled at appearing to manage everything, and the partnership can drift into the lowest priority almost without their noticing. If this connection matters to you, naming the bandwidth issue kindly is more useful than waiting for them to spontaneously rebalance. They are unlikely to do that on their own. Asked directly, however, they often respond well — Pentacles people respect a partner who is honest about what is and is not working in the practical fabric of the relationship.`,
    reversedLong: `The Two of Pentacles reversed as feelings is the juggling act that has tipped over inside them. They may still care about you, but the structure of their life is no longer sustaining the weight of caring well. Cancelled plans pile up. Texts go unanswered for longer. They show up to dates exhausted, half-present, apologetic about a hundred small things they could not get to. The feeling underneath has not necessarily died — but their capacity to express it through any consistent action has collapsed.\n\nThis reversal sometimes describes a more difficult truth, however, which is that they have allowed the relationship to slip to the bottom of their list and are not really intending to lift it back up. Some Pentacles people, faced with overload, simply quietly drop the relationship into the "I will deal with this later" pile and never quite return. From the outside, this looks identical to genuine overwhelm. The difference is whether, when invited to rebalance, they actually rebalance. Watch what happens after you raise the issue, not just what they say in the moment.\n\nFor the querent, the work is to stop accepting "I am just so busy" as a complete explanation. Everyone is busy. People make time for what they prioritise. If you have been carrying the relationship through their distraction for a long stretch, this reversal asks whether that is a temporary season or a settled pattern. Both are survivable, but they require different responses. Their feelings, if real, will hold up to an honest conversation. If they cannot survive that conversation, they were not capable of supporting a relationship anyway.`,
    howTheyFeel: `They feel pulled in many directions and you are one of the genuine things they care about, but probably not the one currently getting the most of them. There is affection — likely more than they are showing — and there is also a quiet panic about everything else they are trying to manage. They probably go to sleep some nights wishing they had given you more attention that day, and then wake up to the same overflowing list and repeat the pattern.\n\nIf you can be patient without being a doormat, this is generally a workable energy. They are not falling out of love; they are losing the plot on logistics. A direct, kind conversation about how the two of you actually want to spend time tends to land far better than waiting for them to notice on their own. Pentacles people respect partners who help them prioritise, as long as the request is honest rather than punishing.`,
    feelingsFaqs: [
      {
        q: 'What does Two of Pentacles mean as feelings?',
        a: 'It means their feelings for you are genuine but currently competing with a great deal of other life. They are juggling work, family, money or unfinished obligations, and you are getting fragmented rather than focused attention. This is rarely about a lack of love. It is about a lack of bandwidth. The card asks you to read their inconsistency as overload rather than ambivalence, and to consider whether the imbalance is a season they will pass through or a settled pattern. A direct, kind conversation about prioritising the relationship usually moves things further than waiting silently.',
      },
      {
        q: 'Is Two of Pentacles a positive sign for feelings?',
        a: 'It is mixed but workable. The card confirms there is real feeling on their side, which is good news. It also warns that their capacity to express that feeling consistently is being squeezed by everything else they are managing. If you need a partner who can give steady, predictable presence right now, the Two of Pentacles may be frustrating. If you can tolerate some short-term inconsistency in exchange for a longer-term build, the feeling underneath is often strong enough to mature into something stable once they get their logistics back under control.',
      },
      {
        q: 'Do they have time for me if Two of Pentacles appears?',
        a: 'Time is exactly the question. They want to. They are also genuinely stretched. The card is not telling you they are using busyness as an excuse — it is telling you they are using busyness as a coping mechanism for too many obligations. The honest test is to ask them, kindly and clearly, what your place in their priorities actually is. Pentacles people, when invited to be specific, will usually be specific. Their answer — and what they do in the two weeks after the conversation — will tell you whether the bandwidth issue is temporary or terminal.',
      },
      {
        q: 'Does Two of Pentacles mean they are confused about their feelings?',
        a: 'Not usually. They are not confused about whether they care; they are confused about how to fit caring into a life that is already overflowing. The feeling is generally clear inside them. What is unclear is the practical answer to the question "how do I show up for this person while also doing everything else?" If you read this card as emotional ambivalence, you will misdiagnose the situation. It is logistical ambivalence dressed up as emotional distance, and it usually resolves the moment they free up real time for the relationship.',
      },
    ],
  },

  'three-of-pentacles': {
    uprightLong: `The Three of Pentacles as feelings describes someone who sees you as a genuine collaborator rather than only a romantic object. Their affection includes respect for your skills, your judgement, the way you handle the practical fabric of life. They are interested in building something with you — a household, a project, a future — and the feeling is steadied by that shared sense of craft. This is one of the most underrated love cards in the deck, because its quiet competence often gets overlooked in favour of flashier signals.\n\nExpect their care to express itself through partnership. They want to plan with you, work on things alongside you, hear your opinion before they make decisions, and let you hear theirs. There is a deep compliment buried in this card — they consider you a peer. They do not want a muse, an audience or a project. They want a co-builder. If you have been used to being romanced from above or below, this even, collaborative quality may feel unfamiliar at first. Let it settle. It is one of the most sustainable forms of love available.\n\nThe card also suggests that their feelings are growing through doing things together rather than only through emotional intimacy. Shared projects — a renovation, a holiday, a piece of work, a small business, raising children — are where their love deepens. Conversation is a part of it, but action is the real love language here. If you want to honour the energy of this card, propose something to build together. They will read that as one of the most romantic gestures you could offer.`,
    reversedLong: `The Three of Pentacles reversed as feelings describes a connection in which the collaborative spirit has broken down or never quite formed. They may still have feelings for you, but the two of you are no longer building anything together — or never started. One of you is doing all the planning while the other coasts. Standards differ wildly. Roles are unclear. Both of you may be acting in good faith and still feel chronically misaligned, as if you are designing different houses on the same plot of land.\n\nIn some readings this reversal points to mismatched effort rather than mismatched feeling. They like you. They are not, however, showing up as a partner in the practical sense — not pulling their share of the load, not contributing to the shared project, not treating the relationship as a co-creation. The feeling on their side may be sincere and still be functionally useless unless it translates into collaborative behaviour. In Pentacles language, love that does not build is barely love at all.\n\nLess commonly, this reversal describes someone whose affection includes an unspoken hierarchy. They want to be the senior partner, or the one whose taste sets the standard, and your contributions are quietly minimised. If that pattern is present, name it. The Three reversed is rarely a death sentence for a connection, but it requires an honest conversation about roles, effort and respect. If they are capable of meeting you as an equal, this card moves quickly. If they are not, it is better to know now than after you have built half a life around a partnership that was never really shared.`,
    howTheyFeel: `They feel a settled, respectful affection for you that includes wanting to build with you, not just be with you. There is a sense on their side that you are someone whose work, judgement and presence they can rely on, and that adds a different texture to the feeling than pure romantic attraction does. They are probably thinking in terms of plans, projects and shared futures more than poetic declarations.\n\nIf you have been waiting for a more emotional, effusive expression, you may be missing the love letter that is already being written in action. Watch what they propose to build with you, what decisions they invite you into, what work they trust you to share. Each of those is the feeling translated into the only language Pentacles people fully trust. Meet them there and the bond tends to deepen quickly and durably.`,
    feelingsFaqs: [
      {
        q: 'What does Three of Pentacles mean as feelings?',
        a: 'It means they see you as a true collaborator and the feeling is grounded in mutual respect for how each of you handles real life. They want to build something with you rather than only feel something for you. Expect their affection to express itself through shared projects, joint decisions and a steady tone of partnership. They may not be dramatic, but they will be deliberate. If you can let action count as romance, this is one of the most stable feelings cards in the deck — the kind of love that compounds quietly over years rather than peaking in early intensity.',
      },
      {
        q: 'Does Three of Pentacles mean they want to commit?',
        a: 'Usually yes. Commitment for Three of Pentacles people is less about a single grand decision and more about steadily building a shared structure — a home, a routine, a project, a future. They are not dragging their feet so much as constructing the scaffolding. If you watch what they propose to do together rather than what they say in the abstract, you will see commitment forming. Inviting them into a concrete plan tends to land better than asking them to define the relationship verbally. They commit through doing, not through declaring.',
      },
      {
        q: 'Are Three of Pentacles feelings romantic or just practical?',
        a: 'They are both, and the practicality is the romance. Three of Pentacles people show love by treating you as a peer, valuing your contribution, and wanting to design a life with you rather than next to you. That is romance in the Pentacles sense — quieter than fireworks, but considerably more durable. If you have been raised on stories where love is loud, this can feel underwhelming at first. Sit with it. The depth is real, the respect is real, and the steady building of shared reality is something most relationships never achieve.',
      },
      {
        q: 'How do I deepen feelings with someone showing Three of Pentacles?',
        a: 'Propose a project to build together. It does not need to be grand — a holiday, a renovation, a recipe collection, a financial plan, a habit you take on as a pair. Three of Pentacles people deepen affection through shared craft rather than through extended emotional conversation. Ask their opinion on practical things. Trust them with real decisions. Let them see you contribute. Each of these acts speaks the language they actually understand. The connection tends to stabilise and deepen quickly when the relationship is treated as a co-creation rather than a feeling to be managed.',
      },
    ],
  },

  'four-of-pentacles': {
    uprightLong: `The Four of Pentacles as feelings describes someone whose affection for you is real but tightly held. They are not effusive. They are not freely demonstrative. They keep their cards close to the chest and parcel out warmth carefully, as if afraid that giving too much might leave them with nothing in reserve. The feeling on their side is often deeper than they let show, but it is being managed rather than expressed. They want to hold onto you — and they may be holding so tightly that they cannot actually share themselves with you.\n\nIn some readings this card describes a partner whose love language is security itself. They demonstrate care by being financially reliable, by being unwavering in their loyalty, by being the person who will not leave. That is a real and valuable form of love, but it can coexist with emotional reserve, control issues, or a fear of vulnerability that makes intimacy feel rationed. They will pay the bills, fix the leaking tap, never abandon you — and may not be able to tell you how they feel.\n\nThe card asks you to read their grip honestly. Is the holding-on a sign of devotion, or a sign of possessiveness? Is the carefulness with affection a sign of depth, or a sign of withholding? Both are possible. The surrounding cards usually tell you which. What is reliably true is that this person feels something for you they are not openly showing, and any movement toward more openness will have to be invited gently. Demand a torrent of words and they will close further. Welcome small acts of vulnerability without making them dramatic, and the grip slowly loosens.`,
    reversedLong: `The Four of Pentacles reversed as feelings is the loosening of a long-held grip. In the positive sense, this can be wonderful — a previously guarded, withholding or controlling partner is finally beginning to open their hands. The walls around their feelings are coming down. They are willing to say more, share more, let themselves be seen in a way they could not previously. If you have been waiting through a long, careful season for them to soften, this reversal often marks the thaw.\n\nIn the more difficult sense, however, the reversal describes feelings that are being held so tightly they have begun to slip away, or the loss of something they were clinging to — financial stability, control, an image of how the relationship should look — that was actually holding their affection in place. Some Four of Pentacles people only feel safe loving you when they feel in control of the surrounding context. When that control destabilises, the feelings can wobble or collapse, not because the love was false but because their nervous system cannot sustain affection without security.\n\nFor the querent, the question is whether the loosening is welcome or forced. If your partner has been controlling, possessive or financially stingy with you, this reversal often marks a real and overdue release. If they have been your steady anchor and that anchor is dragging, the reversal asks you to be gentle with their fear. Either way, the energy is moving. Use the opening to invite real conversation about what they feel and what they need. Four of Pentacles people often find, once they let one finger loose, that the others want to follow.`,
    howTheyFeel: `They feel a real attachment to you that they are not fully letting out into the open. There is a sense of "I want to keep this" that may be stronger than they have admitted to themselves, let alone to you. They are probably more protective of the relationship than effusive about it, which can leave you guessing about the depth of feeling. The depth is usually there. The expression is rationed.\n\nIf you press them to declare themselves, you are likely to get less rather than more. If you create safe, undramatic moments where vulnerability can occur — quiet evenings, shared tasks, gentle questions without ultimatums — they tend to open in small, real increments. Their love is the kind that demonstrates itself over years through consistency and loyalty rather than over weeks through declarations. If you can value that texture, this is a stable, devoted form of affection. If you need verbal romance to feel loved, you will need to negotiate explicitly for it.`,
    feelingsFaqs: [
      {
        q: 'What does Four of Pentacles mean as feelings?',
        a: 'It means their affection for you is real but tightly held. They are guarded, careful with vulnerability and reluctant to show how much they feel. Sometimes this reflects depth that is simply private — they are loyal, devoted and reliable, but emotionally reserved by nature. Other times it reflects fear of loss, control issues or an inability to risk being seen. Watch what they hold onto rather than what they say. Their grip on the relationship — wanting to keep you close, protect what you have, stay loyal — is often a stronger love letter than they realise. Read the action, not the silence.',
      },
      {
        q: 'Are they emotionally closed off if Four of Pentacles appears?',
        a: 'Often yes, at least at the surface. They tend to manage their feelings rather than express them, and may have an internal sense that showing too much is risky. This is rarely about not feeling. It is usually about not feeling safe to feel openly. With patience, undramatic intimacy and respect for their pace, they often soften. With pressure, ultimatums or demands for verbal declaration, they typically close further. Their version of love prioritises reliability over expression, and many of them have never had it pointed out kindly that the two can coexist.',
      },
      {
        q: 'Do they really love me if Four of Pentacles appears?',
        a: 'Probably more than they are telling you. Four of Pentacles people often feel deeply and show it through loyalty, financial reliability, stable presence and a quiet refusal to leave. That is a serious form of love, even when it is not articulated. The mistake many querents make is reading reserve as absence. Watch the things they do not say goodbye to — the relationship itself is high on that list. If you want more verbal warmth, you may need to ask for it directly and specifically. Most Four of Pentacles partners can offer more when they understand what is actually being requested.',
      },
      {
        q: 'How do I get them to open up if Four of Pentacles is showing?',
        a: 'Slowly, undramatically and through actions rather than ultimatums. Create reliable, low-stakes moments where small vulnerability is possible — a quiet walk, a shared meal, an honest question without pressure. Notice and gently appreciate the small openings when they happen. Resist the urge to make a big emotional event out of any disclosure they offer. Their fear is often that vulnerability will be punished, weaponised or simply consumed. Demonstrate that it is safe instead, and they tend to open in real if modest increments. The pace is slower than you might want; the result, when it comes, is durable.',
      },
    ],
  },

  'five-of-pentacles': {
    uprightLong: `The Five of Pentacles as feelings is the cold side of the church window. The other person may feel something for you — sometimes considerable — and they feel cut off from being able to act on it. Financial hardship, a health crisis, depression, loss, the weight of a difficult season they have not told you about: any of these can produce the strange combination of strong feeling and apparent emotional unavailability that this card describes. They are not warm right now because they cannot find their own warmth.\n\nIn some readings this card describes a specifically relational coldness — the sense of being shut out, undervalued, or treated as if your feelings did not matter. They may have feelings for you and still be making you feel desperately alone in the connection. Pentacles cards take material reality seriously, and the Five often points to real, concrete hardship behind the emotional shutdown: a job lost, a debt mounting, a body in pain. Knowing this rarely fixes the loneliness, but it may help you stop blaming yourself for their distance.\n\nThe card also asks you to honour your own experience honestly. If you have been waiting outside the lit window of a relationship that never quite invites you in, that suffering is real, and is not made unreal by the fact that they are also struggling. The path through this card is rarely about trying harder or being more patient alone. It is about asking directly for the warmth you need, naming what is missing, and being willing to walk inside — into honest conversation, into outside help, into the recognition that something has to change. Help is closer than either of you can currently see.`,
    reversedLong: `The Five of Pentacles reversed as feelings marks the end of a cold season. Whatever has been freezing the affection on their side — financial stress, illness, depression, a previous relationship, internal isolation — is beginning to lift. The warmth is returning. They are starting to feel safe enough, resourced enough, present enough to act on what they feel for you. If you have been waiting through a long stretch of emotional unavailability, this reversal often signals that the wait is finally ending.\n\nIn another reading, the reversal can describe someone who is just emerging from a difficult season and is shaky on their feet. The feelings are real, the recovery is real, and their capacity is still small. They may want to give you more than they can yet sustain. The mature response on your side is to receive what is being offered gently, without grasping for the full bouquet of warmth at once. Pentacles recoveries are gradual. Pushed too quickly, they wobble. Trusted to unfold, they tend to stabilise into something genuinely solid.\n\nFor the querent, the work is often to stop expecting yourself to keep enduring the cold. The reversed Five usually arrives with practical help nearby — friends to lean on, professional support, honest conversation, sometimes financial relief. Use it. Asking for warmth is not weakness, even when you are the one who has been waiting. If the relationship is meant to deepen, this reversal favours those who walk inside rather than those who keep stoically standing in the snow. The lit window has been there. You are finally able to see it.`,
    howTheyFeel: `Right now they feel cold, depleted or shut down — and the chill is probably not really about you. Something in their life is hard in a way they may or may not be talking about: money, work, body, mood, family, the weight of a season they did not see coming. From inside that, their feelings for you can be hard to access. They may go quiet, distant or short-tempered, and you can end up feeling locked out of a relationship that, from inside their head, they have not actually closed.\n\nIf you want to test what is really going on, ask plainly and kindly what they are carrying. Not "do you love me?" but "what is going on for you right now?" Pentacles people, when invited to speak about practical hardship rather than feelings, will sometimes share something they could not have shared if asked emotionally. Underneath the cold, there is usually more affection than you currently feel. Whether they have the capacity to express it depends on what kind of warmth — practical, emotional, social — they can be helped to find their way back to.`,
    feelingsFaqs: [
      {
        q: 'What does Five of Pentacles mean as feelings?',
        a: 'It usually means there is real feeling on their side that is being blocked by hardship — material, emotional or both. They may be struggling with money, health, depression, family pressure or a difficult season they have not told you about, and the strain is producing apparent coldness, distance or emotional unavailability. This is rarely a clean signal of indifference. It is more often a signal of depletion. The card asks you to read the chill in context, to ask plainly what they are carrying, and to recognise that warmth often returns when the underlying hardship begins to ease.',
      },
      {
        q: 'Do they still love me if Five of Pentacles appears?',
        a: 'Probably yes, though they may currently be unable to act on it. The Five of Pentacles is a card of feeling separated from expression. Affection is present; access to it is blocked by some form of suffering. If you can hold that distinction, you can stop personalising their coldness and start asking real questions about what is going on. That said, the card does not require you to wait indefinitely. Real love that cannot be expressed, sustained over long enough, becomes functionally indistinguishable from absence. Knowing why they are cold helps; it does not oblige you to freeze with them.',
      },
      {
        q: 'Why are they so distant if Five of Pentacles is showing?',
        a: 'Almost always because something in their material or emotional life is in trouble. Pentacles is the suit of concrete reality, and the Five describes the suffering of being cut off from resources of one kind or another — money, energy, support, hope. When people are in this state, their relational warmth tends to retreat first. They are not punishing you. They are surviving. Ask directly what they are dealing with, in practical terms. Pentacles people often find it easier to discuss circumstances than feelings, and that conversation can be the doorway back into emotional contact.',
      },
      {
        q: 'Will the connection survive if Five of Pentacles appears?',
        a: 'It can, especially if the underlying hardship is named and addressed rather than left to rot in silence. The card describes a difficult season more than a doomed relationship. What it asks of you is honesty — about what you are missing, about what they are struggling with, about whether the cold can be warmed by real help rather than by you simply enduring more of it. Many connections do come through this card stronger, especially when both people are willing to walk inside the lit window of honest conversation and, where needed, outside support.',
      },
    ],
  },

  'six-of-pentacles': {
    uprightLong: `The Six of Pentacles as feelings describes affection that flows through generosity. They show what they feel for you by giving — time, money, attention, help, practical resources. Sometimes this generosity is glorious: a partner who delights in providing, who takes pleasure in your wellbeing, who genuinely wants to share what they have with you. Sometimes it is more complicated: a dynamic in which their care and their power over you have become intertwined, and the gifts come with quiet expectations. The card itself is neutral. The surrounding spread tells you which version is here.\n\nIn the healthy reading, this card is one of the warmer Pentacles signals. They feel real fondness, expressed through abundance and the desire to make your life easier. They notice what you need. They offer it before you have to ask. They take pleasure in providing rather than experiencing it as a burden. If you can receive cleanly — gratefully, without flinching or keeping score — this dynamic tends to feel deeply nourishing on both sides. Pentacles generosity, when it is real, is one of the most steadying forms of love available.\n\nIn the less healthy reading, the card warns of an exchange that is uneven in unspoken ways. They may give materially while receiving emotional labour, compliance, or your erasure of your own preferences. Affection becomes conditional on the maintenance of the imbalance. If that pattern is present, the question is not whether they care — they probably do — but whether their care can survive being asked to be mutual. Ask. The answer is information you need.`,
    reversedLong: `The Six of Pentacles reversed as feelings describes an unequal exchange that has begun to cost something. One of you is giving — money, time, emotional labour, planning, care — and the other is receiving without reciprocating in any sustainable way. The card does not always mean exploitation. It often means a giver-and-receiver pattern has settled in without either of you choosing it, and the imbalance is now corroding what affection was there.\n\nIn some readings, this reversal describes their feelings being conditional in ways that have started to show. They love you when you behave a certain way, or as long as the implicit deal is being honoured. The moment the exchange shifts — you ask for more, you give a little less, you stop accepting the unspoken terms — the warmth cools sharply. That is not love in any reliable sense. It is an arrangement dressed up as love, and the reversed Six is asking you to look at it clearly. The discomfort of recognising the pattern is much smaller than the discomfort of staying inside it for another decade.\n\nIn a gentler version, the reversal simply describes a couple where the giving-and-receiving balance has drifted, and the relationship needs a renegotiation. Money, domestic load, emotional labour, attention — whichever resource has become lopsided, name it. Pentacles people respond to honest accounting better than to vague resentment. If the love is real, it can survive an explicit conversation about fairness. If it cannot survive that conversation, it could not have survived the next ten years of compounded imbalance either. Either way, the truth is a kindness.`,
    howTheyFeel: `They feel fond of you in a way that wants to be expressed through generosity. Their instinct is to give — to help, to provide, to make your life smoother. If the dynamic between you is healthy, this is one of the more genuinely warm Pentacles energies, and you will probably feel cared for in tangible, repeated ways. They are likely thinking about what they can do for you more than what they can say to you.\n\nThe one thing worth watching is whether the giving and receiving feel reciprocal. Even loving Six of Pentacles people can settle into being permanent providers without noticing, and that asymmetry slowly drains a relationship. If you can receive what they offer gracefully and also invite them to receive from you, the bond tends to deepen rather than calcify. Their love language is generosity; your job is to let it be mutual rather than one-directional. Done well, this is a remarkably steady form of affection.`,
    feelingsFaqs: [
      {
        q: 'What does Six of Pentacles mean as feelings?',
        a: 'It means they express their feelings for you through generosity. Giving — money, time, attention, practical help — is their love language, and they often experience providing for you as genuinely pleasurable rather than burdensome. In the healthy version of this card, the warmth is real and the abundance is steadying. In the less healthy version, the giving may come with strings, unspoken expectations or a quiet imbalance of power. Read the surrounding cards, but generally the energy is benevolent. Receive cleanly, invite mutuality and the affection tends to settle into something deeply nourishing.',
      },
      {
        q: 'Is Six of Pentacles a good sign for love?',
        a: 'Usually yes, with one caveat. The card describes a partner whose care expresses itself through tangible giving, which is a real and underrated form of love. The caveat is that healthy generosity needs to be reciprocal. If the dynamic settles into one of you always giving and the other always receiving, even the warmest version of this card can drift into resentment or hidden power imbalance. Keep the exchange flowing in both directions. When it is mutual, the Six of Pentacles is among the more reliably affectionate signs in the deck.',
      },
      {
        q: 'Are their feelings genuine if Six of Pentacles appears?',
        a: 'Generally yes. Their generosity is most often a real expression of fondness rather than a manipulation tactic. The exception is when surrounding cards suggest control, conditionality or hidden expectations — in those cases, the giving may function as a way of buying your compliance. Look for whether they remain affectionate when you push back, ask for more, or fail to perform gratitude. Real Six of Pentacles love can survive those moments. Conditional Six of Pentacles love cannot. The test is honest and revealing without being cruel.',
      },
      {
        q: 'Do they want a long-term relationship if Six of Pentacles appears?',
        a: 'Usually yes, and they are often willing to put concrete resources behind it. Six of Pentacles people tend to like building a life together rather than orbiting it, and their generosity is part of how they declare themselves. Watch what they invest in — your home, your career, your wellbeing, your shared future. Those investments are quiet commitments. They may or may not be skilled at putting commitment into words, but they put it into action regularly. If you value tangible reliability, this is one of the safer cards to see in a feelings reading.',
      },
    ],
  },

  'seven-of-pentacles': {
    uprightLong: `The Seven of Pentacles as feelings describes someone who is taking stock of the connection rather than rushing it. They feel something for you — usually something real — and they are pausing to assess whether it is growing in the right direction, whether their investment is yielding what they hoped, whether the relationship is worth the further work it would take. This is not coldness. It is the deliberate, evaluating quality of someone who tends to love by building and is checking the structure as it rises.\n\nIn many readings, this card describes the patient middle of a relationship that has moved past the early bloom and is now in the slower work of growing into something durable. They are watching what fruit the season is producing — the trust, the compatibility, the shared rhythm — and they are mostly satisfied, though not yet ready to declare a final harvest. Their feelings deepen during this kind of pause rather than dissipate. The connection is being weighed, not abandoned.\n\nSometimes, more uncomfortably, the card describes someone who is reconsidering whether to keep investing. The pause has a cooler edge — they are asking themselves whether the relationship is worth more of their time, energy or resources. Even here, the energy is not dramatic. They are not running. They are sitting with the question, often quietly, often without telling you they are sitting with it. If you sense this version, an honest, low-pressure conversation about how each of you feels the connection is going can be enormously useful. Seven of Pentacles people respect partners who can think alongside them about whether what you are building is what both of you actually want.`,
    reversedLong: `The Seven of Pentacles reversed as feelings describes someone who has lost patience with the slow build, or who has been investing in the connection and not seeing what they hoped to see. Their feelings may still be present, but they are tired — of the lack of progress, the unfulfilled potential, the years of effort that have not yielded the harvest they expected. The card asks honestly whether the work is being put into the right field, or whether the field itself has been mistaken.\n\nIn some readings, this reversal describes them pulling back from continued investment in the relationship. They have looked at what has grown so far and concluded that it is not enough, or not what they wanted, or not in proportion to what they have given. This is rarely a sudden defection. It is the slow recognition, after a long evaluation, that the harvest is not coming or is not worth waiting for. From your side, you may notice a quiet disengagement rather than dramatic exit signs.\n\nIn a gentler reading, the reversal simply marks impatience that can be addressed. They feel for you and are frustrated with the pace of the connection — perhaps yours, perhaps theirs, perhaps life circumstances'. Naming the impatience explicitly often relieves it. Pentacles people respond well to honest accounting: what is working, what is not, what each of you still wants to plant. If both of you are still willing to tend the field, the reversal usually passes and the slow growth resumes. If only one of you is willing, this is information worth respecting now rather than pretending you did not see.`,
    howTheyFeel: `They feel invested in you and are quietly assessing whether the investment is going where they hoped. There is real affection underneath the pause, but they are not currently in a rush to make declarations. They tend to be the kind of person who measures love by what is being built over time, and right now they are looking at the structure so far and asking whether it is the shape they wanted.\n\nIf you can resist reading their thoughtfulness as withdrawal, you will see the affection more clearly. They are not stepping away; they are weighing. An honest, low-pressure conversation about where each of you sees the connection going tends to land well — Seven of Pentacles people respect partners who can think alongside them about the long arc. Avoid pressing for grand reassurances. Trust the steady, patient quality of their care, and let the harvest take the time it needs.`,
    feelingsFaqs: [
      {
        q: 'What does Seven of Pentacles mean as feelings?',
        a: 'It means they are taking stock of the connection rather than racing into it. There is real feeling on their side, but they tend to love by building and they are pausing to assess what has grown so far. This is not coldness. It is the considered, evaluating quality of someone who wants the relationship to be worth the long investment. Their feelings often deepen during this pause rather than fade. Resist the urge to read patience as ambivalence. The Seven of Pentacles favours slow, deliberate love — the kind that, when it does ripen, tends to sustain itself for years.',
      },
      {
        q: 'Are they reconsidering the relationship if Seven of Pentacles appears?',
        a: 'Sometimes, but rarely in a dramatic way. They are looking at the connection so far and asking honestly whether to keep investing. In many cases the answer is yes, and the pause is simply due diligence. In some cases they are noticing things they would like to address or improve. Either way, the energy is reflective rather than impulsive. The most useful response on your side is usually to invite real conversation about how each of you feels the relationship is going. Seven of Pentacles people respect that kind of co-evaluation enormously and tend to deepen rather than withdraw when it is offered.',
      },
      {
        q: 'Do they have long-term feelings if Seven of Pentacles is showing?',
        a: 'Often yes, and that is partly why they are pausing. Seven of Pentacles people think in seasons rather than weeks. They are checking whether the connection is the kind that will still be alive in five or ten years, and that very evaluation is a sign that they are taking it seriously. Short-term flings rarely produce this card. What you may be feeling as hesitation is more accurately described as patience. If the relationship is healthy, that patience tends to become the foundation of one of the steadier loves either of you will know.',
      },
      {
        q: 'How do I move things forward with Seven of Pentacles energy?',
        a: 'Slowly, honestly, with concrete invitations rather than pressure for declarations. Suggest something specific to plan together — a holiday, a project, a financial decision, a shared habit. Talk about how each of you sees the connection developing without demanding immediate answers. Seven of Pentacles people respond to partners who can sit with the long view alongside them. Pushing for rapid escalation tends to make them more cautious, not less. Trusting the pace, while gently bringing real future plans into the conversation, almost always moves the relationship forward more reliably than urgency would.',
      },
    ],
  },

  'eight-of-pentacles': {
    uprightLong: `The Eight of Pentacles as feelings describes someone who is actively working on becoming the partner they want to be — for themselves, and very likely for you. They are taking the connection seriously enough to refine themselves around it. This may show as a willingness to learn how to communicate, to address habits that have hurt previous relationships, to invest real attention in becoming better at the practical fabric of partnership. The feeling on their side is genuine, and it is being expressed through the patient, unglamorous work of self-improvement rather than through romantic declarations.\n\nIn some readings, this card describes a love that grows through daily effort. They are not coasting. They are not assuming that affection alone is enough. They show up, do the small things, refine their attention, learn what you need and adjust. That kind of love is rarer than it sounds and significantly more sustaining than dramatic intensity. If you can recognise the diligence as a love letter — written in tasks done well, promises kept, skills slowly mastered — you are reading the card correctly.\n\nThe card also suggests their feelings may currently be partially absorbed in another arena of effort. Eight of Pentacles people sometimes throw themselves into work, training or craft as a way of managing their inner life, and the relationship gets a slightly distracted version of them as a result. The feeling is real; the bandwidth may be partially elsewhere. Inviting them, kindly, to bring the same craftsmanship to the relationship itself often produces a noticeable deepening. They respond beautifully to being asked to be excellent in love the way they are excellent at their work.`,
    reversedLong: `The Eight of Pentacles reversed as feelings describes a partner whose attention is either misplaced or insufficient. The most common version is workaholism in some form — they are pouring themselves into work, study, training or another arena of effort while the relationship gets the leftovers. The feeling for you may be sincere and still be functionally absent for long stretches because all the bandwidth is going elsewhere. Pentacles people often confuse busyness with virtue, and the Eight reversed is where that confusion starts costing them their love life.\n\nIn a less generous reading, the reversal describes someone who has stopped putting effort into the relationship itself. Early in the connection they invested — learning what you wanted, doing the small things, refining how they showed up — and that effort has plateaued or quietly stopped. The feeling may still be there, but they have settled into autopilot. Cards do not always punish autopilot, but this one tends to, because Eight of Pentacles love requires renewed daily craftsmanship to stay alive.\n\nOccasionally the reversal describes inadequate skill rather than inadequate effort. They want to love you well and have not learned how. Their attempts to express affection miss. Their communication is clumsy. Their understanding of partnership is undercooked because they never apprenticed to it. This is more workable than it sounds, if both of you are willing to treat the relationship itself as a craft to be learned. Couples therapy, honest feedback and shared learning often produce significant change here. Eight of Pentacles people are, at their best, students of mastery. Show them how to apprentice to love, and they often rise to it.`,
    howTheyFeel: `They feel real attachment to you and are putting effort into the relationship in the patient, slightly serious way that defines them. Their love is unlikely to be loud, but it is likely to be diligent. They notice what works, refine what does not, and slowly build their capacity to be the kind of partner they want to be. If you have been hoping for romantic monologues, you may need to translate — but if you watch their behaviour over weeks rather than minutes, you will see the affection in motion.\n\nThe one thing to watch is whether some of their dedication is going into work or another arena at the expense of the relationship. Eight of Pentacles people sometimes pour themselves into craft as a way of regulating their inner life, and the partnership can end up sharing them with a workshop. Inviting them, kindly and specifically, to bring the same care to the relationship that they bring to their work usually lands well. They respect competence and they respect effort. Frame love itself as a craft, and they will tend to commit to mastering it.`,
    feelingsFaqs: [
      {
        q: 'What does Eight of Pentacles mean as feelings?',
        a: 'It means they are putting real, patient effort into the connection and into becoming the kind of partner who can sustain it. Their love language is diligence — small things done well, attention given consistently, skills refined for the relationship. The feeling on their side is genuine, and it is expressed through workmanship rather than declarations. Watch what they invest in, what they learn, what they refine. Each of those is a quiet love letter. If you can read effort as affection, the Eight of Pentacles is one of the most reliably committed cards you can see in a feelings reading.',
      },
      {
        q: 'Are they serious about me if Eight of Pentacles appears?',
        a: 'Almost certainly yes. Eight of Pentacles people do not usually expend this much effort on connections they consider casual. The card describes someone working at the relationship — and at themselves on behalf of the relationship — which is one of the more meaningful signs of seriousness in the deck. They may not be loud about it, and their seriousness can be obscured by the unspectacular quality of their attention. Look at consistency over time. If their behaviour is steadily refining around what works for you, you are watching someone take the connection extremely seriously.',
      },
      {
        q: 'Why do they focus on work if Eight of Pentacles is showing?',
        a: 'Partly because work is one of the main ways they regulate their inner life, and partly because they tend to confuse busyness with virtue. Eight of Pentacles people often pour themselves into craft, training or career as a kind of devotion, and the relationship can get a slightly distracted version of them as a side effect. The feeling for you is rarely the casualty; the bandwidth is. Inviting them gently to bring the same dedication to the partnership that they bring to their craft is often the most productive request you can make. They generally rise to it.',
      },
      {
        q: 'Do their feelings deepen over time with Eight of Pentacles?',
        a: 'Yes, usually substantially. Their affection grows through the ongoing work of getting better at loving you — learning your preferences, refining their communication, becoming more skilled at the practical fabric of partnership. The longer the relationship lasts in a healthy form, the more depth they tend to develop. Their love does not peak early and decline. It compounds. If you can value patient growth over early intensity, the Eight of Pentacles is one of the more rewarding feelings to be on the receiving end of in the long run.',
      },
    ],
  },

  'nine-of-pentacles': {
    uprightLong: `The Nine of Pentacles as feelings describes someone who feels affection for you from a place of genuine self-sufficiency. They do not need you in the desperate sense. They want you, which is a different and more dignified posture. Their inner life is in order, their material life is in order, and from that calm vantage point they have chosen to let you matter to them. This is one of the more emotionally mature signals in the deck. The feeling on their side is unhurried, grounded and adult.\n\nIn many readings this card describes a partner who has done the work — on themselves, on their boundaries, on their finances, on their sense of identity — and arrives in the relationship already whole. They are not looking for you to complete them. They are interested in adding you to a life they already enjoy. That can feel slightly cool at first if you are used to relationships built on mutual need, but the warmth underneath is real. It is simply expressed through invitation rather than dependence.\n\nThe card also suggests their feelings include a clear-eyed appreciation of their own standards. They are not desperate for company. They are picky in a healthy way, and they have chosen you out of genuine recognition. Honour that by meeting them as a peer rather than as someone hoping to win them over. Bring your own self-sufficiency. Bring your own life. The Nine of Pentacles thrives on partnership between two complete people, and their affection deepens noticeably when you are visibly comfortable in your own skin rather than orbiting theirs.`,
    reversedLong: `The Nine of Pentacles reversed as feelings describes affection that is being undermined by something — most often by a quiet undermining of their own self-sufficiency or yours. They may be reaching for the relationship from a place of recent loss, financial stress or shaken identity rather than from the calm wholeness the upright card describes. The feeling is real, but it is wobbling on a foundation that has not yet steadied. Read the surrounding cards to see whether the wobble is small and temporary or larger and structural.\n\nIn some readings this reversal describes someone whose independence has tipped into isolation. They have built a life so self-sufficient that letting anyone — including you — fully in has become difficult. The feeling on their side may be substantial and the door may be quietly closed. They are not absent because they do not care. They are absent because their solitude has become its own kind of comfort, and partnership feels intrusive to the careful order they have built.\n\nLess commonly, the reversal warns of a partner whose elegance and apparent stability mask insecurity, financial trouble or emotional shakiness they have not let you see. The Nine of Pentacles can be a slightly performed card, and reversed it sometimes reveals that the polished version was always partly costume. None of this is fatal. It does, however, ask both of you to drop the appearance of having it all together and to meet each other more honestly. Real affection survives that honesty. Performed affection rarely does.`,
    howTheyFeel: `They feel a calm, considered fondness for you rather than a desperate need. There is a real sense on their side of having chosen you from a place of strength, which can feel either dignified or slightly distant depending on what you are used to. They probably value you specifically — your independence, your taste, your competence — rather than valuing you for what you provide them emotionally. That is a compliment in this card's language.\n\nIf you can resist reading their self-sufficiency as coolness, you will see the warmth more clearly. They are not orbiting you because they do not need to, and that emotional adulthood is part of what they are offering. Meeting them with your own grounded life — your own friendships, work, interests, sense of self — tends to deepen the affection on their side considerably. Nine of Pentacles people are quietly delighted to share their well-ordered existence with someone who has built their own. Bring your version of that, and the relationship tends to settle into something both elegant and durable.`,
    feelingsFaqs: [
      {
        q: 'What does Nine of Pentacles mean as feelings?',
        a: 'It means they feel affection for you from a place of self-sufficiency and genuine choice rather than need. Their life is in order — emotionally, materially, internally — and they have decided to let you matter to them out of dignified preference rather than desperation. This is one of the more emotionally mature feelings in the deck. The energy is unhurried, grounded and adult. Their love does not look like dependence; it looks like invitation. Read their calm as warmth, not coolness, and meet them as a peer rather than as someone hoping to be chosen.',
      },
      {
        q: 'Is Nine of Pentacles a good sign for love?',
        a: 'Generally very good, especially if you value stability and emotional maturity over romantic intensity. The card describes a partner who is already whole and has chosen you from that wholeness, which tends to produce far more sustainable affection than relationships built on mutual need. The main thing to watch is whether their self-sufficiency leaves real room for partnership or whether it has tipped into self-contained isolation. In a healthy reading, the Nine of Pentacles is one of the more dignified and reliable expressions of love in the deck.',
      },
      {
        q: 'Do they really need me if Nine of Pentacles appears?',
        a: 'They do not need you in the desperate sense, and that is part of why the love is healthier. They want you, which is a sturdier basis for partnership than need. If you are used to feeling loved because someone could not function without you, the Nine of Pentacles version of affection can feel unfamiliar at first. Sit with it. Being wanted by a complete person, rather than required by an incomplete one, is one of the more durable forms of being loved you will ever experience. The depth is real, even if the dependence is absent.',
      },
      {
        q: 'Are they emotionally distant if Nine of Pentacles is showing?',
        a: 'Not usually. They are emotionally self-contained, which can read as distance to someone expecting the constant emotional reaching of less grounded relationships. The affection is real; the expression is unhurried. They are unlikely to dissolve into you, and they will not require you to dissolve into them. If that level of mutual emotional separateness feels lonely to you, it is worth naming, because the Nine of Pentacles will not change its temperature on its own. With honest conversation, however, this energy can be deeply warming once you learn to read its language.',
      },
    ],
  },

  'ten-of-pentacles': {
    uprightLong: `The Ten of Pentacles as feelings is one of the most committed signals in the deck. The other person is not just feeling for you — they are imagining you inside their family, their generational story, their long-term wealth, their idea of home. The card describes love that is consciously oriented toward permanence. They see you as someone they could marry, raise children with, build a life around. The feeling is steady, slow-burning and deeply serious.\n\nIn many readings, this card describes affection that has already passed through the early tests and is moving into the territory of legacy. They are introducing you to their parents, integrating you into family rituals, considering financial decisions with you in mind, possibly thinking explicitly about marriage or shared property. Pentacles love at this level is unmistakable in its concreteness. They are putting you into the calendar, the will, the holiday traditions, the long story. Each of those acts is a love letter written in something more lasting than ink.\n\nThe card also suggests their feelings are tied to a sense of belonging — they want you to become family, not just be partner. This carries beautiful weight and occasionally some pressure. Their family of origin, their cultural traditions, their financial dynasty may all become part of the relationship in ways that can feel either welcoming or constraining depending on the specifics. Mostly the Ten of Pentacles arrives with abundance and generosity rather than control. If you want the kind of love that builds dynasties — quiet, durable, generational — this card is among the most reliable signs you can receive.`,
    reversedLong: `The Ten of Pentacles reversed as feelings describes affection that is tangled with family pressure, legacy expectations or material complications. They may feel deeply for you and still be navigating a complicated relationship with their parents, an inheritance situation, a divorce, a previous family they are still untangling, or cultural expectations they cannot quite escape. The feeling is real; the surrounding family system is interfering with their ability to fully bring you into it. Read the surrounding cards for specifics.\n\nIn some readings, this reversal describes a partner whose vision of long-term partnership clashes with yours in important ways. They want the dynasty, the house, the children — and you do not, or vice versa. Or they imagine the long arc with you while not fully showing up in the present. Pentacles love that is too oriented to a far-off future and undernourished in the now slowly loses its grip on real affection. The card asks both of you to bring the long view back into contact with daily life.\n\nLess commonly, this reversal warns of feelings that have become more about role, lineage or material continuity than about you specifically. You may sense that they want a wife, a husband, a co-parent, a stable household — and the particular person filling that slot is somewhat interchangeable. That is harder to hear, and not always the case. Honest conversation about whether they love you or the position you occupy in their life tends to clarify quickly. Real Ten of Pentacles love survives that conversation and often deepens through it.`,
    howTheyFeel: `They feel something serious, durable and oriented toward a real future. There is a sense on their side of imagining you long-term — not as fantasy, but as actual planning. Family, home, money, legacy are likely entering the picture, either explicitly or in the background of their thinking. The affection has a weight and steadiness that does not flicker.\n\nIf you have been waiting for a clear signal of commitment, the Ten of Pentacles is among the most reliable signs you could hope for. The expression of the feeling will still tend to be Pentacles-quiet — practical decisions, family introductions, financial planning, household-building — rather than verbal romance. But the orientation is unmistakable. They are not just feeling something temporary about you. They are considering you part of the long story of their life, and most often acting on that consideration in concrete, observable ways.`,
    feelingsFaqs: [
      {
        q: 'What does Ten of Pentacles mean as feelings?',
        a: 'It means their feelings are oriented toward permanence. They are not just experiencing affection — they are imagining you inside their family, their long-term wealth, their idea of home. The card describes love that is consciously aimed at building a life together over years rather than a connection lived in the present alone. Expect them to express this through concrete actions — family introductions, financial planning, household decisions, possibly marriage conversations. Each of those is a love letter in the language of dynasty. This is one of the most seriously committed cards you can receive in a feelings reading.',
      },
      {
        q: 'Does Ten of Pentacles mean marriage or long-term commitment?',
        a: 'Frequently yes. The Ten of Pentacles is one of the deck\'s clearest signals of legacy-oriented love — the kind that thinks in decades rather than weeks. Many querents see this card around significant commitment milestones: meeting the family, moving in together, getting engaged, buying property, having or planning children. The pace will tend to be measured rather than impulsive, in keeping with Pentacles energy, but the direction is unmistakable. They are not just dating you; they are seriously considering building a long life with you and acting accordingly.',
      },
      {
        q: 'Are their feelings deep if Ten of Pentacles appears?',
        a: 'Almost always yes, though the depth will tend to express itself through stability and concrete planning rather than through dramatic intensity. Ten of Pentacles love is more like an ancient oak than a fireworks display — slow-growing, quiet, profoundly rooted. If you have been raised on stories where love is mainly defined by emotional volatility, you may need to recalibrate. What they feel is substantial. It just expresses itself through the gradual, sturdy building of a shared life rather than through declarations.',
      },
      {
        q: 'How do family dynamics affect feelings with Ten of Pentacles?',
        a: 'Significantly, often in helpful ways and occasionally in complicated ones. Ten of Pentacles love is family-oriented by nature, so their parents, siblings, cultural traditions and inheritance situations tend to become part of the relationship more than they might in other cards. In the healthy reading, this means abundance, belonging and warm integration. In the more difficult reading, it can mean family pressure, generational expectations or unresolved dynamics from their origin household entering your partnership. Either way, expect family to be relevant. Talking about it honestly tends to strengthen the connection rather than threaten it.',
      },
    ],
  },

  'page-of-pentacles': {
    uprightLong: `The Page of Pentacles as feelings describes someone whose affection for you is fresh, earnest and oriented toward learning. They are interested in the connection in a serious-minded way, even if they are young in love — either literally or in experience — and not yet sure how to express what they feel. There is a slightly studious quality to their care, as if they are trying to do partnership properly and are noticing what works. The feeling is genuine; the expression is occasionally awkward; the orientation is unmistakably grounded.\n\nIn many readings, this card describes the early stages of a relationship being approached with real intent. They are paying attention. They are learning your preferences. They are taking small, practical steps to demonstrate care — bringing the right snack, remembering a small detail, offering useful help. Page of Pentacles people are not flashy romantics. They are devoted apprentices, and what they lack in suaveness they tend to make up for in sincerity. Their feelings rarely come with grand declarations; they come with diligent, slightly endearing acts of attention.\n\nThe card also suggests their feelings are still finding their shape. They may not fully know yet what they want from the relationship, only that they want to keep showing up and learning more about you. This is an excellent starting energy, especially if you can resist the urge to rush them into definitive answers. Pages mature into Knights and Kings; Pentacles affection that is allowed to grow at its own earnest pace tends to produce some of the most stable long-term partnerships. Meet them where they are. Trust the apprentice quality. The depth tends to follow.`,
    reversedLong: `The Page of Pentacles reversed as feelings describes affection that is immature, distracted or stuck in fantasy without the willingness to do the practical work. They may feel something for you and lack either the skill, the focus or the seriousness to act on it as a real partner. The feeling is often genuine in spirit and underdeveloped in execution. They want the relationship in theory and have not yet learned how to want it in practice.\n\nIn some readings, this reversal describes someone who treats love as a kind of theoretical project — they read about it, they think about it, they discuss it — and never quite move into the actual labour of partnership. Plans are made and not kept. Promises are sincere and unfulfilled. The intention is there; the follow-through is not yet. With patient, kind feedback this can sometimes mature. Without it, the energy tends to fizzle into perpetual not-quite-readiness.\n\nLess commonly, the reversal warns of a partner whose youthfulness — in age, in experience or in emotional development — makes them genuinely unable to meet you as a peer. The feelings are real and the gap is real. Pentacles loves do mature, sometimes considerably, but expecting an apprentice to be a master is unkind to both of you. Read the surrounding cards for specifics about whether this is a temporary stage or a settled pattern. If the gap is just a phase, patience can work. If it is structural, the kindest response is to stop pretending it is not there.`,
    howTheyFeel: `They feel something earnest and slightly tentative for you. Their affection is real but not yet polished, and they are probably figuring out how to express it as they go. There may be small, slightly clumsy gestures of care — a thoughtful gift that does not quite land, an attempt at planning that needs your help to come together, a sincere message at an odd hour. Each one is an honest love letter, even when the execution is imperfect.\n\nIf you can read their effort as affection rather than as inadequacy, the connection tends to deepen quickly. Page of Pentacles people respond strongly to being met with patience and gentle feedback. They want to be good at this, and they are willing to learn. Avoid the temptation to write them off for early awkwardness. Many of them mature into some of the most attentive, devoted partners in the deck, particularly when their apprentice phase is honoured rather than rushed through.`,
    feelingsFaqs: [
      {
        q: 'What does Page of Pentacles mean as feelings?',
        a: 'It means their affection for you is fresh, earnest and oriented toward learning. They are taking the connection seriously and trying to do it properly, even if they are still finding their feet. The energy is studious rather than smooth — small acts of attention, practical gestures, slightly awkward but genuinely thoughtful efforts. They want the relationship and are willing to apprentice themselves to becoming the partner it requires. The feeling is sincere; the polish will come with time. Honour the apprentice quality, give patient feedback, and the affection tends to deepen into something quietly substantial.',
      },
      {
        q: 'Are they ready for a serious relationship if Page of Pentacles appears?',
        a: 'They are ready to start one, though not necessarily ready to perform one at full maturity yet. The Page of Pentacles describes someone in the early stages of learning what real partnership requires. They are willing, they are earnest and they are growing. If you can let the relationship develop at the apprentice pace, with room for them to make small mistakes and refine their skills, the foundation tends to become quite solid. If you need a fully formed partner immediately, you may need to wait for them to mature into the Knight or King stage — and many of them do.',
      },
      {
        q: 'Is Page of Pentacles a new beginning in love?',
        a: 'Very often yes. The card frequently appears at the start of relationships, the early stages of someone reopening to love after a long absence, or the beginning of a new chapter in an existing partnership. The energy is hopeful and earthy — a small green shoot emerging from real soil. Beginnings under this card tend to be modest rather than dramatic, which is usually a good thing. Pages of Pentacles grow slowly and steadily. The shy beginning often matures into a connection considerably more durable than the showier starts of other cards in the deck.',
      },
      {
        q: 'Do their feelings mature with Page of Pentacles?',
        a: 'Yes, generally, and that is one of the most encouraging things about this card. Page of Pentacles people are apprentices by nature, and apprentices do tend to become journeymen and masters over time if they are given room and good feedback. The affection that begins as earnest and clumsy often matures into deeply attentive, practically devoted love. Patience pays disproportionately well with this energy. Resist the urge to discount them for early awkwardness. Many of the most attentive long-term Pentacles partners began their relationships under this exact card.',
      },
    ],
  },

  'knight-of-pentacles': {
    uprightLong: `The Knight of Pentacles as feelings describes someone whose affection is exceptionally steady, methodical and reliable. They are the slowest-moving knight in the deck, and that is precisely their gift in love. They will not sweep you off your feet. They will, however, show up. Every time. With the things they said they would bring. Doing what they said they would do. Their feeling for you is expressed through consistency at a level most other cards in the deck cannot match.\n\nIn many readings, this card describes a partner who plans the connection like a long campaign rather than a sprint. They are not impulsive. They do not move until they have considered the move. Once they commit, however, they commit thoroughly and tend not to deviate. Their love is the kind that pays the bills on time, remembers the anniversary, fixes the boiler before winter and quietly accumulates into something profound through sheer repetition of small honourable acts. If you want fireworks, this knight will frustrate you. If you want the rarer thing — someone who is genuinely dependable — you have been served well.\n\nThe card can also describe a slight emotional reserve that comes with the steady temperament. They may feel deeply and express it sparingly, preferring action to language. Do not mistake their unflashy quality for shallow feeling. Underneath the unhurried surface, their affection is usually significant, and it grows by the year rather than by the week. Honour the pace. The Knight of Pentacles makes one of the most reliable long-term partners in the deck precisely because they refuse to be rushed into anything they cannot sustain.`,
    reversedLong: `The Knight of Pentacles reversed as feelings describes the slow steadiness tipping into stagnation. They may still care about you, but the relationship has stopped progressing in any meaningful way. The reliability is intact; the growth is absent. They show up, do what they always do, and have stopped imagining anything could be different. Some couples are content with this. Many slowly suffocate inside it. Read the surrounding cards for whether this is comfortable or quietly killing the connection.\n\nIn another reading, the reversal describes a partner whose caution about love has become outright avoidance of commitment. They take so long to move that the relationship never quite forms. Months turn into years of dating, friends-with-something, almost-relationship — never resolving into anything definite. The feelings may be real and the willingness to act on them simply never matures. If you have been waiting for them to translate steadiness into actual partnership, the reversed Knight is sometimes a sign that the translation is not coming.\n\nLess commonly, the reversal can describe someone whose practicality has become a form of emotional withholding. Everything is being done — the bills paid, the chores managed, the logistics covered — and the warmth has been quietly outsourced to admin. Partnership at this point feels like cohabitation with a competent housemate. Naming the absence of emotional life kindly can sometimes restart it. Knight of Pentacles people respond to specific requests far better than to general dissatisfaction. Ask for the warmth concretely. If it cannot return, that itself is information worth respecting.`,
    howTheyFeel: `They feel a steady, durable, slow-building affection for you. There is little drama in what they are experiencing, but there is real substance. Their feeling is more like a low fire than a candle — quiet, persistent, capable of warming a whole house over time. They are probably not going to declare themselves loudly. They are going to show up, repeatedly, in the small dependable ways that define their love language.\n\nIf you can let action count as romance, this is one of the more reliably committed energies in the deck. The pace will frustrate anyone who wants rapid escalation. The reliability will quietly delight anyone who has been burned by partners who moved fast and broke things. Watch the consistency — the small promises kept, the routines maintained, the patient presence — and read it as the love letter it is. Knight of Pentacles affection deepens by the year rather than by the moment, and what it builds tends to last.`,
    feelingsFaqs: [
      {
        q: 'What does Knight of Pentacles mean as feelings?',
        a: 'It means their affection is steady, methodical and exceptionally reliable. The Knight of Pentacles is the slowest-moving knight in the deck, and that pace is part of the gift. They will not sweep you off your feet. They will show up consistently, do what they said, and let the relationship build through patient repetition rather than dramatic gestures. Their feelings are usually deep and quietly expressed. If you can read consistency as romance, this is one of the more dependable and committed signals in the deck — the kind of love that makes a stable life rather than an unforgettable summer.',
      },
      {
        q: 'Are Knight of Pentacles feelings boring?',
        a: 'They can feel that way to anyone who has been raised on the assumption that love must be exciting to be real. They are not boring; they are unhurried. The drama is low and the reliability is high, which is genuinely a different texture of affection than most cards in the deck offer. If you value stability and dependability over intensity, this energy is excellent. If you genuinely need volatility to feel alive in a relationship, the Knight of Pentacles will quietly drive you mad. Both responses are legitimate. Knowing which you are saves a great deal of grief later.',
      },
      {
        q: 'Will they commit if Knight of Pentacles appears?',
        a: 'Almost always yes, though on their own timeline. The Knight of Pentacles is methodical about love because they take it seriously, not because they are uncertain. They tend to commit after considerable, sometimes invisible deliberation, and once they commit they tend not to deviate. Pushing them to commit faster usually slows them rather than speeds them. Trusting their pace, while quietly making your own intentions clear, tends to land much better. When they do commit, they commit profoundly, and the result is often one of the steadier long-term partnerships in the deck.',
      },
      {
        q: 'Why are they so slow if Knight of Pentacles is showing?',
        a: 'Because that is how they love. Knight of Pentacles people consider every significant step carefully, sometimes to a degree that frustrates faster-moving partners. The slowness is not indecision; it is a kind of devotion to getting things right. They do not want to make promises they cannot keep, so they wait until they are sure they can keep them. Once a promise is made, it tends to be honoured for decades. Read the slowness as seriousness rather than reluctance. The patience pays off handsomely in the long run, even when it tests you in the short term.',
      },
    ],
  },

  'queen-of-pentacles': {
    uprightLong: `The Queen of Pentacles as feelings describes someone whose affection for you is nurturing, sensual, embodied and deeply practical. They love by feeding you — sometimes literally — and by making sure the world around you is warm, comfortable, abundant. Their care has a quality of being held inside a beautifully run household, whether or not you actually share a roof. They notice what you need before you have to ask. They quietly arrange for it to be there. The feeling is generous, grounded and unmistakably warm.\n\nIn many readings, this card describes a partner who loves through hospitality, body care, financial competence and the steady creation of comfort. They are not usually the kind to write you sonnets. They are the kind to cook you the meal you needed, run you the bath you forgot to ask for, remember the medication you ran out of, and quietly handle the practical fabric of life so that you can be more easeful in it. Each of these is, in Queen of Pentacles language, a deep declaration of love. The sensuality of this card is also worth noting — their affection tends to include the body, in touch, in food, in physical presence.\n\nThe card also suggests their feelings are tied to a sense of home. They want to make a life with you, not just a relationship. They may begin folding you into their domestic rhythms — meals, routines, the small rituals of comfort — long before they put commitment into words. Read those rituals as the love letters they are. Honour their care by receiving it cleanly rather than deflecting it, and by offering your own version of warmth back. The Queen of Pentacles loves abundantly, and abundance is most beautiful when it is allowed to flow in both directions.`,
    reversedLong: `The Queen of Pentacles reversed as feelings describes nurturing affection that has become depleted, smothering or transactional. They may genuinely care about you and have lost the resourced calm that makes their care nourishing. Tired, stressed or overgiving, they can tip into resentful caretaking — doing the meals, the chores, the logistical heavy lifting, while the warmth that once accompanied those acts has been quietly squeezed out by exhaustion. The feeling is still there; the embodiment of it has gone thin.\n\nIn some readings, this reversal describes love that has become controlling or possessive in a domestic key. They want to nurture you in a way that does not quite leave room for you to be a separate adult — managing your diet, your schedule, your finances, your friendships, all in the name of care. Affection in this mode can feel like being smothered by abundance. Naming the pattern kindly is usually necessary; Queen of Pentacles people rarely realise that their care has tipped into control until someone tells them. Most of them, when told, are open to recalibration.\n\nLess commonly, the reversal warns of a partner who uses material provision as a substitute for emotional presence. They give you the house, the comforts, the well-stocked fridge — and have not been emotionally available in months. The form of love is intact and the substance has hollowed out. Look at the surrounding cards. If the form can be filled with substance again through honest conversation and shared effort, this is workable. If the form has become a way of avoiding intimacy permanently, the kindness is to recognise the absence rather than continue mistaking provision for love.`,
    howTheyFeel: `They feel a warm, embodied affection for you that wants to be expressed through care of your whole life — body, home, comfort, daily wellbeing. There is a sense on their side of wanting to make things easier and lovelier for you, often through small practical acts: feeding you, planning for you, looking after the parts of life that drain other people. The feeling is generous and physical and quietly devoted.\n\nIf you can receive their care without flinching or keeping score, the affection on their side tends to deepen substantially. Queen of Pentacles people are sometimes underappreciated because their love language is so woven into the texture of ordinary life that it can become invisible. Make the invisible visible. Notice the meal, the bath, the well-stocked fridge, the calm presence in a stressful week, and let them know you see it. They flourish under appreciation, and they tend to offer even more of themselves once they feel their care is being received as love rather than expected as service.`,
    feelingsFaqs: [
      {
        q: 'What does Queen of Pentacles mean as feelings?',
        a: 'It means their affection for you is nurturing, embodied and deeply practical. They love through feeding you, caring for your body, creating comfort, managing the domestic fabric of life so you can be at ease in it. The feeling is warm, generous and physical — often more eloquent in action than in language. Each meal cooked, bath run, schedule managed and small comfort arranged is a love letter in their dialect. Receive cleanly, appreciate explicitly, and the affection tends to deepen. This is one of the more genuinely nourishing feelings in the deck, especially in long-term partnerships.',
      },
      {
        q: 'Are Queen of Pentacles feelings stable?',
        a: 'Yes, remarkably so. Queen of Pentacles people tend to love at a steady, sustainable temperature rather than in dramatic peaks and valleys. The affection is woven into daily life in ways that make it durable across years. They are unlikely to flame out emotionally. The main risk is the opposite — that their care becomes so steady and so embedded in routine that it stops being noticed and appreciated. Honour the steadiness explicitly. The relationship tends to thrive when their nurturing is recognised as the active love it actually is rather than treated as a background utility.',
      },
      {
        q: 'How do they show love if Queen of Pentacles appears?',
        a: 'Through care of your whole life. Expect them to nurture you with food, comfort, body care, beautifully run domestic arrangements, financial competence and quiet practical attention to what you need. Many also love through touch, sensuality and physical presence — the body is part of how affection moves for them. If you have been raised expecting love to be primarily verbal, you may need to translate. What looks like simply being taken care of is, in this card\'s language, a continuous and unmistakable declaration of love. The trick is learning to read the dialect.',
      },
      {
        q: 'Do they want a family if Queen of Pentacles is showing?',
        a: 'Frequently, though not always literally. The Queen of Pentacles is deeply oriented to home and to nurturing — which often includes wanting children, but can also mean wanting a richly tended household, deep friendships, animals, gardens, a generous welcoming life. They tend to want a shared rooted existence rather than a relationship lived in restaurants and hotel rooms. If literal children are part of your hopes, this card is usually a strong indicator that they share that orientation. Either way, expect them to want a real, embodied life built with you over years.',
      },
    ],
  },

  'king-of-pentacles': {
    uprightLong: `The King of Pentacles as feelings describes a partner whose affection is generous, steady and rooted in real competence at building a life. Their feeling for you is expressed through the considerable resources they have spent decades accumulating — time, money, attention, judgement, the ability to make things happen in the world. They have done the work of becoming a substantial adult, and they want to share what they have built. The feeling is quiet, confident and unmistakably serious.\n\nIn many readings, this card describes a partner who loves through provision in the largest sense. They will not just feed you; they will think about your long-term financial security. They will not just plan a date; they will plan the next decade. Their attention to your wellbeing extends across the full landscape of life — health, work, family, money, comfort — and their care has a kind of unhurried mastery to it. There is often a touch of paternal quality, regardless of gender, which can be either deeply reassuring or slightly overshadowing depending on how the dynamic is balanced.\n\nThe card also suggests their feelings are inseparable from the life they want to build. They are not romanticising you in the abstract. They are imagining you specifically inside the household, the estate, the legacy, the long sober story of who they are. That is a profound compliment. Honour it by bringing your own substance to the relationship — your own competence, your own resources, your own grown-up self. The King of Pentacles loves most easily when the partnership is between two genuine adults, and the affection tends to deepen considerably when you meet him as a peer rather than as a recipient of his abundance.`,
    reversedLong: `The King of Pentacles reversed as feelings describes affection that has been tangled with money, control or an overbearing sense of authority. They may genuinely care for you and have not yet noticed that their generosity has acquired a slight grip — provision has become expectation, abundance has become leverage, partnership has become patronage. The feeling is real; the expression of it has accumulated some controlling habits that need to be unpicked.\n\nIn another reading, this reversal warns of a partner whose material success has hollowed out their emotional capacity. They have built a great deal — career, money, status, household — and have not done the equivalent inner work, so the emotional life of the relationship has gone undertended. Affection in this state can feel transactional, formal or vaguely corporate. Naming the absence honestly is usually necessary; King of Pentacles people often rise to feedback they respect, especially when it is given competently rather than emotionally.\n\nLess commonly, the reversal describes someone who looks like a King of Pentacles from the outside — substantial, established, providing — and is in fact financially precarious, professionally shaky, or quietly struggling in ways they have not let you see. The appearance of mastery has become more important to them than the reality of it, and the affection is being delivered partly through performance. None of this is fatal. It does, however, require an honest conversation. Real King of Pentacles love survives the dismantling of the mask. Performed King of Pentacles love rarely does, and recognising the difference saves enormous time and grief.`,
    howTheyFeel: `They feel a serious, generous affection for you that wants to express itself through the substantial life they have built. There is unlikely to be a great deal of emotional theatre on their side, but there is real depth underneath the steady surface. They are probably thinking about you in terms of long-term wellbeing — your security, your comfort, your place in their world — more than in terms of romantic intensity.\n\nIf you can read provision, planning and unhurried competence as love, this is one of the more substantively committed energies in the deck. They are not flighty. They are not impulsive. Their affection is the kind that translates into actual decisions about money, household, future and family. Meeting them with your own grown-up presence — your own competence, your own clear preferences, your own life — tends to deepen the connection considerably. King of Pentacles people love most easily between equals, and they offer their best when the partnership is genuinely mutual rather than top-down.`,
    feelingsFaqs: [
      {
        q: 'What does King of Pentacles mean as feelings?',
        a: 'It means their affection for you is generous, steady and rooted in real adult competence. They express love through the substantial life they have built — money, household, judgement, long-term planning — and they want to share what they have made. The feeling is unhurried, confident and seriously committed. They are not usually romantics in the verbal sense. They are providers, planners and quietly devoted partners whose love letters tend to look like financial decisions and household arrangements. Read provision as affection, meet them as a peer, and the connection tends to settle into something both substantial and warm.',
      },
      {
        q: 'Are King of Pentacles feelings serious?',
        a: 'Very. The King of Pentacles is one of the most committed feelings cards in the deck. He does not enter relationships lightly, and he does not stay in them casually. When he loves, he loves with the full resources of the life he has spent decades building. The seriousness will tend to express itself through long-term action — financial planning, household decisions, family integration — rather than through emotional declarations. If you value durable commitment over romantic intensity, this card is excellent news. If you need verbal warmth, you may need to ask for it specifically.',
      },
      {
        q: 'Do they want to provide if King of Pentacles appears?',
        a: 'Almost always yes, and providing is one of their primary love languages. They take genuine pleasure in being able to make your life easier, more comfortable and more secure. The healthy version of this energy is generous and grounding; the less healthy version can tip into control or condescension when their provision becomes expectation. Receive cleanly, contribute your own substance to the partnership, and the abundance flows beautifully. King of Pentacles people tend to love most freely when their generosity is appreciated without being depended on, and when the relationship is mutual rather than hierarchical.',
      },
      {
        q: 'Are they emotionally available if King of Pentacles is showing?',
        a: 'They are reliably available in the practical sense, and somewhat more variable in the emotional sense. Many King of Pentacles people have built their substantial lives partly by being competent at action and somewhat less skilled at feelings work. The affection underneath is usually real and considerable. The expression can be reserved, formal or slightly understated. If you need more verbal warmth, ask for it directly and concretely. King of Pentacles people respond well to specific, competent feedback and can grow noticeably in their emotional fluency when invited to do so by a partner they respect.',
      },
    ],
  },
}
