import type { ReversedContext } from '../card-reversed-extended'

export const MAJOR_2: Record<string, ReversedContext> = {
  'justice': {
    loveLong: `Justice reversed in love almost always points to a quiet imbalance that has been allowed to settle in — one partner doing more of the emotional labour, one voice carrying more weight in the joint decisions, one person's needs habitually deferred while the other's are routinely centred. These imbalances rarely arrive dramatically. They accumulate through a thousand small acquiescences, until the relationship runs on a structural unfairness that neither person quite wants to name because naming it would require change. The card reversed asks you to look at the ledger honestly: who is carrying what, and is that distribution actually fair, or merely habitual?

There is also a more pointed expression — outright dishonesty. A partner withholding information, a financial deception, an emotional affair, or a more mundane pattern of small untruths told to avoid friction. Justice reversed does not always indicate this, but when it appears with other cards of concealment, the discrepancy between what is being said and what is being lived is worth examining. Equally, look at your own behaviour. Are you being scrupulously honest about your feelings, your wants, the things you have done that you would rather not discuss?

The medicine here is not punishment — Justice reversed isn't about meting out consequences — but about restoring genuine fairness through honest conversation. That conversation will be uncomfortable, particularly if the imbalance has been long-standing, but the discomfort is the point of entry. Relationships built on unspoken inequity slowly hollow themselves out. Relationships willing to do the harder work of equitable repair tend to become the more durable kind. Decide which you want this to be.`,
    careerLong: `Justice reversed at work typically appears when something has gone genuinely sideways in a professional setting: a decision that wasn't fair, credit that wasn't given, a contract being interpreted in bad faith, or a workplace culture where outcomes don't match contribution. It can also surface around legal or quasi-legal matters — a tribunal, a dispute, a grievance — where the process itself is not operating with the impartiality it claims to. When the card arrives in a career reading, take it as confirmation that your instinct about the unfairness is probably accurate, even if you have been talking yourself out of that instinct.

The more difficult version of Justice reversed in career is the one that asks about your own conduct. Have you genuinely earned the position you hold, or have you accepted credit for work that wasn't yours? Have you been operating with full integrity around expenses, reporting, hours, or commitments? The card is not interested in shaming you — it is asking you to clean up any genuine misalignments before the consequences arrive on their own schedule. Sloppiness here tends to compound. Honest small corrections now are far cheaper than the larger reckonings that wait.

Practically: document carefully, keep records, read the contracts you sign, and don't agree to terms you wouldn't be willing to defend in front of an impartial third party. If you are in a workplace that operates unfairly and shows no genuine willingness to change, Justice reversed often arrives as the first whisper that you may eventually need to leave. Not yet, perhaps, but begin paying attention. Environments that are structurally unjust rarely repair themselves in time to benefit the people they are harming.`,
    spiritLong: `Justice reversed spiritually points to a gap between the values you profess and the life you are actually living — the daily choices, small honesties, and unwitnessed actions that constitute the real shape of a person's spiritual practice. Most people in spiritual circles can articulate their values clearly: integrity, compassion, presence, honesty. The reversed card asks something more uncomfortable: when no one is watching, are those values actually the ones organising your behaviour, or have they become decorative — language you wear rather than principles you inhabit?

There is also a particular shadow of spiritual life that this card surfaces: bypassing accountability through spiritual reframing. The deflection that turns "I behaved badly and need to make amends" into "everything happens for a reason." The avoidance that turns "I owe someone an apology" into "we were just karmically entangled." Genuine spiritual maturity requires the capacity to sit inside discomfort about your own behaviour without immediately escaping it into a cosmic frame that exonerates you. Justice reversed is asking you to stop bypassing.

The remedy is consistency between belief and action, not perfection but honest reckoning. Where you have caused harm, acknowledge it specifically. Where you have benefited from arrangements that weren't fair, examine that benefit. Where you have spoken in ways your actions don't support, narrow the gap. None of this is about self-flagellation; it is about integrity in the literal sense — being one piece, the inner and outer life corresponding. The scales return to balance when you stop trying to weight them in your own favour.`,
    reversedFaqs: [
      {
        q: 'What does Justice reversed mean in love?',
        a: `Justice reversed in love most commonly points to an imbalance in the relationship that has been allowed to persist — unequal emotional labour, one person consistently giving more than they receive, or a quiet pattern of one voice mattering more than the other in joint decisions. It can also indicate dishonesty, either a specific deception or a more general pattern of small untruths told to avoid friction. The remedy is genuinely uncomfortable honest conversation about what is and isn't fair. Both people need to be willing to examine their own behaviour, not just the other's, for repair to be real rather than performed.`,
      },
      {
        q: 'Is Justice reversed a bad sign?',
        a: `Justice reversed isn't bad so much as honest — it is asking you to look at something you have probably been avoiding. The discomfort it brings is informative rather than punitive. If there is an unfair situation in your life that needs addressing, the card is confirming that your sense of unfairness is accurate; if you are the one operating without full integrity, it is gently asking you to put that right before consequences arrive. The card rewards honest self-examination and tends to be unkind only to those who refuse it. Treated as feedback rather than verdict, it is genuinely useful.`,
      },
      {
        q: 'What does Justice reversed mean in career?',
        a: `Justice reversed in career often signals an unfair workplace situation — biased decisions, credit not given, a contract being interpreted in bad faith, or a culture where outcomes don't reflect contribution. It can also indicate legal or quasi-legal matters not progressing fairly. Practically, document everything, read agreements carefully, and don't accept terms you wouldn't defend in front of an impartial third party. If the card surfaces around your own conduct, it is asking you to make honest small corrections now before larger reckonings arrive on their own schedule. Integrity at work, once compromised, is expensive to restore.`,
      },
      {
        q: 'How do I work with Justice reversed in a reading?',
        a: `Treat Justice reversed as an invitation to look honestly at fairness, accountability, and the alignment between your words and your actions. Ask: where in this situation is the balance off, and what is my own role in that imbalance? Resist the temptation to focus only on what others have done. Where you have been wronged, the card supports your perception; where you have caused harm or operated sloppily, it supports correction. Practical steps — documenting, having honest conversations, making specific amends — matter more than abstract reflection. The card rewards integrity put into action, not merely contemplated.`,
      },
    ],
  },

  'the-hanged-man': {
    loveLong: `The Hanged Man reversed in love almost always describes a relationship caught in a holding pattern that has stopped being productive and become merely stuck. The pause that once had purpose — time to think, space to feel, a deliberate stepping back from intensity — has calcified into avoidance. Both people are still in the structure of the relationship but neither is doing the inner work the suspension was originally meant to enable. You may be circling the same conversations, deferring the same decisions, hoping the situation will somehow resolve itself without anyone having to risk anything definitive. It will not.

There is also a particular shadow this card surfaces in love: martyrdom dressed up as patience. The willingness to wait indefinitely for a partner to change, to meet you, to choose you — framed as devotion or maturity but functioning as a refusal to accept what the relationship actually is. The Hanged Man at his best is a card of voluntary, conscious sacrifice for genuine perspective. Reversed, the sacrifice tips into something less healthy: enduring rather than transforming, suffering rather than learning. If you have been waiting for someone to come around for a long time, ask honestly whether the waiting itself has become the relationship.

The way through is rarely dramatic action — that would betray the card's deeper teaching about not forcing. But it does require a willingness to be honest about what the current pause is actually doing. If you genuinely cannot see a new perspective emerging, if the time spent in stillness is producing no insight, the suspension has outlived its purpose. The choice may be to recommit to the relationship with full engagement, or to acknowledge that the pause has become a way of not deciding. Either is a real movement. Indefinite limbo is not.`,
    careerLong: `The Hanged Man reversed at work typically describes a stalled situation that everyone is treating as temporary but that has, in fact, become the new normal. The project waiting for sign-off that never quite arrives. The decision being deferred to a meeting that keeps getting rescheduled. The role you took as a stepping stone that has now lasted three years longer than intended. The pause that was meant to be strategic has become structural, and the longer it continues the harder it becomes to break the inertia. The card reversed is asking you to recognise that waiting more is unlikely to produce different results.

There is also a more inward expression: the perfectionist's pause, where you cannot move forward on a piece of work because you cannot see it clearly enough yet, but you also cannot see it clearly enough yet because you have not actually engaged with it. The Hanged Man's gift is the perspective that arrives through genuine surrender — putting down the urgency to know, allowing understanding to come at its own pace. Reversed, this becomes a refusal to act until certainty arrives, which means action is endlessly deferred. Most professional clarity is forged in motion, not in advance of it.

Practical work here often involves identifying the smallest concrete next step you can take that would generate genuine new information, and taking it. Not the dramatic pivot, not the big announcement — the modest action that breaks the cycle of suspended deliberation. If you have been on a sabbatical or career pause that was meant to clarify direction, the card is asking whether the pause is still doing its work or whether it has become a way of avoiding the harder questions about what comes next. Either way, gentle motion tends to dissolve what continued stillness only entrenches.`,
    spiritLong: `The Hanged Man reversed spiritually points to a particular form of stuckness familiar to anyone who has been on a path for some time: the practice that has lost its capacity to genuinely interrupt you. You still meditate, still attend the workshops, still keep the journal — but the surrender that the Hanged Man asks for, the genuine willingness to be turned upside-down by what you encounter, has quietly evaporated. The structures of practice remain. The transformative encounter that they were meant to support has gone elsewhere. This is one of the more disorienting passages in spiritual life because nothing visible has gone wrong, and yet something essential has dimmed.

There is also the opposite expression: a refusal to pause at all. The spiritual seeker who responds to every difficulty with more practice, more reading, more workshops, more processing — never allowing the actual silence in which insight might arrive. The Hanged Man reversed often appears for people whose spirituality has become another arena of striving, where the relentless self-improvement has crowded out the receptive, fallow state from which genuine understanding emerges. Doing more is not always the answer. Sometimes the work is to genuinely stop, even if stopping reveals an uncomfortable emptiness.

The card invites you to examine your relationship with not-knowing. Can you sit inside genuine uncertainty about the direction of your spiritual life without rushing to resolve it? Can you allow yourself to be in a pause whose purpose has not yet revealed itself? The Hanged Man's central teaching is that some insights are only available from a position of voluntary surrender, and that the surrender itself must precede the understanding it makes possible. Reversed, the card asks whether you are willing to genuinely pause, or whether you are merely waiting.`,
    reversedFaqs: [
      {
        q: 'What does The Hanged Man reversed mean in love?',
        a: `The Hanged Man reversed in love most often describes a relationship stuck in a holding pattern that has stopped being productive — neither moving forward nor ending, with both people circling the same conversations and deferring the same decisions. It can also indicate a martyrdom pattern: waiting indefinitely for a partner to change, framed as patience but functioning as a refusal to face what the relationship actually is. The way through usually involves honest acknowledgement that the pause has outlived its purpose, and a willingness to either fully recommit or accept that the suspension has quietly become a way of not deciding.`,
      },
      {
        q: 'Is The Hanged Man reversed a bad sign?',
        a: `Not bad, but genuinely uncomfortable. The Hanged Man reversed names a stuckness that you have probably been minimising — a pause that was once meaningful but has now become avoidance, or a refusal to allow the pause that a situation actually needs. It is one of the more honest cards in the deck, asking you to look squarely at where motion has stalled and why. The card is gentle rather than punitive in its tone, but it does insist on examination. People who treat it as feedback tend to find it useful; those who refuse the question it raises tend to stay where they are.`,
      },
      {
        q: 'What does The Hanged Man reversed mean in career?',
        a: `The Hanged Man reversed at work describes a stalled professional situation that everyone is treating as temporary but that has become the new normal — the deferred decision, the project waiting indefinitely for sign-off, the stepping-stone role that lasted years longer than planned. It can also indicate perfectionist paralysis: an inability to move on a piece of work because the clarity you are waiting for can actually only be forged through engagement. The remedy is usually identifying the smallest concrete action that would generate new information, and taking it. Most professional understanding is built in motion rather than ahead of it.`,
      },
      {
        q: 'How do I work with The Hanged Man reversed in a reading?',
        a: `Ask honestly whether the current pause in your life is still doing genuine work or has become a way of avoiding decision. If you can identify a fresh insight, perspective, or feeling that has emerged recently, the suspension is probably still productive. If you cannot — if the situation feels exactly as it did three months ago — the card is suggesting the pause has run its course. The way forward rarely requires dramatic action; usually it is the modest next concrete step that breaks the inertia. The card also rewards examining your relationship with not-knowing more generally.`,
      },
    ],
  },

  'death': {
    loveLong: `Death reversed in love is one of the more poignant cards to receive because it almost always describes a relationship that has, in some essential way, already ended — but where neither person has been able to formally acknowledge the ending. You still live together, still call each other, still observe the rituals of being a couple, but the living heart of the connection has quietly departed. There is no acute crisis to point to; the affection hasn't curdled into hatred; there is just an absence where presence used to be. The card asks whether you are still in a relationship or in the shape of one that no longer holds anything alive.

There is also the inverse pattern: clinging to a partnership that has ended in fact but not in feeling. The breakup happened months or years ago, but you are still inhabiting it — still telling the story, still measuring new connections against it, still rearranging the past in your mind looking for the moment things might have gone differently. Grief that doesn't move becomes a kind of dwelling, and the dwelling slowly forecloses on the future you might otherwise have. Death reversed is not asking you to suppress the grief but to actually let it carry you somewhere, rather than freezing the loss in place.

The work either way is honesty about what has actually happened. Not what you wish were true, not what would be easier to maintain, but what is genuinely alive between you and another person. Sometimes that honesty leads to a clean, sad ending that frees both people to live more fully. Sometimes it leads to a real reckoning that allows a relationship to genuinely transform rather than simply continue in name. The card refuses the third option of pretending. If something has ended, give it the dignity of being ended. The chapter that follows needs the cleared space.`,
    careerLong: `Death reversed in career describes the role, company, or career path that ended for you internally some time ago but that you are still going through the motions of inhabiting. You know, often quite precisely, the date when the work stopped genuinely engaging you. You know which conversation broke the spell. You know what you would do instead if you let yourself consider it seriously. And yet you continue, because the financial logic seems to hold, because the alternative is unclear, because endings are frightening when you cannot yet see what comes next. The card is asking you to recognise that staying is no longer neutral — it is actively costing you something.

This is rarely a card that demands immediate, dramatic exit. Reckless quitting is its own form of avoidance. What Death reversed does ask is honest acknowledgement: that this chapter is complete, that the genuine learning you needed from it has been received, that the part of you that is alive and growing is no longer being fed by this work. From that acknowledgement, planning can begin — financial preparation, skill development, conversations with people in fields that interest you. The exit, when it comes, will be better-considered than a sudden break, but it does need to come.

There is also an organisational expression of this card: a company or industry refusing to acknowledge that a particular model, product, or way of working has ended. Doubling down on what isn't working, redoubling effort on the strategy that has clearly run its course. If you are in that environment, the card is partly asking whether your future is bound to theirs. Sometimes the most loyal thing is to leave a sinking organisation rather than help it ignore the water. Either way, Death reversed in career is the gentle insistence that pretending an ending isn't an ending only postpones — and worsens — the eventual transition.`,
    spiritLong: `Death reversed spiritually points to a version of yourself you have outgrown but cannot quite stop being. Most people on a serious inner path notice, at certain junctures, that an identity they have inhabited — the wounded one, the seeker, the recovering person, the spiritually advanced person, the responsible elder, whatever — has become a costume rather than a current truth. The growth has happened. The role hasn't been updated to match. Death reversed is the recognition that you are still playing a part whose script you no longer believe.

This kind of holding-on is rarely conscious. The identity that has run its course often feels integral to who you are, because it has been integral for so long. Letting it go feels like a small death — which is precisely what the card is naming. The grief is real. The previous version of you served you well for the season in which it was needed. Honour it. But also: notice when honouring slips into preserving. There is a difference between gratitude for what an identity gave you and continued residence in an identity that no longer fits.

The invitation is to consent to the next, less defined version of yourself — the one that doesn't yet have a clear story, that hasn't yet figured out how it explains itself, that is currently more space than shape. Spiritual maturation involves repeated small deaths of this kind, and the willingness to inhabit the unformed period between identities is a significant capacity to develop. Death reversed is not asking you to manufacture transformation. It is asking you to stop resisting the one that is already underway.`,
    reversedFaqs: [
      {
        q: 'What does Death reversed mean in love?',
        a: `Death reversed in love typically describes a relationship that has effectively ended without anyone formally acknowledging it — the structure of partnership continues but the living connection has quietly departed. It can also indicate the inverse: a relationship genuinely over in fact, but still inhabited emotionally, where the grief has frozen into dwelling rather than passing through. Either way, the card asks for honest acknowledgement of what has actually happened between you. Sometimes this leads to a clean ending that frees both people; sometimes it allows a real transformation rather than a quiet hollowing out. What it refuses is continued pretending.`,
      },
      {
        q: 'Is Death reversed a bad sign?',
        a: `Death reversed is sober rather than bad — it is naming an ending you have probably been minimising, and asking you to engage with it honestly. The discomfort is real, but the alternative is worse: continued residence in a chapter that has already closed slowly drains energy from the parts of your life that are still alive. People who let the card do its work usually find that the eventual transition, once they consent to it, is less devastating than they feared and considerably more freeing than continued avoidance would have been. The card is harsh only to those who refuse what it is gently insisting upon.`,
      },
      {
        q: 'What does Death reversed mean in career?',
        a: `Death reversed in career describes the role or path that ended for you internally some time ago, but where you are still going through the motions of inhabiting it. The work no longer engages you, the learning has been received, and yet you continue out of financial logic, fear, or the lack of a clearer alternative. The card rarely demands immediate exit, but it does ask for honest acknowledgement that staying has stopped being neutral. From that recognition, real planning can begin — preparation, skill-building, exploration of what is calling next. The eventual exit, properly considered, will be better than a sudden break.`,
      },
      {
        q: 'How do I work with Death reversed in a reading?',
        a: `Ask yourself what you are continuing to inhabit that has, in some essential way, already ended — a relationship, a role, an identity, a belief, a story about yourself. Resist the urge to defend the continuation. The card rewards honesty rather than reasoning. Once the ending is acknowledged, the next steps are usually clearer than they seemed: grieve what genuinely needs grieving, complete what can be completed, prepare for what comes next. The card does not demand dramatic action; it asks for honest acceptance. That acceptance, once given, tends to dissolve a great deal of accumulated weight.`,
      },
    ],
  },

  'temperance': {
    loveLong: `Temperance reversed in love describes a relationship in which the patient, integrative work that healthy partnership requires has broken down — usually in favour of extremes. One person is over-investing while the other holds back. Closeness and distance are no longer in any natural rhythm; instead, the relationship swings between suffocating proximity and chilly retreat. Or the partnership is being forced to a particular shape — a specific commitment, a particular timeline, a fixed picture of what it should be — at the cost of the slow, attentive process by which two people actually come to know each other. The card asks where the gentle blending has been replaced by pressure.

There is also a more individual reading: your own approach to the relationship has fallen out of balance. Perhaps you are putting too much in too quickly, before genuine trust has had time to form, in hope of accelerating closeness. Perhaps you are holding so much back, trying so hard not to be the one who cares more, that you have become emotionally unavailable to a partner who actually wants to meet you. Both are versions of the same underlying issue: an inability to inhabit the patient middle in which real intimacy actually develops. The relationship cannot find its rhythm because one of you isn't allowing one.

The work is restoration of flow, which usually means doing less rather than more. Stop trying to manage the relationship into a particular shape. Let interactions breathe at their own pace. Notice when you are reaching for intensity to avoid the discomfort of slower, less dramatic connection — and resist that reach. Temperance reversed in love is not the end of the relationship; it is a signal that the rhythm has been disrupted and that conscious patience can usually restore it. The middle path, in love, is far more interesting than its reputation suggests.`,
    careerLong: `Temperance reversed in career most often appears around unsustainable working patterns — chronic overwork that has stopped being a phase and become a way of life, or the opposite, a chronic disengagement that has hollowed out any sense of meaningful contribution. The card is rarely about one bad day. It is about a structural imbalance that has been allowed to settle in, where rest is genuinely impossible and recovery is theoretical, or where the work has so little weight that it provides no real engagement. Either extreme erodes the quiet alchemy by which good work actually develops.

There is also a project-level expression: an attempt to force a particular outcome on a timeline the situation cannot honour. The synthesis you are trying to manufacture isn't ready. The collaboration you are pushing requires more time for trust to settle. The product you are about to launch needs another iteration that you are reluctant to give it. Temperance reversed often appears when ambition or anxiety is overruling genuine readiness, and the cost is showing up in quality. The medicine is patience, but patience held with discipline — not drift, but a willingness to let something take the time it actually needs.

Practically, the card asks where you are running on fumes, where the rhythm of work and rest has broken down, and where you are forcing what would benefit from slower attention. If burnout is operating, treat it as the genuine condition it is rather than a productivity problem to be solved by trying harder. If a project is being pushed faster than the work allows, examine what fear is driving that push. Temperance reversed at work rewards honest assessment of pace and proportion. The slow, steady, sustainable approach is almost always available; you have to choose it rather than wait for it to feel possible.`,
    spiritLong: `Temperance reversed spiritually describes a practice that has tipped out of its sustaining balance — usually in one of two directions. Either too much intensity (the relentless schedule of retreats, fasts, austerities, and disciplines that has crowded out the ordinary nourishment a body and mind actually need), or too much laxity (the practice that has dissolved into vague intention and occasional reading, no longer providing any real container). Both extremes feel virtuous in their own way to the people in them, which is part of why the imbalance persists. The card invites you to notice what your practice is actually doing to you, not what it is supposed to be doing.

There is also the imbalance between transcendence and embodiment that this card surfaces. Spiritual life that has become too cerebral, too disconnected from the body, too focused on states of consciousness divorced from the texture of ordinary days. Or, conversely, a wellness practice that has substituted physical attention for the inner work that genuine integration requires. The angel of Temperance stands with one foot on land and one in water — the spiritual and the earthly equally held. Reversed, one foot has lifted, and the integration is suffering.

Restoration is rarely dramatic. It usually involves quiet, honest adjustment: more rest into a schedule that has become punishing, more discipline into a drift that has become formless, more time outdoors if you have become a person who lives in your head, more contemplative quiet if you have become a person who fixes everything through movement. Temperance's deeper teaching is that genuine spiritual life is steady rather than spectacular. Reversed, the card calls you back to that steadiness — gently, without drama, but firmly.`,
    reversedFaqs: [
      {
        q: 'What does Temperance reversed mean in love?',
        a: `Temperance reversed in love describes a relationship that has fallen out of its natural rhythm — usually because one or both people are operating in extremes. Closeness and distance no longer move in any sustainable cycle, or the partnership is being forced into a particular shape on a timeline it cannot honour. It can also describe an individual approach that has fallen out of balance — over-investing too quickly, or holding back so much that genuine availability has become impossible. The work is restoration of flow, usually through doing less rather than more. The patient middle is where real intimacy actually develops.`,
      },
      {
        q: 'Is Temperance reversed a bad sign?',
        a: `Temperance reversed is not bad so much as informative — it is naming an imbalance that has probably been operating for a while and is now generating real cost. The card is one of the gentler reversals in the Major Arcana; it rarely points to dramatic crisis, more often to a quiet erosion of sustainability that, if addressed, can be readily restored. People who treat it as a signal to examine their pace, their proportions, and their excesses usually find genuine relief. People who push through it tend to encounter the more painful versions of the same lesson later. Listen now and the correction is small.`,
      },
      {
        q: 'What does Temperance reversed mean in career?',
        a: `Temperance reversed at work most often points to unsustainable patterns — chronic overwork that has become structural rather than situational, or chronic disengagement that has hollowed out any real contribution. It can also surface around projects being forced to a timeline they cannot honour, or collaborations being pushed before trust has had time to settle. The remedy is patience held with discipline rather than drift. Address burnout as the genuine condition it is rather than a productivity problem. Let work that needs time take the time it actually needs. The slow, steady, sustainable approach is almost always available if you choose it.`,
      },
      {
        q: 'How do I work with Temperance reversed in a reading?',
        a: `Ask honestly where you are operating in extremes — overdoing or underdoing, rushing or stalling, all heat or all distance. The card almost always points to a specific imbalance rather than a general malaise. Once you have identified the extreme, the medicine is usually a quiet, undramatic move toward the middle: a little more rest, a little more discipline, a little more honesty about what pace the situation actually allows. Temperance rewards patient adjustment rather than dramatic correction. The integration it asks for is real but quiet, and it tends to restore far more than it costs.`,
      },
    ],
  },

  'the-devil': {
    loveLong: `The Devil reversed in love is one of the more hopeful reversals in the deck, but it is hope of a particular kind: the hope that arrives when you have finally seen clearly what has been holding you in a pattern that wasn't serving you. The chains the upright card depicts are loose; the reversed card often catches you in the moment of noticing this. The compulsive draw to someone who isn't good for you, the relationship you have stayed in for reasons that don't actually serve either of you, the dynamic that runs on fear or familiarity rather than genuine choice — these are becoming visible as patterns rather than identities. That visibility is itself the beginning of freedom.

The card does not, however, glamorise leaving. Recognition is not yet release, and release is rarely clean. The Devil reversed in love often describes someone in the early, disorienting stages of disentanglement — where you can see the pattern clearly but cannot yet inhabit the freedom that seeing it implies. There may be relapses, returns, moments of wondering whether you were imagining the unhealth. This is normal. Long-standing patterns rarely dissolve on a single insight; they require steady, often unglamorous practice of new choices, supported by people who can witness the work honestly.

Treat the card with care. If you are leaving an unhealthy attachment, give yourself credit for the readiness to leave — that readiness is genuine and significant. But also give yourself patience with the unevenness of actually leaving. If you are still inside the pattern and the card has surfaced as recognition, the work is to allow the seeing without rushing to either dismiss it or act on it impulsively. Real change in this territory tends to be slower and more honest than dramatic gestures, and it is almost always supported by genuine outside help — therapy, recovery work, trusted friends who can hold the truth when you start to talk yourself out of it.`,
    careerLong: `The Devil reversed in career most often signals the beginning of release from work arrangements that have been quietly compulsive rather than genuinely chosen. The job kept for the salary that long ago stopped being worth the cost. The role retained for the title that no longer means what it once did. The industry stayed in because leaving feels too disorienting, even though staying has stopped feeling like a real choice. The reversed card catches you in the moment of recognising that what felt like commitment was actually inertia dressed up in professional language.

There is also a recovery from workplace dynamics that operate on fear: bosses who manage through anxiety, cultures that bind people through shame about not being productive enough, environments where the implicit message is that you should be grateful to be there regardless of what is being asked of you. Seeing these dynamics clearly is the first step out of them. Acting on what you see takes longer and usually requires practical preparation — savings, contacts, skills, a sense of what genuinely interests you beyond what has been demanded.

The card asks you to begin moving, even if the move is internal. Stop performing enthusiasm for work that no longer enthuses you. Stop accepting terms you wouldn't have accepted from a clearer position. Stop disguising compulsion as commitment. The Devil reversed at work is gentle in that it doesn't demand sudden exit; it asks for honest reorientation, the slow accumulation of choices that align with what you actually want rather than what fear has been deciding for you. Liberation in professional life rarely arrives in a single dramatic moment. It is built through steady, increasingly honest choices about what you are willing to participate in and what you are not.`,
    spiritLong: `The Devil reversed spiritually points to the beginning of genuine shadow work — the willingness to make conscious what has been operating in the dark. Most people resist this work strenuously, even after they have learned its language, because what becomes visible is rarely flattering. The defensive patterns that have protected you also limited you. The compulsions you didn't quite acknowledge owned more of your behaviour than you would like to know. The narratives you ran were not the noble ones you preferred to tell. Reversed Devil is naming the moment when these begin to become undeniable.

The card is hopeful precisely because what is now visible can finally be worked with. Patterns that operate unconsciously cannot be addressed; patterns that have come into the light can be questioned, grieved, and gradually replaced. But the work is real, and it is rarely glamorous. It often involves sitting with quite uncomfortable truths about your own behaviour, your own complicity in situations you preferred to see yourself as a victim of, your own use of spiritual language to avoid rather than confront. Shadow work is not the recreational version of inner exploration that workshops sometimes suggest. It is genuine reckoning.

Support helps enormously. Therapy, properly held inner work, recovery communities for those for whom that applies, friends who can hear truth without flinching — these are the structures within which the Devil reversed actually delivers what it promises. Done alone, the work tends to stall or distort into self-flagellation. Done in relationship, it becomes the steady, often unspectacular practice of becoming a more honest person. The card invites you not into transformation as event, but into the longer, more durable transformation that honest contact with your own shadow makes possible.`,
    reversedFaqs: [
      {
        q: 'What does The Devil reversed mean in love?',
        a: `The Devil reversed in love often signals the beginning of release from an unhealthy pattern — a relationship that has been running on compulsion, fear, or familiarity rather than genuine choice. The chains are becoming visible, which is the first step toward removing them. The card is hopeful but realistic: recognition is not yet release, and long-standing patterns rarely dissolve on a single insight. There may be relapses or returns. The work tends to be steady rather than dramatic, and it is almost always supported by genuine outside help — therapy, trusted friends, recovery work — rather than performed alone.`,
      },
      {
        q: 'Is The Devil reversed a bad sign?',
        a: `The Devil reversed is one of the more hopeful reversals — it usually signals the early stages of becoming free from a pattern that has been quietly costly. The discomfort it brings is the discomfort of honest recognition, which is the precondition of real change. It is not pleasant in the moment, but it tends to be far better than continued residence in the pattern it is naming. The card rewards engagement with what is becoming visible; it tends to be unkind only to those who refuse what they are starting to see. Treated as an invitation to honest work, it is genuinely useful.`,
      },
      {
        q: 'What does The Devil reversed mean in career?',
        a: `The Devil reversed in career typically signals the beginning of release from work arrangements that have been quietly compulsive — kept for reasons that no longer hold, in environments that operate on fear, anxiety, or shame about not being productive enough. The card asks you to start moving, even if the movement is internal: stop performing enthusiasm you don't feel, stop accepting terms from inertia, stop disguising compulsion as commitment. Practical preparation usually follows recognition. Liberation at work rarely arrives in a single moment; it is built through steady, increasingly honest choices about what you are willing to participate in.`,
      },
      {
        q: 'How do I work with The Devil reversed in a reading?',
        a: `Treat it as an invitation to make conscious what has been operating beneath your awareness — the compulsions, fears, and patterns that have quietly run more of your life than you have wanted to admit. Seek genuine support: therapy, recovery work, trusted people who can hear hard truth without flinching. Resist the temptation to either dramatise what you are seeing or rush to act on it impulsively. Real change in this territory is steady, often slow, and far more durable than dramatic gestures. The card rewards honest, supported engagement with the shadow far more than it rewards heroic solo reckoning.`,
      },
    ],
  },

  'the-tower': {
    loveLong: `The Tower reversed in love is one of the more delicate cards to interpret honestly, because the difficulty it names doesn't go away just because the imagery is inverted. Reversed, the card most often describes a slow-burn revelation rather than a sudden one — a truth about the relationship that has been gradually surfacing through small cracks, near-conversations, and the accumulating sense that something is not quite right. The collapse is happening, but it is happening over months rather than minutes. This is not easier than the upright version; in some ways it is harder, because the dread is sustained and the resolution keeps not arriving.

There is also the situation where the Tower moment has already occurred and what the reversed card describes is the aftermath: the revelation has been spoken, the disruption has happened, and now both people are inside the dust. The work here is not avoidance of difficulty but honest engagement with what has been revealed. Trying to put the tower back together as it was is usually impossible; the foundations that failed will fail again. What can sometimes be done is honest examination of what was actually being built between you, and a clearer choice about whether to rebuild on different ground or to honour the ending.

The card asks for unusual honesty about the structure of the relationship — not the surface but the load-bearing assumptions underneath. What have you been pretending was solid that isn't? What has been working only because no one was looking at it carefully? The Tower reversed in love is not asking you to manufacture crisis; it is asking you to stop manufacturing the appearance of stability over genuine instability. Either the relationship can survive that honesty or it cannot, but the honesty is required either way. Continued maintenance of a structure that is genuinely failing costs more than the eventual reckoning would.`,
    careerLong: `The Tower reversed in career often describes a workplace, role, or industry in real structural trouble that is being held together by increasingly desperate maintenance. Layoffs that everyone can feel coming but no one is officially preparing for. A business model that has stopped working but is being defended with renewed marketing budget. A career trajectory that has lost its viability but that you are reluctant to acknowledge has shifted. The collapse is not imminent in the sense of tomorrow, but it is no longer avoidable in the longer arc. The card is asking you to start preparing for what you can feel coming.

There is also the more inward expression: a private professional reckoning that has been unfolding without anyone else seeing it. The growing knowledge that the work isn't right, that the role doesn't fit, that the path you have been on is no longer the path you want to walk — and yet no external event has forced the issue. The Tower reversed in this form is the internal shattering that hasn't yet translated into visible action. The reckoning is real even though it is private. Honouring it usually means starting to make small, concrete preparations for the change you can feel forming, before the situation forces a less considered version of the same transition.

Practically, the card rewards quiet, steady preparation rather than dramatic announcement. Update your skills. Save more aggressively. Rebuild contacts you have let lapse. Identify the work or environment that might actually fit you better. None of this requires premature decision; all of it positions you better when the eventual transition becomes unavoidable. The Tower reversed at work is the gentle insistence that you stop pretending stability where the foundations have already begun to give way. The kindness in it is that the warning has arrived early enough to be useful.`,
    spiritLong: `The Tower reversed spiritually describes the slow erosion of a worldview, belief system, or spiritual framework that has held you for some time but is no longer holding. The clean break of a sudden Tower experience has its own difficulty, but its reversed version has another: the gradual loss of faith in something you cannot quite stop participating in, the dawning recognition that a teacher or tradition or community has been less than what you believed, the quiet dimming of conviction in beliefs you cannot yet replace with anything more honest. This is one of the more disorienting passages in spiritual life because there is no single moment of collapse to mourn — just the slow draining of belief from structures that look outwardly the same.

The work is allowing the collapse to be what it is. The temptation, when a worldview begins to fail, is either to redouble belief through force (trying harder to believe what you used to believe naturally) or to flip into cynical rejection of everything the previous framework contained. Both are forms of avoiding the actual reckoning. The Tower reversed asks for something harder: sitting honestly inside the loss of a structure without manufacturing a replacement before genuine clarity has had time to form. The cleared ground is uncomfortable. Stay there long enough and something more honest tends to emerge.

There is also the recognition that what is collapsing was never quite what you thought it was. Beliefs you held because the people around you held them. Practices you maintained because their absence felt unsafe. Identifications with a tradition that were partly social belonging rather than genuine alignment. The Tower's gift, even in reverse, is the clearing of these less-than-honest structures so that what remains can be inhabited with more integrity. The faith that survives a Tower experience is almost always sturdier than the faith that hadn't yet been tested. Trust the process even while it is uncomfortable.`,
    reversedFaqs: [
      {
        q: 'What does The Tower reversed mean in love?',
        a: `The Tower reversed in love most often describes a slow-burn revelation rather than a sudden one — a truth about the relationship surfacing gradually through small cracks and accumulating disquiet, where the dread is sustained and resolution keeps not arriving. It can also describe the aftermath of a Tower moment that has already occurred, where both people are working through what has been revealed. The card is not easier than the upright version; in some ways it is harder. The work is honest examination of what the relationship was actually built on, and a clearer choice about whether to rebuild on different ground or honour the ending.`,
      },
      {
        q: 'Is The Tower reversed a bad sign?',
        a: `The Tower reversed remains a difficult card. It does not transform crisis into ease; it changes the timing and quality of the disruption from sudden to slow. The honesty it asks for is real, and the situations it describes are usually genuinely uncomfortable. That said, the card is rarely catastrophic in the sense of unsurvivable. What it asks you to face is what was going to need facing anyway; the gentleness is that the warning has arrived before the situation has forced your hand. Treated as preparation rather than verdict, it tends to be more useful than its reputation suggests.`,
      },
      {
        q: 'What does The Tower reversed mean in career?',
        a: `The Tower reversed in career often describes a workplace, role, or industry in real structural trouble being held together by increasingly desperate maintenance — layoffs everyone can feel coming, a business model that has stopped working but is being defended, a career trajectory that has lost its viability. It can also describe a private professional reckoning that has not yet become visible to others. The card rewards quiet, steady preparation rather than dramatic announcement: update skills, save, rebuild contacts, identify what might fit better. The kindness in the card is that the warning has arrived early enough to be useful.`,
      },
      {
        q: 'How do I work with The Tower reversed in a reading?',
        a: `Take the warning seriously without rushing to dramatic action. The card is telling you that something is genuinely unstable in the situation it describes, and that the eventual reckoning is not avoidable. Examine the load-bearing assumptions: what have you been pretending was solid that isn't? Then begin steady, undramatic preparation for the change you can feel forming. Resist the temptation to manufacture crisis to get the painful part over with, and equally resist the temptation to pretend the warning isn't there. The Tower reversed rewards honest, prepared engagement with difficulty rather than either dramatising or denying it.`,
      },
    ],
  },

  'the-star': {
    loveLong: `The Star reversed in love describes the particular tiredness that comes when hope itself has started to feel like a betrayer. You have hoped before and been disappointed; the relationships you trusted didn't hold; the connection you believed in turned out to be less than you had been told. And now, faced with a new possibility or a current relationship that asks something of you, the part of you that knows how to hope is reluctant to step forward again. The card is not asking you to perform optimism. It is naming the genuine weariness that long disappointment leaves behind, and inviting honest attention to what that weariness has cost you.

There is also a particular pattern this card surfaces in established partnerships: the slow dimming of inspiration that can happen when two people have been together long enough for their relationship to become more habit than discovery. The light that drew you to each other hasn't been extinguished, but it has been allowed to fade through inattention. Neither of you is doing the things — the small attentions, the genuine curiosity about each other, the moments of being properly seen — that kept the original spark alive. The card asks whether the dimming is actually a sign that the love is over, or whether it is a sign that the love has been neglected.

The work is honest and gentle. If you are guarding against hope, the medicine is not forced positivity but a real reckoning with the previous hurts that produced the guarding, often supported by therapy or genuine inner work. If a current relationship has dimmed, the medicine is the steady practice of small, real attentions, with the recognition that what once happened spontaneously now requires choice. The Star at her best is the hope that comes after honest difficulty rather than instead of it. Reversed, she is asking you to do the difficulty honestly so that the hope, when it returns, can be the real version rather than the rehearsed one.`,
    careerLong: `The Star reversed in career describes professional disillusionment that has settled in — usually because the inspiration that originally drew you to this work has been worn down by the daily texture of the role, the politics of the environment, or the slow recognition that the vision you held doesn't quite match the reality of doing the job. This is not the same as not wanting to work. It is the particular dimming of meaning that happens when work that once felt purposeful has become merely a series of tasks, and the part of you that was nourished by the meaning is going hungry.

There is also the more acute expression: burnout that has crossed from depleted but recoverable into something more entrenched. The card reversed often appears when someone has been running on professional fumes for long enough that the reserves they used to rely on are no longer available. Pushing harder is not the answer here; pushing harder is part of what produced the depletion. The work is honest assessment of what you have been sustaining and at what cost, and a genuine reduction in load while you investigate what would actually nourish you again.

Practically, the card invites you to remember why you chose this work or this field in the first place — not as nostalgia but as diagnostic. The original signal that pointed you here is usually still discoverable if you give it real attention. Sometimes the recovery involves returning to the part of the work that originally drew you. Sometimes it involves recognising that what called you no longer lives where you are working, and that finding it again will require a meaningful change. Either way, The Star reversed at work asks you to take the dimming seriously rather than dismissing it as cynicism or pushing through it as discipline. The light is the information.`,
    spiritLong: `The Star reversed spiritually points to what contemplative traditions have long called the dark night of the soul — the period in which the sustaining sense of connection to something meaningful has become inaccessible. This is one of the most significant and least comfortable experiences in genuine spiritual life. The practices that previously nourished you no longer seem to. The guiding sense of direction has gone quiet. The faith that you didn't have to think about because it was just there has somehow become absent. The temptation is to treat this as failure or as evidence that the path was never real.

The card invites a different relationship with the experience. Spiritual maturation, in nearly every tradition that takes the inner life seriously, includes passages in which the previous arrangement of belief and experience has to dissolve so that something more honest can develop. The discomfort is real, but it is not pathological. Forcing yourself back into the old shape — performing belief, performing devotion, performing the spiritual identity that used to fit — only delays the genuine reorganisation that is trying to happen. The Star reversed asks you to consent to the dark instead of pretending it isn't there.

The way through is usually slower than seekers want it to be. Small honesties about what no longer feels true. Small attentions to what still does, even if what remains is much less than the previous certainty. Permission to grieve the loss of the easier faith. Trust, very gradually, in what is being built underneath the visible structure even though you cannot yet see its shape. The hope that emerges on the other side of this passage is usually more grounded than the hope that hadn't yet been tested. Stay in the dark long enough for the actual stars to become visible. They are quieter than the daylight version of faith, but they are also more honest.`,
    reversedFaqs: [
      {
        q: 'What does The Star reversed mean in love?',
        a: `The Star reversed in love describes the particular weariness that comes when hope itself has started to feel like a betrayer — the guardedness that follows from previous disappointment, or the slow dimming of inspiration in an established relationship that has slipped from discovery into habit. The card does not ask you to perform optimism. It asks you to honestly engage with what the weariness has cost you and what might actually be needed: real reckoning with previous hurts if you are guarding against hope, or the steady practice of small real attentions if a current relationship has dimmed through inattention rather than ended.`,
      },
      {
        q: 'Is The Star reversed a bad sign?',
        a: `The Star reversed is melancholy rather than catastrophic — it names a real difficulty with hope, meaning, or inspiration, but it does so in a way that is more diagnostic than predictive. The card rarely says "all is lost"; it more often says "something important has dimmed and needs honest attention." Treated as an invitation to look at what has actually depleted your reserves of hope or meaning, the card is genuinely useful. The hope it ultimately promises tends to be sturdier than the easier version it has temporarily replaced, but reaching that sturdier hope requires moving through the dark rather than around it.`,
      },
      {
        q: 'What does The Star reversed mean in career?',
        a: `The Star reversed in career describes professional disillusionment — the slow dimming of meaning in work that once felt purposeful, or burnout that has crossed from depleted-but-recoverable into something more entrenched. Pushing harder is not the answer; pushing is part of what produced the depletion. The card invites honest assessment of what you have been sustaining and at what cost, and genuine reduction in load while you investigate what would actually nourish you again. Sometimes recovery means returning to the original part of the work that drew you; sometimes it means recognising that what called you no longer lives where you are working.`,
      },
      {
        q: 'How do I work with The Star reversed in a reading?',
        a: `Take the dimming seriously rather than dismissing it as cynicism or pushing through it as discipline. The loss of hope, meaning, or inspiration is real information, not weakness. Ask what has depleted you and whether the depletion is recent or long-standing. Resist forced positivity; the medicine here is not optimism but honest reckoning with what has worn you down, often supported by therapy, rest, or genuine reduction of demands. The hope that returns after this kind of honest passage is usually more durable than the hope that hadn't yet been tested. Stay in the dark long enough for the actual stars to become visible.`,
      },
    ],
  },

  'the-moon': {
    loveLong: `The Moon reversed in love describes the moment when illusion begins to clear — for better or worse. The fog you have been operating in around a relationship is starting to lift, and what is becoming visible may be a relief (the fears you were carrying turn out to have been unfounded) or it may be unsettling (something you had hoped wasn't true is becoming undeniable). Either way, the card is asking you to honour the clarity rather than retreat into the more comfortable confusion it is replacing. Confusion has its own comforts; clear seeing rarely does. But clear seeing is what allows real choice.

There is also the particular pattern this card surfaces around projection. The Moon reversed often appears when you have been seeing a partner through the lens of old wounds — projecting onto them the fears, expectations, or templates carried from earlier relationships or formative experiences — and the projection is becoming visible as a projection. This is uncomfortable. It usually means recognising that some of the difficulty you have attributed to a partner has actually been your own pattern operating, and some of the idealisation you have offered has been a fantasy that the actual person could never sustain. Both recognitions ask you to encounter the partner more accurately.

The work is patient and honest. As the fog clears, resist the temptation to act immediately on the new clarity; what you are seeing now may itself be partial, and reactive decisions made at the moment of recognition tend not to age well. Let the seeing settle. Have the honest conversations that the new clarity makes possible. Notice whether what is being revealed is actually about your partner or about your own inner landscape. The Moon's deeper teaching is that what is visible in clear light is rarely what looked solid in moonlight. Take the time the situation needs to absorb that difference.`,
    careerLong: `The Moon reversed in career describes the lifting of confusion in a professional situation that has been operating in a kind of fog — workplace politics that are becoming legible, a colleague's actual motivations becoming visible, a project whose real shape is emerging from beneath the official narrative. This clarity is genuinely useful, but it asks something of you: a willingness to act on what you are now able to see rather than continuing to operate as if you still didn't know. Wilful obliviousness, once the clarity has arrived, is its own form of cost.

There is also the more inward expression: the easing of anxiety-driven thinking that had been distorting your assessment of a situation. The Moon at its most distorting often makes things look more threatening, more complicated, or more hopeless than they actually are; reversed, you may be returning to a more accurate read on what you are facing. Decisions that felt impossibly fraught begin to look more proportionate. Relationships you had decided were doomed begin to seem more recoverable. Possibilities you had dismissed return to view. The card invites you to trust the clearer perception even though you are not yet entirely sure what it shows.

Practically, this is often a useful moment for revisiting decisions you had postponed because the fog was too thick to navigate. Contracts you couldn't read clearly. Conversations you couldn't have because too much was uncertain. Choices you couldn't commit to. As the lunar distortion fades, the practical landscape returns to manageable proportions. Honour the clarity by acting on it carefully but decisively. The Moon reversed in career also cautions: don't assume you have the whole picture yet. Clarity is arriving, but its arrival is gradual, and overshooting into false certainty would only replace one distortion with another.`,
    spiritLong: `The Moon reversed spiritually points to the integration of unconscious material that the upright Moon initially surfaced. The dreams that were disturbing, the symbols that were confusing, the inner figures that arrived in meditation without explanation — these are beginning to be worked with consciously rather than merely experienced as disorientation. This is genuine progress, even though it doesn't feel particularly enlightened. Shadow integration is a long, gradual process; the reversal usually catches you in the middle of it, where the material is no longer overwhelming but is not yet resolved.

There is also the recognition that some of what felt like genuine spiritual experience was projection — the teacher you idealised who turned out to be ordinary, the path you thought was uniquely yours that turned out to be widely walked, the mystical communication you experienced that began to look more like internal material seeking voice. This kind of demystification is uncomfortable but valuable. It returns spiritual experience to a more honest scale, where what is real can be held alongside what was inflated, and the eventual relationship with the path becomes sturdier for the calibration.

The card asks you to keep doing the actual work without expecting that clarity will arrive all at once. Dreams continue to be worth attending to; intuitions continue to be worth honouring; the inner life continues to be a real territory worth taking seriously. But the reversed Moon also asks for the discernment that distinguishes genuine inner communication from anxiety, projection, or wishful thinking. Both honour and scrutiny. The lunar light, when properly integrated, becomes a quieter and more reliable companion than it was during its more dramatic phases. Trust that quieter signal as it develops.`,
    reversedFaqs: [
      {
        q: 'What does The Moon reversed mean in love?',
        a: `The Moon reversed in love describes a clearing of confusion or illusion — either reassuringly (fears turn out to be unfounded) or revealingly (something you had hoped wasn't true becomes undeniable). It often surfaces when you have been seeing a partner through the lens of old wounds or projections, and the projection itself is becoming visible. The work is honouring the clarity rather than retreating into the more comfortable fog, while also resisting the temptation to act immediately on new perceptions that may themselves be partial. Let the seeing settle. The honest conversations that become possible after clarity tends to age better than reactive ones.`,
      },
      {
        q: 'Is The Moon reversed a bad sign?',
        a: `The Moon reversed is more often relieving than alarming — it usually describes the lifting of confusion or distortion rather than the arrival of fresh trouble. The clarity it brings may be uncomfortable in cases where what becomes visible is something you would rather not have seen, but the discomfort of accurate perception is almost always preferable to the costs of continued fog. The card rewards honest engagement with what is becoming clear, even when the clarity is unwelcome. It tends to be a card of growing accuracy rather than worsening conditions.`,
      },
      {
        q: 'What does The Moon reversed mean in career?',
        a: `The Moon reversed in career describes the lifting of confusion in a professional situation that has been operating in fog — workplace politics becoming legible, real motivations becoming visible, a project's actual shape emerging from beneath the official narrative. It can also indicate the easing of anxiety-driven thinking that had been making situations look more threatening than they actually were. The card invites you to act on the new clarity carefully but decisively, while cautioning against overshooting into false certainty. Clarity is arriving but is gradual; honour it without assuming you yet have the whole picture.`,
      },
      {
        q: 'How do I work with The Moon reversed in a reading?',
        a: `Notice what has been confusing you and ask whether the confusion is genuinely beginning to clear. If it is, give the new perception time to settle before acting on it. Examine what role projection has been playing in the situation — what you have been seeing through the lens of old wounds, old expectations, or anxiety rather than through current accurate sight. The card rewards honest, gradual recalibration rather than dramatic reaction to fresh clarity. Dreams, intuitions, and gut feelings remain useful; the work is in distinguishing genuine inner signal from the noise of projection or fear.`,
      },
    ],
  },

  'the-sun': {
    loveLong: `The Sun reversed in love rarely indicates that love itself has gone; more often it describes something quietly dimming the light that is actually present. Insecurity that won't let you trust what is being offered. A persistent habit of finding the problem in a connection that is mostly working. A relationship that looks sunny to outside observers but has a more complex interior reality that neither person is quite acknowledging. The card asks what is obscuring the genuine warmth, both within you and between you, and whether the obscuration is being maintained more than the warmth is being protected.

There is also the particular shadow of performed happiness this card surfaces. The relationship that looks bright because both people are working hard to make it look bright, while the actual texture between them has become flatter and more managed than the public story admits. This isn't necessarily a failed relationship; it may simply be a connection that has prioritised appearance over honesty for longer than is sustainable. The card asks whether the joy is genuinely available between you or whether it is being performed for outside witnesses, including yourselves.

The work is finding and protecting the real warmth rather than producing more of the performed kind. Where in the relationship is there actual delight, actual ease, actual recognition? What conditions allow that warmth to come forward? What habits, conversations, or pressures dim it? Small, honest attention to the genuine light is far more restorative than redoubled effort to brighten what has been managed too long. The Sun's deeper teaching is that real joy in love is undefended; the work of reversed Sun in love is finding where defences have crept in and gently releasing them, in service of the warmth that is actually still available.`,
    careerLong: `The Sun reversed at work most often describes the slow loss of genuine engagement with work that once felt energising. The tasks that previously produced satisfaction now feel mechanical. Recognition, when it arrives, doesn't land — either it isn't being given proportionate to your contribution, or you are unable to feel it fully even when it is there. Something has dimmed in your relationship with your work, and the card is asking what that dimming is actually telling you. It is not always evidence of burnout; sometimes it is evidence of misalignment that has gone unaddressed.

There is also the version of this card that surfaces around impostor syndrome and the inability to inhabit success that is actually present. You are doing well, by most reasonable measures, and yet the doing-well doesn't reach you. Compliments slide off; achievements are immediately diminished; the inner critic remains louder than the actual evidence. This is a particular kind of dimming worth taking seriously, because it tends to undermine careers from inside even when external circumstances are favourable. The work is internal: gradually allowing the success to be real rather than continuing to deflect it.

Practically, the card invites you to reconnect with what genuinely energises you in your work, however small. Which parts of the role bring you actually alive? Which conversations leave you with more energy than you had before them? Which projects you could lose hours to without noticing? These are the diagnostic clues. The Sun reversed in career doesn't always demand a wholesale change; sometimes the medicine is restructuring the existing role so that more of it lives in the energising territory. Sometimes the dimming is information that the role itself has run its course. Either way, find and protect the actual light.`,
    spiritLong: `The Sun reversed spiritually describes a practice or worldview that has become solemn, anxious, or heavy rather than genuinely alive. Spiritual life, at its best, includes joy, wonder, embodied delight, and the kind of clarity that is naturally warm rather than effortfully maintained. If your spirituality is producing more self-criticism, obligation, and gravity than it is producing aliveness, the card is asking whether the practice has drifted into a particular shadow that contemplative traditions have long warned about: the seriousness that mistakes itself for depth.

There is also the more pastoral expression: the burnout of the spiritual helper, the teacher, the carer, the person whose role has involved giving so much for so long that the light they originally brought to the work has dimmed. The Sun reversed in this form is a gentle but firm insistence that the giver also needs to receive, that the wells you draw from need genuine replenishment, that performing radiance you no longer feel is its own form of self-betrayal. Real spiritual life includes rest, pleasure, and the unguarded enjoyment of being alive.

The work is finding what genuinely brings you alive — and doing more of that, not less. The body as a site of spiritual experience rather than only the mind. The senses as legitimate access to the sacred rather than distractions from it. The small pleasures of an ordinary day taken seriously as nourishment rather than dismissed as superficial. The Sun's deeper spiritual teaching is that joy is not the reward at the end of the path but a real and present aspect of any healthy practice. Reversed, the card calls you back to that aliveness, gently but unmistakably.`,
    reversedFaqs: [
      {
        q: 'What does The Sun reversed mean in love?',
        a: `The Sun reversed in love rarely indicates that love is gone; more often it describes something quietly dimming the light that is actually present — insecurity, a habit of finding problems where things are mostly working, or a relationship that looks bright to outsiders but has a more complex interior reality. It can also surface around performed happiness, where both people are working hard to maintain an appearance that no longer matches the texture between them. The work is finding and protecting the real warmth rather than producing more of the performed kind. Small, honest attention to the genuine light is more restorative than redoubled effort to brighten what is being managed.`,
      },
      {
        q: 'Is The Sun reversed a bad sign?',
        a: `The Sun reversed is one of the gentler reversals — it rarely transforms a positive card into a genuinely negative one. The light is still there; something is obscuring it. The card is asking what is dimming the warmth, and inviting honest attention to that dimming. It tends to be more diagnostic than alarming. Treated as a signal to find the actual joy or vitality that is still present and to remove what has been obscuring it, the card is usually more useful than worrying. Even reversed, The Sun rarely says no — it says "yes, but something is in the way."`,
      },
      {
        q: 'What does The Sun reversed mean in career?',
        a: `The Sun reversed at work describes the slow loss of genuine engagement — tasks that no longer feel energising, recognition that doesn't land, the inability to inhabit success that is actually present. It can also surface around impostor syndrome, where good work is being done but not internalised. The card invites you to reconnect with what genuinely energises you in your work, however small, and to find ways of restructuring the existing role so more of it lives in that energising territory. Sometimes the dimming is information that the role has run its course. Either way, find and protect the actual light.`,
      },
      {
        q: 'How do I work with The Sun reversed in a reading?',
        a: `Locate what is genuinely warm in the situation the card addresses — the real moments of ease, joy, or rightness, however small — and ask what has been dimming them. Resist the urge to perform brightness; the card rewards honesty about where the actual light is and where it has gone. Often the medicine is doing more of what genuinely brings you alive rather than working harder at what should bring you alive but doesn't. The Sun reversed is gentle in tone, but it does insist on real engagement with the question of what makes you actually well rather than what looks well from outside.`,
      },
    ],
  },

  'judgement': {
    loveLong: `Judgement reversed in love describes a significant conversation, decision, or acknowledgement that has been hovering for some time without being made. You know, often quite precisely, what needs to be said. You know which question, asked honestly, would shift the relationship into a new chapter. And yet the saying keeps being postponed, often dressed up in reasonable-sounding language about the timing not being right, the other person not being ready, the situation needing to settle further. The card is asking whether the timing genuinely isn't right, or whether the deferral has become a way of not facing what you already know.

There is also a particular shadow this card surfaces: unresolved guilt or shame that is interfering with present connection. The behaviour from earlier in the relationship that was never properly acknowledged. The pattern from a previous partnership you have been quietly bringing into this one. The thing you did or didn't do that you have been carrying around as private burden rather than offering honestly. Judgement reversed in love sometimes asks for the apology, conversation, or admission that, however uncomfortable, would actually free the relationship from a weight it has been carrying without naming.

The card also describes the difficulty of forgiving — whether forgiving a partner for a real hurt, forgiving a former partner so that you can be more fully present in a new relationship, or forgiving yourself for behaviour you regret. Forgiveness in this sense is not a feeling that arrives spontaneously; it is a choice that is gradually inhabited through honest reckoning. The work is rarely dramatic. It is the slow practice of releasing what you have been carrying so that what is actually alive between you can have the space it needs. Decide what needs to be said, acknowledged, or released, and begin.`,
    careerLong: `Judgement reversed at work most often appears when a genuine vocational calling is being ignored in favour of the safer, more familiar, or financially more convenient choice. Something has been calling you — quietly but persistently — and you have been treating the call as a passing distraction rather than as the signal it actually is. The card is asking you to take the calling seriously, not necessarily to act on it immediately but to stop pretending it isn't there. Vocations that are repeatedly ignored tend to either go silent (which is its own kind of loss) or to surface more disruptively later.

There is also the version of this card that appears around significant professional evaluations being avoided. The honest conversation with yourself about whether the role you are in is still working. The performance review you are dreading because you know what it will reveal. The decision about whether to pivot, stay, leave, or recommit that you have been deferring through busyness. Judgement reversed gently insists that the assessment cannot be deferred indefinitely. The longer it waits, the more accumulated material it carries when it is finally faced.

Practically, the card invites you to do the assessment now, in the form that is available to you. Honest journalling about what is and isn't working. A real conversation with a trusted mentor or therapist. A weekend of genuine reflection rather than another set of incremental tactical decisions made on top of an unexamined foundation. Judgement at its best is the experience of being able to see your professional life clearly enough to make real decisions about it. Reversed, the card asks for the seeing — even when the seeing implies changes you would rather not have to make.`,
    spiritLong: `Judgement reversed spiritually points to a reluctance to fully reckon with your own life — either to grieve what has passed, to honestly assess what has and hasn't served your genuine growth, or to accept a call to deeper engagement that you have been hearing for some time. The card is not asking you to judge yourself harshly; the upright card is about awakening, not condemnation. The reversal usually describes the resistance to that awakening, the various ways we manage to half-hear an important inner call and then return to our previous arrangements without quite acknowledging that we have done so.

There is also the particular pattern of harsh self-judgement that this card surfaces. Not the clear-eyed reckoning the upright card invites, but its punitive cousin — the inner verdict that keeps you frozen in shame rather than allowing actual movement. People who are most reluctant to face Judgement are often those who fear the verdict will be ruinous, and they are usually wrong about what they would actually find. Honest self-examination almost always reveals a more nuanced, more forgivable, more workable picture than fear had been imagining. The work is examining the actual evidence rather than continuing to flinch from an imagined sentence.

The medicine is honest reckoning held without self-violence. Look at what you have done and not done. Notice where you have grown and where you have not. Grieve what needs grieving. Forgive what genuinely needs forgiving, both in others and in yourself. The trumpet's call in the upright card is to a larger version of yourself; reversed, the card asks whether you are willing to actually hear that call and answer, or whether you would prefer to keep deferring on the grounds that you are not yet ready. You will not become ready by waiting. You will become ready by beginning.`,
    reversedFaqs: [
      {
        q: 'What does Judgement reversed mean in love?',
        a: `Judgement reversed in love most often describes a significant conversation, decision, or acknowledgement that has been hovering for some time without being made — usually one whose nature you already know quite precisely. It can also surface around unresolved guilt or shame from earlier in the relationship that has never been properly acknowledged. The card asks for the apology, conversation, or admission that would actually free the relationship from weight it has been carrying. It also addresses the difficulty of forgiving — a partner, a former partner, or yourself. The work is rarely dramatic; it is the slow practice of releasing what you have been carrying.`,
      },
      {
        q: 'Is Judgement reversed a bad sign?',
        a: `Judgement reversed is more uncomfortable than bad — it names a reckoning you have probably been deferring, and asks you to engage with it honestly. The card rewards the willingness to face what you already know, and tends to be unkind only to those who refuse the question it raises. People who fear the verdict will be ruinous are usually wrong about what they would actually find; honest self-examination almost always reveals a more nuanced and workable picture than fear had been imagining. Treated as invitation to honest reckoning rather than as condemnation, the card is consistently useful.`,
      },
      {
        q: 'What does Judgement reversed mean in career?',
        a: `Judgement reversed at work most often signals a genuine vocational calling being ignored in favour of the safer or more convenient choice, or a significant professional evaluation being avoided through busyness. Something has been calling you, quietly but persistently, and you have been treating it as a passing distraction. The card invites you to do the honest assessment now — in journalling, in conversation with a trusted mentor or therapist, in a genuine weekend of reflection — rather than continuing to defer. Vocations that are repeatedly ignored tend to either go silent or surface more disruptively later. Begin the seeing now.`,
      },
      {
        q: 'How do I work with Judgement reversed in a reading?',
        a: `Identify what you already know but have been refusing to fully acknowledge — the conversation, decision, calling, or honest assessment you have been deferring. Resist both the temptation to dramatise the eventual reckoning and the temptation to keep avoiding it through reasonable-sounding rationale. The work is usually quieter than you fear and more useful than you expect. Practical steps — honest journalling, a real conversation with someone trusted, a deliberate weekend of reflection — tend to dissolve far more accumulated weight than further deferral would. Begin where you are, with what is actually available to be acknowledged today.`,
      },
    ],
  },

  'the-world': {
    loveLong: `The World reversed in love most often describes a relationship at the threshold of a meaningful completion or deepening — but not quite stepping through. Sometimes this is about a partnership genuinely coming to a natural end after its cycle has been fulfilled, where both people sense the ending but neither has yet had the courage to name it. More often, it is about a connection that is ready to deepen — an engagement, a shared home, a new level of vulnerable commitment — that is being circled but not entered. The final yard, in either direction, is asking to be walked.

There is also a particular form of perfectionism this card surfaces in love. The relationship that is "almost right" indefinitely. The partner who is "almost ready" indefinitely. The conditions that are "almost in place" for the commitment to finally make sense. The card asks whether you are waiting for genuine readiness or for an impossible certainty that no honest love has ever waited for. Most significant relationship commitments are made before the people involved feel entirely sure. The making of the commitment is part of what produces the deeper readiness, not its precondition.

The work is examining the final step honestly. If the completion is an ending, what has been keeping the conversation unspoken? What does each of you need in order to let the chapter close with dignity rather than slow erosion? If the completion is a deepening, what is the specific fear or unfinished business that has been preventing the step into the next chapter? Sometimes the work is genuinely concluding what is finished. Sometimes it is gently risking the step you have been circling. Either way, indefinite hovering at the threshold tends to cost more than the actual movement would.`,
    careerLong: `The World reversed in career most often describes a significant achievement or completion that is within reach but is not being received. The project that is ninety per cent done but cannot quite be declared finished. The role you have outgrown but cannot quite leave. The recognition that has arrived but somehow does not land. The card is asking what is preventing the final step — perfectionism, fear of what comes next, an inability to allow yourself the satisfaction of arrival, external circumstances that have genuinely complicated the conclusion.

There is also the pattern of premature closure this card surfaces. Declaring something complete before the genuine work of integration has been done. Moving on before the learning has been absorbed. Treating the visible milestone as the actual end when the inner consolidation that would make the milestone meaningful is still in progress. The World's wholeness, when it lands, is genuinely earned; the reversed card sometimes catches the moment of trying to skip the part of the earning that doesn't look like progress on the outside.

Practically, the card asks you to identify what specific completion is at stake and what is required to genuinely complete it. Sometimes this is concrete — a final draft, a difficult conversation, a transition that has been almost made for too long. Sometimes it is more inward — allowing yourself to accept that the work is done, that the cycle has been fulfilled, that the chapter can be closed. The next beginning the card promises is genuinely available, but the completion has to actually happen first. The final yard is asking to be walked.`,
    spiritLong: `The World reversed spiritually describes a journey of integration that is almost — but not quite — complete. The work has been done. The lessons have been received. The dark passages have been crossed. And yet something prevents the actual landing — a final piece of understanding that hasn't been received, a remaining forgiveness that has not been offered, a small but stubborn resistance to fully embodying what the journey has taught. The card asks what is in the way of arrival, gently but firmly.

There is also the inverse: a readiness to begin the next cycle that has not yet been acknowledged. The completion is real; the new beginning is already forming; and yet you remain in the closed chapter as if more remained to be done within it. This is a particular kind of stuckness because nothing visible is wrong — you have done the work, the integration is genuine, but the consent to move into the next phase has not been given. Sometimes the work is grieving the previous chapter so that the new one can be properly entered.

The medicine is asking honestly what genuine completion would look like, and giving yourself permission to actually arrive. Not perfectly. Not having resolved every remaining question. Not having achieved a final, unimprovable state. Just acknowledging that the cycle has been substantially fulfilled, that what was meant to happen has happened, that you have actually grown and the growth is real. The World's deepest teaching is that completion always contains a new beginning. Reversed, the card asks you to honour the completion enough to allow the new beginning that is already calling.`,
    reversedFaqs: [
      {
        q: 'What does The World reversed mean in love?',
        a: `The World reversed in love describes a relationship at the threshold of meaningful completion or deepening that has not quite stepped through — either an ending that hasn't been named, or a deepening (commitment, shared life, vulnerable opening) that is being circled but not entered. It can also surface around perfectionism in love, where the relationship is "almost right" indefinitely or the conditions for commitment are "almost in place" forever. The card asks whether you are waiting for genuine readiness or for an impossible certainty no honest love has ever required. The final step asks to be taken.`,
      },
      {
        q: 'Is The World reversed a bad sign?',
        a: `The World reversed is rarely about fundamental failure; it is almost always about the final yard. The card describes a completion that is within reach but is not being received, or a transition into a new cycle that is being resisted at the threshold. The good news the card brings is that you are genuinely close. The work, when it is identified honestly, is usually smaller than it appears. People who treat the card as encouragement to take the final step usually find that the step is more manageable than the indefinite hovering had felt. The card is one of the more hopeful reversals in the Major Arcana.`,
      },
      {
        q: 'What does The World reversed mean in career?',
        a: `The World reversed in career most often describes a significant achievement or completion within reach but not being received — the ninety-per-cent-done project, the role you have outgrown but cannot quite leave, the recognition that has arrived but does not land. The card asks what is preventing the final step — perfectionism, fear of what comes next, an inability to allow yourself the satisfaction of arrival. It can also surface around premature closure, where you are declaring something complete before the inner integration has actually happened. Either way, identify what completion would look like and take the specific step that allows it.`,
      },
      {
        q: 'How do I work with The World reversed in a reading?',
        a: `Identify what specific completion is at stake — what relationship, project, chapter, or cycle is at the threshold of actually concluding or deepening. Then ask what specific step remains to be taken and what has been keeping it untaken. The work is usually smaller than the indefinite hovering would suggest. Allow yourself to actually arrive, even imperfectly. The new beginning the card promises is genuinely available, but the completion has to happen first. Resist both premature declaration of doneness and indefinite postponement of arrival. The final yard asks honestly to be walked.`,
      },
    ],
  },
}
