import type { ReversedContext } from '../card-reversed-extended'

export const SWORDS: Record<string, ReversedContext> = {
  'ace-of-swords': {
    loveLong: `The Ace of Swords reversed in love speaks of confused thinking around a connection. A breakthrough you thought you had — a sudden moment of clarity about who someone is, what you want, or what you need to say — has become muddled. The clean cut of truth has gone blunt. You may have rehearsed a difficult conversation a hundred times in your head only to find the words slipping away when the moment arrives, or you may have leapt into honesty too soon and now wonder if you delivered it cruelly rather than cleanly.

This reversal also points to mental noise crowding out the heart. Conflicting advice from friends, half-finished texts, drafts you never sent — all of it is fog obscuring a signal that is genuinely there underneath. The truth has not disappeared; it has simply become hard to hear. If you have recently received news about a relationship that hit harder than expected, give yourself permission to sit with it before responding. The first clear thought is rarely the wisest one when emotions are still spinning.

The good news in the Ace of Swords reversed is that clarity is recoverable. Step away from the noise. Write things down by hand rather than thinking in circles. Ask yourself the simple, unflattering questions — what is true here, what do I actually want, what am I avoiding saying? The blade can be sharpened again, but it will not happen while you keep grabbing at it. Patience with your own thinking is the way through.`,
    careerLong: `The Ace of Swords reversed at work indicates a breakthrough that has not quite landed. You may have an idea you cannot articulate clearly, a strategy that sounded brilliant at midnight but fell apart in the morning meeting, or a decision you keep almost making and then withdrawing. Mental clarity is the gift of the upright Ace; reversed, that clarity is clouded by overthinking, second-guessing, or information you have not yet been given.

This card reversed in career can also signal miscommunication at a critical moment. A pitch landed wrong. An email was misread. Feedback was harsher than intended, or softer than needed, and now the meaning is lost. If you are leading a project, double-check that what you said is what people heard — assumptions about shared understanding are particularly costly when this card is reversed. Slow down, restate the obvious, and put things in writing where you can.

There is also a creative dimension here. A brilliant idea may be arriving in raw, unrefined form. Honour it by writing it down without judgement, but do not announce it or build the whole strategy around it yet. Let it cook. The Ace of Swords reversed often shows the moment just before genuine breakthrough, when the mind is straining toward an insight it has not quite grasped. Rest, walk, sleep on it. The blade will reveal itself once you stop forcing the cut.`,
    spiritLong: `The Ace of Swords reversed spiritually points to a mind that has become its own obstacle. You may be intellectualising practice instead of engaging with it — reading another book about meditation rather than sitting, debating theology rather than praying, collecting frameworks instead of experiencing presence. The sword that was meant to cut through illusion has become a tool for building more elaborate illusions, dressed in spiritual language.

This reversal often appears when a real spiritual insight has arrived but has been distorted in transmission to yourself. You felt something true, then immediately reached for words, and the words flattened it. Now you are arguing with the flattened version. Notice this gently. The original truth is still available — it lives under the commentary, not in it. Returning to silence, breath, or body for even a few minutes restores access more reliably than another thought-experiment will.

The Ace of Swords reversed can also indicate that brutal spiritual honesty is needed but not yet delivered with kindness. Telling yourself the truth about a habit, a belief, or a relationship is right work — but doing it with self-cruelty is not the same as doing it with clarity. The clean blade cuts without contempt. If your self-talk has the edge of a weapon, that is the reversal showing itself. Sharpen the discernment; soften the tone.`,
    reversedFaqs: [
      { q: 'What does Ace of Swords reversed mean in love?', a: 'It points to confused thinking around a romantic situation rather than the decisive clarity of the upright card. You may know something important is true about your connection but feel unable to say it cleanly, or you may have spoken truth in a way that came out blunt and wounding. The card asks you to slow down, separate the signal from the noise, and approach honest conversations with both precision and care. Clarity is still available — it has simply been clouded by overthinking, advice from too many sources, or your own fear of what naming the truth will set in motion.' },
      { q: 'Is Ace of Swords reversed a bad sign?', a: 'Not really, and often it carries genuine relief. The upright Ace can be a shock — sudden truth, a cut you did not see coming. Reversed, that edge is softened. You have more time to refine your thinking, to choose your words, to gather information before acting. The reversal warns against confusion and miscommunication, but it also protects you from delivering or receiving a truth too sharply. Treat it as an invitation to sharpen your discernment privately before you bring it into the world. A delayed clarity is still clarity.' },
      { q: 'What does Ace of Swords reversed mean for communication?', a: 'Communication is the heart of this card, and reversed it is where the trouble lives. Expect drafts you cannot finish, conversations that veer off the point, and meanings that get lost between sender and receiver. Slow your pace. Restate what you heard back to the other person before responding. Put important things in writing so the words can be re-read. If you have been holding a difficult message, the card does not say never send it — it says refine it first. Truth told carelessly is not the same as truth told well.' },
      { q: 'How do I work with Ace of Swords reversed in a reading?', a: 'Treat it as a signal to pause before acting on whatever insight feels urgent. Ask: is this thought genuinely clear, or only loud? Write the idea down without sharing it for twenty-four hours. Test the conversation you want to have by saying it aloud to yourself first. Look for what information you are missing rather than what conclusion you can force. The Ace of Swords reversed rewards patience with your own mind. The breakthrough has not failed — it is still forming, and your job is to give it space to arrive cleanly.' },
    ],
  },

  'two-of-swords': {
    loveLong: `The Two of Swords reversed in love is the moment the blindfold slips. The stalemate you have been holding — the difficult choice about whether to stay or go, to commit or step back, to speak or stay silent — is no longer something you can defer. Circumstances are forcing the decision, or your own heart has quietly made it without consulting your fears. Either way, the comfortable suspension is ending.

For some, this reversal brings welcome relief. You have been exhausted by the weight of not-deciding, and the moment of choosing — even when the choice is hard — feels like air returning to the room. For others, it lands as panic. You were not ready, you wanted more time, and now the situation has its own momentum. Both responses are legitimate. The card does not promise the decision will be easy, only that it will finally happen.

What the Two of Swords reversed asks of you is honesty about which side of the scale already weighs more. You usually know. Beneath the careful balancing act, beneath the lists of pros and cons, there is a quiet preference that you have been refusing to admit because admitting it commits you to something. Look at that preference now. Speak to it. The truce is over, and your relationship — whatever shape it takes next — needs you to choose with your eyes open rather than continue to play fair with a question that no longer has time for fairness.`,
    careerLong: `The Two of Swords reversed in career signals that a decision you have been postponing is becoming unavoidable. The job offer needs an answer. The conflict between colleagues will not de-escalate on its own. The project direction must be set. You have been balancing on the blade for too long, hoping the question would resolve itself, and the situation is now writing its own deadline.

This card reversed at work also warns against the cost of perpetual indecision. Teams cannot move when their leader will not choose. Opportunities expire while you weigh them. The information you have been waiting for in order to feel certain may never arrive — at some point the choice has to be made with what you have. Often the reversed Two reveals that you have actually had enough information for weeks; what you lacked was the willingness to be held accountable for picking a direction.

There is also a softer reading: clarity is finally returning after a long fog. You can suddenly see both sides of an issue you were stuck on, and the path forward emerges from that wider view. If this is your moment, act on it before the clarity slips again. Write the decision down, share it with the people it affects, and start moving. The Two of Swords reversed rewards motion. The longest thing you can do at this point is keep standing still.`,
    spiritLong: `The Two of Swords reversed spiritually marks the end of a long internal stalemate — the kind where two parts of yourself have been arguing past each other for months or years. Heart against head. Old self against new. Loyalty to who you were against the pull of who you are becoming. The blindfold that let you avoid choosing has worn thin, and the conflict is rising into conscious view where it can finally be addressed.

This is uncomfortable but it is good work. The reversal often arrives alongside a sense that you cannot keep meditating around a question, journaling around a question, or performing equanimity about a question. The spiritual life requires you to actually answer it. Truth-telling to yourself is the practice now — not the polished version you would share with a teacher, but the unflattering admission you have been refusing to make even in private.

Approach this gently. The Two of Swords reversed does not demand you slash through your own complexity to force a tidy resolution. It asks you to take the blindfold off and look. Some choices, once seen clearly, almost make themselves. Others require sitting with the discomfort of two truths that both feel real. Either way, the work is sight. Let yourself see what you already know, and trust that the path forward will become walkable once you stop pretending the crossroads is not there.`,
    reversedFaqs: [
      { q: 'What does Two of Swords reversed mean in love?', a: 'It usually means a decision you have been postponing in a relationship is becoming unavoidable. The blindfold of avoidance is slipping, and the question of whether to stay, go, commit, or speak up is rising to the surface. This can feel like relief or like pressure depending on how long you have been deferring. The card reversed honours that the choice is hard, but it confirms that the suspended state is no longer sustainable. Be honest with yourself about which way your heart actually leans — you likely already know.' },
      { q: 'Is Two of Swords reversed a bad sign?', a: 'Often it is genuine relief compared to upright. The upright Two is the agony of indefinite avoidance, the blindfold tightened. Reversed, the blindfold loosens and the stalemate breaks. Decisions can finally be made. Information becomes available. The standoff with another person, or with yourself, finds movement. The reversal can feel destabilising if you were comfortable in the limbo, but it is fundamentally a liberating card — it returns your agency and ends the exhausting work of pretending you cannot see what is in front of you.' },
      { q: 'What does Two of Swords reversed mean for communication?', a: 'It points to long-avoided conversations that are now ready, or required, to happen. The truce of not-talking has run its course. This reversal often shows up when someone finally says the thing — the boundary, the truth, the disagreement — that has been sitting under the surface of polite interaction. Communication may feel clumsy at first; you have been silent too long for the words to flow easily. Start anyway. Imperfect honesty restarts a stalled situation more reliably than another month of careful nothing.' },
      { q: 'How do I work with Two of Swords reversed in a reading?', a: 'Take it as permission and pressure to choose. Identify the specific decision you have been deferring — name it plainly, even just to yourself. Then ask which side you already privately prefer; usually it is clear once you stop performing fairness. Make a small concrete move in that direction within the next few days, even if you do not announce the full choice. The card rewards motion. It does not require certainty, only honesty about where you have actually been standing all along beneath the careful balancing act.' },
    ],
  },

  'three-of-swords': {
    loveLong: `The Three of Swords reversed in love is one of the most quietly hopeful reversals in the deck. The heartbreak that defines the upright card is starting to release its grip. The grief is not gone — it does not vanish on command — but it is no longer the only weather in the sky. You are beginning to have whole hours, sometimes whole days, when the pain is not the loudest thing in the room.

This is the card of healing in progress. It may show forgiveness becoming possible toward someone who hurt you, or toward yourself for choices you made when you were hurting. It may show the slow return of appetite, of laughter, of curiosity about other people. None of this happens evenly. You will have setbacks — anniversaries, photographs, songs that ambush you in the supermarket — and they will feel like backsliding. They are not. Recovery from a broken heart is recursive rather than linear, and the reversed Three honours that.

If you are still inside the pain, the Three of Swords reversed in love is a gentle promise rather than an instruction. You do not need to rush the grief to be useful for it. The card simply notes that the worst of it has passed, even when you cannot yet feel that, and that the work now is to keep tending the wound rather than reopening it. Be slow with yourself. Let other people in carefully. Trust that what feels like dull ache today will, in time, become a story you tell with a softer voice.`,
    careerLong: `The Three of Swords reversed in career marks recovery from a professional wound — a redundancy, a public failure, a betrayal by a colleague you trusted, a project that collapsed loudly. The acute phase of the pain is behind you. You are no longer crying in the car park or rehearsing the conversation that broke you. The lesson is integrating, even if you cannot yet articulate what it was.

This reversal also shows the slow return of confidence after a hit. You may not yet be ready to leap back in at full strength, and you should not force yourself. The instinct to prove you are unbroken by overworking the next opportunity is a trap; it tends to recreate the very dynamic that hurt you. Choose your next move from a recovered place rather than from the urge to outrun what happened. Take the rest you actually need.

There is forgiveness work here too — sometimes of others, sometimes of yourself. You may be ready to stop replaying the meeting where it all went wrong, to release the colleague who undermined you, to forgive the version of you who did not see it coming. The Three of Swords reversed at work does not ask you to pretend none of it happened. It asks you to stop letting it be the only story you tell about your career. There is more after it, and you are beginning to feel that.`,
    spiritLong: `The Three of Swords reversed spiritually represents the soft passage from acute grief into integrated wisdom. The wound is closing — not vanishing, but becoming part of who you are rather than a fresh injury you keep examining. You may notice you can think about the loss now without the bottom dropping out of your chest, and that small return of stability is a holy thing.

This reversal often brings a renewed sense of meaning. The pain you went through, while you would not wish it again, is beginning to feel like it belongs to your story rather than being an interruption of it. You may find yourself more able to sit with other people in their pain, more able to tell the truth about hard things, more reluctant to perform fine when you are not fine. These are gifts. They cost a great deal, and they are real.

The Three of Swords reversed spiritually also warns gently against premature transcendence. There is a temptation, when grief begins to lift, to leap straight into the lesson — to declare what it taught you, to wrap it in a tidy spiritual frame so you never have to feel the raw edge again. Resist that for a while longer. Some wisdom only forms when you let the pain finish speaking. Stay with the slow, honest recovery. The meaning will arrive on its own, and it will be more trustworthy for not being rushed.`,
    reversedFaqs: [
      { q: 'What does Three of Swords reversed mean in love?', a: 'It usually means heartbreak is beginning to heal. The acute grief of the upright Three is loosening its grip — you are having more hours when the pain is not the loudest thing. Forgiveness, of yourself or of the person who hurt you, is becoming quietly possible. This is not a linear process; expect setbacks around anniversaries or unexpected reminders. The card reversed honours those without taking back the progress. Be slow and patient with your own recovery. The wound is closing, even when on a hard day you cannot feel that it is.' },
      { q: 'Is Three of Swords reversed a bad sign?', a: 'No — it is one of the gentler reversals in the deck. The upright card is the moment heartbreak lands; reversed, you are past the worst of it and into recovery. The pain is no longer fresh. You can begin to think about what happened without being undone by it. Forgiveness, integration, and a careful return to openness all become possible. The card does not promise the grief is over, only that the acute phase has passed and healing is genuinely underway. That is a deeply hopeful place to receive a Three of Swords from.' },
      { q: 'What does Three of Swords reversed mean for communication?', a: 'It points to the conversation after the wound — the talk where you finally say what hurt, or hear what hurt the other person, without re-opening the injury. Communication at this stage tends to be quieter and more honest than during the conflict itself. There may be apologies that have taken months to form, or simple acknowledgements that something happened and mattered. You may also need to talk about the pain with a friend, therapist, or journal rather than with the person involved. Speaking grief out loud is part of how it leaves the body.' },
      { q: 'How do I work with Three of Swords reversed in a reading?', a: 'Take it as permission to recognise how far you have actually come, even if the pain is still present. Make space for grief without making it the whole story. Practical steps: notice the hours that are easier now, name them, let them count. Resist the urge to leap into the lesson before the feeling has finished. Be careful about who you let close while you are still tender. The card asks you to keep tending the wound rather than test it. Healing is happening on its own clock — your job is mostly not to interrupt it.' },
    ],
  },

  'four-of-swords': {
    loveLong: `The Four of Swords reversed in love often shows someone re-emerging from a period of relational hibernation. Maybe you took time away after a difficult breakup, deliberately stayed single to do inner work, or simply withdrew from the dating world to rest. The rest has done its job — and yet now you are caught in the threshold, unsure whether to fully re-enter or stay in the quiet a little longer.

There is another reading too: rest that has gone on too long. The retreat began as healing and slid into avoidance. You have used solitude as armour, and now any time someone shows interest the instinct is to disappear back into the cave. The card reversed asks gently whether the rest is still serving you, or whether it has become the new way of avoiding the very thing rest was meant to prepare you for.

If you are in an existing relationship, the Four of Swords reversed can indicate that one of you has been disengaged for too long. The phone scrolling on the sofa, the parallel lives, the quiet drift — these are forms of rest that have curdled. The card invites a careful return to presence. You do not need to fix everything in one conversation; you only need to begin showing up again, gently, and let the connection rebuild. Coming back is its own small act of courage. The card reversed honours both the rest you took and the work of stepping out of it.`,
    careerLong: `The Four of Swords reversed at work points to either restlessness after enforced stillness or burnout from refusing to stop. Both readings are common. In the first, you have been on extended leave, between roles, or in a quieter phase of your career, and you are beginning to itch for movement again. The card supports a slow return rather than a leap. Do not undo the recovery by sprinting on the first day back.

In the second reading, you have been running on empty and treating rest as something other people get to have. Your body has started filing complaints — headaches, insomnia, a heaviness that does not lift on weekends — and the card is reversed because you have ignored the upright instruction to stop. This is the gentler warning before something more forceful insists. Take the time off before the situation takes it for you. Cancel the optional commitments. Sleep is not weakness.

If you are leading a team, the Four of Swords reversed can show that your people are exhausted in ways you may not have fully seen. The output is still happening, but the spark is gone, and small mistakes are creeping in. Build in real recovery time, not performative wellness days. Burnout is much cheaper to prevent than to fix. The card reversed at work is fundamentally a course-correction toward sustainability — either step back into the world after rest, or step back from the world before collapse forces it. Choose now while choosing is still cheap.`,
    spiritLong: `The Four of Swords reversed spiritually shows the practitioner who has either rested deeply and is now ready to re-engage, or who has used spiritual retreat as a form of avoidance and is being gently called back. Both versions are honest possibilities. Ask yourself which you are in.

If you have done the rest, this reversal is a kind nudge that the world is ready for the version of you that emerged from it. The insights gained in silence are meant to be lived, not just collected. Returning to the world after deep practice can feel jarring — the noise is loud, people seem fast, your nervous system is recalibrating. Go gently. You do not have to grab everything that returns. Let yourself re-enter with the same care you used to withdraw.

If you have over-rested, the card reversed is honest with you. Meditation can become a hiding place. Spiritual practice can become a way to never have to engage with messy human relationships, difficult conversations, or the simple challenge of being a person in the world. The cave is meant to be temporary. The reversed Four asks: what are you avoiding by staying in retreat? The answer usually arrives quickly when you ask honestly. Re-entry, however clumsy, is the medicine. Practice is not the goal; it is preparation for a life lived more awake. Step back into that life now.`,
    reversedFaqs: [
      { q: 'What does Four of Swords reversed mean in love?', a: 'It can mean re-emerging from a chosen period of being single or withdrawn — the rest has served its purpose and you are ready to be open again. It can also mean rest that has slid into avoidance, where solitude has stopped healing and started insulating. In existing relationships, the reversal often shows a slow drift back into presence after a quiet phase, or warns that one of you has been emotionally absent too long. Look honestly at whether the rest is still nourishing or whether it has become a way of not engaging with what love asks of you.' },
      { q: 'Is Four of Swords reversed a bad sign?', a: 'Not usually. It tends to mark a transition rather than a wound. If you have been in retreat, it signals that re-entry is near. If you have been refusing to rest, it is a gentler warning to stop before something more drastic insists. Either way the card is helpful information. The upright Four can be a forced stillness; reversed, you are recovering your agency around rest — choosing when to be still and when to re-engage rather than having either imposed on you. That return of choice is genuinely good news.' },
      { q: 'What does Four of Swords reversed mean for communication?', a: 'It often shows someone breaking a long silence — reaching out after months of being out of contact, replying to messages they had let sit, or restarting a conversation that paused. The communication may feel rusty at first. Words come slowly, tone is uncertain. That is normal and not a sign of failure. The card reversed honours that re-engagement is a skill that returns with practice. It can also mean noticing that someone has been quietly disengaged in a relationship and gently inviting them back into dialogue. Begin small.' },
      { q: 'How do I work with Four of Swords reversed in a reading?', a: 'Ask which version applies to you right now — emerging from rest, or stuck in too much of it. If emerging, go slow. Re-enter one area at a time rather than reclaiming everything at once. If over-resting, identify a specific thing you have been avoiding and take one small concrete step toward it this week. Either way, treat the transition with the same care you would treat physical recovery from illness. Sustainability matters more than speed. The card rewards a thoughtful re-engagement, not a triumphant return.' },
    ],
  },

  'five-of-swords': {
    loveLong: `The Five of Swords reversed in love is the aftermath. The argument is over. The cutting words have already been said. Someone won and someone lost, or perhaps you both lost, and now you are standing in the wreckage trying to work out what to do with it. This reversal is the card of release — the moment when ego loosens its grip and the question shifts from who was right to what mattered more than being right.

For many, this card reversed brings a quiet, unflattering recognition. You see the part you played. You notice that the point you were defending so fiercely was not actually worth the damage done in defending it. The reversed Five does not demand you grovel; it asks you to be honest. An apology, when one is genuinely owed, costs less than the silence that follows refusing to give it. If your partner is also in this card, expect them to be working through something similar in their own time.

Sometimes the Five of Swords reversed in love marks the beginning of reconciliation, sometimes the beginning of a clear-eyed parting. Both are forms of release. What it almost never recommends is staying locked in the position you took during the fight. The conflict has done its damage; the question now is whether you can put down the sword for long enough to see what is salvageable. Pride is heavy to carry. The card reversed gently invites you to set it down and see what remains underneath.`,
    careerLong: `The Five of Swords reversed at work signals the aftermath of conflict — a difficult meeting, a passive-aggressive thread, a power struggle that did not go as anyone hoped. The fight is finished. The fallout is here. The reversed card asks how you want to behave in this next phase, when the heat is gone and the consequences are still arriving.

If you won the conflict, the reversed Five often shows the cost. Colleagues who used to trust you are now careful around you. Information dries up. You are technically right and increasingly alone. The card invites you to make repair where you can — not by surrendering the principle you defended, but by acknowledging that you may have defended it harder than it required. A short, honest conversation with the person you bruised goes further than another quarter of professional politeness.

If you lost, the card reversed is kinder than it looks. The thing you fought for may not have been the thing you most needed. Sometimes losing a battle protects you from a war you should not have been fighting at all. There is space now to ask what you actually want from this role, this team, this work. Use it. Step away from the temptation to relitigate the disagreement in your head. The Five of Swords reversed at work rewards those who can release the grievance and move forward — not because the grievance was wrong, but because carrying it is a tax you cannot keep paying.`,
    spiritLong: `The Five of Swords reversed spiritually is the practice of putting down a fight you have been holding for too long — usually with yourself. Old grievances, replayed grudges, the running argument with someone who has not been in your life for years: these are weight, and the reversed Five offers a chance to release it.

This card asks honest questions. What are you still defending? Whose voice are you still trying to win against in your head? What victory are you waiting for that will let you finally rest? Often the answer reveals an old wound dressed up as a position. You are not actually arguing about the thing — you are arguing because being right about it has been holding a younger, hurt version of you together. The reversed Five invites compassion for that younger self, and the slow work of letting the case go.

Forgiveness here is not approval. The reversed Five does not ask you to say the harm was acceptable, or to invite the person back into your life, or to perform peace you do not feel. It only asks whether you can stop carrying the sword. That is enough. The release is for you, not for them. The Five of Swords reversed spiritually returns energy that has been tied up in old conflict — and you will likely be surprised by how much of it there is. Use the returned energy gently. Rest before you redeploy it.`,
    reversedFaqs: [
      { q: 'What does Five of Swords reversed mean in love?', a: 'It typically marks the aftermath of an argument or relational wound and asks how you want to behave now that the heat is gone. The card invites release of ego — the part that wants to keep being right at the cost of the connection. This can be the beginning of genuine reconciliation, or the clear-eyed start of a parting, but it almost always involves setting down the sword. An honest apology, when one is genuinely owed, opens doors that another month of righteous silence will keep closed. Look at what mattered more than winning.' },
      { q: 'Is Five of Swords reversed a bad sign?', a: 'It is often a relief compared to upright. The upright Five is the destructive phase of a fight; reversed, the fight is over and you have the chance to choose what comes next. The damage is done — that is not nothing — but the wound is no longer being deepened with every passing day. Repair becomes possible. Honest reflection on your own part becomes possible. The reversal hands you back the agency that conflict had stolen. Use it gently. It is not a triumphant card, but it is genuinely a hopeful one.' },
      { q: 'What does Five of Swords reversed mean for communication?', a: 'It often shows the careful conversation after the angry one — the message you draft and rewrite, the apology that has taken weeks to form, the difficult acknowledgement that you handled something badly. Communication at this stage is quieter and slower than during the conflict. It works best when you lead with what you got wrong rather than what they did, even if their share was larger. The reversed Five rewards humility in the rebuilding phase. Listening matters more than defending; understanding lands deeper than vindication.' },
      { q: 'How do I work with Five of Swords reversed in a reading?', a: 'Identify the specific conflict the card is pointing to, then ask what you are still carrying from it that you would be willing to set down. Make a list of grievances you have been replaying and choose one to release this week — not by minimising it, but by deciding it no longer gets to live rent-free in your mind. If repair is possible with the other person, send one honest message. If not, do the release work privately. The card returns energy that has been tied up in old fights. Spend it on something better.' },
    ],
  },

  'six-of-swords': {
    loveLong: `The Six of Swords reversed in love speaks to resistance to moving on. You know the relationship is over, or that the dynamic needs to change, but something in you keeps rowing back toward the shore you just left. A text you should not have sent. A drive past the old place. A conversation with mutual friends that ends up being about them again. The boat is leaving — the reversed Six is the part of you that keeps reaching for the dock.

This is human. The card does not judge you for it. It only points out, gently, that the resistance is costing you the very calm waters the journey was meant to bring you to. Each backward glance restarts the grief from a slightly earlier point. Each unanswered question you go back to ask drains the energy you need for the crossing. The card reversed asks what you are still hoping the past will give you. Often the honest answer is closure — and closure, when it comes, almost never comes from the person who hurt you. It comes from inside, slowly, as you stop looking for it elsewhere.

There is another reading too. Sometimes the Six of Swords reversed in love shows rough waters that have not yet calmed — a transition you have begun but that is taking longer and feeling harder than you expected. The card honours that. Not every passage from a difficult relationship is smooth. Keep rowing anyway. The other shore is real. The chop you are in is not the destination.`,
    careerLong: `The Six of Swords reversed at work shows someone struggling to leave behind a role, a team, or a way of working that they have outgrown. The new offer is on the table; the resignation is drafted; the change is clearly the right move — and yet something keeps pulling you back. Loyalty to colleagues. Fear of starting over. The comfort of mastery in a place that is no longer challenging you.

This reversal also appears when a transition is underway but rougher than expected. The new role is harder than the recruiter implied. The team you joined is in turmoil. The relocation is not delivering the fresh start it promised. The card reversed honours that the journey is not always smooth, while quietly insisting that the way forward is still forward. Returning to the old place rarely solves what made you leave it.

If you are not yet in motion, the Six of Swords reversed at work warns against the cost of indefinite staying. Sometimes you remain in a role long after it has stopped serving you, telling yourself you are being responsible, when in truth you are being afraid. The boat is at the dock. The card reversed is the gentle voice noting that boats are not meant to sit at docks forever. Pack carefully, say your goodbyes, and let the water carry you. The calm shore is still there. Trust the movement, even when the rowing is tiring.`,
    spiritLong: `The Six of Swords reversed spiritually marks a transition that has begun but not yet completed. You have left an old way of seeing the world — an old religion, an old framework, an old identity — but the new one has not yet arrived. You are in the boat, on the water, with neither shore visible. This is the bewildering part of spiritual change, and the card honours how disorienting it can be.

The reversal also shows the part of you that keeps reaching back for what you released. The certainty of the old belief system. The community you no longer belong to. The version of yourself that knew exactly what it thought about everything. These are not shameful things to miss; they are real losses. The card reversed asks you to grieve them honestly without rebuilding the structure you outgrew just to escape the discomfort of growth.

There is a quiet practice here. When the urge to row back arises, name it. Notice the homesickness. Then return your hands to the oars and keep moving. The Six of Swords reversed spiritually does not promise the new shore will be more comfortable than the old one — only that arriving fully requires you to keep going. Companions on the journey matter at this stage. Find people who have made similar crossings. Their presence will not make the water still, but it will remind you that the chop is normal and the far bank is real.`,
    reversedFaqs: [
      { q: 'What does Six of Swords reversed mean in love?', a: 'It often shows resistance to moving on — knowing a relationship is over but reaching back for it anyway, through texts, drive-bys, conversations with mutual friends that always circle to them. The card does not shame the reaching; it simply notes that each backward glance restarts the grief. Sometimes the reversal also shows a transition that is underway but rougher than expected, where the calmer waters have not yet arrived. Keep rowing. What you are hoping the past will give you — closure, an explanation, a clean ending — almost never comes from there. It forms slowly, inside, as you stop looking back.' },
      { q: 'Is Six of Swords reversed a bad sign?', a: 'Not exactly. It is more a warning about what is costing you than a prediction of harm. The upright Six is hopeful movement away from difficulty; reversed, the movement is stalled or being undermined by your own backward glances. The relief is delayed but not denied. Acknowledging the resistance is most of the work — you do not have to overcome it in a day, only stop pretending it is not happening. The card reversed honours how hard transition is. The far shore is still there. The journey will resume once you stop reaching for the dock.' },
      { q: 'What does Six of Swords reversed mean for communication?', a: 'It often points to communication that re-litigates what should be done — late-night texts to an ex, the message you draft and re-draft to the colleague you have moved past, the conversation with family about a decision you have already made. The reversal asks whether the communication is actually moving you forward or simply tethering you to what you left. Sometimes silence is the more honest message. When you do need to communicate during a transition, keep it brief, clear, and forward-facing rather than rehearsing the old grievances one more time.' },
      { q: 'How do I work with Six of Swords reversed in a reading?', a: 'Identify what you keep reaching back for and ask what you hope it will give you. Usually the answer is some form of resolution that the past is not going to provide. Then choose one small concrete action that points forward instead — book the new appointment, sign the new lease, send the polite no to the invitation that would have pulled you back. The card rewards repeated small motions toward the new shore more than dramatic gestures. Companions help. Find someone who has made a similar transition and let them remind you the crossing is normal.' },
    ],
  },

  'seven-of-swords': {
    loveLong: `The Seven of Swords reversed in love splits into two readings depending on which side of the deception you are on. For some, it is the moment of discovery — the realisation that something has been hidden, the receipt that does not match the story, the silence that finally cracks open. For others, it is the moment of coming clean — the confession you have been carrying, the truth you can no longer keep buried, the relief of finally being honest even though the consequences will be heavy.

If you are the one finding out, the reversed Seven asks you to slow your response by even a few hours before acting on the discovery. The instinct to confront in fury is understandable but rarely serves you. Gather information. Document what you need to. Talk to one trusted person outside the situation before you talk to the person inside it. The truth is now visible; it is not going anywhere, and you have time to choose how you want to handle it. Your dignity matters here.

If you are the one with the secret, the reversed Seven is the card finally pushing toward honesty. Whatever you have been hiding — the small lie that grew, the boundary you crossed, the truth about who you really are — is asking to come into the light. Disclosure will not be easy. It may end the relationship. But the energy required to keep maintaining the deception is also no longer sustainable, and the relationship as it currently exists is built on a foundation that cannot hold. Tell the truth. Let the consequences land. The card reversed honours both the cost and the necessity.`,
    careerLong: `The Seven of Swords reversed at work points to deception being uncovered — yours, a colleague's, a vendor's, an institution's. Documents come to light. The numbers do not match what was reported. The colleague who has been taking credit for your work is finally caught in a context that exposes them. The reversal often arrives with a kind of grim relief: at least now the situation is real rather than gaslit.

Handle the revelation carefully. The temptation to make a dramatic public reckoning is rarely strategic. Document everything in writing. Loop in the right people through the right channels. Let the institution do its work rather than appointing yourself the lone enforcer. The card reversed protects you when you proceed with integrity and patience; it punishes those who try to fight dishonesty with theatrics.

If you are the one who has been cutting corners, this reversal is a warning. The shortcut is about to be visible. The expense claim, the inflated metric, the credit you took that was not yours — whatever the specific form, it is on the verge of being exposed. Get ahead of it. Confess to the right person before they find out. The penalty for self-disclosure is almost always lighter than the penalty for being caught. The Seven of Swords reversed at work asks you to choose integrity now, while choosing is still cheaper than it will be in a week.`,
    spiritLong: `The Seven of Swords reversed spiritually is the return of conscience. A small dishonesty you have been carrying — a story you have told yourself about your own motives, a way you have been spinning your behaviour to keep liking yourself — is becoming impossible to maintain. The truth is rising, and your spirit is no longer willing to help you bury it.

This is uncomfortable but it is healthy work. The reversal often shows up after a long phase of self-justification, where you have been carefully constructing the version of events that lets you off the hook. That version is collapsing. The honest version is harder to live with but easier to grow from. The card asks you to sit with the truer story, even where it does not flatter you, and to do the small repairs it suggests.

Sometimes the Seven of Swords reversed spiritually also points to a teacher or tradition that has been less honest with you than you wanted to admit. You have known something was off for a while — the inconsistencies, the parts that did not add up, the dynamics that felt wrong — and you have looked away. The card reversed is asking you to look. This does not require you to denounce or destroy. It simply asks you to see clearly, name what is true to yourself, and act accordingly. Integrity here means not pretending you do not know what you know.`,
    reversedFaqs: [
      { q: 'What does Seven of Swords reversed mean in love?', a: 'It usually means deception is being uncovered or confessed. If you are the one discovering, the truth is becoming visible — receipts, inconsistencies, silences that crack open. If you are the one with the secret, the card pushes you toward honesty even though disclosure will be heavy. The reversal asks for slow, dignified responses rather than dramatic ones. Gather information, talk to a trusted person outside the situation, and choose how you want to handle the truth rather than reacting in fury. Whichever side you are on, the situation as it currently exists is no longer sustainable.' },
      { q: 'Is Seven of Swords reversed a bad sign?', a: 'It is mixed. Compared to the upright Seven, which is the phase where deception is actively operating, the reversal often brings genuine relief — the truth is coming out, the gaslighting is ending, the secret is no longer eating you. That said, the revelation itself can be painful, and the consequences are real. The card is not telling you the news will be pleasant; it is telling you the truth is becoming visible. In the longer run, that visibility is almost always better than another month of carefully maintained illusion.' },
      { q: 'What does Seven of Swords reversed mean for communication?', a: 'It points to honest conversations that have been postponed too long. The confession, the disclosure, the difficult update — these are knocking on the door. Communication at this stage works best when it is direct and unembellished. No long preambles, no elaborate justifications. Say what is true. If you are receiving someone else\'s confession, give yourself a beat before responding; your first reaction may not be the response you actually want to make. Document anything important. Avoid the urge to fight dishonesty with dramatic public exposure when private channels would serve better.' },
      { q: 'How do I work with Seven of Swords reversed in a reading?', a: 'Identify which side of the truth you are on. If you are uncovering, slow down by twenty-four hours before you act, and choose dignity over theatrics. Gather what you need. Decide what outcome you actually want before you confront. If you are concealing, choose disclosure before disclosure is chosen for you — the penalty for being caught is always heavier than the penalty for coming clean. The card rewards integrity exercised early. It punishes attempts to keep spinning the situation. Honest action now is cheaper than continued maintenance of an untenable position.' },
    ],
  },

  'eight-of-swords': {
    loveLong: `The Eight of Swords reversed in love is the moment you realise the prison was never locked. The dynamic you felt trapped in — the relationship you could not leave, the pattern you could not break, the partner you could not speak honestly with — turns out to have more give in it than you allowed yourself to see. The blindfold loosens. The ropes were always slack. The exit has been there the whole time.

This recognition is liberating and slightly humbling. You can see, in retrospect, how much of the trap was built by your own thinking. The story that you could not afford to leave, that you would not survive being alone, that nobody else would want you, that the relationship was as good as it gets — these are the threads that held the prison together. They were thoughts, not facts. The reversed Eight does not mock you for believing them; it simply notes that you are no longer obliged to.

If you are still inside the dynamic, the card reversed is the first crack of light. You do not have to know how to leave yet. You only have to stop pretending you cannot. From that small piece of honesty, the path forward becomes visible in stages. Talk to someone outside the situation. Look at the practical resources you actually have. Notice the friends you have been told not to see. The Eight of Swords reversed in love is the beginning of reclaiming your own agency. The fear may still be loud, but it no longer has the final word.`,
    careerLong: `The Eight of Swords reversed at work shows someone waking up to the fact that they have been trapping themselves in a role they were free to leave. The job is unbearable but you have been telling yourself you have no options. The reversal lifts the blindfold. You see the recruiter messages you never replied to. You remember the savings you actually have. You notice that the colleague who left last year is doing better than ever.

This is not always comfortable. There can be a flash of frustration at how long you stayed in the cage, or grief for the years you spent inside a situation you could have changed earlier. Be kind to that earlier version of you. The reasons for staying were real at the time — they just turned out to be smaller obstacles than the story made them.

The card reversed at work invites a clear-eyed inventory. What are the actual constraints? What are the imagined ones? What is one concrete action you could take this week that would not have seemed possible last month? Often the path out is not a dramatic resignation but a series of small steps that reveal the door has been ajar for some time. Update the document. Have the exploratory conversation. Apply for the thing. The Eight of Swords reversed rewards small, brave, practical motions. You are not as stuck as you have been telling yourself, and the proof comes through doing rather than thinking.`,
    spiritLong: `The Eight of Swords reversed spiritually is the moment a belief that has bound you for years reveals itself as a belief — not a law of nature, not a fact about reality, just a thought you have practised so many times it began to feel like the world itself. You can see it now. The recognition alone changes everything.

The card reversed often arrives at the threshold of a significant inner shift. You have been doing the work — therapy, journalling, contemplation, reading, conversations with people you trust — and the patterns that ran your life are starting to lose their grip. The shame story. The unworthiness story. The you-have-to-earn-love story. They were never the truth; they were inherited or installed in younger moments when you had no choice but to take them in. Now you have the choice. The card reversed offers the door.

Walking through is the work of months, not minutes. The old beliefs will reassert themselves — at three in the morning, in moments of stress, in the presence of certain people. That is not failure. The Eight of Swords reversed spiritually does not promise the cage door slams shut behind you forever; it promises you can now see that the cage was always made of thought, and you can leave it again each time you find yourself back inside. The freedom is a practice, not a single event. Begin it gently and keep beginning.`,
    reversedFaqs: [
      { q: 'What does Eight of Swords reversed mean in love?', a: 'It usually means recognising that a relational trap you felt powerless inside has more give in it than you let yourself see. The blindfold is loosening. You notice options, supports, and exits that were always there. This can be liberating and slightly humbling — you see how much of the cage was built from your own thinking. The card does not mock you for believing the limits; it simply hands back your agency. You may not know how to act yet, but you no longer have to pretend you cannot. That first honest acknowledgement is most of the work.' },
      { q: 'Is Eight of Swords reversed a bad sign?', a: 'No, it is one of the more genuinely liberating reversals in the deck. The upright Eight is the experience of feeling trapped; reversed, the trap reveals itself as largely self-imposed and therefore movable. There may be discomfort in seeing how long you stayed bound by something you could have questioned earlier, but the underlying movement is from imprisonment toward freedom. Treat the card as encouragement. The path forward is becoming visible. You only need to take it in steps you can actually walk, not in one dramatic leap.' },
      { q: 'What does Eight of Swords reversed mean for communication?', a: 'It often shows someone finally saying the thing they have been telling themselves they cannot say — the boundary, the truthful no, the request for help, the disclosure of how bad things have actually been. Communication at this stage works best when it is simple and direct. The story you told yourself about why you could not speak was usually more elaborate than the truth requires. Short sentences. Specific requests. Trust that the people who matter will receive what you say better than the imagined audience in your head ever let you believe.' },
      { q: 'How do I work with Eight of Swords reversed in a reading?', a: 'Make a list of the things you have been telling yourself you cannot do, and test each one against actual reality rather than imagined consequence. Often three of the five turn out to be more available than the story claimed. Choose one concrete action you would not have taken a month ago and take it this week — a phone call, an application, a conversation, a search. The card rewards small motions that test the supposed limits. Each one that holds is information; each one that gives is freedom. Be patient with yourself. The cage took years to build.' },
    ],
  },

  'nine-of-swords': {
    loveLong: `The Nine of Swords reversed in love is the dawn after the longest night. The anxiety that has tormented you about a relationship — the catastrophising at three in the morning, the worst-case imagining, the conviction that you are about to be left or have already done something unforgivable — is beginning to ease its grip. You are not yet on solid ground, but the worst of the spiralling has passed.

For most readers, this is genuinely good news. The dark night was real, and you survived it. The reversal asks you now to keep tending to your nervous system rather than testing it. Be careful with caffeine, sleep, alcohol, and the kind of late-night phone scrolling that feeds rumination. Talk to someone who can hold what you are carrying. The anxiety did not invent itself; if there are real concerns in the relationship, address them in daylight with support around you. They are almost always less catastrophic than the night-time version made them.

There is, more rarely, a harder reading: anxiety that is worsening rather than lifting, and that needs more help than the card alone can give. If your sleep has been wrecked for weeks, if intrusive thoughts are constant, if the fear is no longer in proportion to anything happening, please speak to a professional. The Nine of Swords reversed in love does not stigmatise that step — it gently points toward it. Healing the mind is its own act of love, and you do not need to do it alone. The card holds both readings with care.`,
    careerLong: `The Nine of Swords reversed at work usually marks the easing of a long mental burden — the imposter syndrome that crushed you for months, the dread before every Monday, the certainty that you were about to be found out or fired. Something has shifted. The fears were largely catastrophic, and reality has begun to disprove them one ordinary day at a time.

This reversal asks you to consolidate the recovery rather than test it. Do not immediately overcommit to prove you are fine. The mind that was spinning needs gentler work for a while — fewer late nights, fewer stimulants, fewer high-stakes decisions made in the small hours. Sleep matters now more than productivity. Boring competence is the medicine; you do not have to be brilliant for the next few weeks. You only have to be steady.

The harder reading: anxiety at work that is worsening rather than lifting and that genuinely needs intervention beyond the card. Burnout, depression, and chronic overwhelm are real medical events, not character flaws. If the dread is constant, if you cannot sleep, if you have lost the ability to enjoy anything outside work, please get help — from a GP, a therapist, an employee assistance programme, a trusted friend. The Nine of Swords reversed in career does not romanticise suffering. The dark night is not a badge. Walking out of it, with whatever support you need, is the brave work. Begin today.`,
    spiritLong: `The Nine of Swords reversed spiritually marks the slow ending of the dark night of the soul. The phase where every prayer felt hollow, every practice felt false, every reach for meaning came back empty — that phase is loosening. You may not yet feel restored faith, but the despair is not the entire weather any more. There are minutes, then hours, then sometimes whole days when something gentler is possible.

Honour this with care. The card reversed warns against rushing to declare yourself healed or to leap immediately back into ambitious practice. The mind that has been through the dark night is tender. What it needs now is rest, kindness, and small reliable rituals rather than dramatic spiritual exertion. A short walk. A few minutes of breath. A cup of tea taken slowly. These are not concessions — they are the actual practice for this stage.

The dark night, when it ends, leaves gifts you may not yet have recognised. A softer relationship with other people\'s suffering. A lower tolerance for spiritual performance. A truer sense of what matters and what does not. The Nine of Swords reversed spiritually invites you to let these gifts settle without rushing to articulate them. If you are still in the night, take this card as a quiet promise: it does end. People come through. The morning is not a trick. Keep going gently. You are closer than the night is letting you feel.`,
    reversedFaqs: [
      { q: 'What does Nine of Swords reversed mean in love?', a: 'It usually means anxiety about a relationship is beginning to lift. The three-in-the-morning catastrophising is loosening its grip and reality is starting to look less terrifying than the night-time version claimed. The card asks you now to be careful with your nervous system — sleep, caffeine, late-night phone scrolling all matter. Talk to someone you trust about what you have been carrying. If there are real concerns in the relationship, address them in daylight with support around you. They are almost always smaller than the spiral made them feel. The dawn is genuinely arriving.' },
      { q: 'Is Nine of Swords reversed a bad sign?', a: 'No — it is one of the most genuinely hopeful reversals in the deck. The upright Nine is the depth of mental anguish; reversed, the worst of it is passing. You are coming out of the dark night rather than deeper into it. There is a rarer harder reading where anxiety is worsening and professional help is needed, and the card gently supports that step too. Either way, the message is fundamentally compassionate. You are not alone in the dark, and you are not stuck in it. Keep going gently. Help is available and worth reaching for.' },
      { q: 'What does Nine of Swords reversed mean for communication?', a: 'It often shows the moment you finally tell someone how bad it has been — the friend you call, the therapist you book, the partner you let in on what you have been carrying alone. Communication at this stage works best when it does not require you to have it all figured out. You can simply say it has been hard. You do not have to perform recovery or have a plan. The card rewards reaching out before you feel ready to. The right people will meet you where you are, and the speaking itself is part of the relief.' },
      { q: 'How do I work with Nine of Swords reversed in a reading?', a: 'Treat your nervous system as the priority. Sleep, hydration, daylight, movement, contact with people who love you — boring fundamentals first. Resist the urge to make any high-stakes decisions at night; whatever feels urgent at three in the morning will look smaller at ten. If the anxiety is not lifting, please speak to a professional — the card supports that step rather than stigmatising it. Keep your commitments small for a while. You do not need to prove you are healed. Steadiness now is more valuable than performance.' },
    ],
  },

  'ten-of-swords': {
    loveLong: `The Ten of Swords reversed in love is delicate territory. Sometimes it shows slow recovery from a relationship ending that has already happened — the worst is genuinely behind you, dawn is breaking in the background of the card, and life is gradually returning. The pain is no longer fresh. You can think about what was lost without being completely undone by it.

The other reading is harder. Sometimes the reversed Ten shows refusal to acknowledge what is clearly over. The relationship has ended in every meaningful way — the connection, the trust, the future — and yet you are still treating it as ongoing, still hoping for a return that the situation will not give you. The card reversed asks gently whether you are recovering or whether you are holding the body of something that has already left. Both can feel similar from inside. The difference matters.

Be honest with yourself about which version you are in. If you are recovering, the work is patience and tending: let the dawn come at its own pace, accept help, do not test yourself prematurely with reminders of the loss. If you are denying, the work is harder but kinder in the long run: let yourself name that it is over, let the grief actually begin rather than postpone it indefinitely, let the next chapter become possible. The Ten of Swords reversed in love does not condemn either response. It simply asks you to know which one is yours, and to act with the honesty the moment requires.`,
    careerLong: `The Ten of Swords reversed at work usually marks slow recovery from a professional collapse — a redundancy, a failed venture, a public mistake, a betrayal by someone you trusted. The crisis itself is behind you. The integration is the work now. You may still feel raw, still rehearse what happened, still wonder if your reputation will recover — and all of that is normal at this stage. The dawn is real even when you cannot yet feel its warmth.

Take the recovery seriously. The temptation to rush back to full capacity — to prove you are unbroken, to outrun the story by working twice as hard at the next thing — almost always recreates the conditions that broke you. Slow is the speed that lasts. Choose your next move from a place of recovered ground rather than from the urge to escape what just happened. The right opportunity will wait for you to be ready for it.

The harder reading: refusing to acknowledge that something is genuinely over. The role you have been clinging to. The project everyone else has stopped believing in. The professional identity that is no longer accurate to what you actually do or want. The Ten of Swords reversed at work asks whether you are recovering from an ending or postponing one. If it is the latter, the kindest thing you can do for yourself is to let the ending be real. The new chapter cannot start while you are still standing in the ruins of the old one pretending the roof is intact.`,
    spiritLong: `The Ten of Swords reversed spiritually is the slow dawn after the death of an old self. Something major has ended — a belief system, an identity, a way of being in the world — and you are in the tender phase where the old structure is gone and the new one has not yet formed. The card reversed honours this in-between. It is not failure. It is the necessary fallow ground.

This stage cannot be rushed. The instinct to immediately construct a new spiritual identity — a new framework, a new label, a new certainty — is the ego trying to plug the hole the old one left. The card reversed asks you to leave the hole open for a while. Let the not-knowing teach you. The wisdom that forms in this empty space is more trustworthy than anything you could rebuild from urgency or fear.

The harder reading appears too: refusing to let an old spiritual identity die when it has clearly stopped serving. You know the practice is hollow now. You know you do not believe what you used to believe. And yet you keep performing the old shape because the alternative — admitting it — feels like betraying who you were. The Ten of Swords reversed spiritually gently invites the admission. The death you are postponing is not avoidable, only delayable, and delay does not honour the past version of you. Living the next true version does. Let the old self lie down. Watch the sun come up. The new way is forming in the silence underneath.`,
    reversedFaqs: [
      { q: 'What does Ten of Swords reversed mean in love?', a: 'It usually shows slow recovery from a relationship ending that has already happened — the worst is behind you, even if you cannot yet feel that fully. Dawn is breaking; pain is no longer fresh. The other reading is harder: refusal to acknowledge what is clearly over, clinging to a relationship that has effectively ended. Be honest about which version you are in. If recovering, be patient and tender with yourself. If denying, the kinder long-term work is to let the ending be real so a next chapter can begin. The card honours both with care.' },
      { q: 'Is Ten of Swords reversed a bad sign?', a: 'It is one of the most genuinely hopeful reversals when read accurately. The upright Ten is rock bottom; reversed, you are past the worst and rising. The crisis is done. Recovery is happening, even slowly. The sun in the corner of the card is becoming the whole sky. The harder reading is about postponing an ending that needs to be acknowledged, and even then the card is fundamentally pointing toward eventual freedom rather than continued harm. Treat it as a profoundly compassionate card. You have survived the worst. The next chapter is real and approaching.' },
      { q: 'What does Ten of Swords reversed mean for communication?', a: 'It often shows the quiet, honest conversations after a major ending — the explanations to family, the goodbye notes, the careful catch-ups with friends who have not seen you since it happened. Communication at this stage works best when it does not pretend the loss did not occur. You do not have to perform recovery. Simply naming what happened, in plain words, is enough. If you are postponing an ending, the harder communication is with yourself first and the other person second. Begin with the truth told privately, then bring it gently into the world when you are ready.' },
      { q: 'How do I work with Ten of Swords reversed in a reading?', a: 'Treat yourself like someone recovering from something significant, because you are. Sleep, food, daylight, gentle company. Resist the urge to immediately prove you are fine. Choose your next move slowly, from rested ground rather than from the desire to outrun what happened. If you are postponing an ending, name it honestly to one trusted person this week — naming is most of the work. The card rewards small, steady acts of integration over dramatic rebuilding. The dawn is not a test. Let yourself simply arrive into it without earning the right to.' },
    ],
  },

  'page-of-swords': {
    loveLong: `The Page of Swords reversed in love often shows immature communication patterns surfacing in a connection. Gossip about your relationship reaching you through third parties. Half-formed accusations sent in late-night texts. The sharp comment dressed up as a joke. The reversed Page is the energy of someone — possibly you, possibly the person you are with — who is using words as weapons before they have learned to use them as bridges.

This is not a verdict on the relationship. It is information about how words are being deployed in it right now. The card reversed asks for a step back from the keyboard. Voice notes lose the tone that texts erase. Conversations held in person allow for the small clarifications that prevent escalation. If you have been firing off cutting messages and regretting them, the reversal is the gentle prompt to slow down. If someone is doing this to you, the card supports naming the pattern directly rather than absorbing each cut and pretending it did not land.

The Page of Swords reversed in love also points to chronic suspicion that is corroding a connection. The phone-checking. The interrogation disguised as casual conversation. The cynicism that assumes the worst before evidence arrives. Curiosity is the upright gift of the Page; reversed, it has turned into surveillance. Notice the difference. Real questions are open; weaponised questions are traps. If you are setting traps, you already know the answer you want — work out what you actually need from the conversation and ask for that directly instead.`,
    careerLong: `The Page of Swords reversed at work shows scattered thinking, hasty communication, and information being handled carelessly. Drafts sent before they were ready. Confidential details mentioned in the wrong meeting. Messages to colleagues that came across sharper than intended because they were typed quickly between other tasks. The reversal asks for slower, more deliberate handling of words at work.

This card can also point to gossip — being part of it, being the subject of it, or working in a culture where it has become a substitute for direct communication. The Page of Swords reversed has the energy of the office Slack channel that runs hot with speculation about who is leaving, who is in trouble, who is being talked about by whom. None of this is harmless. Step away from the side conversations and toward the direct ones. If you have a real concern, take it to the person who can address it.

For early-career readers, the reversed Page can show a phase of learning hard lessons about professional communication. The angry email you regret sending. The cynical comment that reached the wrong ear. The intelligence you displayed that came across as arrogance. These are common, recoverable mistakes — the card reversed treats them as growing pains rather than fatal flaws. Slow your responses. Read messages twice before you send. Ask before assuming. The Page of Swords reversed at work rewards thoughtfulness over speed, every single time.`,
    spiritLong: `The Page of Swords reversed spiritually is the seeker whose questions have soured into cynicism. The intellectual curiosity that once opened doors is now closing them — every tradition gets debunked before it can be experienced, every teacher gets dismissed before they can teach, every practice gets analysed before it can change you. The mind that was meant to be a tool of discovery has become a wall against it.

This is a common phase, especially for those who came to spirituality through scepticism and read their way in. The card reversed does not ask you to abandon discernment — it asks you to remember that discernment includes the willingness to be wrong about your own assumptions. Some truths only arrive after you have stopped requiring them to prove themselves on your terms. The Page upright is the curious learner; reversed, the learner has forgotten that learning requires not-yet-knowing.

The reversal also points to spiritual gossip — the habit of talking about other people\'s practice, other people\'s teachers, other people\'s paths, instead of attending to your own. Online spiritual culture is particularly susceptible to this. Notice when you are doing it. The Page of Swords reversed spiritually invites a return to your own quiet practice without the running commentary about everyone else\'s. The work is harder when you stop performing it. That harder work is the real work.`,
    reversedFaqs: [
      { q: 'What does Page of Swords reversed mean in love?', a: 'It typically points to immature communication patterns — gossip reaching you about your relationship, sharp messages sent in haste, comments dressed as jokes that land like cuts. It can also show chronic suspicion that has turned curiosity into surveillance. The card reversed asks for a step back from the keyboard and into slower, more honest forms of communication. Voice notes over texts. In-person conversations over written ones. If someone is using words against you, naming the pattern directly is more effective than absorbing each cut. If you are doing it, the card is asking you to stop.' },
      { q: 'Is Page of Swords reversed a bad sign?', a: 'It is more a warning than a doom. The reversal points to specific behaviours — gossip, hasty words, cynicism, scattered thinking — that can be corrected once you see them clearly. None of these are character verdicts. The Page is young energy by definition; reversed, the youth shows as immaturity rather than freshness. The work is straightforward even when it is uncomfortable: slow down, speak more carefully, stop the side conversations, do not assume the worst before evidence arrives. The card rewards thoughtful course correction. There is plenty of time to grow into the upright version of this energy.' },
      { q: 'What does Page of Swords reversed mean for communication?', a: 'Communication is the whole heart of this card, and reversed it is where the trouble lives. Expect typos, tone misreadings, half-formed messages, and conversations that escalate because nobody slowed down enough to clarify. The card reversed warns against responding quickly, especially when emotions are involved. Read drafts twice. Ask what you actually mean before you press send. If you are receiving sharp communication, do not match the energy — slow your reply, request a clearer conversation, or move to a different channel. Words matter, and the reversal is a reminder to handle them with more care than the moment is asking for.' },
      { q: 'How do I work with Page of Swords reversed in a reading?', a: 'Identify the specific communication pattern the card is pointing to — gossip, hasty replies, cynicism, scattered focus — and choose one to address this week. Practical steps: introduce a twenty-four-hour delay on emotional emails before sending. Step out of one side conversation that has been running in your life. Replace one piece of cynicism with a genuine question. The card rewards small, repeated corrections more than grand gestures. Treat yourself as someone learning a craft — because communication is one, and the Page is exactly the energy of someone still learning it.' },
    ],
  },

  'knight-of-swords': {
    loveLong: `The Knight of Swords reversed in love shows the energy of someone — possibly you, possibly the person across from you — charging into a relationship with more speed than care. Sudden declarations. Big promises made early. Fights picked at the slightest provocation. Messages fired off in volleys when one careful sentence would have served better. The Knight reversed is the cavalry without a map, and the romance is the field it is currently galloping across.

This is exhausting on both sides. If you are the Knight, you may be confusing intensity with intimacy, mistaking the rush of the chase for the depth of connection. Slow down. Ask the person you are pursuing what pace they actually want. Notice when you are escalating because the situation feels boring rather than because the moment requires it. If you are on the receiving end of this energy, the card reversed gives you permission to ask for less velocity. You do not have to keep up. The right person will adjust their stride to walk with you rather than expecting you to sprint at theirs.

The Knight of Swords reversed in love also points to argument as default mode. Every conversation becomes a battle to be won. Every difference becomes a debate. The relationship starts to feel like a courtroom rather than a home. If this dynamic has set in, the card asks you to lay down the sword first, regardless of who picked it up. Listening is not losing. Curiosity is not weakness. A relationship that survives requires both partners to occasionally stop trying to be right, and the Knight reversed is the gentle nudge to be the first to do that.`,
    careerLong: `The Knight of Swords reversed at work is the colleague who replies in three minutes when twenty-four hours would have served everyone better — possibly you. Reactive emails. Half-thought-through pitches. Big strategic pronouncements made before the data has arrived. The reversal is the warning that speed has become a substitute for thought, and the cost is showing up in the work.

This card reversed also points to argumentative communication that has drifted into something corrosive. Meetings where everyone leaves bruised. Threads that escalate because someone could not let a small point go. The brilliant person whose intellect has stopped serving the team because it is now being deployed primarily to win. The Knight upright is decisive; reversed, the decisiveness has tipped into attack. Notice this in yourself if you find people going quiet around you in conversations they used to engage in.

Slow your responses. Build a habit of writing the angry reply and then deleting it. Ask whether the point you are about to make is genuinely useful or simply correct. The Knight of Swords reversed at work asks you to trade some velocity for credibility. The colleague who responds slowly and carefully is trusted in a way the colleague who responds instantly and sharply will never be. If you are leading a team, model this. Reactive cultures hire reactive teams, and the rework cost is enormous. Strategic patience is a competitive advantage in a world that rewards haste.`,
    spiritLong: `The Knight of Swords reversed spiritually shows the practitioner whose seeking has become a charge — collecting practices, jumping between traditions, racing toward enlightenment as though it were a finish line. The reversal asks for the dismount. The horse needs water. The road is longer than the urgency suggested.

This energy often shows up in the spiritual life of high-achieving people. The same drive that won the career is now being applied to the inner work, with the same impatience and the same insistence on visible results. It does not work in the same way. Awakening is not a deliverable. Compassion does not respond to deadlines. The card reversed invites you to put down the timeline and accept that some things ripen on their own clock, not yours.

The reversal also points to spiritual argument — the energy that wants to debate every teacher, refute every framework, win every conversation about consciousness. There is a place for sharp questioning. The Knight reversed simply points out that you have crossed from questioning into combat, and combat does not produce wisdom. Sit with the practices that frustrate you most before dismissing them. Ask what your insistence on disproving them might be protecting you from. The Knight of Swords reversed spiritually is the moment the swordsman realises he cannot stab his way to peace. Lay the weapon down. Let the slower path begin.`,
    reversedFaqs: [
      { q: 'What does Knight of Swords reversed mean in love?', a: 'It shows someone charging into a relationship with more speed than care — big declarations early, fights picked easily, messages fired off in volleys. If you are the Knight, the reversal asks you to slow your pace and check whether you are confusing intensity with intimacy. If you are on the receiving end, you have permission to request less velocity without apologising for it. The card also points to argumentative dynamics where every conversation becomes a battle to win. Laying down the sword first, regardless of who picked it up, is the move the card is gently asking for.' },
      { q: 'Is Knight of Swords reversed a bad sign?', a: 'It is a warning more than a verdict, and the warning is actionable. The reversal points to specific behaviours — haste, recklessness, argument as default — that can be moderated once you see them. Often the relief in this card comes from finally noticing the speed itself rather than being swept along by it. Slowing down is almost always recoverable; the dynamic is not fatally broken, just running too hot. Treat the card as a request from the situation to lower the temperature. The Knight is good energy when it is harnessed; reversed, it just needs reins.' },
      { q: 'What does Knight of Swords reversed mean for communication?', a: 'It warns against reactive, sharp, or escalatory communication. Reply speed is not a virtue when the message you are responding to triggered you. Build a delay into emotional replies — twenty-four hours for written ones, at least a few hours for spoken. Ask whether what you are about to say is useful or simply true and forceful. If the person you are communicating with is the Knight reversed, you do not have to match their pace. A calm short reply often defuses the energy faster than meeting it on its own terms. Slowness is its own kind of competence.' },
      { q: 'How do I work with Knight of Swords reversed in a reading?', a: 'Identify the place in your life where you have been moving too fast or too sharply and slow it deliberately this week. Cancel one urgent reply. Let one disagreement go without responding. Ask for a longer timeline on one decision. The card rewards reclaimed pace. Practical practices: write angry replies and then delete them; speak the difficult sentence aloud before you send it; ask one clarifying question before assuming the worst. Treat your nervous system as the resource the Knight reversed is depleting. Slow down to protect it.' },
    ],
  },

  'queen-of-swords': {
    loveLong: `The Queen of Swords reversed in love shows what happens when a brilliant, discerning woman has been disappointed too many times and has hardened around the wound. The clarity that was once a gift has become a blade she carries pointed outward at all times. Every potential connection gets vetted with the same suspicion. Every honest moment gets met with a sharper one back. The reversal honours how this defence got built — usually for very good reasons — while gently asking whether it is still serving.

Bitterness is the central note here. The Queen reversed can be the woman who has decided love is for fools, dating is theatre, and men, women, or whichever flavour of partner she has stopped trusting are not worth the risk. Some of her conclusions are accurate. Others are her old pain pretending to be wisdom. The card reversed asks her to know the difference. Real discernment stays open to evidence that contradicts the story; armoured cynicism does not.

There is also the matter of oversharing — telling the difficult truth in places that did not earn it, weaponising honesty in casual conversations, processing personal wounds with strangers as though everyone in the room needs to know. The Queen upright tells truth precisely; reversed, the truth-telling has become indiscriminate. Reserve the deep honesty for the few people who can hold it. Let smaller talk be small. The Queen of Swords reversed in love invites a return to the clarity that includes warmth — and the recognition that being right about love is no consolation for being alone in it when you did not want to be.`,
    careerLong: `The Queen of Swords reversed at work is the leader whose clarity has curdled into harshness. The feedback that used to be useful is now humiliating. The directness that used to clear meetings has started ending careers. The high standards that built the team are now driving the best people out of it. The reversal asks her to notice that the same sharpness which made her great is now making her dangerous, and to soften it before the cost becomes irrecoverable.

This card reversed also shows the brilliant woman who has gone cold — emotionally unavailable to her own team, unreachable for the small human conversations that grease a workplace, present only when there is a problem and absent the rest of the time. People become afraid to bring her good news or bad news in case she finds fault with either. The reversal does not ask her to perform warmth she does not feel; it asks her to remember that leadership requires more than competence, and that her team needs the human being underneath the executive.

If you have been on the receiving end of a reversed Queen at work, the card supports clear-eyed self-protection. Document the harsh feedback in writing. Build allies who can vouch for what you actually contribute. Do not internalise the contempt as truth — it is her wound, not your worth. The Queen of Swords reversed at work is solvable, but only by her, and only when she is willing to see what the armour has cost. The intelligence is still there. It just needs to remember whom it was meant to serve.`,
    spiritLong: `The Queen of Swords reversed spiritually is the practitioner whose hard-won wisdom has begun to wall her off from further growth. She has earned the right to her cynicism — life has taught her things, and she is not wrong about most of them. But the lessons have hardened into a fortress, and now nothing new can enter. The card reversed asks whether the protection has outlived the threat it was built for.

This card often shows up in spiritual contexts where someone has been burned by a teacher, a community, or a tradition, and now armours against all such structures permanently. The discernment is real and earned. The reversal simply notes that armour, when worn too long, becomes its own prison. The next layer of growth may require a vulnerability you have sworn off — joining a group again, trusting a teacher again, letting someone close to your inner life again, on your own informed terms.

The reversed Queen also speaks to intellectual spirituality that has lost contact with the heart. The frameworks are immaculate. The reading list is impressive. The capacity for analysis is sharp. And underneath, something feels arid — the practice has become a museum of insights rather than a living relationship with the sacred. The card reversed gently asks you to put the books down for a while. Sit somewhere quiet without analysing what you experience. Let the mind serve the soul rather than substitute for it. The Queen of Swords reversed spiritually wants her warmth back. It is still there, beneath the careful edges.`,
    reversedFaqs: [
      { q: 'What does Queen of Swords reversed mean in love?', a: 'It usually shows brilliant discernment that has hardened into bitterness — defences built for good reasons that have outlived their usefulness. Every potential connection gets vetted with the same suspicion; every honest moment gets met with a sharper one back. The card asks her to know the difference between real discernment and armoured cynicism. Real discernment stays open to contradicting evidence. The reversal also warns against oversharing — using indiscriminate honesty in contexts that did not earn it. Reserve depth for the few who can hold it. The clarity is still a gift; it just needs warmth to soften the edge.' },
      { q: 'Is Queen of Swords reversed a bad sign?', a: 'It is a warning rather than a verdict, and the warning is loving once you see it. The reversal points to bitterness, isolation, and harsh judgement — patterns that are correctable. The Queen has been hurt and has armoured; the card simply asks her to notice the armour is now keeping new good things out alongside the old bad ones. Compared to upright, the reversal can feel uncomfortable to receive, but it is a generous diagnosis. The remedy is within her own choices. Wisdom plus warmth restores her; wisdom alone has been narrowing her.' },
      { q: 'What does Queen of Swords reversed mean for communication?', a: 'It warns against truth-telling that lands as contempt rather than clarity. The Queen upright says hard things in ways that respect the listener; reversed, she says them in ways that flatten the listener. Slow down. Ask whether the sharp comment is necessary or simply available. Use direct messages for direct people and keep the deeper truths for relationships strong enough to hold them. The card also flags oversharing — processing personal wounds with strangers or in professional settings. Reserve depth for the right rooms. Smaller talk has its own value and does not need to be diagnosed.' },
      { q: 'How do I work with Queen of Swords reversed in a reading?', a: 'Notice where you have been carrying the sword pointed outward for so long that you have forgotten you are holding it. Choose one relationship where the armour is heavier than the situation requires and soften by one degree this week. Practical practices: ask one question instead of making one statement; receive one compliment without batting it away; offer one piece of warmth alongside one piece of feedback. The card rewards the return of texture rather than the abandonment of standards. Stay sharp. Get warmer. Both are possible at once and you have done both before.' },
    ],
  },

  'king-of-swords': {
    loveLong: `The King of Swords reversed in love shows the cold judge — the partner who has stopped meeting his lover as a human being and has started cross-examining her as though every conversation were a deposition. The intellect is intact. The fairness has gone. Arguments are won by precision rather than resolved by care, and the relationship has begun to feel less like a refuge than a courtroom. The reversal asks him to put down the gavel.

This card reversed can also indicate weaponised intellect — the partner who uses his greater command of language, logic, or information to dominate disagreements that should have been collaborative. The other person leaves every conversation feeling smaller. They start choosing their words around him rather than with him. They stop bringing things up because the cost of being verbally outmanoeuvred has grown too high. None of this is love, and the King reversed is being asked to see what his sharpness has done to the person he says he cares for.

There is sometimes also the dimension of cold withholding — affection rationed, warmth carefully measured, emotional generosity treated as a resource to be deployed strategically. The reversal does not ask the King to become someone he is not; it asks him to stop using the parts he is good at as a substitute for the parts he has not developed. Honesty without warmth is interrogation. Authority without tenderness is rule. The King of Swords reversed in love is being invited to remember that the people he loves are not subjects to be governed, and that softness is not weakness.`,
    careerLong: `The King of Swords reversed at work is the leader whose authority has tipped into tyranny — possibly subtly, possibly grossly. The fairness that made him trustworthy has been replaced by ruthlessness. Decisions are made unilaterally where consultation used to happen. Dissent is treated as disloyalty. Performance reviews have started to read as character assessments. The team has become quieter, more careful, less creative — and he tells himself this is discipline rather than fear.

This reversal also covers more sophisticated forms of misuse: the executive who uses superior information asymmetrically to win negotiations he should not have been having alone, the partner who codes manipulation as strategy, the leader who knows the right words for ethical behaviour but uses them to provide cover for something else. The card reversed at work is unflinching about all of these. Power without integrity is its central concern.

If you are on the receiving end of a reversed King at work, the card supports careful, documented self-protection rather than direct confrontation. Build allies. Keep records. Find external mentors who can sanity-check what you are experiencing. The cold judgement of a reversed King can be deeply destabilising; you are not imagining it, and you are not the problem. If you are the King — or recognise the energy in yourself — the card is asking you to remember that authority is borrowed from those you serve, not owed to those who fear you. Lead through respect, not through cold. The work is worth doing.`,
    spiritLong: `The King of Swords reversed spiritually is the mind that has appointed itself the arbiter of the sacred. Every teaching gets weighed and found wanting. Every teacher gets analysed and dismissed. Every practice gets evaluated for its logical coherence before it is allowed near the heart. The intellect that was meant to serve the soul has put itself in charge of it, and the soul has gone quiet in protest.

This is a particularly tempting reversal for highly educated readers. The same sharp mind that excels at law, science, or strategy can build an immaculate intellectual cathedral that has no living God inside it. The card reversed does not ask you to abandon discernment — discernment is precisely the King\'s genuine gift. It asks you to recognise that some truths only become available to a mind that has briefly stopped insisting on its supremacy. Surrender is a competence, not a defeat. The wisest people you have ever met knew how to put their cleverness down at the threshold of the temple and walk in without it.

There is also the matter of cold judgement turned inward. The King reversed spiritually can be relentlessly hard on himself — auditing every spiritual experience for evidence of self-deception, refusing the comfort of unearned grace, treating his own inner life with the same cross-examining rigour he applies to his work. The card asks for mercy. The same compassion he might extend to a friend struggling on the path deserves to be turned on his own striving self. Let the king kneel. Let the mind serve. The throne is not where the truth lives.`,
    reversedFaqs: [
      { q: 'What does King of Swords reversed mean in love?', a: 'It shows the partner whose intellect has tipped into cold judgement — winning arguments by precision rather than resolving them with care, using superior command of language or logic to dominate conversations that should have been collaborative. The reversal also covers cold withholding, where affection is rationed and warmth measured. The card asks him to remember that the people he loves are not subjects to be governed. Honesty without warmth is interrogation. Authority without tenderness is rule. The work is reclaiming the parts of himself he has been hiding behind his sharpness — softness is not weakness, and the relationship requires both.' },
      { q: 'Is King of Swords reversed a bad sign?', a: 'It is more serious than most reversals in this suit and worth reading carefully. The card points to the misuse of power — intellectual, emotional, structural — and that is genuine information. If you recognise yourself in the reversed King, the card is asking for honest course correction; the remedy is within your reach. If you are on the receiving end, the card supports clear-eyed self-protection rather than dismissal of what you are experiencing. The harshness is real, the cold is real, and you are not the problem. Both readings are recoverable, but neither resolves through pretending the dynamic is normal.' },
      { q: 'What does King of Swords reversed mean for communication?', a: 'It warns against communication that wins rather than connects — surgical, precise, devastating, and ultimately corrosive. Notice when your sharpness is serving the conversation versus when it is serving your need to be right. Slow your replies. Ask one genuine question for every two statements you make. If you are receiving this energy, you do not have to outdebate it; calmly naming the pattern is often more effective than matching it. The card is not asking you to dim your intelligence. It is asking you to use it to understand rather than to dominate. Same tool, different aim.' },
      { q: 'How do I work with King of Swords reversed in a reading?', a: 'If the energy is yours, identify one relationship — personal or professional — where you have been governing rather than relating, and soften by one specific behaviour this week. Listen for ten minutes without rebuttal. Concede a small point you would normally have contested. Offer warmth where you would normally have offered analysis. If the energy is in someone else, build allies and documentation, find external mentors who can sanity-check the dynamic, and protect your nervous system. The card rewards reclaimed humanity on both sides. Authority without warmth ages badly; the King has time to become the leader he was meant to be.' },
    ],
  },
}
