import type { ReversedContext } from '../card-reversed-extended'

export const WANDS: Record<string, ReversedContext> = {
  'ace-of-wands': {
    loveLong: `The Ace of Wands reversed in love is the moment when the spark refuses to catch. You feel the heat of attraction or the outline of a fresh romantic chapter, yet something keeps stalling the strike — hesitation on one side, mismatched timing on the other, or a chemistry that looks brilliant on paper but never quite combusts in person. If you are single, you may be flirting, swiping and almost-meeting without anything truly igniting. If you are partnered, the once-electric current between you has dimmed and intimacy now requires deliberate kindling rather than arriving on its own.

The honest question this card asks is whether the desire is genuine or merely the idea of desire. Sometimes the spark hesitates because you are trying to force a connection your body has already declined. Other times it stalls because fear of disappointment is making you keep one foot out of the door. Notice which it is. A real flame can survive a slow start; a counterfeit one cannot survive your full attention.

Practical guidance: stop performing passion and return to what genuinely lights you up. Honour your own appetite — for play, beauty, touch, laughter — outside the relationship first, and the romantic fire will have something to catch on. If the connection is right, the Ace reversed simply asks for patience and better timing. If it is wrong, this card is the merciful sign-off before you invest any further.`,
    careerLong: `The Ace of Wands reversed in career describes a brilliant idea that cannot find its match. You have the vision, perhaps even the plan, but the launch keeps getting postponed — by funding, by team disagreements, by a quiet voice inside that whispers "not yet". A new role, project or creative venture is sitting at the starting line and refusing to fire. Frustration is the dominant note here, especially if you have been here before with other initiatives.

Reversed Aces of Wands rarely mean the idea is wrong. More often, they mean the conditions, the support or the timing are off. Maybe the market is not quite ready. Maybe you are exhausted from earlier rounds and have nothing left to spend on the new spark. Maybe a stakeholder is blocking momentum without saying so directly. Investigate before you scrap anything — a small adjustment can sometimes restart the engine.

The remedy at work is to protect the spark rather than push it. Sketch, prototype, journal — do the unglamorous early work in private until you trust the idea enough to defend it loudly. If you are stuck waiting for permission, ask explicitly for what would unblock you. And if a venture has truly stalled, give yourself the dignity of naming that out loud. Releasing one false start frees the fuel for the real one.`,
    spiritLong: `The Ace of Wands reversed spiritually points to inspiration that has not yet landed in the body. You read the books, follow the teachers, save the practices — but something inside has not actually caught fire. The fuse is there; the flame is still hiding. This can feel quietly demoralising, especially if you remember a previous chapter when your practice felt vivid and alive.

In Fire-element terms, this is what happens when the spark is rationed too carefully. You are protecting yourself from disappointment, or from the embarrassment of caring openly about something invisible. Spiritual life cannot run on cautious approval; it needs the willingness to look slightly foolish. The Ace reversed asks where you have been keeping your enthusiasm small.

Work with this card by making one tiny, undignified gesture toward the sacred this week. Light a real candle. Speak a prayer out loud even if the room is empty. Walk somewhere beautiful with no agenda. Spiritual fire returns to those who feed it scraps without demanding immediate evidence. The Ace of Wands reversed is not a closed door — it is a pilot light asking to be noticed.`,
    reversedFaqs: [
      { q: 'What does Ace of Wands reversed mean in love?', a: 'The Ace of Wands reversed in love is the spark that refuses to catch. A new attraction is hesitating, or an existing relationship has lost its easy heat. It is rarely a verdict; usually it signals mismatched timing, fear of disappointment, or a connection you have been trying to force. Stop performing passion and return to what genuinely lights you up. Real chemistry can survive a slow start. If the spark still refuses after honest effort, this card is the gentle sign-off before you over-invest.' },
      { q: 'Is Ace of Wands reversed a bad sign?', a: 'No — Ace of Wands reversed is rarely a bad omen, only an inconvenient one. It marks a delayed beginning, a stalled spark or a creative impulse that has not yet found traction. The energy you sense is real; the conditions for ignition are simply not aligned yet. Treat it as a diagnostic, not a death notice. Investigate what is blocking momentum — timing, support, exhaustion, fear — and address the actual cause. Most reversed Aces resolve into successful starts once the obstacle is honoured rather than ignored.' },
      { q: 'What does Ace of Wands reversed mean for ambition?', a: 'Reversed, the Ace of Wands shows ambition that has not yet ignited. You can feel the potential humming underneath, but the will to strike is hesitating — often because previous false starts have made you cautious. The card asks you to honour the spark privately before announcing it publicly. Do the small, unglamorous prep work that protects fresh enthusiasm from premature judgement. Ambition does not need to roar to be real; sometimes it needs a quiet room and a little time before it consents to burn brightly.' },
      { q: 'How do I work with Ace of Wands reversed in a reading?', a: 'Read it as a question rather than a verdict. Ask what spark in your life is asking to be lit and what is currently dampening it. Look at surrounding cards for the cause — Swords often point to overthinking, Cups to emotional reluctance, Pentacles to practical blockers. Then take one small, embodied action toward the unlit fire: a phone call, a sketch, a candle, a written intention. The Ace reversed responds beautifully to gentle, repeated tending rather than dramatic relaunch attempts.' },
    ],
  },

  'two-of-wands': {
    loveLong: `The Two of Wands reversed in love is the indecision card. You are standing on a balcony with two possible futures in your hand and neither feels safe enough to commit to. This might be a literal choice between two people, but more often it is the choice between staying and leaving, between long-distance and same-city, between defining the relationship and keeping it pleasantly vague. The map is in your pocket; you simply do not want to unfold it.

Reversed, this card warns that the comfort of the unmade decision is starting to cost you. While you weigh, the other person waits — and waiting has a shelf life. The energy of possibility, so seductive at first, curdles into anxiety when nobody plants a flag. If you are single, you may be running a quiet shortlist of options without ever fully showing up for any of them. If you are partnered, the relationship has reached the moment where it must either expand into a shared future or politely contract.

The Two of Wands reversed in love asks you to look beyond your familiar horizon. Where you live, who you trust, what you say out loud — these often need to widen before the romantic decision can be made well. Pick the future that requires more of you, not the one that requires less. Indecision is not neutrality; it is a slow no dressed up as patience.`,
    careerLong: `The Two of Wands reversed in career points to a career strategy that is too narrow, too cautious or simply unmade. You have skills, you have a respectable position, and yet the bigger picture eludes you. Perhaps you have been telling yourself you will plan "once things settle" — but things do not settle, and the months keep passing without a clear direction. Reversed, this card describes the cost of refusing to lift your eyes from the desk.

Two of Wands reversed in career also flags fear of the unknown disguised as pragmatism. The international role, the agency you keep almost starting, the cross-functional move — they remain in the "maybe one day" file because the known job is just good enough to keep you safely small. Notice the language you use when you describe your ambitions to friends. If it sounds apologetic or hedged, this card is calling out the hedge.

The remedy is to draft the plan that scares you slightly. Sketch a two-year horizon, not a two-week one. Talk to one person already living the version of work you covet, and ask them concrete questions. You do not have to commit yet; you only have to refuse to stay map-less. The Two of Wands rewards bold cartography. Its reverse only asks that you stop pretending you have no opinions about your own future.`,
    spiritLong: `The Two of Wands reversed spiritually shows a soul that has not yet committed to a direction. You sample teachings, dabble in practices, read across traditions — and there is real value in this curious phase. But reversed, the card asks whether your breadth has become a hiding place. Choosing nothing is also a choice, and it quietly drains the fire that drew you to the spiritual path in the first place.

The fire-element imbalance here is dispersion. Wands wants a focused flame, not a row of unlit matches. When you keep your spiritual life provisional, your inner authority cannot grow. You stay a tourist in your own depth. This is the moment to ask what you actually believe — even tentatively, even imperfectly — and to plant a small flag.

Practical step: choose one practice for the next forty days and do it daily, badly, without seeking external validation. Pick a teacher you trust enough to disagree with. Let the act of choosing matter more than the choice itself. The Two of Wands reversed dissolves the moment you stop hovering and start walking, in any direction, with full presence in your steps.`,
    reversedFaqs: [
      { q: 'What does Two of Wands reversed mean in love?', a: 'The Two of Wands reversed in love describes indecision about commitment. You are weighing options, holding multiple possibilities open, or stalling a defining conversation because the unmade choice feels safer than any actual one. Reversed, this card warns that the comfort of ambiguity is beginning to cost real connection — the other person can sense the hedge. Pick the future that requires more of you, not less. Indecision in romance is rarely neutral; it is a slow no in a kinder costume, and prolonged it will choose for you.' },
      { q: 'Is Two of Wands reversed a bad sign?', a: 'Not bad, but uncomfortable. The Two of Wands reversed signals stalled planning, narrow vision or fear of stepping beyond familiar horizons. It is essentially a nudge: lift your eyes, expand your perspective, draft the bolder map. Treated as feedback, it can move you forward quickly. Ignored, it tends to produce months of restless dissatisfaction. Take it seriously without panicking — the card describes a missing strategy, not a doomed outcome.' },
      { q: 'What does Two of Wands reversed mean for ambition?', a: 'Reversed, the Two of Wands describes ambition that has not yet become a plan. You feel the pull toward something larger, but you keep deferring the actual scoping work. The drive is real; the cartography is missing. This card asks you to commit to a horizon in writing — two-year, five-year, whatever stretches you — and to begin the small first conversations that make it tangible. Ambition without a map calcifies into resentment. With even a rough map, it becomes a direction you can walk.' },
      { q: 'How do I work with Two of Wands reversed in a reading?', a: 'Treat it as a planning prompt. Ask the querent — or yourself — what decision is currently being avoided and what fear is keeping it un-made. Look at surrounding cards for the missing variable: information, courage, support or timing. The Two of Wands reversed is rarely fatalistic; it almost always lifts once a concrete next step is named, however modest. Encourage one small, declarative action: a calendar block, a conversation, a written intention. Movement dissolves this card faster than analysis ever will.' },
    ],
  },

  'three-of-wands': {
    loveLong: `The Three of Wands reversed in love often describes a missed window. The ships you were watching for did come in — you simply were not at the shore. A message you meant to send, a trip you meant to take, a feeling you meant to express finally arrived at someone else's address. This card carries a particular ache because the original opportunity was real; the timing was just wrong by inches.

If you are single, this can show up as someone you nearly dated who is now genuinely unavailable, or as a long-distance attraction that ran out of patience while you decided whether to take it seriously. If you are partnered, it can mean that an expansion you were both planning — moving abroad, starting a family, building a shared project — has hit delays that risk becoming permanent if you keep treating them as temporary.

The Three of Wands reversed in love does not ask you to grieve forever. It asks you to learn the shape of the window you missed so you can spot the next one earlier. Distance, foresight, courage and follow-through are the gifts of this card upright; reversed, it teaches you to honour them by no longer leaving the shoreline unattended. Some opportunities come back in disguise. Some do not. Either way, your job now is to stay closer to the water.`,
    careerLong: `The Three of Wands reversed in career describes delayed expansion. You set things in motion, you waited for the harvest, and the ships are arriving slowly — or not all of them are arriving. International deals stall, partnerships go quiet, the bigger market you were betting on contracts before you reach it. This is not failure; it is a hand on your shoulder slowing down a particular kind of growth.

Reversed, this card often flags that the expansion plan was based on limited information or yesterday's map. The world moved while you were preparing for it. Suppliers shifted, the audience pivoted, the platform you built on changed the rules. Frustration is appropriate; despair is premature. Ask what you can now see from the shore that you could not see when you first set sail.

The work, then, is honest reforecasting. Re-examine which results were realistic versus aspirational. Lean on partners who can extend your reach where yours has stretched thin. Resist the urge to double down purely from pride. The Three of Wands reversed at work rewards practitioners who can grieve a plan without abandoning the dream behind it. Smaller ships, returning sooner, often outperform the spectacular fleet that was never quite seaworthy.`,
    spiritLong: `The Three of Wands reversed spiritually points to growth that is slower than your impatience can comfortably tolerate. You have done the foundational work — the practices, the inner inventory, the quiet investments — and you expected, by now, to feel different. Reversed, the card asks you to widen your timeline and trust the seeding.

The fire-element risk here is forcing visibility. You want proof. You want the practice to show something legible — peace, intuition, synchronicity — and when it withholds, you suspect you are doing it wrong. Often you are not. You are simply at the part of the journey where the work is happening below the surface and refusing to perform.

Sit with the longer view. Trust that the spiritual ships will come in, but possibly to a different harbour than you originally charted. Be willing to receive results you did not specifically ask for. The Three of Wands reversed teaches that expansion sometimes arrives sideways: as compassion you did not have last year, as patience you did not used to possess, as silence that no longer frightens you. Honour those quiet returns. They count.`,
    reversedFaqs: [
      { q: 'What does Three of Wands reversed mean in love?', a: 'The Three of Wands reversed in love often shows a missed window — a message unsent, a trip not taken, a feeling left unspoken until the other person had already moved on. It can also describe stalled long-distance plans or an expansion the relationship needed but did not receive. The card asks you to grieve cleanly, learn the shape of the window you missed, and stay closer to the shore next time. Some opportunities return in disguise; your job is to stop leaving the water unattended.' },
      { q: 'Is Three of Wands reversed a bad sign?', a: 'It is a difficult sign but not a final one. The card describes delays, limited vision and frustrations with timing, but the underlying expansion is rarely cancelled — only reshaped. Read it as a slowdown, not a stop. Use the delay to refine your plan, widen your information base and double-check whether you are still aiming at the right horizon. Most Three of Wands reversed situations recover well once the practitioner stops insisting on the original schedule.' },
      { q: 'What does Three of Wands reversed mean for ambition?', a: 'Reversed, the Three of Wands describes ambition that has expanded beyond your current resources or information. The vision is good; the execution has reached limits the original plan did not foresee. The card asks you to reforecast honestly, lean on partners, and accept smaller ships returning sooner over a grand fleet that may never arrive. Ambition matures here. The reversal is not a punishment; it is the universe trimming the sails so the journey can actually be completed.' },
      { q: 'How do I work with Three of Wands reversed in a reading?', a: 'Ask what was set in motion that has not yet returned, and what would help the practitioner widen their view. Look at surrounding cards for the bottleneck — Pentacles often point to material delay, Cups to emotional withdrawal, Swords to a missed message. The Three of Wands reversed responds well to practical action: send the email, check the late delivery, reach out to the contact who went quiet. Movement softens the card faster than rumination.' },
    ],
  },

  'four-of-wands': {
    loveLong: `The Four of Wands reversed in love often describes friction at home or a milestone reached too quickly. The card upright is the wedding-arch, the housewarming, the shared celebration; reversed, the same scene contains a guest who didn't come, an argument the morning of, an engagement announced while both partners were privately uncertain. The container of celebration is here — but it is straining.

For couples, this can mean domestic disagreements over shared space, family pressure around milestones, or a mismatch between the public story and the private feeling. You posted the photo. You took the trip. You moved in. Something underneath, however, has not yet caught up with the public commitment, and it is starting to hiss quietly under the floor. For singles, this can be a near-miss with a partner who looked like home until you got close enough to see the cracks.

Reversed, the Four of Wands in love asks you to make sure the celebration is real before you scale it. Slow the milestone if you can. Have the unflattering conversation now rather than later. Pay attention to who is missing from the gathering and why. The card is not anti-celebration; it is anti-pretence. Genuine joy can survive a delay. Performed joy collapses the moment anyone stops watching.`,
    careerLong: `The Four of Wands reversed in career points to recognition that does not feel quite earned or a milestone that is more wobbly than it appears. You hit the launch date, you closed the round, you got the promotion — and yet the team is fractious, the offering is patched together, or you privately suspect the win is built on shortcuts. The party is on the calendar. Whether you can fully enjoy it is the open question.

This reversal can also describe a workplace transition that has destabilised what used to feel like a stable base. A merger, a leadership change, a return-to-office mandate — something has unsettled the foundation people had quietly relied on. Productivity suffers more than anyone says out loud, and small frictions multiply because the larger container has cracked.

Working with the Four of Wands reversed at work means honouring the achievement without overselling it. Mark the milestone honestly: name what worked, name what is fragile, thank the people who actually carried the load. Then rebuild whatever foundation has slipped before the next push. Wands fire flourishes in a steady hearth. Reversed, this card is the reminder to repair the hearth before you throw another log on it.`,
    spiritLong: `The Four of Wands reversed spiritually describes celebration that has not quite settled into the body. You hit a milestone in your practice — a year of meditation, a completed programme, a noticeable shift — but the joy is muted. Either you are already chasing the next badge, or you are subtly disappointed that the arrival did not transform you as completely as you had hoped.

This is a common stage in any sustained spiritual life. The threshold is real; the celebration is internal and unphotographable; and the ego, denied a parade, grows restless. Reversed, this card invites you to honour the quieter forms of arrival. Light a candle. Tell one trusted person what shifted. Stop midway through your day to thank yourself for staying the course.

The Four of Wands reversed spiritually can also flag spiritual community friction — a group, teacher or tradition that no longer feels like home. If your hearth has cooled, it is not always a sign you have failed. Sometimes the structure that served the earlier flame can no longer hold the larger fire you have become. Build the new hearth slowly. Celebrate the old one with gratitude as you go.`,
    reversedFaqs: [
      { q: 'What does Four of Wands reversed mean in love?', a: 'The Four of Wands reversed in love describes friction beneath a celebration — milestones rushed past genuine readiness, family pressure around engagement or moving in, or a public commitment that the private reality has not yet caught up with. The card asks you to slow the milestone if you can and have the honest conversation before scaling further. Genuine joy survives delay; performed joy collapses the moment nobody is watching. Celebrate when the celebration is real, not before.' },
      { q: 'Is Four of Wands reversed a bad sign?', a: 'It is a complicating sign rather than a catastrophic one. The card describes instability inside something that looks settled, or a celebration that has not fully landed. Treated as a warning to slow down and reinforce foundations, it spares you a larger problem later. Most Four of Wands reversed situations recover well — the festivity is delayed or recalibrated, not cancelled. The card is most dangerous when it is ignored, not when it appears.' },
      { q: 'What does Four of Wands reversed mean for ambition?', a: 'Reversed, the Four of Wands warns against celebrating ambition prematurely. You have hit a visible milestone — launch, raise, promotion — but the underlying structure is shakier than the announcement suggests. The card asks you to honour the achievement without overselling it, repair the foundation before the next push, and resist the urge to leap straight to the next badge. Ambition built on a wobbly hearth burns the hearth, not the goal. Stabilise first; then ignite further.' },
      { q: 'How do I work with Four of Wands reversed in a reading?', a: 'Look at what is being celebrated and ask whether the celebration matches the reality. Identify who is missing from the gathering — literally or symbolically — and why. Surrounding cards usually clarify the friction: Cups for emotional misalignment, Pentacles for material instability, Swords for unsaid truths. Encourage the querent to slow the milestone, reinforce the foundation and have the unglamorous conversation. The card rewards honesty far more than it rewards momentum.' },
    ],
  },

  'five-of-wands': {
    loveLong: `The Five of Wands reversed in love is the moment you outgrow petty conflict. Where the card upright shows constant friction, bickering and competing for the last word, reversed it suggests you are stepping back from that arena. You have noticed that arguing about who said what at dinner is not the same as solving an actual problem, and you are quietly refusing to play.

This can be deeply liberating for a relationship that has been stuck in chronic skirmish mode. The thermostat lowers. Conversations become possible again. Both partners discover what they actually wanted underneath all the noise. For singles, the Five of Wands reversed often shows the end of a chaotic dating chapter — the group chats, the rivalries, the situationship triangles — in favour of something more deliberate.

The shadow side, though, is avoidance dressed up as maturity. Sometimes the card reversed shows somebody who has stopped fighting because they have stopped caring, or who is suppressing legitimate disagreement to keep the peace. Notice which version is on the table. Real surrender of petty conflict comes from clarity, not exhaustion. The Five of Wands reversed in love invites you to choose your fights from a place of confidence, not to abandon them out of fatigue.`,
    careerLong: `The Five of Wands reversed in career describes a workplace where the bickering is finally winding down — or, less happily, where you have privately disengaged from the competition altogether. The upright card is the open-plan office where everyone is jostling for the manager's attention; reversed, it is the moment you decide that game is not yours.

This can be a healthy professional milestone. You stop chasing visibility through volume. You let colleagues win small status battles you used to care about. Your work begins to speak more clearly because you are not constantly interrupting it with politics. Promotions and respect often follow this shift, not because you are playing the game better but because you have stopped playing the wrong game entirely.

However, Five of Wands reversed at work can also signal a team that has gone conflict-avoidant in unhealthy ways. Disagreements get buried, hard truths go unspoken in meetings and resurface in side-channels, and the surface calm hides a slow erosion of trust. If this is your team, the work is to reintroduce honest, structured disagreement before the resentment compounds. Good teams fight well; they do not stop fighting altogether.`,
    spiritLong: `The Five of Wands reversed spiritually describes the end of an internal civil war. Different parts of you — the inherited religion, the new practice, the rational sceptic, the longing mystic — have been arguing for years, and now, finally, a kind of ceasefire is emerging. You are tired of the noise. You want integration, not victory for any one faction.

This is genuine spiritual maturation. The card asks you to let the different voices inside you sit at the same table rather than insisting one of them prevail. Your childhood faith, your adult doubt, your current practice and your unmet longing can all hold something true at once. The point is no longer to win the argument but to hear what each voice is protecting.

The risk reversed, though, is bypass — declaring peace before the real disagreements have actually been heard. If you find yourself smoothing over genuine theological or ethical concerns just to feel calm, that is suppression, not resolution. The Five of Wands reversed spiritually rewards practitioners who can hold tension without rushing to dissolve it. Let the different fires inside you sort out who is keeping which post. Integration is slower than ceasefire, but it lasts.`,
    reversedFaqs: [
      { q: 'What does Five of Wands reversed mean in love?', a: 'The Five of Wands reversed in love marks the end of petty conflict — the bickering, the rivalry, the constant low-grade friction. You are stepping back from arenas that no longer serve the relationship. At its best, this brings real relief and lets deeper conversation become possible again. At its worst, it disguises avoidance as maturity. Notice which is happening. Real surrender of small fights comes from clarity and confidence, not from fatigue or quiet resignation. Honest peace is louder, not softer.' },
      { q: 'Is Five of Wands reversed a bad sign?', a: 'Usually it is a relief card, not a warning. It describes conflict resolving, tension lowering and the practitioner choosing not to engage with chaos that does not belong to them. The only caution is when the de-escalation is actually suppression — peace bought by burying real disagreement. Read the surrounding cards to tell the difference. Genuine Five of Wands reversed feels like exhalation. False Five of Wands reversed feels like something quietly rotting under the floorboards.' },
      { q: 'What does Five of Wands reversed mean for ambition?', a: 'Reversed, the Five of Wands shows ambition maturing past competitive noise. You are no longer trying to win every meeting or be the loudest voice in your field. The drive is still there; it has simply chosen better arenas. This is often when serious recognition begins to arrive, because your work is no longer drowned out by your scramble for it. Channel the energy you used to spend on rivalry into the work itself. Quiet competence outlasts loud competition every time.' },
      { q: 'How do I work with Five of Wands reversed in a reading?', a: 'Ask what conflict the querent is putting down and whether they are doing so from strength or from exhaustion. Look for the difference between resolution and avoidance in the surrounding cards. Encourage them to name the one fight that genuinely matters and to release the rest. The Five of Wands reversed responds beautifully to a question like: "If you stopped competing in this arena, what would you actually pursue?" The answer is usually the real reading.' },
    ],
  },

  'six-of-wands': {
    loveLong: `The Six of Wands reversed in love points to ego made fragile by romance. Upright, this card shows a partner who champions you publicly and a relationship you are proud to be seen in. Reversed, the dynamic distorts: praise is craved more than offered, success becomes a competition between partners, or one of you is privately tallying who got more attention at the party.

If you are partnered, this card can describe a season when external validation has crept too close to the centre of your bond. You start performing the relationship for friends, family or social media rather than tending to it in private. Or you notice yourself sulking when your partner's career is celebrated and yours is not. Reversed, the Six of Wands in love asks who the relationship is for — and whether the audience has accidentally become the point.

For singles, this card can flag dating from a wounded ego: chasing partners primarily for the boost their attention gives, or refusing to be seen with someone whose status does not match yours. The work is to soften the audience and turn the camera off. Real intimacy is allergic to constant performance. Six of Wands reversed in love invites quieter wins — the inside joke, the unwitnessed kindness, the praise that never makes it to anyone else's feed.`,
    careerLong: `The Six of Wands reversed in career describes recognition gone slightly off — either delayed, accidentally private, or distorted by arrogance. You did the work. The credit is muddled. A colleague is taking the bow you should have taken, or the announcement landed quietly when you expected fanfare, or you got the title without the actual decision-making power that was supposed to come with it.

There is also a self-inflicted version of this reversal: success that has tipped into hubris. Wins start getting attributed to your singular brilliance rather than to the team that carried you, and the people who used to support you become quietly less generous. Six of Wands reversed at work warns when the parade is starting to outrun the achievement. Take stock before the gap becomes visible to everyone else.

The remedy is twofold. If your win is being overlooked, advocate for it cleanly — facts, dates, contributions, no resentment. If your win is being over-claimed, redistribute the credit publicly before someone else has to do it for you. The Six of Wands reversed responds well to leaders who can be specific about who did what. Vague triumph collapses fast; precise gratitude compounds.`,
    spiritLong: `The Six of Wands reversed spiritually describes a path complicated by visibility. You may be teaching, sharing, writing or leading in some capacity and finding that the public role is starting to crowd the private practice. The audience grew faster than the inner work, and now you are performing a depth you do not always inhabit when you are alone.

This is a delicate place. The card is not condemning your visibility — many people are called to share what they have found — but it is asking whether the applause is feeding the practice or replacing it. Reversed, the Six of Wands warns of spiritual celebrity, however small the platform. Notice if you have started to need the recognition more than the silence.

There is also a humbler version of this reversal: doing the work invisibly and quietly mourning that no one knows. Both extremes — the parade and the resentment of not being paraded — are signs that the ego has snuck into the temple. The remedy is the same: return to a practice no one will ever see. Pray in a room with no recording device. Serve someone who will never thank you. The Six of Wands reversed spiritually heals through deliberate, untheatrical depth.`,
    reversedFaqs: [
      { q: 'What does Six of Wands reversed mean in love?', a: 'The Six of Wands reversed in love describes ego made fragile by romance — chasing praise, comparing wins with your partner, or performing the relationship for an audience instead of tending to it in private. The card asks who the relationship is actually for, and whether the audience has accidentally become the point. Soften the performance. Real intimacy is allergic to constant visibility. Quiet wins, unwitnessed kindness and praise that never makes it to anyone else are the medicine here, especially after a chapter of curated romance.' },
      { q: 'Is Six of Wands reversed a bad sign?', a: 'It is a humbling sign more than a damaging one. The card describes recognition that has gone slightly off-key — delayed, private, distorted by ego, or claimed by someone other than the one who earned it. Treated as feedback, it usually leads to cleaner credit and steadier confidence. Treated as injustice, it can spiral into resentment. Read it as a calibration prompt. Most Six of Wands reversed situations resolve once the practitioner speaks accurately about who did what.' },
      { q: 'What does Six of Wands reversed mean for ambition?', a: 'Reversed, the Six of Wands warns ambition that has begun to confuse acclaim with achievement. You may be chasing the announcement more than the actual work, or letting praise inflate your sense of contribution. The card asks for honest accounting: what did you build, and what did others build with you? Ambition is healthiest when it is paired with precise gratitude. Redistribute credit, name your team, and the recognition that returns will be far more durable than the kind you grabbed at.' },
      { q: 'How do I work with Six of Wands reversed in a reading?', a: 'Ask whether the querent is over-claiming or under-claiming credit in the situation. Both look like Six of Wands reversed from different angles. Look at surrounding cards: Cups often signal wounded validation needs, Pentacles a tangible withholding, Swords a story about who deserves what. Encourage the querent to advocate cleanly where they have been overlooked and to redistribute credit where they have been over-praised. Specificity, not volume, dissolves this card.' },
    ],
  },

  'seven-of-wands': {
    loveLong: `The Seven of Wands reversed in love is the moment you surrender a battle that was never really yours. Upright, this card shows you defending the relationship — against family doubt, ex partners, gossip or simply your own anxious projections. Reversed, you are lowering the staff. Sometimes that is wisdom; sometimes it is fatigue.

The healthier reading is that you have stopped fighting for approval that was never going to come. The relative who disapproves of your partner has been factored in and no longer dictates the relationship. The ex who keeps stirring trouble has been ignored long enough to lose interest. You and your partner have agreed to stop performing the defence and simply live the life. That is real strength, not retreat.

The less healthy version, though, is that you have stopped defending the relationship because you no longer believe it is worth the effort. The criticisms have landed. Self-doubt has crept in. You hand over the ground because you are tired, not because the fight has resolved. Reversed, the Seven of Wands in love asks you to be honest about which version is operating. Some battles deserve to be released. Others deserve one more steady, quiet stand — not from anger, but from the conviction that this love is worth the trouble.`,
    careerLong: `The Seven of Wands reversed in career describes the moment professional defence stops paying. You have been holding your position — against competitors, sceptics, the new hire who has been quietly campaigning for your role — and the cost-benefit has tipped. Either the battle is no longer worth winning, or you have already lost it on a level you have not yet admitted.

Reversed, this card sometimes signals burnout from constant proving. If you have been the lone defender of a standard or a project for too long, your energy reserves are depleted and your decisions are getting brittle. You snap at junior colleagues. You take legitimate feedback as attack. The reversal is the body's warning that your defensive posture has become the problem, not the solution.

The healthier version is strategic withdrawal: choosing not to die on a particular hill because the broader campaign matters more. Pick a different battlefield. Let someone else carry the flag on this one. The Seven of Wands reversed at work rewards practitioners who can distinguish between principled stand and reflexive resistance. The first is leadership. The second is exhaustion in disguise.`,
    spiritLong: `The Seven of Wands reversed spiritually describes the surrender of beliefs that no longer need defending. For years, perhaps, you have argued for your practice — at family dinners, at school, in your own internal debates. Reversed, the card asks whether you still need to. Some of what you believe has settled below the level of argument. It simply is yours now.

There is enormous peace in this transition. The energy you used to spend convincing others — or convincing yourself — becomes available for actual practice. You stop performing certainty and rest into something quieter and more durable. Your spirituality becomes less a position and more a posture.

The shadow side is collapse: giving up on what you knew was true because the constant questioning eroded your nerve. Reversed, the Seven of Wands spiritually can show someone who has stopped defending a practice not from confidence but from social fatigue. If this is your situation, the work is to find one trustworthy space — a teacher, a small circle, a journal — where you do not have to defend, only deepen. Conviction needs shelter sometimes. Build it deliberately.`,
    reversedFaqs: [
      { q: 'What does Seven of Wands reversed mean in love?', a: 'The Seven of Wands reversed in love describes putting down a defensive posture. At best, you have stopped fighting for approval that was never coming and chosen to live the relationship rather than perform its justification. At worst, you have surrendered from fatigue rather than wisdom. Be honest about which is happening. Some battles deserve release; others deserve one more quiet, grounded stand. The reversal is most healing when the release is chosen, not collapsed into.' },
      { q: 'Is Seven of Wands reversed a bad sign?', a: 'Not necessarily — it often marks a healthy end of unnecessary defence. But it can also signal burnout from too much proving, or capitulation when a stand was actually warranted. The surrounding cards tell you which. Read for whether the practitioner is choosing peace from strength or accepting defeat from exhaustion. Both look similar from the outside; only one heals well. The card responds to honesty far more than to bravado.' },
      { q: 'What does Seven of Wands reversed mean for ambition?', a: 'Reversed, the Seven of Wands shows ambition that needs strategic withdrawal. You have been defending a position that may no longer be worth the energy — a project, a title, a role. The card asks whether this is the right hill, given everything you now know. Sometimes the most ambitious move is to release a battle so the broader campaign can continue. Conserve your fire. Pick the battlefield that actually advances the bigger vision rather than the one your pride keeps insisting on.' },
      { q: 'How do I work with Seven of Wands reversed in a reading?', a: 'Ask what the querent has been defending and whether the defence is still serving them. Differentiate between burnout, strategic withdrawal and genuine surrender. Surrounding cards usually show the cost: Pentacles for material drain, Cups for emotional depletion, Swords for mental fatigue. Encourage the querent to choose their next stand deliberately rather than reflexively, and to find safe spaces where they do not have to defend at all. Conviction needs both backbone and rest.' },
    ],
  },

  'eight-of-wands': {
    loveLong: `The Eight of Wands reversed in love is the card of delayed messages, missed signals and stalled romantic momentum. Upright, the eight wands fly through the air — texts arrive, plans accelerate, the relationship leaps forward. Reversed, the wands hang suspended. You are waiting for a reply that does not come, sending messages that do not land, or watching a once-fast connection cool into uncertain silence.

For couples, this card often shows a communication breakdown — not necessarily a dramatic argument, but a slow erosion of the easy back-and-forth you used to share. Texts get shorter. Conversations get postponed. The little daily threads that kept the connection lively have frayed. Reversed, the Eight of Wands in love is asking you to notice the silence before it becomes the new normal.

For singles, this card frequently flags a flirtation that has gone quiet. You messaged. They went vague. Maybe a reply will come; maybe it will not. The Eight of Wands reversed counsels patience without delusion. Send the one clarifying message you need to send, then release the loop. Romantic momentum cannot be forced from one side. If the answer is yes, it will speed up again. If it is no, the silence is the answer — and you deserve to redirect your fire elsewhere.`,
    careerLong: `The Eight of Wands reversed in career describes stalled momentum at work. The launch is delayed. The reply from the recruiter has not come. The project that was sailing through approvals has hit a sudden, mysterious bottleneck. Whatever was moving fast has slowed, and the slowdown is more frustrating because the upright energy of this card had taught you to expect speed.

Sometimes the delay is technical — a system outage, a missing signature, a key player on holiday. Sometimes it is political — someone is sitting on a decision and will not say why. Either way, your job is to diagnose, not to push harder. Eight of Wands reversed at work rarely rewards more force. It rewards intelligent follow-up: one clear email rather than ten, a calendar check rather than another anxious slack, a phone call when text has failed.

The other meaning is haste that has backfired. You may have moved too fast and sent the email that should have been slept on, scheduled the launch before the team was ready, or jumped on the opportunity without the necessary due diligence. The reversal asks you to slow down and tidy up. Wands fire is not extinguished by patience. It is sharpened by it.`,
    spiritLong: `The Eight of Wands reversed spiritually describes a season when the synchronicities have gone quiet. For months perhaps everything seemed connected — the right book appeared, the right teacher, the right conversation at the right moment. Now the cosmos has gone strangely silent. The downloads have stopped. The signs have dried up.

Reversed, the Eight of Wands invites you to trust the lull. Not every season can be peak transmission; the soul, like a field, needs fallow time. Pushing for more signs in this period often produces only anxious pattern-matching, where you read meaning into anything that moves. The work is to settle, return to baseline practice and let the next wave arrive on its own schedule.

There is also a version of this card that points to spiritual information overload. You took in too much too fast — books, retreats, podcasts, teachers — and the inner integration has not kept up. The wands are stuck mid-air because you have nowhere to land them. Stop consuming for a while. Sit with what you already have. The Eight of Wands reversed spiritually rewards consolidation over acquisition. Momentum will return; it just wants a more solid ground to land on.`,
    reversedFaqs: [
      { q: 'What does Eight of Wands reversed mean in love?', a: 'The Eight of Wands reversed in love is the card of delayed replies, stalled flirtations and communication breakdowns. Messages go unanswered, plans get postponed, and the once-easy back-and-forth thins into silence. The card asks you to notice the silence before it becomes the relationship norm. Send the one clarifying message you need to send, then release the loop. Romantic momentum cannot be forced from one side. If the connection is real, speed will return; if not, the silence is the answer.' },
      { q: 'Is Eight of Wands reversed a bad sign?', a: 'Mostly it is frustrating rather than truly bad. The card describes delays, miscommunications and momentum that has slowed unexpectedly. These rarely cancel the underlying movement — they only postpone it. Treat the reversal as a diagnostic: what is blocking flow, who has gone silent, where has haste created mess? Once the obstacle is named, things usually pick up again. The card is far more often a pause than a stop.' },
      { q: 'What does Eight of Wands reversed mean for ambition?', a: 'Reversed, the Eight of Wands describes ambition that has either stalled or moved too fast for its own good. Either momentum has dropped and you cannot find the cause, or you accelerated past necessary due diligence and now have to backtrack. The card asks for intelligent follow-up rather than more force. One clear email beats ten anxious ones. One slow, tidy week beats another sprint that creates more rework. Drive is fine; uncoordinated speed is not.' },
      { q: 'How do I work with Eight of Wands reversed in a reading?', a: 'Ask where communication has broken down and whether the practitioner has been pushing speed where patience would serve better. Look at surrounding cards for the bottleneck — Swords for an unsaid truth, Pentacles for a logistical block, Cups for emotional withdrawal. Encourage one well-chosen action — a single phone call, a calendar check, a slept-on email — rather than another round of frantic outreach. The Eight of Wands reversed responds to precision, not volume.' },
    ],
  },

  'nine-of-wands': {
    loveLong: `The Nine of Wands reversed in love is the card of walls — either dropping at last, or standing too long. Upright, the nine of wands shows you battle-worn and on guard, scarred by past relationships and braced for the next disappointment. Reversed has two faces, and which one is yours matters enormously.

The first face is healing. After years of armoured dating or guarded partnership, you are finally letting the walls down. You risk being seen again. You stop scanning your partner for the early signals of betrayal that an old wound taught you to expect. This version of the reversal is tender and slow and worth honouring. It often coincides with therapy, a trustworthy partner, or the quiet realisation that the cost of staying defended exceeds the cost of being hurt again.

The second face is the opposite — walls that should have come down years ago but are still standing, now reinforced by exhaustion. You are too tired to fight, but you have not let anyone close enough to actually rest. Suspicion has hardened into worldview. Notice which version is operating. Both are Nine of Wands reversed in love; only one leads to real intimacy. The remedy in either case is the same: small, deliberate acts of trust, with people who have earned them. You do not have to fling the gate open. You only have to crack it.`,
    careerLong: `The Nine of Wands reversed in career often describes burnout that the practitioner has refused to acknowledge. You are battle-worn at work — too many projects, too many setbacks, too much of carrying the weight of a team or a quarter alone. Upright, the card says you are nearly at the finish line and can dig deep for one more push. Reversed, it asks whether the finish line you are running toward is real or just another mirage.

This card frequently shows up for high performers who have been overriding their nervous system for too long. The body is sending signals — insomnia, irritability, illness, a strange flatness — and you have been ignoring them in service of a deadline that keeps moving. Reversed, the Nine of Wands at work is the universe escalating the warning. Pay attention now or pay later with greater interest.

The alternative reading is professional paranoia: a workplace where you have been so often blindsided that you now read threat into everything. Colleagues are not always plotting. Sometimes a critical email is just a critical email. If the rigidity of your defences is making collaboration impossible, the work is to soften — selectively, where evidence supports it — and to seek out the colleagues who have actually behaved well. Trust, rebuilt slowly, is the antidote.`,
    spiritLong: `The Nine of Wands reversed spiritually describes the late stage of the dark night of the soul, when the exhaustion is real but the dawn has not yet arrived. You have done so much inner work, weathered so many cycles, and the practice is starting to feel like another job. The fire that originally drew you is now a chore to maintain.

Reversed, the card invites a particular kind of surrender. Not abandoning the path — but admitting how tired you are, and allowing your practice to soften. Take rest into the practice rather than treating rest as a betrayal of the practice. Sit with a teacher, a friend or a wise text and let yourself be carried for a while. Spiritual endurance does not require constant intensity. Sometimes the deepest progress happens when you let yourself collapse safely into the support that is available.

The shadow side is spiritual paranoia — the conviction that you must protect your inner life from every influence, every relationship, every input. This kind of fortress eventually starves what it was built to protect. Crack one window. Trust one person with what is actually going on. The Nine of Wands reversed spiritually heals through carefully chosen connection, not through fiercer isolation.`,
    reversedFaqs: [
      { q: 'What does Nine of Wands reversed mean in love?', a: 'The Nine of Wands reversed in love shows walls coming down — or staying up too long. The healing version is real: after years of armoured dating, you finally let the gate crack and risk being seen again. The shadow version is exhaustion mistaken for safety, defences that should have softened years ago. Notice which is yours. The remedy in either case is small, deliberate acts of trust with people who have earned them. You do not have to fling the gate open; you only have to crack it.' },
      { q: 'Is Nine of Wands reversed a bad sign?', a: 'It is a tired sign, not a doomed one. The card describes burnout, hyper-vigilance and the late, weary stage of a long battle. Treated as feedback, it leads to genuine rest, softened defences and slow rebuilding of trust. Ignored, it tends to produce collapse — a real health, work or relationship crisis that forces the rest the practitioner refused to take voluntarily. Heed it early. The Nine of Wands reversed is one of the more merciful warnings the deck offers.' },
      { q: 'What does Nine of Wands reversed mean for ambition?', a: 'Reversed, the Nine of Wands shows ambition operating on fumes. You have pushed through many cycles already and the next push is asking more than your reserves can sustain. The card asks you to honour the depletion rather than override it. Real ambition includes recovery; the practitioner who refuses to rest eventually stops producing anything worth recognising. Take the break before the breakdown. The goals will still be there. Your capacity to pursue them, if you ignore this card, may not be.' },
      { q: 'How do I work with Nine of Wands reversed in a reading?', a: 'Ask how tired the querent actually is, and whether their defences are still proportional to the real threat. Differentiate between healing softening, exhausted collapse and reinforced paranoia. Encourage practical rest, one trustworthy ally, and a single small act of letting someone in. The card rewards specificity: not "rest more" in the abstract, but "take Friday off and tell one person what is going on". Concrete, modest acts of trust dissolve this card faster than grand resolutions.' },
    ],
  },

  'ten-of-wands': {
    loveLong: `The Ten of Wands reversed in love is the moment you set down a burden you have been carrying for the relationship — usually alone, often invisibly, frequently for far too long. Upright, this card shows you bent under a bundle of responsibilities. Reversed, the bundle is finally hitting the ground. The relief is real. So is the question of what to do with the version of yourself who no longer has to carry it.

For couples, this can mean a fairer renegotiation of domestic load: who handles the family logistics, who manages the emotional weather of the household, who has been quietly absorbing more than their share of the worry. The Ten of Wands reversed asks the carrying partner to name what they have been holding and the other partner to actually take some of it. Without that explicit handoff, the load gets picked back up out of habit within a week.

For singles, this card often shows the release of relationship baggage from earlier chapters — the protective stories, the worst-case-scenario reflexes, the unchosen-but-still-carried responsibility for an ex's feelings. Reversed, the Ten of Wands in love invites you to grieve the weight rather than just drop it. Acknowledge how heavy it was. Honour the version of you who carried it. Then make the choice to move into the next chapter with lighter hands.`,
    careerLong: `The Ten of Wands reversed in career describes a working life that is either finally releasing some weight, or refusing to despite all warning signs. Upright, the card shows you crushed by responsibility — too many projects, too many direct reports, too many problems you are the only one solving. Reversed has two paths.

The healthier path is delegation, deletion and honest renegotiation. You have realised that the heroic load you have been carrying is not sustainable, and you are beginning the unglamorous work of putting things down. Some get handed to colleagues. Some get cancelled outright. Some get re-scoped to be a third of their original size. The relief, when it begins, is immediate — and somewhat frightening, because you may have wrapped a lot of identity in being the one who could carry everything.

The unhealthier path is the one where the card warns you that you cannot let go. You know the load is killing you. You also cannot imagine who you would be without it. The Ten of Wands reversed at work asks honestly: what would be true about you if you carried half of what you carry now? If the answer scares you, the work is not just operational. It is identity-level. Burdens we cannot release are usually doing something for us that we have not yet named.`,
    spiritLong: `The Ten of Wands reversed spiritually describes spiritual burdens being put down — or the troubling discovery that you do not know how to put them down. The path attracted you partly because it offered a way out of suffering; somewhere along the way, it accumulated its own pile of obligations: practices you owe, lineages you must defend, perfections you must perform.

Reversed, the card invites a great divestment. Drop the practices that are no longer alive. Release the spiritual identity you built when you needed armour. Let yourself be a beginner again somewhere, with no track record to protect. The point of the path is freedom, not a more elegant cage. If your spirituality is making you tireder, not lighter, the Ten of Wands reversed is the merciful reminder that the load was never the point.

There is also a deeper version of this reversal: surrendering responsibility for everyone else's awakening. If you have been carrying the spiritual weight of your family, your partner, your community — quietly hoping your practice would heal them too — this card asks you to set them down with love. They have their own paths. Your work is yours. The Ten of Wands reversed spiritually heals when the practitioner finally trusts that lighter, freer and slower can also be the way.`,
    reversedFaqs: [
      { q: 'What does Ten of Wands reversed mean in love?', a: 'The Ten of Wands reversed in love marks the moment you put down a burden you have been carrying for the relationship — often alone, often invisibly. For couples, it asks for a fair renegotiation of domestic and emotional load. For singles, it signals release of baggage from earlier chapters. The card rewards explicit handoff over silent resentment. Name what you have been carrying. Let yourself grieve the weight before you drop it. Then choose to move into the next chapter with deliberately lighter hands.' },
      { q: 'Is Ten of Wands reversed a bad sign?', a: 'Generally it is a hopeful sign — a burden being released — though it can also flag a practitioner who knows the load is unsustainable and still cannot let go. Both versions point at the same medicine: honest delegation, honest grieving, honest renegotiation. The card is rarely fatalistic. It is asking you to stop being heroic about a weight that was never yours to carry alone. Most Ten of Wands reversed situations improve quickly once the practitioner actually puts something down.' },
      { q: 'What does Ten of Wands reversed mean for ambition?', a: 'Reversed, the Ten of Wands shows ambition that has accumulated too much weight to remain useful. The pile of obligations, projects and identities you took on in service of your drive has started to crush the drive itself. The card asks for ruthless prioritisation: what would you cancel, delegate or re-scope if you knew the load was killing the work? Ambition is best served by lightness, not by martyrdom. Put down half. The remaining half will go further.' },
      { q: 'How do I work with Ten of Wands reversed in a reading?', a: 'Ask the querent what they are carrying that was never theirs to carry, and what they fear would be true about them if they put it down. Look at surrounding cards for the identity bind — Pentacles often show provider identity, Cups carer identity, Swords the burden of being the smart one. Encourage one specific handoff this week, not abstract release. The Ten of Wands reversed dissolves through one concrete act of unburdening, not through promises of future ease.' },
    ],
  },

  'page-of-wands': {
    loveLong: `The Page of Wands reversed in love describes immature flirtation, scattered romantic energy or an interrupted spark. Upright, the Page bounds into the dating world with curiosity and playfulness; reversed, the same curiosity becomes unfocused, slightly performative, or unable to settle into anything real. You are flirting in five directions at once and arriving nowhere in particular.

For singles, this card frequently shows the chronic almost-dating phase — lots of matches, lots of banter, no actual meeting that leads anywhere. The energy is real but ungrounded. You have not yet asked yourself what you are actually looking for, so the universe is sending you a parade of approximations. Reversed, the Page of Wands in love asks for a small, embarrassing degree of specificity: what would you want if you let yourself want?

For couples, this card can describe a season when one partner is acting younger than the relationship can hold — flirting outside the bond, sulking when challenged, refusing to engage with adult conversations about the future. It can also describe a once-exciting connection that has been interrupted before it could mature: a long-distance situation neither of you fully committed to, a romance derailed by external chaos at the worst possible moment. The remedy is patience without pretence. Either grow the connection up deliberately, or release it cleanly.`,
    careerLong: `The Page of Wands reversed in career describes creative energy that cannot find its footing. You start projects with enthusiasm and abandon them when the first hard week arrives. You have a notebook full of ideas, three half-built side-hustles, and a chronic feeling that you are about to discover your real direction any minute now. The fire is real. The follow-through is missing.

Reversed, this card asks for the unglamorous discipline of finishing one small thing. Not the dream project — the small one. Ship one piece. Complete one cycle. The Page upright says: try everything. Reversed, it says: you have tried enough things; now stay with one until it actually matures into a skill. Curiosity without commitment becomes its own form of avoidance.

There is also a workplace version where Page of Wands reversed at work describes a junior colleague whose enthusiasm has not yet been balanced with judgement — or an organisation in its scrappy, impulsive early phase that needs to grow up into more reliable processes. If this is you, accept the boring work of building systems. If this is a colleague, mentor patiently. The fire is genuinely valuable; it only needs structure to become useful.`,
    spiritLong: `The Page of Wands reversed spiritually points to spiritual restlessness — leaping from teacher to teacher, modality to modality, never staying long enough for any single practice to actually mark you. The enthusiasm is genuine; the depth is impossible to develop while you keep moving. Reversed, the Page asks for a commitment that may feel like a death of curiosity but is in fact its maturation.

This card can also show a spiritual beginning that has been interrupted — a practice you started and abandoned, a teacher whose course you never finished, an initiation you walked away from at the moment it asked something real of you. There is no shame in any of this; it is how most spiritual lives go. The reversal simply asks you to notice the pattern and to consider returning to one of the abandoned thresholds rather than starting a new one.

Practical step: pick the spiritual book, practice or teacher you most resisted last time and revisit it. The Page of Wands reversed spiritually rewards practitioners who can stay with the slightly boring middle stage of a practice — the part after the novelty has worn off and before the depth has revealed itself. That middle is where the work actually happens. Sit through it once and your relationship to the path changes permanently.`,
    reversedFaqs: [
      { q: 'What does Page of Wands reversed mean in love?', a: 'The Page of Wands reversed in love describes scattered, immature or interrupted romantic energy. Lots of flirtation, little landing. For singles, it often shows chronic almost-dating — matches, banter, no actual meeting that goes anywhere. For couples, it can describe one partner acting younger than the relationship can hold, or a once-exciting connection derailed before it could mature. The remedy is small, embarrassing specificity about what you actually want, followed by the patience to let one connection develop rather than five flirtations stay shallow.' },
      { q: 'Is Page of Wands reversed a bad sign?', a: 'Mild and developmental rather than damaging. The card describes immaturity, lack of focus or a spark that has been interrupted. None of these are fatal; they are simply growth edges. Treated as feedback, the reversal usually leads to better focus and more grounded enthusiasm. The card rewards practitioners who can stay with one thing long enough to learn it properly, and it gently warns those who keep mistaking novelty for progress.' },
      { q: 'What does Page of Wands reversed mean for ambition?', a: 'Reversed, the Page of Wands shows ambition that is all spark and no follow-through. You start projects passionately and abandon them when the first hard week arrives. The card asks for the unglamorous discipline of finishing one small thing — not the dream project, just one complete cycle. Curiosity without commitment is its own avoidance. Real ambition is forged in the boring middle of a project, not in the exciting first week. Pick one. Finish it. Then choose the next.' },
      { q: 'How do I work with Page of Wands reversed in a reading?', a: 'Ask what spark the querent keeps almost following and what keeps interrupting it. Look at surrounding cards: Cups for emotional avoidance, Swords for self-criticism that kills enthusiasm, Pentacles for material instability. Encourage one concrete completion this month — one small finished thing, not a grand re-launch. The Page of Wands reversed responds beautifully to the dignity of finishing. It does not need more inspiration; it needs the practitioner to honour the spark already burning.' },
    ],
  },

  'knight-of-wands': {
    loveLong: `The Knight of Wands reversed in love is passion that cannot be relied upon. Upright, the Knight charges in with charm, intensity and inspired pursuit; reversed, the same energy is inconsistent, performative or volatile. The texts are passionate when they come and absent when they do not. The grand gestures alternate with weeks of distracted silence. The flame is real; the flame is also unreliable.

If you are dating this energy, the question is not whether the passion is genuine — it usually is — but whether it can be trusted to show up tomorrow. Reversed, the Knight of Wands in love often describes someone who falls hard, declares everything, then disappears when boring daily life arrives. They are not lying when they say they love you. They are also not capable, yet, of the steady warmth that love actually requires.

If you are the one moving like this, the card asks for the courage to slow down. Your passion is not the problem; your inconsistency is. The intensity you bring when you are present is undermined by the absence you let yourself drift into between bursts. The remedy is rhythm: smaller, more frequent acts of attention rather than dramatic peaks and disappearances. Real fire in love is not the loudest blaze. It is the one that burns dependably enough to warm a household.`,
    careerLong: `The Knight of Wands reversed in career describes drive that has tipped over into recklessness, or charisma that is starting to outrun delivery. Upright, the Knight makes the bold pitch, lands the big deal, opens the new market through sheer force of will. Reversed, the same energy creates problems: promises made without checking capacity, pivots executed before the team can follow, decisions taken at speed that produce expensive backtracks.

This is the card of the founder who keeps changing the strategy, the colleague who launches three projects and finishes none, the manager whose passion in meetings does not translate into actual outcomes for the team. Knight of Wands reversed at work asks you to honour the difference between motion and progress. Charging is not the same as advancing. Sometimes the bravest professional move is to slow down enough to actually finish what you started.

There is also an interpersonal warning here: anger or impatience starting to fray relationships at work. If you have been short with colleagues, the card is asking you to repair before the pattern hardens into reputation. Reversed Wands court cards heal most through specific, small acts of accountability. Apologise where you snapped. Renegotiate the deadlines you set too aggressively. Your fire is genuinely valuable; it only needs to be paired with reliability to become trustworthy.`,
    spiritLong: `The Knight of Wands reversed spiritually describes spiritual intensity that has lost its rhythm. You go on retreat, return ablaze, declare a new daily practice — and three weeks later the practice has collapsed and you are mildly ashamed. The pattern repeats. The fire is real every time; the structure to sustain it is missing.

Reversed, this card asks you to fall in love with the unspectacular middle of practice. Not the peak experience, not the breakthrough — the ordinary Tuesday when you sit anyway. Most spiritual depth is built in those middling sessions, and the Knight of Wands reversed flags the practitioner who keeps trying to live in the peaks. Peaks are gifts. They cannot be the whole shape of the path.

There can also be a more troubling version here: spiritual aggression. Passionate convictions deployed as weapons — toward family who do not share your path, toward yourself when you fall short, toward other practitioners whose approach offends yours. Notice the heat. If your spirituality is producing more conflict than peace, the Knight reversed is asking you to bank the fire. Inspired action does not have to be loud. Sometimes the most radical spiritual move is to be quietly, reliably present to your practice without telling anyone about it.`,
    reversedFaqs: [
      { q: 'What does Knight of Wands reversed mean in love?', a: 'The Knight of Wands reversed in love is passionate but inconsistent — grand gestures followed by silence, intensity followed by drift. The fire is genuine; its reliability is not. If you are dating this energy, the question is whether tomorrow will look like today. If you are this energy, the card asks for rhythm: smaller, more frequent acts of attention instead of dramatic peaks and disappearances. Real fire in love is not the loudest blaze. It is the one that burns dependably enough to warm a shared life.' },
      { q: 'Is Knight of Wands reversed a bad sign?', a: 'Mixed rather than purely bad. The card describes real passion and drive operating without enough discipline or rhythm to be reliable. Channelled well, the Knight of Wands reversed becomes a maturation card — the practitioner learns to pair their fire with consistency. Ignored, it produces broken commitments, recurring conflict and a reputation for unreliability. The energy is valuable; the structure around it is what needs work. Read it as a coaching card more than a warning card.' },
      { q: 'What does Knight of Wands reversed mean for ambition?', a: 'Reversed, the Knight of Wands shows ambition tipping into recklessness — bold moves made faster than capacity can support, pivots that exhaust the team, promises bigger than delivery. The card asks you to slow down enough to finish what you started. Motion is not the same as progress. The drive is excellent; the impulse control is the work. Pair your fire with reliable follow-through, and the same ambition that was causing chaos becomes formidable. Mature it; do not mute it.' },
      { q: 'How do I work with Knight of Wands reversed in a reading?', a: 'Ask where the querent is confusing intensity with consistency. Look at surrounding cards for the cost of the inconsistency: Cups for damaged relationships, Pentacles for financial volatility, Swords for self-recrimination after the burst burns out. Encourage one small, repeatable rhythm rather than another grand resolution. The Knight of Wands reversed responds to discipline rather than to motivation. It does not need more fire; it needs a sturdier hearth.' },
    ],
  },

  'queen-of-wands': {
    loveLong: `The Queen of Wands reversed in love often describes jealousy, smothering or a confidence wobble in the realm of romance. Upright, the Queen is warm, magnetic and entirely herself; reversed, the same fire is turned inward as insecurity, or outward as possessiveness. The radiance dims, and what fills the space is either neediness or comparison.

For partnered women and femmes especially, this card can flag a season when self-trust has slipped — perhaps because of an external trigger like an ex re-appearing, a partner's success, or simply tired eyes in the mirror — and that slippage is now contaminating the relationship. You text more often than you mean to. You scroll where you shouldn't. You compare yourself to people who have nothing to do with your actual life. Reversed, the Queen of Wands in love asks you to return to what lights you up, not because it will impress your partner but because that fire is the original source of your magnetism.

For couples, this card can also show smothering — too much warmth, too closely held. Love that does not give the other person room to breathe eventually scorches. The remedy is the deliberate cultivation of your own life again: friendships, projects, beauty, joy that does not include your partner. Paradoxically, the more fully you live outside the relationship, the more compelling you become inside it. The Queen of Wands reversed heals through reclaimed autonomy, not louder devotion.`,
    careerLong: `The Queen of Wands reversed in career describes creative confidence that has wobbled or hardened into something more defensive. Upright, this is the warm, magnetic leader who lights up rooms and rallies teams; reversed, the same person becomes either insecure and over-reactive, or self-protective and territorial. Either way, the natural radiance is muffled.

This card often appears for women in leadership who are absorbing too much projected judgement and starting to lose their grounding. The constant micro-criticisms — about tone, about appearance, about whether they are too much or not enough — have accumulated, and the once-confident creative voice is now hedging or over-explaining. The Queen of Wands reversed at work is the call to return to your own counsel. Your taste is good. Trust it.

There is also a shadow version where Queen of Wands reversed describes a leader who has tipped from confident to controlling. Warmth becomes performance; magnetism becomes manipulation; the team learns to handle you rather than trust you. If this is the case, the work is humility — explicit acknowledgement of where you have been overbearing, followed by genuine repair. Wands queens at their best lead by lit example. Reversed, they remind us that the lamp needs tending or it starts to smoke.`,
    spiritLong: `The Queen of Wands reversed spiritually describes a practitioner whose inner fire has dimmed under outside pressure. You used to light up about your practice. You used to feel the heat of your own knowing. Now you find yourself defending it, apologising for it or comparing it to other people's curated spiritual lives. The Queen reversed asks who you stopped trusting.

For women especially, this card can flag the corrosive effect of spiritual environments that subtly punish female confidence. If your tradition or community rewards smallness, your fire eventually goes quiet to fit. Reversed, the Queen of Wands says: relight. Find the practices, teachers and rooms that respond to your full presence rather than your shrunken one.

There is also a smothering shadow here — a practitioner whose spirituality has become so all-encompassing that it leaves no room for the messy humanity around them. Spiritual perfectionism, like romantic smothering, scorches what it claims to love. The Queen of Wands reversed spiritually heals through reclaimed warmth: warmth toward yourself first, then toward the imperfect people in your life, then toward the imperfect spirituality that is the only kind available to anyone. The flame returns when it is allowed to be ordinary again.`,
    reversedFaqs: [
      { q: 'What does Queen of Wands reversed mean in love?', a: 'The Queen of Wands reversed in love describes jealousy, smothering or a wobble in confidence. The natural magnetism of this card dims when self-trust slips, and what fills the space is either neediness or comparison. The remedy is to return to what genuinely lights you up — friendships, beauty, your own creative life — not to impress your partner but because that fire is the original source of your attractiveness. Paradoxically, fuller autonomy makes you more compelling, not less. Reclaim your own warmth first.' },
      { q: 'Is Queen of Wands reversed a bad sign?', a: 'Uncomfortable, not catastrophic. The card describes a confident person operating from a wobble — insecurity, defensiveness, controlling behaviour or smothering warmth. Read as feedback, it points clearly at the medicine: reclaim self-trust, soften the grip, return to what genuinely energises you. Most Queen of Wands reversed situations resolve gracefully once the practitioner stops trying to compensate externally and tends to their inner flame instead. It is more often a calibration than a crisis.' },
      { q: 'What does Queen of Wands reversed mean for ambition?', a: 'Reversed, the Queen of Wands shows creative confidence that has slipped — too much external criticism absorbed, too much hedging in once-bold work, or warmth that has hardened into territoriality. The card asks you to return to your own counsel. Your taste is good. Trust it. Real ambition for a Queen of Wands is led by lit example, not anxious performance. Stop explaining yourself. Make the thing. The radiance returns the moment you stop borrowing other people\'s nervous systems.' },
      { q: 'How do I work with Queen of Wands reversed in a reading?', a: 'Ask where the querent has lost touch with their own warmth and whose judgement they have been over-weighting. Look at surrounding cards: Swords often show internalised criticism, Cups projected jealousy, Pentacles material insecurity feeding the wobble. Encourage one act of unapologetic self-trust this week — wearing something they love, posting the work, choosing the meal they actually want. The Queen of Wands reversed heals through small, embodied confidence rather than through more analysis.' },
    ],
  },

  'king-of-wands': {
    loveLong: `The King of Wands reversed in love describes dominance, control or vision that has hardened into authoritarianism within a relationship. Upright, the King is a confident, visionary partner who leads with charisma and protects fiercely; reversed, the same energy becomes overbearing, dismissive of other perspectives, or quick to anger when the relationship does not unfold according to plan.

If you are partnered with this energy, the card asks you to notice where the leadership has slid into rule-by-decree. The big decisions are made unilaterally. Your input is invited but not actually heard. Concerns get reframed as overreaction. Reversed, the King of Wands in love is the moment when these patterns must be named — not because the partner is irredeemable, but because charisma cannot indefinitely cover for a refusal to share power.

If you are the one operating like this, the card asks for the harder kind of leadership: the kind that listens. Your vision for the relationship may be genuinely good; it is not, however, the only valid vision in the room. Your partner has their own life, their own clarity, their own veto. A King of Wands at his best knows that real authority is conferred, not seized. Reversed, he is being asked to return the favour to the person who has been quietly conferring authority on him for years.`,
    careerLong: `The King of Wands reversed in career describes leadership that has tipped from visionary to domineering. Upright, this is the founder, executive or senior expert whose vision and charisma carry the team through difficult terrain; reversed, the same person becomes a bottleneck — refusing to delegate, dismissing dissent, making impulsive calls that the organisation then has to absorb the cost of.

This card often shows the late stage of an unchecked leadership pattern. Early on, the King's boldness was the magic. Over time, without the seasoning of feedback, it has calcified into ego. Decisions get worse, not better, because nobody dares disagree. King of Wands reversed at work asks the leader to actively cultivate dissent — to reward the colleague who tells them the uncomfortable truth, to slow down the impulsive pivot, to bring in voices that complement rather than echo theirs.

If you are working under this energy rather than embodying it, the card asks where you have been over-deferring to charisma at the cost of your own judgement. Brilliant leaders still make ordinary mistakes. Your job is to bring your full clarity, especially when the room is full of people too dazzled or too afraid to do the same. The King of Wands reversed at work is healed by teams that can disagree well, and by leaders who can be wrong gracefully.`,
    spiritLong: `The King of Wands reversed spiritually describes a teacher, elder or leader whose authority has stopped serving the work. Upright, this is a magnetic guide whose presence lights up a tradition; reversed, the same authority is being misused — for ego, for control, for the wrong kind of influence. The fire is real; the wisdom has not quite kept pace.

This card can be a warning about a teacher in your life — or about you, if you have stepped into a teaching or guiding role. King of Wands reversed spiritually asks where charisma has been allowed to substitute for character. A teacher's authority is on loan from the lineage and from the students who consent to it. The moment it starts being claimed as personal property, things go wrong.

For practitioners not in leadership, this card can describe spiritual arrogance — the conviction that your way is the way, deployed with charm and certainty in conversations that did not invite it. Even the best spiritual frameworks become small when held with this kind of grip. The King of Wands reversed spiritually heals by remembering that the path is longer than your current chapter of it, and that the most powerful spiritual leaders, throughout history, have been disarmingly humble. Let your fire be visionary without being imperial. The universe rewards the difference.`,
    reversedFaqs: [
      { q: 'What does King of Wands reversed mean in love?', a: 'The King of Wands reversed in love describes controlling or domineering behaviour — leadership that has slid into rule-by-decree. Decisions made unilaterally, input invited but not heard, concerns dismissed as overreaction. If you are partnered with this energy, the card asks you to name the pattern. If you are this energy, it asks for the harder leadership of actually listening. Charisma cannot indefinitely cover for a refusal to share power. Real authority in love is conferred, not seized, and it must be re-earned every season.' },
      { q: 'Is King of Wands reversed a bad sign?', a: 'It is a serious sign that asks for honesty rather than a doomed one. The card describes leadership that has hardened into ego or vision that has tipped into authoritarianism. Read as feedback, it can prompt genuine repair — better listening, redistributed power, recovered humility. Ignored, it tends to produce real damage to relationships, teams and reputations. The King of Wands reversed is most dangerous when the practitioner refuses to hear it, and most healing when they actually do.' },
      { q: 'What does King of Wands reversed mean for ambition?', a: 'Reversed, the King of Wands shows ambition that has lost its checks. The vision is still bold; the willingness to be questioned has dropped, and decisions are getting worse without the input that used to refine them. The card asks for cultivated dissent — actively rewarding the colleagues, advisors or partners who tell you the uncomfortable truth. Ambition at its strongest is paired with humility about how often a single mind can be wrong. Stay visionary; stop being imperial. The two are not the same.' },
      { q: 'How do I work with King of Wands reversed in a reading?', a: 'Ask where the querent — or someone in their life — has confused vision with dominance. Look at surrounding cards for the cost: Cups for damaged trust, Swords for unspoken resentment in the team or relationship, Pentacles for material consequences of impulsive calls. Encourage one specific act of power-sharing this week: a question genuinely asked, a decision genuinely delegated, an apology genuinely offered. The King of Wands reversed heals through redistributed authority far more than through louder leadership.' },
    ],
  },
}
