export type CardSuit = 'major' | 'wands' | 'cups' | 'swords' | 'pentacles'
export type YesNo = 'yes' | 'no' | 'maybe'

export interface Card {
  id: number; name: string; slug: string; suit: CardSuit; suitLabel: string;
  number: string; symbol: string; element: string; yn: YesNo; yn_exp: string;
  kw_up: string[]; kw_rev: string[]; up: string; rev: string;
  love: string; career: string; spirit: string;
}

export const CARDS: Card[] = [
  { id:0, name:'The Fool', slug:'the-fool', suit:'major', suitLabel:'Major Arcana',
    number:'0', symbol:'🌟', element:'Air',
    yn:'yes', yn_exp:'The Fool says yes — leap forward with trust. New beginnings await those who dare to start.',
    kw_up:['beginnings', 'spontaneity', 'innocence', 'potential', 'adventure'],
    kw_rev:['recklessness', 'naivety', 'foolishness', 'risk', 'chaos'],
    up:'The Fool marks the start of a brand new journey. You are stepping into the unknown with openness and a willingness to experience life fully. Trust the process — what looks like a risk is actually an invitation to grow.',
    rev:'Recklessness or naivety may be leading you astray. You might be taking unnecessary risks without thinking through the consequences. Pause, ground yourself, and consider whether you have enough information before leaping.',
    love:'An exciting new romantic beginning or a carefree energy in your relationship. Stay open-hearted but aware.',
    career:'A bold new opportunity or career change is on the horizon. Take the leap — but have a basic plan.',
    spirit:'You are being invited into a fresh spiritual awakening. Approach your practice with beginner\'s mind.' },
  { id:1, name:'The Magician', slug:'the-magician', suit:'major', suitLabel:'Major Arcana',
    number:'I', symbol:'⚗️', element:'Air',
    yn:'yes', yn_exp:'The Magician is a powerful yes — you have everything you need to make it happen right now.',
    kw_up:['willpower', 'skill', 'manifestation', 'resourcefulness', 'action'],
    kw_rev:['manipulation', 'untapped talent', 'deception', 'wasted potential'],
    up:'The Magician tells you that all the tools, skills and resources you need are already in your hands. Now is the time to focus your will and take deliberate action. What you can conceive, you can create.',
    rev:'Your talents may be going to waste, or someone around you may be using manipulation to get what they want. Check your intentions — are you using your gifts wisely and honestly?',
    love:'You have the power to attract the relationship you desire. Be intentional about what you want and communicate it clearly.',
    career:'Your skills are at their peak. Now is the ideal time to pitch that idea, launch the project or ask for the promotion.',
    spirit:'You are a channel for higher wisdom. Your spiritual practice has real power — use it with intention and integrity.' },
  { id:2, name:'The High Priestess', slug:'the-high-priestess', suit:'major', suitLabel:'Major Arcana',
    number:'II', symbol:'🌙', element:'Water',
    yn:'maybe', yn_exp:'The High Priestess says maybe — not everything is revealed yet. Go inward before you decide.',
    kw_up:['intuition', 'mystery', 'inner knowing', 'patience', 'subconscious'],
    kw_rev:['secrets', 'hidden agendas', 'surface thinking', 'repressed feelings'],
    up:'The High Priestess urges you to be still and listen to the quiet voice within. Not all answers come through logic — some truths can only be felt. Trust your gut even when you cannot fully explain it.',
    rev:'Important information may be hidden from you, or you may be ignoring your intuition in favour of what seems rational. Secrets and hidden agendas could be at play.',
    love:'There is more beneath the surface of your relationship. Avoid rushing to conclusions — let things reveal themselves naturally.',
    career:'Not the right time to make a big move. Gather information quietly, observe, and wait for clarity before acting.',
    spirit:'Deepen your meditation and reflective practice. The answers you seek are already within you.' },
  { id:3, name:'The Empress', slug:'the-empress', suit:'major', suitLabel:'Major Arcana',
    number:'III', symbol:'🌿', element:'Earth',
    yn:'yes', yn_exp:'The Empress is a warm yes — abundance, growth and nurturing energy surround your question.',
    kw_up:['abundance', 'nurture', 'creativity', 'fertility', 'beauty'],
    kw_rev:['creative block', 'dependence', 'smothering', 'neglect'],
    up:'The Empress radiates abundance, creativity and maternal warmth. This is a time to nurture your projects, relationships and yourself. Growth is natural and assured when you tend to it with love and patience.',
    rev:'You may be neglecting your own needs or smothering those around you. Creative blocks or a sense of lack could be present. Return to self-care and allow yourself to receive as well as give.',
    love:'Deep romantic fulfillment, sensuality and possibly a significant development in your love life — even pregnancy or a new family chapter.',
    career:'Your creative work flourishes now. Abundance and success come through nurturing your ideas rather than forcing them.',
    spirit:'Connect with the natural world. The earth, seasons and your body are your most powerful spiritual teachers right now.' },
  { id:4, name:'The Emperor', slug:'the-emperor', suit:'major', suitLabel:'Major Arcana',
    number:'IV', symbol:'🏛️', element:'Fire',
    yn:'yes', yn_exp:'The Emperor is a confident yes — take charge, establish structure and lead with authority.',
    kw_up:['authority', 'structure', 'stability', 'leadership', 'discipline'],
    kw_rev:['rigidity', 'control', 'domination', 'inflexibility', 'tyranny'],
    up:'The Emperor calls you to step into your power with discipline and clear intention. Build on solid foundations, establish order and take responsibility for your domain. Leadership and structure will serve you well.',
    rev:'Excessive control or rigidity may be creating problems. Power could be abused — either by you or someone around you. Loosen your grip and allow some flexibility.',
    love:'Stability and commitment are highlighted. A strong, protective partnership — but watch for controlling dynamics.',
    career:'A strong yes for ambition and authority. Build systems, set clear goals and assert your expertise confidently.',
    spirit:'Discipline in your spiritual practice will yield profound results. Structure is not the enemy of transcendence — it is its foundation.' },
  { id:5, name:'The Hierophant', slug:'the-hierophant', suit:'major', suitLabel:'Major Arcana',
    number:'V', symbol:'🕊️', element:'Earth',
    yn:'maybe', yn_exp:'The Hierophant says maybe — align with your deeper values and established wisdom before deciding.',
    kw_up:['tradition', 'guidance', 'belief', 'convention', 'mentorship'],
    kw_rev:['rebellion', 'dogma', 'unconventional path', 'challenging norms'],
    up:'The Hierophant invites you to seek wisdom through established traditions, a trusted teacher or your own deeply held values. This is a time for spiritual study, ritual and aligning your choices with your highest principles.',
    rev:'You may be feeling stifled by convention or called to break from tradition. It is time to question inherited beliefs and find what is authentically true for you.',
    love:'A conventional, committed relationship is favoured. Marriage or a deepening of shared values is indicated.',
    career:'Working within established institutions or mentorship structures serves you well now. Credentials and experience matter.',
    spirit:'Formal spiritual study, joining a community or working with a teacher or guide will deepen your path right now.' },
  { id:6, name:'The Lovers', slug:'the-lovers', suit:'major', suitLabel:'Major Arcana',
    number:'VI', symbol:'❤️', element:'Air',
    yn:'yes', yn_exp:'The Lovers say yes — especially in matters of the heart. Align your choice with your deepest values.',
    kw_up:['love', 'alignment', 'choice', 'connection', 'values'],
    kw_rev:['imbalance', 'misalignment', 'temptation', 'avoidance', 'conflict'],
    up:'The Lovers speak of deep connection, meaningful choice and alignment between heart and values. A significant relationship or decision is at hand — choose from your authentic self, not from fear or pressure.',
    rev:'A relationship may be out of balance, or you are avoiding a difficult but necessary choice. Temptation or values misalignment could be creating inner conflict.',
    love:'A powerful romantic connection, soulmate energy or a key decision about commitment. Follow your heart\'s deepest truth.',
    career:'A choice between two paths or projects. Pick what truly aligns with your values, not just the most comfortable option.',
    spirit:'Integration of opposites within yourself — head and heart, shadow and light. True union begins within.' },
  { id:7, name:'The Chariot', slug:'the-chariot', suit:'major', suitLabel:'Major Arcana',
    number:'VII', symbol:'⚡', element:'Water',
    yn:'yes', yn_exp:'The Chariot is a strong yes — victory comes through focused will, discipline and forward momentum.',
    kw_up:['determination', 'victory', 'control', 'willpower', 'momentum'],
    kw_rev:['lack of direction', 'aggression', 'scattered energy', 'defeat'],
    up:'The Chariot signals that victory is within reach — but it requires focused will, discipline and the ability to manage opposing forces. You have the strength to overcome obstacles. Keep your eyes on the destination.',
    rev:'You may be moving in too many directions at once, or aggression and ego are getting in the way of progress. Regain control of your emotions and refocus your direction.',
    love:'Pursuing love with confidence and intention. Do not wait for things to happen — take the wheel.',
    career:'Push forward with conviction. A competitive situation or challenge can be won through sheer determination.',
    spirit:'Harness your willpower in service of spiritual growth. Discipline and dedication will carry you far.' },
  { id:8, name:'Strength', slug:'strength', suit:'major', suitLabel:'Major Arcana',
    number:'VIII', symbol:'🦁', element:'Fire',
    yn:'yes', yn_exp:'Strength says yes — approach your situation with courage, compassion and quiet confidence.',
    kw_up:['courage', 'patience', 'compassion', 'inner strength', 'resilience'],
    kw_rev:['self-doubt', 'weakness', 'insecurity', 'fear', 'suppression'],
    up:'True strength is not force — it is the quiet courage to face challenges with grace, patience and compassion. You have more inner resources than you realise. Approach your situation with gentleness rather than aggression.',
    rev:'Self-doubt and insecurity may be holding you back. You might be suppressing emotions that need to be acknowledged. Be kinder to yourself.',
    love:'A relationship built on genuine care, patience and emotional maturity. Love through understanding, not control.',
    career:'You can handle difficult people and challenges through diplomacy and inner poise. Your composure is your greatest asset.',
    spirit:'The spiritual warrior does not fight — they endure with love. Your compassion is your greatest spiritual gift.' },
  { id:9, name:'The Hermit', slug:'the-hermit', suit:'major', suitLabel:'Major Arcana',
    number:'IX', symbol:'🕯️', element:'Earth',
    yn:'maybe', yn_exp:'The Hermit says maybe — the answer requires solitude and inner reflection before it becomes clear.',
    kw_up:['solitude', 'introspection', 'inner guidance', 'wisdom', 'retreat'],
    kw_rev:['isolation', 'withdrawal', 'loneliness', 'avoidance', 'lost'],
    up:'The Hermit calls you inward. Step away from the noise of the world and seek your own inner light. This is a time for honest self-examination, meditation and the wisdom that only silence can reveal.',
    rev:'You may be withdrawing from life in an unhealthy way, or refusing to look honestly at yourself. Isolation has become avoidance. Find the courage to re-engage.',
    love:'A period of introspection about what you truly need in love. Solitude before connection. Know yourself first.',
    career:'A time for careful analysis rather than action. Research, planning and quiet focus will serve you better than bold moves.',
    spirit:'A profound period of spiritual awakening through solitude. Meditation, journaling and nature walks are your teachers now.' },
  { id:10, name:'Wheel of Fortune', slug:'wheel-of-fortune', suit:'major', suitLabel:'Major Arcana',
    number:'X', symbol:'☸️', element:'Fire',
    yn:'yes', yn_exp:'The Wheel of Fortune says yes — change is already in motion. Trust the natural cycle turning in your favour.',
    kw_up:['change', 'cycles', 'fate', 'turning point', 'luck'],
    kw_rev:['bad luck', 'resistance', 'stagnation', 'clinging to the past'],
    up:'The Wheel of Fortune signals a turning point — circumstances are shifting in your favour. What has felt stuck begins to move. Trust that the universe has a plan, even if you cannot see the full picture yet.',
    rev:'You may be resisting inevitable change, or feeling like fate is working against you. Rather than fighting the current, look for the lesson in the difficulty.',
    love:'A significant turning point in your love life. New romantic opportunities or a relationship reaching a new chapter.',
    career:'A lucky break, unexpected opportunity or shift in your career trajectory. Be ready to move when the moment comes.',
    spirit:'Life is cyclical — all things pass and return. Embrace impermanence as a spiritual truth, not a threat.' },
  { id:11, name:'Justice', slug:'justice', suit:'major', suitLabel:'Major Arcana',
    number:'XI', symbol:'⚖️', element:'Air',
    yn:'maybe', yn_exp:'Justice says maybe — the outcome depends on honesty and whether your actions have been fair and grounded in truth.',
    kw_up:['truth', 'fairness', 'cause and effect', 'accountability', 'clarity'],
    kw_rev:['injustice', 'dishonesty', 'avoidance', 'imbalance', 'bias'],
    up:'Justice demands truth, fairness and accountability. A situation is being weighed carefully — the outcome will reflect the choices that have been made. Act with integrity and trust that what is right will prevail.',
    rev:'There may be injustice at play, or a refusal to accept responsibility for past actions. Dishonesty will not hold up under scrutiny for long.',
    love:'Fairness and honesty are the foundations of a healthy relationship. Address any imbalances with open communication.',
    career:'Contracts, legal matters or performance reviews are highlighted. Act with complete integrity and document everything.',
    spirit:'Karmic balance is at play. Every thought and action has a consequence — align your daily choices with your highest values.' },
  { id:12, name:'The Hanged Man', slug:'the-hanged-man', suit:'major', suitLabel:'Major Arcana',
    number:'XII', symbol:'🌀', element:'Water',
    yn:'no', yn_exp:'The Hanged Man says not yet — pause, surrender, and allow a new perspective to emerge before acting.',
    kw_up:['pause', 'surrender', 'new perspective', 'letting go', 'patience'],
    kw_rev:['resistance', 'stalling', 'martyrdom', 'indecision', 'avoidance'],
    up:'The Hanged Man asks you to stop, surrender, and see things from an entirely different angle. What looks like a delay is actually a profound gift — a chance to gain the perspective that will change everything.',
    rev:'You may be stalling or resisting necessary change, perhaps even playing the victim. The suspension you are experiencing is of your own making. Let go of what no longer serves.',
    love:'A pause in love — not a dead end, but a necessary rethinking. Release control and allow the relationship to breathe.',
    career:'This is not the time to push or force results. Step back, reconsider your approach and wait for greater clarity.',
    spirit:'Deep spiritual insight comes through surrender, not effort. Release your grip on outcomes and let Spirit move through you.' },
  { id:13, name:'Death', slug:'death', suit:'major', suitLabel:'Major Arcana',
    number:'XIII', symbol:'🌑', element:'Water',
    yn:'no', yn_exp:'Death says no to what was — but yes to transformation. An ending is clearing space for essential renewal.',
    kw_up:['transformation', 'endings', 'renewal', 'transition', 'release'],
    kw_rev:['resistance to change', 'stagnation', 'clinging', 'fear of endings'],
    up:'Death in tarot rarely means physical death — it heralds profound transformation. Something must end for something new to begin. This transition, though difficult, is deeply necessary and ultimately liberating.',
    rev:'You are resisting an inevitable ending and clinging to something that has already run its course. The longer you hold on, the more painful the eventual release will be.',
    love:'The end of one relationship chapter and the beginning of another. A relationship may conclude, or a significant transformation occurs within it.',
    career:'A career, role or project is coming to an end. Clear the old to make way for a more authentic path.',
    spirit:'Ego death and rebirth are core to the spiritual path. You are being called to shed old identity layers and emerge renewed.' },
  { id:14, name:'Temperance', slug:'temperance', suit:'major', suitLabel:'Major Arcana',
    number:'XIV', symbol:'🌊', element:'Fire',
    yn:'yes', yn_exp:'Temperance says yes — with patience and balance. The right blend of elements will bring the desired outcome.',
    kw_up:['balance', 'patience', 'moderation', 'integration', 'flow'],
    kw_rev:['imbalance', 'excess', 'lack of harmony', 'impatience', 'extremes'],
    up:'Temperance calls for balance, patience and the blending of opposites. Flow, do not force. The middle path between extremes leads to lasting harmony. Integration takes time but produces something far more durable.',
    rev:'You may be going to extremes or forcing a situation that needs time to develop naturally. Imbalance in lifestyle, relationships or thinking is causing disruption.',
    love:'A beautifully balanced relationship built on mutual respect, patience and genuine compatibility. Healing is possible if both are willing.',
    career:'Success comes through steady, measured effort rather than dramatic action. Collaboration and integration of different skills are favoured.',
    spirit:'You are on the path of alchemical integration — bringing together the disparate parts of yourself into a harmonious whole.' },
  { id:15, name:'The Devil', slug:'the-devil', suit:'major', suitLabel:'Major Arcana',
    number:'XV', symbol:'🔗', element:'Earth',
    yn:'no', yn_exp:'The Devil says no — what you are pursuing may be driven by fear, addiction or unhealthy attachment.',
    kw_up:['shadow', 'attachment', 'bondage', 'materialism', 'awareness'],
    kw_rev:['liberation', 'release', 'reclaiming power', 'breaking free', 'detachment'],
    up:'The Devil confronts you with your shadows — the habits, beliefs and attachments that keep you in chains. Awareness is the first step toward freedom. What are you giving your power away to?',
    rev:'You are breaking free from a pattern, addiction or toxic situation that has held you back. Reclaim your power — the chains were never as solid as they seemed.',
    love:'Unhealthy attachment, obsession or a toxic dynamic in the relationship. True intimacy requires freedom, not control.',
    career:'Greed, ego or a toxic work environment may be trapping you. Examine what you are sacrificing for material gain.',
    spirit:'Confront your shadow — the parts of yourself you have denied or suppressed. Integration, not avoidance, brings wholeness.' },
  { id:16, name:'The Tower', slug:'the-tower', suit:'major', suitLabel:'Major Arcana',
    number:'XVI', symbol:'🌩️', element:'Fire',
    yn:'no', yn_exp:'The Tower says no — a disruption is coming or needed. False structures must fall before truth can be built.',
    kw_up:['disruption', 'revelation', 'upheaval', 'sudden change', 'awakening'],
    kw_rev:['avoiding collapse', 'fear of change', 'internal disruption', 'delaying the inevitable'],
    up:'The Tower brings sudden, dramatic disruption — but it only demolishes what was built on false foundations. Though jarring, this upheaval reveals truth and creates the space needed for authentic rebuilding.',
    rev:'You may be avoiding an inevitable collapse or living in constant anxiety about potential disruption. The internal chaos needs to be addressed before it manifests externally.',
    love:'A sudden revelation or upheaval in the relationship. Hidden truths come to light. This crisis, though painful, can be clarifying.',
    career:'Sudden job loss, organisational upheaval or a project collapse. What is being destroyed was not built to last.',
    spirit:'A dramatic spiritual awakening that shatters your old worldview. What falls away was never your true foundation.' },
  { id:17, name:'The Star', slug:'the-star', suit:'major', suitLabel:'Major Arcana',
    number:'XVII', symbol:'✨', element:'Air',
    yn:'yes', yn_exp:'The Star is a beautiful yes — hope, healing and trust in the future. You are on the right path.',
    kw_up:['hope', 'healing', 'serenity', 'inspiration', 'faith'],
    kw_rev:['despair', 'disconnection', 'loss of faith', 'hopelessness', 'directionless'],
    up:'The Star arrives after storms to offer healing, hope and a renewed sense of direction. The universe is guiding you toward something genuinely good. Trust the process, believe in the journey, and let yourself be replenished.',
    rev:'You may be struggling to find hope or feeling cut off from any sense of purpose or divine guidance. Reconnect with beauty, nature and small moments of grace.',
    love:'Hope and healing in love. After difficulty, a tender, genuine connection is on its way — or currently deepening.',
    career:'Inspiration, vision and renewed purpose in your work. A creative breakthrough or a sense of meaningful direction returns.',
    spirit:'You are being guided and held by something greater than yourself. Trust in the benevolence of the universe right now.' },
  { id:18, name:'The Moon', slug:'the-moon', suit:'major', suitLabel:'Major Arcana',
    number:'XVIII', symbol:'🌙', element:'Water',
    yn:'no', yn_exp:'The Moon says no — too much is unclear or hidden right now. Wait for more light before making a decision.',
    kw_up:['illusion', 'the unconscious', 'dreams', 'confusion', 'intuition'],
    kw_rev:['clarity returning', 'fear releasing', 'deception exposed', 'misunderstanding resolved'],
    up:'The Moon casts long shadows and distorts reality. Not everything is as it appears. Hidden fears, unconscious patterns and illusions are rising to the surface. Pay close attention to your dreams and gut feelings.',
    rev:'Confusion is beginning to lift and a deception may be revealed. As the fog clears, you can finally see a situation more accurately.',
    love:'Confusion, fear or hidden feelings are complicating the relationship. Be honest about what you are projecting versus what is real.',
    career:'Do not sign anything or make major moves right now — things are not as they appear. Wait for clarity.',
    spirit:'Your unconscious is speaking loudly through dreams, symbols and synchronicities. Keep a dream journal and pay attention.' },
  { id:19, name:'The Sun', slug:'the-sun', suit:'major', suitLabel:'Major Arcana',
    number:'XIX', symbol:'☀️', element:'Fire',
    yn:'yes', yn_exp:'The Sun is an enthusiastic yes — clarity, joy and success shine brightly on your question.',
    kw_up:['joy', 'clarity', 'success', 'vitality', 'confidence'],
    kw_rev:['temporary setback', 'clouded optimism', 'inner child wounds', 'lack of clarity'],
    up:'The Sun radiates pure joy, clarity and success. This is one of the most positive cards in the deck. You are stepping into a period of vitality, confidence and authentic self-expression. Celebrate who you are.',
    rev:'A temporary dip in confidence or a situation that is not quite as bright as it appears. Inner child wounds or past disappointments may be dimming your light.',
    love:'Joy, warmth and a deeply fulfilling romantic connection. If you are single, confident self-expression attracts love naturally.',
    career:'Recognition, success and creative vitality in your work. You are shining in your field right now.',
    spirit:'Your spirit is radiant and expansive. This is a time of spiritual joy — embodied, present and full of gratitude.' },
  { id:20, name:'Judgement', slug:'judgement', suit:'major', suitLabel:'Major Arcana',
    number:'XX', symbol:'🎺', element:'Fire',
    yn:'yes', yn_exp:'Judgement says yes — you are being called to rise, forgive, and step fully into who you are becoming.',
    kw_up:['awakening', 'renewal', 'reckoning', 'calling', 'absolution'],
    kw_rev:['self-doubt', 'refusing the call', 'inability to forgive', 'ignoring the signal'],
    up:'Judgement heralds a profound awakening and a calling to rise above the past. You are being summoned to a higher version of yourself — release old judgements, forgive what needs forgiving and answer the call.',
    rev:'You may be doubting your worthiness or refusing to heed an important calling. Old guilt or self-judgement is keeping you stuck. It is time to forgive and move forward.',
    love:'A second chance, a significant reconciliation or a relationship that has reached a profound turning point of truth.',
    career:'A calling to your true purpose. You may receive recognition for past work, or feel a strong pull toward a completely different path.',
    spirit:'A spiritual awakening of significant proportion. You are being initiated into a new level of consciousness and purpose.' },
  { id:21, name:'The World', slug:'the-world', suit:'major', suitLabel:'Major Arcana',
    number:'XXI', symbol:'🌍', element:'Earth',
    yn:'yes', yn_exp:'The World is a resounding yes — completion, wholeness and achievement. You have arrived.',
    kw_up:['completion', 'wholeness', 'achievement', 'integration', 'success'],
    kw_rev:['incompletion', 'shortcuts', 'loose ends', 'delayed closure'],
    up:'The World celebrates the successful completion of a major cycle. You have integrated the lessons, done the work and arrived at a place of genuine wholeness. Honour what you have accomplished before stepping into the next great adventure.',
    rev:'Something is left incomplete or you are taking shortcuts to avoid the final steps. True closure requires finishing what has been started.',
    love:'A deeply fulfilling, complete relationship or a love story reaching its natural, joyful culmination.',
    career:'Major success, completion of a long-term project or achievement of a significant professional goal.',
    spirit:'You have achieved a level of integration and wholeness that is genuinely rare. Rest in this completion before beginning the next cycle.' },
  { id:22, name:'Ace of Wands', slug:'ace-of-wands', suit:'wands', suitLabel:'Wands',
    number:'Ace', symbol:'🔥', element:'Fire',
    yn:'yes', yn_exp:'Ace of Wands is a fiery yes — new creative energy and passion are ready to ignite.',
    kw_up:['inspiration', 'new beginnings', 'passion', 'creative spark', 'potential'],
    kw_rev:['delays', 'lack of motivation', 'creative block', 'false start'],
    up:'The Ace of Wands delivers a burst of creative fire and new beginnings. An exciting idea, project or opportunity is emerging — act on it while the energy is high. This is the moment to begin.',
    rev:'Creative energy is blocked or a new venture has stalled before it really started. Reignite your passion by returning to what truly excites you.',
    love:'A passionate, exciting new romance or a renewed spark in an existing relationship.',
    career:'A brilliant new idea, creative project or business opportunity is ready to launch.',
    spirit:'A new spiritual inspiration or awakening of your life purpose. Follow the fire.' },
  { id:23, name:'Two of Wands', slug:'two-of-wands', suit:'wands', suitLabel:'Wands',
    number:'2', symbol:'🔭', element:'Fire',
    yn:'yes', yn_exp:'Two of Wands says yes — you are in the planning phase and the path ahead is open.',
    kw_up:['planning', 'vision', 'future', 'expansion', 'decisions'],
    kw_rev:['fear of the unknown', 'lack of planning', 'limited perspective'],
    up:'The Two of Wands shows you standing at a crossroads with the world at your feet. You have a solid foundation — now it is time to plan your next bold move and think beyond your current horizon.',
    rev:'Fear of the unknown or lack of foresight is keeping you small. Expand your vision and trust in your ability to navigate new territory.',
    love:'Planning a future together or considering whether a relationship has long-term potential.',
    career:'Strategic planning, business expansion or a decision about taking your career international.',
    spirit:'You are being called to expand your spiritual horizons beyond familiar territory.' },
  { id:24, name:'Three of Wands', slug:'three-of-wands', suit:'wands', suitLabel:'Wands',
    number:'3', symbol:'⛵', element:'Fire',
    yn:'yes', yn_exp:'Three of Wands says yes — your ships are coming in. Expansion and reward are on the way.',
    kw_up:['expansion', 'foresight', 'growth', 'opportunities', 'reward'],
    kw_rev:['delays', 'obstacles', 'limited vision', 'frustration'],
    up:'The Three of Wands shows that what you set in motion is bearing fruit. Growth, expansion and rewards are coming — often from unexpected directions. Keep the faith and continue building.',
    rev:'Delays and frustrations are testing your patience. Broaden your perspective or seek help from outside your current circle.',
    love:'A relationship is growing and deepening. Long-distance love or international romance may be indicated.',
    career:'Business expansion, new markets or receiving results from past efforts.',
    spirit:'Your spiritual practice is beginning to bear tangible fruit. Stay consistent.' },
  { id:25, name:'Four of Wands', slug:'four-of-wands', suit:'wands', suitLabel:'Wands',
    number:'4', symbol:'🎊', element:'Fire',
    yn:'yes', yn_exp:'Four of Wands is a joyful yes — celebration, stability and a milestone are at hand.',
    kw_up:['celebration', 'home', 'milestone', 'stability', 'community'],
    kw_rev:['instability', 'conflict at home', 'transition', 'temporary setback'],
    up:'The Four of Wands invites you to celebrate a milestone, honour what you have built and enjoy the stability and warmth of community and home. A moment of genuine joy and completion deserves to be marked.',
    rev:'Domestic instability or a disruption to a celebratory moment. A transition period that requires flexibility.',
    love:'Celebration in love — engagement, moving in together or a significant romantic milestone.',
    career:'Recognition of your work, a project completion or team celebration.',
    spirit:'Gratitude practice, community and sacred ritual are powerful for you right now.' },
  { id:26, name:'Five of Wands', slug:'five-of-wands', suit:'wands', suitLabel:'Wands',
    number:'5', symbol:'⚔️', element:'Fire',
    yn:'no', yn_exp:'Five of Wands says no — there is too much conflict and competition blocking a clear path forward.',
    kw_up:['conflict', 'competition', 'tension', 'disagreement', 'chaos'],
    kw_rev:['resolution', 'end of conflict', 'avoiding confrontation', 'internal struggle'],
    up:'The Five of Wands brings chaotic energy, competition and conflicting forces. Multiple voices or egos are clashing. This is a challenge — but it can also be creative friction that, once channelled properly, leads to breakthroughs.',
    rev:'A conflict is resolving, or you are choosing to rise above the chaos rather than engage with it.',
    love:'Arguments, misunderstandings or competing needs creating friction in the relationship.',
    career:'Workplace competition, disagreements or a scramble for recognition. Stay focused on your own work.',
    spirit:'Internal conflict between different belief systems or values. Seek integration rather than choosing sides.' },
  { id:27, name:'Six of Wands', slug:'six-of-wands', suit:'wands', suitLabel:'Wands',
    number:'6', symbol:'🏆', element:'Fire',
    yn:'yes', yn_exp:'Six of Wands is a triumphant yes — success, recognition and public acclaim are coming.',
    kw_up:['victory', 'recognition', 'success', 'acclaim', 'pride'],
    kw_rev:['arrogance', 'private victory', 'delayed success', 'fall from grace'],
    up:'The Six of Wands heralds well-deserved recognition and victory. Your efforts are being acknowledged publicly. This is a moment to hold your head high and accept the reward that your hard work has earned.',
    rev:'Success may come quietly, or arrogance is diminishing a genuine achievement. Stay humble in victory.',
    love:'Being proud of your relationship or a partner who champions you publicly.',
    career:'Public recognition, promotion, award or a high-profile success.',
    spirit:'Your spiritual journey is beginning to positively influence and inspire those around you.' },
  { id:28, name:'Seven of Wands', slug:'seven-of-wands', suit:'wands', suitLabel:'Wands',
    number:'7', symbol:'🛡️', element:'Fire',
    yn:'maybe', yn_exp:'Seven of Wands says maybe — you can succeed, but it will require standing your ground against opposition.',
    kw_up:['perseverance', 'defense', 'courage', 'resilience', 'competition'],
    kw_rev:['giving up', 'overwhelm', 'self-doubt', 'backing down'],
    up:'The Seven of Wands calls you to hold your position under pressure. You have earned your place and others may challenge it — but you have every right to defend what you have built. Stand firm with confidence.',
    rev:'Exhaustion or self-doubt is making it hard to keep fighting. Consider whether this battle is worth the energy.',
    love:'Defending your relationship against outside interference or pressure from family.',
    career:'Competition or challenges to your position. Maintain your professional standards and hold your ground.',
    spirit:'Your beliefs and values are being tested. Stand firm in what you know to be true.' },
  { id:29, name:'Eight of Wands', slug:'eight-of-wands', suit:'wands', suitLabel:'Wands',
    number:'8', symbol:'🚀', element:'Fire',
    yn:'yes', yn_exp:'Eight of Wands is a swift yes — things are moving fast and momentum is in your favour.',
    kw_up:['swift movement', 'rapid progress', 'communication', 'travel', 'momentum'],
    kw_rev:['delays', 'miscommunication', 'frustration', 'haste'],
    up:'The Eight of Wands signals rapid movement and momentum after a period of waiting. Things are progressing quickly now — communications arrive, plans come together and travel or exciting news is likely. Go with the flow.',
    rev:'Delays, missed messages or moving too fast without thinking things through.',
    love:'Fast-moving romance, exciting news in a relationship, or a whirlwind connection.',
    career:'A project accelerates, news arrives quickly or travel for work is on the horizon.',
    spirit:'Rapid spiritual downloads, synchronicities and a sense of divine momentum carrying you forward.' },
  { id:30, name:'Nine of Wands', slug:'nine-of-wands', suit:'wands', suitLabel:'Wands',
    number:'9', symbol:'🏹', element:'Fire',
    yn:'maybe', yn_exp:'Nine of Wands says maybe — you are nearly there, but it requires one final push of courage.',
    kw_up:['resilience', 'persistence', 'last stand', 'courage', 'near completion'],
    kw_rev:['paranoia', 'rigidity', 'burnout', 'giving up near the finish line'],
    up:'The Nine of Wands shows battle-worn resilience. You have come so far and faced so much — and you are nearly at the finish line. Dig deep for that last reserve of courage. You can do this.',
    rev:'Exhaustion, paranoia or stubbornness may be making the final stretch harder than it needs to be. Ask for support.',
    love:'Past relationship wounds are making it hard to trust. Healing is needed before full openness is possible.',
    career:'Perseverance in the face of setbacks. Do not give up when you are this close to your goal.',
    spirit:'Spiritual endurance. The dark night of the soul is nearly over — keep going.' },
  { id:31, name:'Ten of Wands', slug:'ten-of-wands', suit:'wands', suitLabel:'Wands',
    number:'10', symbol:'🪵', element:'Fire',
    yn:'no', yn_exp:'Ten of Wands says no — you are carrying too much right now to take on anything more.',
    kw_up:['burden', 'responsibility', 'hard work', 'completion', 'overload'],
    kw_rev:['releasing burden', 'delegating', 'unable to let go', 'burnout'],
    up:'The Ten of Wands shows you carrying a heavy load. You have taken on too much and the weight is becoming unsustainable. It is time to reassess, delegate and release some of your responsibilities.',
    rev:'You are beginning to put down the weight, or you are struggling to let go of burdens you no longer need to carry.',
    love:'Feeling weighed down in the relationship or taking on too much emotional responsibility.',
    career:'Overwork and burnout. You cannot do everything alone — delegate and prioritise ruthlessly.',
    spirit:'The burden of perfectionism or over-responsibility is blocking your spiritual lightness. Learn to surrender.' },
  { id:32, name:'Page of Wands', slug:'page-of-wands', suit:'wands', suitLabel:'Wands',
    number:'Page', symbol:'🌱', element:'Fire',
    yn:'yes', yn_exp:'Page of Wands says yes — approach with enthusiasm, curiosity and a willingness to learn.',
    kw_up:['enthusiasm', 'curiosity', 'new ideas', 'exploration', 'creative energy'],
    kw_rev:['lack of direction', 'hasty', 'immaturity', 'unfocused energy'],
    up:'The Page of Wands arrives with creative enthusiasm and an eagerness to explore. A fresh idea or passion project is sparking. Approach it with curiosity and don\'t worry about getting it perfect — just begin.',
    rev:'Scattered energy, jumping from idea to idea without follow-through. Focus and patience are needed.',
    love:'A flirtatious, playful and exciting new romantic energy.',
    career:'A new creative idea, internship or the very beginning of an exciting project.',
    spirit:'A fresh, enthusiastic approach to your spiritual path. Study, explore, try new practices.' },
  { id:33, name:'Knight of Wands', slug:'knight-of-wands', suit:'wands', suitLabel:'Wands',
    number:'Knight', symbol:'🏇', element:'Fire',
    yn:'yes', yn_exp:'Knight of Wands says yes — act boldly, move fast and trust your passion.',
    kw_up:['action', 'adventure', 'passion', 'boldness', 'energy'],
    kw_rev:['impulsiveness', 'recklessness', 'anger', 'scattered'],
    up:'The Knight of Wands charges forward with passion and fearlessness. This is the energy of inspired action — bold, fast and driven by genuine enthusiasm. The time to act is now.',
    rev:'Impulsive decisions and reckless behaviour are creating problems. Slow down and think before you charge.',
    love:'An exciting, passionate and adventurous romantic energy — or someone sweeping you off your feet.',
    career:'A bold career move, entrepreneurial energy or rapid advancement through sheer drive.',
    spirit:'Passionate, active spiritual practice. Pilgrimage, retreats or vigorous study call to you.' },
  { id:34, name:'Queen of Wands', slug:'queen-of-wands', suit:'wands', suitLabel:'Wands',
    number:'Queen', symbol:'🌻', element:'Fire',
    yn:'yes', yn_exp:'Queen of Wands says yes — confidence, charisma and warmth will carry you to success.',
    kw_up:['confidence', 'charisma', 'warmth', 'independence', 'passion'],
    kw_rev:['jealousy', 'selfishness', 'demanding', 'burnout', 'insecurity'],
    up:'The Queen of Wands is boldly herself — confident, warm, creative and magnetically charismatic. She leads with heart and presence. Step into your own authority and let your authentic nature shine.',
    rev:'Jealousy, self-centredness or burnout may be dimming your natural radiance. Return to what lights you up.',
    love:'Passionate, confident love. Someone who knows their worth attracting what they deserve.',
    career:'Creative leadership, entrepreneurship and the courage to be fully yourself in your professional life.',
    spirit:'Embody your spiritual gifts with confidence. Share your light — it is time to stop hiding it.' },
  { id:35, name:'King of Wands', slug:'king-of-wands', suit:'wands', suitLabel:'Wands',
    number:'King', symbol:'👑', element:'Fire',
    yn:'yes', yn_exp:'King of Wands says yes — lead with vision, courage and charisma.',
    kw_up:['leadership', 'vision', 'entrepreneurship', 'boldness', 'inspiration'],
    kw_rev:['arrogance', 'impulsiveness', 'forceful', 'domineering'],
    up:'The King of Wands is a master of vision and inspired leadership. He acts boldly, leads by example and brings others along through sheer charisma and competence. Take the lead — others will follow.',
    rev:'Arrogance, domineering behaviour or impulsive decisions are undermining your leadership.',
    love:'A confident, passionate partner who leads and protects. Or embracing your own leadership in love.',
    career:'Entrepreneurial success, executive leadership or launching a major creative venture.',
    spirit:'Spiritual leadership and the courage to teach, guide or inspire others on their path.' },
  { id:36, name:'Ace of Cups', slug:'ace-of-cups', suit:'cups', suitLabel:'Cups',
    number:'Ace', symbol:'💧', element:'Water',
    yn:'yes', yn_exp:'Ace of Cups says yes — emotional new beginnings, love and heartfelt connection are flowing in.',
    kw_up:['new love', 'emotional beginning', 'compassion', 'creativity', 'intuition'],
    kw_rev:['blocked emotions', 'repressed feelings', 'emotional loss', 'emptiness'],
    up:'The Ace of Cups overflows with love, compassion and new emotional beginnings. An open heart invites deep connection, creative inspiration and spiritual nourishment. Allow yourself to feel fully.',
    rev:'Emotional blocks or repressed feelings are preventing true connection. Something is stopping you from opening your heart.',
    love:'A beautiful new love or a profound emotional deepening in an existing relationship.',
    career:'Creative inspiration, meaningful work and emotionally satisfying projects.',
    spirit:'Spiritual love and compassion are opening within you. The heart is your greatest guide.' },
  { id:37, name:'Two of Cups', slug:'two-of-cups', suit:'cups', suitLabel:'Cups',
    number:'2', symbol:'🥂', element:'Water',
    yn:'yes', yn_exp:'Two of Cups says yes — connection, partnership and mutual attraction are flowing between you.',
    kw_up:['partnership', 'connection', 'attraction', 'harmony', 'union'],
    kw_rev:['imbalance', 'breakup', 'disconnection', 'incompatibility'],
    up:'The Two of Cups celebrates a powerful connection between two people — romantic or otherwise. There is genuine mutual attraction, respect and a sense of coming home to each other. This union has real potential.',
    rev:'A relationship falling out of balance, or incompatibility becoming apparent despite initial attraction.',
    love:'A soulmate connection, deepening romance or a relationship that feels mutually fulfilling and balanced.',
    career:'A highly compatible business partnership or a colleague who becomes a trusted ally.',
    spirit:'The sacred meeting of two souls. Spiritual partnership and the union of inner masculine and feminine.' },
  { id:38, name:'Three of Cups', slug:'three-of-cups', suit:'cups', suitLabel:'Cups',
    number:'3', symbol:'🎉', element:'Water',
    yn:'yes', yn_exp:'Three of Cups says yes — celebration, friendship and joyful community support your situation.',
    kw_up:['celebration', 'friendship', 'community', 'joy', 'reunion'],
    kw_rev:['overindulgence', 'gossip', 'third-party interference', 'isolation'],
    up:'The Three of Cups is pure celebration — joy shared with friends and community. A reason to celebrate is here or coming. Honour the connections that lift you up and allow yourself to receive the love of your tribe.',
    rev:'Overindulgence, gossip within a social circle or a third party creating complications.',
    love:'Celebrating love with friends, a reunion or a new romantic connection made through your social circle.',
    career:'Team success, office celebration or a collaborative project reaching completion.',
    spirit:'Spiritual community and the joy of shared devotion. Seek your people.' },
  { id:39, name:'Four of Cups', slug:'four-of-cups', suit:'cups', suitLabel:'Cups',
    number:'4', symbol:'🫙', element:'Water',
    yn:'no', yn_exp:'Four of Cups says no — apathy or self-absorption may be causing you to miss what is right in front of you.',
    kw_up:['apathy', 'contemplation', 'withdrawal', 'missed opportunity', 'introspection'],
    kw_rev:['re-engagement', 'new perspective', 'clarity', 'openness'],
    up:'The Four of Cups signals emotional withdrawal and apathy. You may be so caught up in what you don\'t have that you are missing an opportunity that is being offered to you. Look up from your inner world.',
    rev:'You are shaking off apathy and beginning to re-engage with life\'s possibilities. A new opportunity catches your attention.',
    love:'Emotional withdrawal or taking a partner for granted. Practice gratitude for what you have.',
    career:'Boredom or disengagement at work. A new opportunity is being offered — are you too focused inward to see it?',
    spirit:'Spiritual stagnation caused by self-absorption. Open your eyes to the gift that is being extended.' },
  { id:40, name:'Five of Cups', slug:'five-of-cups', suit:'cups', suitLabel:'Cups',
    number:'5', symbol:'😢', element:'Water',
    yn:'no', yn_exp:'Five of Cups says no — grief and loss are clouding the picture. Healing must come first.',
    kw_up:['grief', 'loss', 'regret', 'disappointment', 'mourning'],
    kw_rev:['acceptance', 'healing', 'moving on', 'finding hope'],
    up:'The Five of Cups dwells in loss and regret — but there are still cups standing behind you. Grief deserves to be felt, but do not let it be the only story. When you are ready, turn around and see what remains.',
    rev:'You are beginning to accept a loss and find the strength to move forward. Hope is returning.',
    love:'Grief over a relationship ending or a disappointment in love. Allow the mourning before you can truly move on.',
    career:'Disappointment, loss or a project not going as hoped. Look for what can still be salvaged.',
    spirit:'The dark emotions — grief, loss, regret — are also spiritual teachers. Let yourself feel them.' },
  { id:41, name:'Six of Cups', slug:'six-of-cups', suit:'cups', suitLabel:'Cups',
    number:'6', symbol:'🌸', element:'Water',
    yn:'yes', yn_exp:'Six of Cups says yes — nostalgia, reunion and the sweetness of the past are supporting you now.',
    kw_up:['nostalgia', 'childhood', 'reunion', 'innocence', 'kindness'],
    kw_rev:['living in the past', 'naivety', 'moving forward', 'leaving home'],
    up:'The Six of Cups brings a warm wave of nostalgia and the sweetness of cherished memories. A reunion, a return to a familiar place or an act of genuine kindness is indicated. Innocence and goodwill surround you.',
    rev:'You may be stuck in nostalgia or refusing to grow beyond the past. It is time to take the best of your history forward.',
    love:'A reunion with a past love, a childhood sweetheart resurfacing or a relationship filled with genuine sweetness.',
    career:'Returning to a previous employer, a mentorship from the past or work with children or community.',
    spirit:'Healing the inner child. Past lives and ancestral patterns may be relevant to your current path.' },
  { id:42, name:'Seven of Cups', slug:'seven-of-cups', suit:'cups', suitLabel:'Cups',
    number:'7', symbol:'✨', element:'Water',
    yn:'no', yn_exp:'Seven of Cups says no — too many illusions and fantasies are clouding your ability to see clearly.',
    kw_up:['fantasy', 'illusion', 'choices', 'wishful thinking', 'imagination'],
    kw_rev:['clarity', 'making a choice', 'reality check', 'focus'],
    up:'The Seven of Cups presents a dizzying array of possibilities — but not all that glitters is real. Wishful thinking and illusions may be distracting you from what is genuinely achievable. Get grounded before you choose.',
    rev:'The fog is clearing and you are gaining the clarity needed to make a real, grounded choice.',
    love:'Fantasy vs. reality in love. Be honest with yourself about whether you are seeing your relationship as it truly is.',
    career:'Too many ideas, a lack of focus or being seduced by get-rich-quick thinking.',
    spirit:'Spiritual escapism or becoming lost in fantasies of enlightenment rather than doing the actual work.' },
  { id:43, name:'Eight of Cups', slug:'eight-of-cups', suit:'cups', suitLabel:'Cups',
    number:'8', symbol:'🚶', element:'Water',
    yn:'no', yn_exp:'Eight of Cups says no — something needs to be left behind before you can move toward what truly fulfils you.',
    kw_up:['walking away', 'transition', 'soul searching', 'leaving', 'moving on'],
    kw_rev:['fear of moving on', 'staying too long', 'aimless wandering', 'returning'],
    up:'The Eight of Cups signals the courage to walk away from something that no longer feeds your soul, even when it is comfortable or familiar. A deeper calling is pulling you toward something more meaningful.',
    rev:'Fear of leaving or clinging to something long past its expiration date. Or a return to something you left behind.',
    love:'Leaving a relationship that no longer serves your soul, or feeling emotionally unfulfilled despite apparent stability.',
    career:'Leaving a stable but unfulfilling job to pursue something more meaningful.',
    spirit:'A spiritual pilgrimage — inner or outer — calling you away from the familiar toward something sacred.' },
  { id:44, name:'Nine of Cups', slug:'nine-of-cups', suit:'cups', suitLabel:'Cups',
    number:'9', symbol:'🌈', element:'Water',
    yn:'yes', yn_exp:'Nine of Cups says yes — this is the wish card. Your heart\'s desire is within reach.',
    kw_up:['wish fulfillment', 'contentment', 'satisfaction', 'gratitude', 'pleasure'],
    kw_rev:['dissatisfaction', 'greed', 'materialism', 'overindulgence'],
    up:'The Nine of Cups is known as the \'wish card\' — contentment, satisfaction and the fulfilment of your heart\'s deepest desire are close. Count your blessings and know that you are more fortunate than you may realise.',
    rev:'Material satisfaction without emotional fulfilment. Overindulgence or taking what you have for granted.',
    love:'Deep emotional satisfaction in love — or the arrival of the relationship you have wished for.',
    career:'Success and satisfaction in your professional life. What you have worked toward is coming to fruition.',
    spirit:'Deep spiritual contentment and a sense of genuine gratitude for the gift of life.' },
  { id:45, name:'Ten of Cups', slug:'ten-of-cups', suit:'cups', suitLabel:'Cups',
    number:'10', symbol:'🌈', element:'Water',
    yn:'yes', yn_exp:'Ten of Cups is a radiant yes — emotional fulfillment, lasting happiness and family harmony.',
    kw_up:['happiness', 'harmony', 'family', 'long-term fulfillment', 'love'],
    kw_rev:['broken home', 'disharmony', 'unrealistic expectations', 'values misalignment'],
    up:'The Ten of Cups represents the ultimate emotional fulfillment — a deeply happy family life, lasting love and a sense of belonging that nourishes the soul. This is what love and community look like at their very best.',
    rev:'Disruption to family harmony or a gap between the ideal picture and the reality of home life.',
    love:'A deeply happy, lasting and emotionally fulfilling partnership — possibly with children and a beautiful home.',
    career:'Work that is aligned with your values and supports the life you want to build with those you love.',
    spirit:'Heaven on earth — the spiritual ideal of love, connection and belonging made real in everyday life.' },
  { id:46, name:'Page of Cups', slug:'page-of-cups', suit:'cups', suitLabel:'Cups',
    number:'Page', symbol:'🐟', element:'Water',
    yn:'yes', yn_exp:'Page of Cups says yes — an intuitive message or creative emotional beginning is coming through.',
    kw_up:['intuition', 'creative message', 'sensitivity', 'dreams', 'emotional intelligence'],
    kw_rev:['emotional immaturity', 'escapism', 'unrealistic fantasies', 'blocked intuition'],
    up:'The Page of Cups brings a gentle, intuitive message from the heart. Creative ideas, prophetic dreams and tender emotional beginnings are present. Be open to the unexpected — something surprising and meaningful is emerging.',
    rev:'Emotional immaturity or escapism is blocking genuine connection. Ground your feelings before acting on them.',
    love:'A tender, heartfelt message or the beginning of a sweet and emotionally deep romance.',
    career:'A creative message or inspiration arrives. Trust your intuition about a new project or opportunity.',
    spirit:'Your intuition and psychic sensitivity are opening. Pay attention to dreams and inner promptings.' },
  { id:47, name:'Knight of Cups', slug:'knight-of-cups', suit:'cups', suitLabel:'Cups',
    number:'Knight', symbol:'🦢', element:'Water',
    yn:'yes', yn_exp:'Knight of Cups says yes — romance, creative pursuit and following your heart will be rewarded.',
    kw_up:['romance', 'charm', 'imagination', 'following the heart', 'creativity'],
    kw_rev:['moodiness', 'unrealistic', 'jealousy', 'over-idealisation'],
    up:'The Knight of Cups is the romantic idealist — pursuing love, beauty and creative inspiration with genuine feeling. Follow your heart\'s calling. What you are pursuing with sincerity and charm is worth chasing.',
    rev:'Over-idealisation, moodiness or pursuing something that looks beautiful but lacks substance.',
    love:'A romantic, charming suitor arriving, or a deeply heartfelt romantic gesture.',
    career:'Pursuing a creative career path with passion and emotional intelligence.',
    spirit:'A romantic quest for spiritual truth and beauty. Follow what moves your soul.' },
  { id:48, name:'Queen of Cups', slug:'queen-of-cups', suit:'cups', suitLabel:'Cups',
    number:'Queen', symbol:'🌊', element:'Water',
    yn:'yes', yn_exp:'Queen of Cups says yes — trust your emotional wisdom and lead with compassion.',
    kw_up:['compassion', 'emotional intelligence', 'intuition', 'nurturing', 'sensitivity'],
    kw_rev:['emotional overwhelm', 'codependency', 'insecurity', 'giving too much'],
    up:'The Queen of Cups is deeply emotionally intelligent, compassionate and intuitively wise. She knows how to hold space for others while staying true to her own inner world. Trust your emotional guidance — it is reliable.',
    rev:'Emotional overwhelm, giving too much at the expense of yourself, or being overly sensitive.',
    love:'Deeply empathic, nurturing love — someone who truly sees and holds you emotionally.',
    career:'Work in the caring professions, counselling, creativity or any field requiring emotional intelligence.',
    spirit:'The mystic who feels her way to truth. Intuition, prayer and emotional depth are your spiritual gifts.' },
  { id:49, name:'King of Cups', slug:'king-of-cups', suit:'cups', suitLabel:'Cups',
    number:'King', symbol:'🌊', element:'Water',
    yn:'yes', yn_exp:'King of Cups says yes — lead with emotional maturity, wisdom and calm authority.',
    kw_up:['emotional maturity', 'wisdom', 'diplomacy', 'compassion', 'balance'],
    kw_rev:['emotional manipulation', 'moodiness', 'suppression', 'cold'],
    up:'The King of Cups holds emotional mastery — he feels deeply but is not ruled by his feelings. He leads with wisdom, compassion and genuine authority. Bring this mature emotional intelligence to your current situation.',
    rev:'Emotional suppression, manipulation through feelings or someone whose mood swings create instability.',
    love:'A mature, emotionally available and genuinely caring partner who provides real security.',
    career:'Leadership with empathy, counselling, negotiation or creative direction.',
    spirit:'The spiritual elder — wise, compassionate and deeply experienced in the ways of the heart.' },
  { id:50, name:'Ace of Swords', slug:'ace-of-swords', suit:'swords', suitLabel:'Swords',
    number:'Ace', symbol:'⚔️', element:'Air',
    yn:'yes', yn_exp:'Ace of Swords says yes — clarity, truth and a breakthrough cut through the confusion.',
    kw_up:['clarity', 'truth', 'breakthrough', 'intellect', 'new idea'],
    kw_rev:['confusion', 'brutal truth', 'mental block', 'misinformation'],
    up:'The Ace of Swords brings razor-sharp clarity, truth and a decisive breakthrough. The fog lifts, the truth is revealed and a powerful new idea or direction emerges. Cut through illusion and speak your truth.',
    rev:'Mental confusion, a truth that cuts too harshly or a brilliant idea that needs more refinement before action.',
    love:'A conversation that clears the air — or a decision made with complete honesty.',
    career:'A breakthrough idea, a clear decision or the courage to speak difficult truths in a professional context.',
    spirit:'Mental clarity and the sword of discernment — the ability to cut through illusion and see what is real.' },
  { id:51, name:'Two of Swords', slug:'two-of-swords', suit:'swords', suitLabel:'Swords',
    number:'2', symbol:'🚫', element:'Air',
    yn:'no', yn_exp:'Two of Swords says no — you are in a stalemate. A decision must be made before things can move.',
    kw_up:['indecision', 'stalemate', 'avoidance', 'blocked perspective', 'truce'],
    kw_rev:['decision made', 'clarity', 'seeing both sides', 'release from stalemate'],
    up:'The Two of Swords shows you blindfolded at a crossroads, avoiding a difficult but necessary decision. The stalemate will not resolve itself. Take off the blindfold, face the truth, and make the choice.',
    rev:'The indecision is breaking. You are gaining the clarity and courage to finally make the move.',
    love:'Avoiding a difficult conversation or refusing to see the relationship clearly.',
    career:'A decision must be made between two paths or options. Avoid indefinite delay.',
    spirit:'Resisting a spiritual truth that requires you to change. The blindfold is self-imposed.' },
  { id:52, name:'Three of Swords', slug:'three-of-swords', suit:'swords', suitLabel:'Swords',
    number:'3', symbol:'💔', element:'Air',
    yn:'no', yn_exp:'Three of Swords says no — heartbreak, grief or painful truth are at the centre of this situation.',
    kw_up:['heartbreak', 'grief', 'loss', 'painful truth', 'separation'],
    kw_rev:['healing', 'recovery', 'forgiveness', 'releasing grief'],
    up:'The Three of Swords speaks of heartbreak, sorrow and painful truths that cannot be avoided. This pain is real and valid — allow yourself to grieve fully. In time, the tears will cleanse and the heart will heal.',
    rev:'A period of healing and recovery. Grief is lifting and forgiveness is becoming possible.',
    love:'Heartbreak, betrayal or a painful separation that requires genuine grieving.',
    career:'Disappointment, rejection or a painful professional setback.',
    spirit:'Grief as a spiritual teacher. The open wound eventually becomes wisdom.' },
  { id:53, name:'Four of Swords', slug:'four-of-swords', suit:'swords', suitLabel:'Swords',
    number:'4', symbol:'🛌', element:'Air',
    yn:'no', yn_exp:'Four of Swords says not yet — rest is required before any meaningful action can be taken.',
    kw_up:['rest', 'recovery', 'retreat', 'contemplation', 'recuperation'],
    kw_rev:['restlessness', 'burnout', 'inability to rest', 're-awakening'],
    up:'The Four of Swords commands you to stop and rest. Your mind and body need recovery time before the next challenge. This is not defeat — it is the wisdom to know that action without rest leads to collapse.',
    rev:'Restlessness, inability to truly rest, or beginning to slowly re-emerge after a period of recuperation.',
    love:'A needed break from relationship intensity. Space and quiet restore what urgency drains.',
    career:'Take a break before burnout forces one on you. Strategic retreat now prevents collapse later.',
    spirit:'Meditation, silence and retreat are essential medicine for your soul right now.' },
  { id:54, name:'Five of Swords', slug:'five-of-swords', suit:'swords', suitLabel:'Swords',
    number:'5', symbol:'⚔️', element:'Air',
    yn:'no', yn_exp:'Five of Swords says no — winning at all costs damages what matters most. Choose integrity over victory.',
    kw_up:['conflict', 'defeat', 'hollow victory', 'ego', 'betrayal'],
    kw_rev:['reconciliation', 'moving on', 'choosing battles wisely', 'guilt'],
    up:'The Five of Swords warns of a hollow victory — you may win the battle but lose something far more important. Ego-driven conflict creates lasting damage. Is this fight truly worth the cost?',
    rev:'A conflict is resolving, or you are recognising the cost of a previous battle and seeking reconciliation.',
    love:'A destructive argument, manipulation or someone winning at the expense of the relationship.',
    career:'Office politics, sabotage or a situation where someone is playing dirty.',
    spirit:'Choosing ego over integrity always comes at a spiritual cost. True victory requires honour.' },
  { id:55, name:'Six of Swords', slug:'six-of-swords', suit:'swords', suitLabel:'Swords',
    number:'6', symbol:'⛵', element:'Air',
    yn:'yes', yn_exp:'Six of Swords says yes — you are moving toward calmer waters. Transition and healing are underway.',
    kw_up:['transition', 'moving on', 'healing', 'calmer waters', 'travel'],
    kw_rev:['stuck', 'resistance to change', 'unable to move on', 'rough waters'],
    up:'The Six of Swords shows a journey away from turbulence toward calmer waters. The worst is behind you. This transition — physical or emotional — is necessary and healing. Trust the movement.',
    rev:'You are struggling to leave a difficult situation behind, or calm waters are still out of reach.',
    love:'Leaving a difficult relationship dynamic and moving toward emotional peace.',
    career:'A transition away from a difficult work environment, a resignation or a meaningful career change.',
    spirit:'A spiritual journey from chaos toward clarity and inner peace.' },
  { id:56, name:'Seven of Swords', slug:'seven-of-swords', suit:'swords', suitLabel:'Swords',
    number:'7', symbol:'🦊', element:'Air',
    yn:'no', yn_exp:'Seven of Swords says no — deception, hidden agendas or dishonesty are undermining the situation.',
    kw_up:['deception', 'strategy', 'sneakiness', 'hidden agenda', 'getting away with it'],
    kw_rev:['confession', 'being caught', 'conscience', 'coming clean'],
    up:'The Seven of Swords signals deception — either you or someone around you is not playing with full integrity. Hidden agendas, half-truths and strategic manoeuvring are at play. Proceed with eyes wide open.',
    rev:'A deception is being exposed, or a guilty conscience is prompting someone to come clean.',
    love:'Dishonesty, infidelity or someone not being fully transparent in the relationship.',
    career:'Intellectual theft, office politics or someone taking credit for your work. Document everything.',
    spirit:'The shadow side of intelligence — using cleverness for self-serving ends. Return to integrity.' },
  { id:57, name:'Eight of Swords', slug:'eight-of-swords', suit:'swords', suitLabel:'Swords',
    number:'8', symbol:'🪢', element:'Air',
    yn:'no', yn_exp:'Eight of Swords says no — you feel trapped, but the bonds are largely self-imposed. The way out exists.',
    kw_up:['restriction', 'trapped', 'powerlessness', 'self-imposed limits', 'victim mentality'],
    kw_rev:['liberation', 'release', 'seeing clearly', 'reclaiming power'],
    up:'The Eight of Swords shows you blindfolded and bound — but if you looked carefully, you would see the exit is nearby. The prison is largely mental. Question your assumptions about what is and is not possible.',
    rev:'You are breaking free from mental restrictions and seeing your situation with new clarity.',
    love:'Feeling trapped in a relationship or being held back by fear of being alone.',
    career:'Feeling stuck in a job or role through fear rather than genuine obligation.',
    spirit:'The mind creates its own cage. Liberation begins with questioning the beliefs that bind you.' },
  { id:58, name:'Nine of Swords', slug:'nine-of-swords', suit:'swords', suitLabel:'Swords',
    number:'9', symbol:'😰', element:'Air',
    yn:'no', yn_exp:'Nine of Swords says no — anxiety and worst-case thinking are overwhelming your judgment right now.',
    kw_up:['anxiety', 'nightmares', 'worry', 'mental anguish', 'fear'],
    kw_rev:['facing fears', 'releasing anxiety', 'clarity', 'moving through the dark night'],
    up:'The Nine of Swords is the card of anxiety and 3am worry spirals. The fears that torment you at night are often far worse than reality. Seek support, challenge catastrophic thinking, and know that dawn will come.',
    rev:'You are beginning to face your fears and release the grip of anxiety. Clarity and relief are coming.',
    love:'Anxiety about a relationship, fear of abandonment or sleepless nights worrying about love.',
    career:'Overwhelming work stress, imposter syndrome or fear of failure dominating your thinking.',
    spirit:'The dark night of the soul — a necessary spiritual trial that deepens compassion and wisdom.' },
  { id:59, name:'Ten of Swords', slug:'ten-of-swords', suit:'swords', suitLabel:'Swords',
    number:'10', symbol:'🌅', element:'Air',
    yn:'no', yn_exp:'Ten of Swords says no — a painful ending is occurring, but dawn follows every darkest moment.',
    kw_up:['painful endings', 'rock bottom', 'betrayal', 'crisis', 'new dawn'],
    kw_rev:['recovery', 'slow improvement', 'resistance to inevitable ending'],
    up:'The Ten of Swords marks a painful ending — a crisis, betrayal or collapse that feels devastating. But notice: in the background, the sun is rising. The very worst is over. This ending, though painful, clears the way.',
    rev:'A very slow or partial recovery, or resisting an ending that has already effectively occurred.',
    love:'A painful relationship ending or betrayal. The darkest moment before a new beginning.',
    career:'Job loss, project failure or professional crisis. The rock bottom from which you can only rise.',
    spirit:'Ego death. What falls away in the deepest darkness creates the space for spiritual rebirth.' },
  { id:60, name:'Page of Swords', slug:'page-of-swords', suit:'swords', suitLabel:'Swords',
    number:'Page', symbol:'💨', element:'Air',
    yn:'yes', yn_exp:'Page of Swords says yes — approach with curiosity, sharp thinking and a willingness to gather more information.',
    kw_up:['curiosity', 'intellect', 'communication', 'vigilance', 'news'],
    kw_rev:['gossip', 'haste', 'cynicism', 'scattered thinking'],
    up:'The Page of Swords is sharp, curious and alert — always watching, learning and gathering information. A quick-witted energy is called for. Be vigilant, ask good questions, and don\'t accept things at face value.',
    rev:'Gossip, hasty words or using sharp intelligence in cutting ways. Think before you speak.',
    love:'A curious, communicative and sometimes guarded energy in romance. Intellectual connection matters.',
    career:'Research, analysis, journalism or any field where sharp thinking and information-gathering are valued.',
    spirit:'Seeking spiritual truth through study, questioning and intellectual rigour.' },
  { id:61, name:'Knight of Swords', slug:'knight-of-swords', suit:'swords', suitLabel:'Swords',
    number:'Knight', symbol:'🗡️', element:'Air',
    yn:'maybe', yn_exp:'Knight of Swords says maybe — bold action is needed, but impulsiveness without strategy can backfire.',
    kw_up:['direct', 'fast', 'decisive', 'ambitious', 'intellectual'],
    kw_rev:['impulsive', 'reckless', 'argumentative', 'scattershot'],
    up:'The Knight of Swords charges forward with intellectual precision and decisive action. He is fast-thinking and fearless — but sometimes too hasty. Balance urgency with strategy for the best outcome.',
    rev:'Reckless, impulsive action or arguments that do more damage than good. Slow down and think.',
    love:'Direct communication, intellectual passion or a forceful personality who says exactly what they think.',
    career:'Fast-paced, decisive professional action. An opportunity requiring immediate and bold response.',
    spirit:'The seeker of truth who cuts through spiritual noise with sharp discernment.' },
  { id:62, name:'Queen of Swords', slug:'queen-of-swords', suit:'swords', suitLabel:'Swords',
    number:'Queen', symbol:'🧊', element:'Air',
    yn:'yes', yn_exp:'Queen of Swords says yes — apply clear thinking, direct communication and well-earned experience.',
    kw_up:['clarity', 'directness', 'independence', 'intellect', 'experience'],
    kw_rev:['coldness', 'bitterness', 'isolation', 'harsh judgment'],
    up:'The Queen of Swords sees clearly, speaks directly and has earned her wisdom the hard way. She does not fool herself and she does not tolerate fools. Approach your situation with honesty, clarity and self-sufficiency.',
    rev:'Coldness, bitterness or using sharp intelligence as a weapon rather than a tool.',
    love:'Independent and discerning in love — knowing what you want and not settling for less.',
    career:'Leadership through clarity and direct communication. No-nonsense, highly competent.',
    spirit:'The wisdom that comes from having moved through great difficulty with integrity intact.' },
  { id:63, name:'King of Swords', slug:'king-of-swords', suit:'swords', suitLabel:'Swords',
    number:'King', symbol:'⚖️', element:'Air',
    yn:'yes', yn_exp:'King of Swords says yes — act with intellectual authority, fairness and clear strategic thinking.',
    kw_up:['authority', 'intellect', 'truth', 'strategy', 'justice'],
    kw_rev:['tyranny', 'manipulation', 'cold judgment', 'abuse of power'],
    up:'The King of Swords commands through intellectual authority, strategic clarity and an unwavering commitment to truth. He is a master of the mind who leads with fairness and precision. Think clearly, speak carefully, decide firmly.',
    rev:'Using intellectual power manipulatively, ruthlessly or to dominate rather than serve.',
    love:'A partner who values truth, intelligence and directness above all else.',
    career:'Legal matters, leadership through strategy, academic authority or executive decision-making.',
    spirit:'The disciplined mind in service of truth is a powerful spiritual instrument.' },
  { id:64, name:'Ace of Pentacles', slug:'ace-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'Ace', symbol:'💰', element:'Earth',
    yn:'yes', yn_exp:'Ace of Pentacles says yes — a new material beginning, financial opportunity or grounded path is opening.',
    kw_up:['new opportunity', 'material beginning', 'abundance', 'prosperity', 'manifestation'],
    kw_rev:['missed opportunity', 'poor planning', 'financial setback', 'materialism'],
    up:'The Ace of Pentacles offers a tangible new beginning — a financial opportunity, a new job, a business idea or a practical foundation being laid. Take this offer seriously and build on it with diligence.',
    rev:'A financial opportunity missed or a practical project that has not been properly thought through.',
    love:'Building a stable, practical foundation for a relationship — security, commitment and long-term potential.',
    career:'A new job offer, financial opportunity or the beginning of a prosperous business venture.',
    spirit:'Grounding spiritual practice in the physical world. Service, bodywork and care for the earth.' },
  { id:65, name:'Two of Pentacles', slug:'two-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'2', symbol:'⚖️', element:'Earth',
    yn:'maybe', yn_exp:'Two of Pentacles says maybe — you are juggling multiple priorities and need to find better balance first.',
    kw_up:['balance', 'juggling', 'adaptability', 'time management', 'priorities'],
    kw_rev:['overwhelm', 'loss of balance', 'financial instability', 'poor time management'],
    up:'The Two of Pentacles shows the art of juggling competing priorities with grace and adaptability. You are managing multiple demands — the key is staying flexible and keeping a sense of humour about the chaos.',
    rev:'You are dropping balls and losing the ability to keep all the plates spinning. Prioritise ruthlessly.',
    love:'Balancing a relationship alongside other life demands. Be careful not to neglect what matters most.',
    career:'Multitasking, managing multiple projects or navigating financial fluctuations.',
    spirit:'Finding spiritual practice within the rhythms and demands of everyday life.' },
  { id:66, name:'Three of Pentacles', slug:'three-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'3', symbol:'🏗️', element:'Earth',
    yn:'yes', yn_exp:'Three of Pentacles says yes — collaboration, skill and teamwork will bring this to successful completion.',
    kw_up:['teamwork', 'skill', 'collaboration', 'planning', 'apprenticeship'],
    kw_rev:['disharmony', 'lack of teamwork', 'poor planning', 'mediocrity'],
    up:'The Three of Pentacles celebrates mastery through collaboration. Each person brings their unique skills to a shared vision, and the result is greater than any individual effort. Work well with others and honour expertise.',
    rev:'Poor teamwork, lack of planning or settling for mediocre results rather than reaching for excellence.',
    love:'Building a relationship through shared effort, values and a common vision for the future.',
    career:'Skilled teamwork, architectural thinking or apprenticeship under a true master.',
    spirit:'Spiritual community and the sacred geometry of shared creation.' },
  { id:67, name:'Four of Pentacles', slug:'four-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'4', symbol:'🤑', element:'Earth',
    yn:'no', yn_exp:'Four of Pentacles says no — fear of loss and clinging to security are blocking growth and generosity.',
    kw_up:['security', 'conservation', 'control', 'materialism', 'hoarding'],
    kw_rev:['generosity', 'releasing control', 'financial loss', 'openness'],
    up:'The Four of Pentacles grips its possessions tightly out of fear of loss. Security is important, but hoarding energy — whether financial or emotional — creates stagnation. Open your hands to receive by first letting go.',
    rev:'Financial loss or a breakthrough of generosity after a period of holding on too tightly.',
    love:'Emotional withholding, possessiveness or fear of vulnerability in the relationship.',
    career:'Excessive caution, unwillingness to invest or holding too tightly to old business models.',
    spirit:'Attachment to material comfort as a substitute for genuine spiritual security.' },
  { id:68, name:'Five of Pentacles', slug:'five-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'5', symbol:'❄️', element:'Earth',
    yn:'no', yn_exp:'Five of Pentacles says no — hardship, lack or isolation are the current reality that needs addressing first.',
    kw_up:['hardship', 'poverty', 'isolation', 'insecurity', 'lack'],
    kw_rev:['recovery', 'support arriving', 'finding help', 'improvement'],
    up:'The Five of Pentacles speaks of hardship — financial, physical or emotional. You may be feeling left out in the cold. Remember: help is closer than you think. Do not let pride prevent you from asking for it.',
    rev:'Financial or material recovery is underway. Help arrives or you find your way back inside from the cold.',
    love:'Feeling emotionally impoverished in a relationship or going through financial hardship together.',
    career:'Financial difficulty, job loss or an industry downturn affecting your livelihood.',
    spirit:'Spiritual poverty — feeling cut off from the divine. Seek community and human warmth.' },
  { id:69, name:'Six of Pentacles', slug:'six-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'6', symbol:'💝', element:'Earth',
    yn:'yes', yn_exp:'Six of Pentacles says yes — generosity flows in both directions. Give freely and receive gracefully.',
    kw_up:['generosity', 'giving', 'receiving', 'charity', 'balance'],
    kw_rev:['strings attached', 'debt', 'power imbalance', 'conditional giving'],
    up:'The Six of Pentacles celebrates the beautiful balance of giving and receiving. Generosity flows freely — you may be in a position to give or to receive. Both are acts of grace. Share what you have.',
    rev:'Giving with strings attached, a power imbalance in the exchange, or receiving charity that comes with conditions.',
    love:'Generosity, reciprocity and a beautifully balanced exchange of care and support.',
    career:'Philanthropy, grants, salary increases or a mentor who invests in your growth.',
    spirit:'The spiritual law of reciprocity — what you give with a full heart returns to you multiplied.' },
  { id:70, name:'Seven of Pentacles', slug:'seven-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'7', symbol:'🌱', element:'Earth',
    yn:'maybe', yn_exp:'Seven of Pentacles says maybe — you are in the waiting period. The harvest is coming but not yet here.',
    kw_up:['patience', 'long-term investment', 'harvest', 'assessment', 'perseverance'],
    kw_rev:['impatience', 'poor investment', 'lack of reward', 'giving up too soon'],
    up:'The Seven of Pentacles asks you to step back, assess your progress and trust that slow, steady growth will yield a meaningful harvest. This is not the moment of reward — but it is the moment of promise.',
    rev:'Impatience, poor return on investment or a project that is not growing as hoped.',
    love:'A relationship that is growing steadily — trust the slow build rather than rushing to conclusions.',
    career:'Long-term investment in skills, a business or a project that has not yet reached maturity.',
    spirit:'Spiritual growth is not linear. Trust the unseen development happening beneath the surface.' },
  { id:71, name:'Eight of Pentacles', slug:'eight-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'8', symbol:'🔨', element:'Earth',
    yn:'yes', yn_exp:'Eight of Pentacles says yes — dedicated effort and mastery of your craft will bring results.',
    kw_up:['diligence', 'skill', 'mastery', 'focus', 'craftsmanship'],
    kw_rev:['perfectionism', 'lack of focus', 'poor quality', 'monotony'],
    up:'The Eight of Pentacles celebrates dedicated, patient craftsmanship. You are honing your skills and doing the work with genuine care and focus. Mastery comes from exactly this kind of committed practice. Keep going.',
    rev:'Perfectionism paralysis, sloppy work or grinding repetition that has lost all meaning.',
    love:'Building a relationship through consistent, caring effort over time.',
    career:'Apprenticeship, skill development, meticulous work or professional mastery through sustained practice.',
    spirit:'Spiritual discipline and the sacred repetition of daily practice building genuine depth.' },
  { id:72, name:'Nine of Pentacles', slug:'nine-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'9', symbol:'🌷', element:'Earth',
    yn:'yes', yn_exp:'Nine of Pentacles says yes — self-sufficiency, abundance and well-deserved luxury are yours.',
    kw_up:['abundance', 'self-sufficiency', 'luxury', 'independence', 'reward'],
    kw_rev:['overwork', 'financial dependency', 'superficiality', 'hollow success'],
    up:'The Nine of Pentacles is a card of elegant self-sufficiency and hard-earned abundance. You have built something beautiful through your own efforts. Savour the rewards — you have earned this independence and luxury.',
    rev:'Success that came at too high a personal cost, or financial dependency undermining genuine independence.',
    love:'Loving yourself and your independent life — a strong foundation from which to attract a worthy partner.',
    career:'Financial independence, entrepreneurial success or a beautifully comfortable professional life.',
    spirit:'The spiritual grace of enjoying the fruits of this material world without being attached to them.' },
  { id:73, name:'Ten of Pentacles', slug:'ten-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'10', symbol:'🏰', element:'Earth',
    yn:'yes', yn_exp:'Ten of Pentacles says yes — lasting wealth, family legacy and generational abundance are indicated.',
    kw_up:['legacy', 'family wealth', 'long-term success', 'inheritance', 'tradition'],
    kw_rev:['family conflict', 'financial instability', 'short-term thinking', 'broken legacy'],
    up:'The Ten of Pentacles represents the pinnacle of material success — a lasting legacy, family wealth and the satisfaction of building something that will endure across generations. Long-term security and fulfilment are here.',
    rev:'Family conflict over money, a legacy that is unravelling or focusing on short-term gain at the cost of something lasting.',
    love:'A deeply stable, lasting relationship that becomes the foundation of a beautiful family life.',
    career:'Long-term business success, a family business or the creation of a lasting financial legacy.',
    spirit:'The physical world as a sacred inheritance — care for it, build upon it and pass it on with love.' },
  { id:74, name:'Page of Pentacles', slug:'page-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'Page', symbol:'📚', element:'Earth',
    yn:'yes', yn_exp:'Page of Pentacles says yes — apply yourself with diligence, curiosity and a student\'s mindset.',
    kw_up:['studiousness', 'diligence', 'new opportunity', 'practical learning', 'groundedness'],
    kw_rev:['lack of focus', 'procrastination', 'missed opportunities', 'impracticality'],
    up:'The Page of Pentacles is an eager student of the material world — studious, practical and committed to learning. A new practical skill or opportunity is emerging. Approach it with diligence and attention to detail.',
    rev:'Procrastination, distraction or refusing to put in the practical work required.',
    love:'Building a stable, grounded foundation for love. Practical steps toward commitment.',
    career:'A new learning opportunity, scholarship, apprenticeship or the very beginning of a practical career.',
    spirit:'Grounding spiritual learning in practical, everyday application.' },
  { id:75, name:'Knight of Pentacles', slug:'knight-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'Knight', symbol:'🐂', element:'Earth',
    yn:'yes', yn_exp:'Knight of Pentacles says yes — steady, methodical effort will get you there.',
    kw_up:['reliability', 'patience', 'methodical', 'hard work', 'routine'],
    kw_rev:['stubbornness', 'boredom', 'stagnation', 'perfectionism'],
    up:'The Knight of Pentacles may be the slowest of the knights, but he is the most reliable. He commits to the long game and does not cut corners. Steady, methodical effort and trustworthy follow-through are your greatest assets now.',
    rev:'Stubbornness, getting stuck in routine or perfectionism that prevents progress.',
    love:'A reliable, steady and committed partner who is in it for the long haul.',
    career:'Methodical progress, reliable work habits and the discipline to see a long project through to completion.',
    spirit:'The spiritual value of regularity — daily practice, consistency and showing up even when uninspired.' },
  { id:76, name:'Queen of Pentacles', slug:'queen-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'Queen', symbol:'🌺', element:'Earth',
    yn:'yes', yn_exp:'Queen of Pentacles says yes — practical wisdom, nurturing abundance and down-to-earth care.',
    kw_up:['practicality', 'nurturing', 'abundance', 'groundedness', 'resourcefulness'],
    kw_rev:['materialism', 'neglect of self', 'overwork', 'smothering'],
    up:'The Queen of Pentacles is the ultimate earth mother — practical, nurturing, resourceful and deeply connected to the physical world. She creates abundance through care and common sense. Trust your practical wisdom.',
    rev:'Neglecting self-care, over-working or placing too much emphasis on material accumulation.',
    love:'A warm, nurturing, grounded love — secure, practical and deeply caring.',
    career:'Business acumen, financial management, homemaking as an art, or work in food, nature or wellness.',
    spirit:'Sacred embodiment — honouring the divine through care of the body, home and natural world.' },
  { id:77, name:'King of Pentacles', slug:'king-of-pentacles', suit:'pentacles', suitLabel:'Pentacles',
    number:'King', symbol:'💎', element:'Earth',
    yn:'yes', yn_exp:'King of Pentacles says yes — financial mastery, stability and practical authority will serve you well.',
    kw_up:['abundance', 'financial mastery', 'stability', 'leadership', 'security'],
    kw_rev:['greed', 'materialism', 'stubbornness', 'poor financial decisions'],
    up:'The King of Pentacles has mastered the material world through patience, discipline and practical wisdom. He provides security and abundance for those in his care. Step into this energy of financial mastery and grounded leadership.',
    rev:'Greed, excessive materialism or poor financial management undermining genuine security.',
    love:'A stable, secure and generous provider — someone who builds a beautiful life with you.',
    career:'Financial mastery, executive leadership, entrepreneurial success or real estate and investment.',
    spirit:'The sacred responsibility of stewardship — caring wisely for the resources and people entrusted to you.' },
]

export const CARDS_BY_SLUG = Object.fromEntries(CARDS.map(c => [c.slug, c]))

export type { Card as TarotCard }

export const SUITS: {key: CardSuit; label: string}[] = [
  {key:'major', label:'Major Arcana'},
  {key:'wands', label:'Wands'},
  {key:'cups', label:'Cups'},
  {key:'swords', label:'Swords'},
  {key:'pentacles', label:'Pentacles'},
]