import { CARDS, CARDS_BY_SLUG, type Card } from './cards'

export function getElementRel(e1: string, e2: string) {
  const has = (e: string, s: string) => e.includes(s)
  if ((has(e1,'Fire')&&has(e2,'Air'))||(has(e1,'Air')&&has(e2,'Fire')))
    return { type: 'amplifying', desc: 'Fire and Air feed each other — this combination surges with inspiration and rapid forward movement.' }
  if ((has(e1,'Earth')&&has(e2,'Water'))||(has(e1,'Water')&&has(e2,'Earth')))
    return { type: 'nurturing', desc: 'Earth and Water create fertile ground — a combination of growth, nourishment and patient manifestation.' }
  if ((has(e1,'Fire')&&has(e2,'Water'))||(has(e1,'Water')&&has(e2,'Fire')))
    return { type: 'tension', desc: 'Fire and Water create steam — this combination holds passion and emotional complexity in dynamic opposition.' }
  if ((has(e1,'Air')&&has(e2,'Earth'))||(has(e1,'Earth')&&has(e2,'Air')))
    return { type: 'grounding', desc: 'Air and Earth balance thought with action — ground your ideas into practical reality.' }
  if (e1 === e2 || e1.includes(e2) || e2.includes(e1))
    return { type: 'resonant', desc: 'Sharing the same element, these cards speak the same language — their energies amplify and deepen each other powerfully.' }
  return { type: 'complex', desc: 'These two cards carry distinct elemental energies creating a layered, multifaceted combination.' }
}

// ---------------------------------------------------------------------------
// Signal detection — produces a coalition of flags for procedural enrichment
// ---------------------------------------------------------------------------

const CRISIS_SLUGS = new Set(['the-tower', 'death', 'the-devil', 'three-of-swords', 'nine-of-swords', 'ten-of-swords', 'five-of-cups', 'five-of-pentacles'])
const HEALING_SLUGS = new Set(['the-star', 'temperance', 'the-sun', 'six-of-pentacles', 'nine-of-cups', 'ten-of-cups', 'six-of-cups'])
const COMMITMENT_SLUGS = new Set(['the-hierophant', 'the-lovers', 'two-of-cups', 'four-of-wands', 'ten-of-cups'])
const TRANSITION_SLUGS = new Set(['death', 'wheel-of-fortune', 'the-tower', 'judgement', 'the-hanged-man', 'eight-of-cups'])
const SHADOW_SLUGS = new Set(['the-moon', 'the-devil', 'seven-of-cups', 'eight-of-swords', 'nine-of-swords'])
const WILLPOWER_SLUGS = new Set(['the-chariot', 'strength', 'the-emperor', 'the-magician'])
const INTUITION_SLUGS = new Set(['the-high-priestess', 'the-moon', 'the-hermit', 'seven-of-cups'])

const PIP_NUMBER_PREFIX: Record<string, number> = {
  ace: 1, two: 2, three: 3, four: 4, five: 5,
  six: 6, seven: 7, eight: 8, nine: 9, ten: 10,
}

function isCourtSlug(slug: string): boolean {
  return /^(page|knight|queen|king)-of-/.test(slug)
}
function pipNumber(slug: string): number | null {
  const m = slug.match(/^(ace|two|three|four|five|six|seven|eight|nine|ten)-of-/)
  return m ? PIP_NUMBER_PREFIX[m[1]] : null
}

export type ComboArchetype =
  | 'two-majors' | 'major-court' | 'major-pip'
  | 'two-courts' | 'court-pip' | 'two-pips'

export type ComboSignals = {
  elementalRelation: 'amplifying' | 'nurturing' | 'tension' | 'grounding' | 'resonant' | 'complex'
  elementalDesc: string
  archetype: ComboArchetype
  sameSuit: boolean
  sameNumber: boolean   // pip-pip only
  crisis: boolean
  healing: boolean
  commitment: boolean
  transition: boolean
  shadow: boolean
  willpower: boolean
  intuition: boolean
}

export function detectSignals(c1: Card, c2: Card): ComboSignals {
  const rel = getElementRel(c1.element, c2.element)
  const c1Major = c1.suit === 'major'
  const c2Major = c2.suit === 'major'
  const c1Court = isCourtSlug(c1.slug)
  const c2Court = isCourtSlug(c2.slug)
  const c1Pip = !c1Major && !c1Court
  const c2Pip = !c2Major && !c2Court

  let archetype: ComboArchetype
  if (c1Major && c2Major) archetype = 'two-majors'
  else if ((c1Major && c2Court) || (c2Major && c1Court)) archetype = 'major-court'
  else if ((c1Major && c2Pip) || (c2Major && c1Pip)) archetype = 'major-pip'
  else if (c1Court && c2Court) archetype = 'two-courts'
  else if ((c1Court && c2Pip) || (c2Court && c1Pip)) archetype = 'court-pip'
  else archetype = 'two-pips'

  const p1 = pipNumber(c1.slug)
  const p2 = pipNumber(c2.slug)

  const has = (set: Set<string>) => set.has(c1.slug) || set.has(c2.slug)

  return {
    elementalRelation: rel.type as ComboSignals['elementalRelation'],
    elementalDesc: rel.desc,
    archetype,
    sameSuit: c1.suit === c2.suit && !c1Major,
    sameNumber: archetype === 'two-pips' && p1 !== null && p2 !== null && p1 === p2,
    crisis: has(CRISIS_SLUGS),
    healing: has(HEALING_SLUGS),
    commitment: has(COMMITMENT_SLUGS),
    transition: has(TRANSITION_SLUGS),
    shadow: has(SHADOW_SLUGS),
    willpower: has(WILLPOWER_SLUGS),
    intuition: has(INTUITION_SLUGS),
  }
}

// ---------------------------------------------------------------------------
// Signal-driven nuanced fragments — used when no hand-curated ComboContext exists
// ---------------------------------------------------------------------------

function buildShadowForm(c1: Card, c2: Card, s: ComboSignals): string {
  if (s.crisis)
    return `The shadow of this pair is collapse without release — small repeated breakages instead of one clean rupture. ${c1.name} or ${c2.name} keeps surfacing the same fragility in a slightly altered shape, and the querent asks why the situation keeps arriving. The work is structural, not cosmetic.`
  if (s.shadow)
    return `The shadow is the story the querent has been telling themselves to avoid a quieter, less flattering truth. ${c1.name} and ${c2.name} together rarely deceive on purpose; they highlight the explanation that has grown too convenient to question.`
  if (s.commitment)
    return `The shadow is commitment dressed up as inevitability — staying because leaving feels like failure, or because the alternative is unfamiliar, rather than because the staying still serves either life involved.`
  if (s.healing)
    return `The shadow of this pair is calling completion at the wrong gate. Healing combinations like ${c1.name} and ${c2.name} often arrive in the middle of the work, not at the end. The relief feels final until life tests whether it actually finished.`
  if (s.transition)
    return `The shadow is the transition stretched indefinitely — keeping one foot in the previous life because fully committing to the new one feels like betraying the old. ${c1.name} and ${c2.name} are pointing at the unfinished crossing.`
  if (s.willpower)
    return `The shadow is force applied where patience was required, or patience held where action was overdue. ${c1.name} and ${c2.name} sharpen whichever of those two errors the querent has been making.`
  if (s.archetype === 'two-majors')
    return `The shadow of two-Major pairings is treating the reading as fate rather than diagnosis. ${c1.name} and ${c2.name} describe the dynamic at play, not the choices that remain open inside it.`
  if (s.elementalRelation === 'tension')
    return `The shadow is treating the tension as a problem to be solved. ${c1.name} and ${c2.name} hold two valid energies in friction; the work is in letting both stay present rather than forcing resolution.`
  if (s.elementalRelation === 'amplifying')
    return `The shadow is acceleration without direction — momentum that feels like progress but multiplies whatever was already off-course. ${c1.name} and ${c2.name} amplify the system as it actually is, not as the querent wishes it were.`
  if (s.elementalRelation === 'nurturing')
    return `The shadow is over-tending — staying so long in the patient mode that growth quietly becomes stagnation. ${c1.name} and ${c2.name} reward care, then ask whether the care is still doing useful work.`
  if (s.elementalRelation === 'grounding')
    return `The shadow is hyper-pragmatism that crushes the imaginative spark the pair was offering. ${c1.name} and ${c2.name} ask for follow-through, not for the original vision to be filed away.`
  if (s.elementalRelation === 'resonant')
    return `The shadow is the echo chamber — the same energy compounded into a single dominant note, drowning out adjacent information the spread is also offering.`
  return `The shadow of this pair is mistaking its complexity for incoherence. ${c1.name} and ${c2.name} are asking for a more careful reading, not a different one.`
}

function buildEdgeCase(c1: Card, c2: Card, s: ComboSignals): string {
  if (s.crisis)
    return `Crisis pairs like ${c1.name} and ${c2.name} are sometimes misread as future prediction when the querent is actually mid-recovery. Read the timing of the question, not just the cards — the same pair means very different things on day one of a rupture and on day ninety.`
  if (s.shadow)
    return `Pairs with strong shadow-cluster energy are frequently misread for paranoia when the signal is accurate intuition, or for accuracy when the signal is the querent's threat-detection misfiring. Verify against external evidence before acting on what ${c1.name} and ${c2.name} appear to be saying.`
  if (s.archetype === 'major-court')
    return `Court cards in the pair often describe an actual person around the querent. Before reading ${c1.name} or ${c2.name} as a facet of the querent's own personality, ask whether there is a specific real person in the situation the card might be naming.`
  if (s.archetype === 'two-courts')
    return `Two courts in a single pair almost always describe a relational dynamic between two specific people. Decide which of ${c1.name} or ${c2.name} the querent is in the situation — and which they are receiving — before reading further.`
  if (s.sameNumber)
    return `Same-number pip pairs like ${c1.name} and ${c2.name} read as energy in stereo — two suits processing the same numerical theme at once. The reading converges on the theme; the suits become texture.`
  if (s.archetype === 'major-pip')
    return `A Major + Pip pair is usually best read as the archetypal force (${c1.suit === 'major' ? c1.name : c2.name}) acting on the specific situation (${c1.suit === 'major' ? c2.name : c1.name}). Resist reading them as two co-equal voices; one is context, one is content.`
  if (s.healing)
    return `Healing combinations sometimes appear early in a difficult process to signal that the path back exists, not that it has been walked yet. Don't treat ${c1.name} and ${c2.name} as confirmation that the work is done.`
  if (s.elementalRelation === 'tension')
    return `Tension pairs are sometimes misread as warnings. They are not. ${c1.name} and ${c2.name} describe the friction the situation contains; the warning would look like different cards saying that friction is destroying something.`
  return `The pair benefits from being read against the question that was actually asked. ${c1.name} and ${c2.name} are flexible enough to fit several adjacent situations; precision in the question produces precision in the reading.`
}

function buildReaderNote(c1: Card, c2: Card, s: ComboSignals): string {
  if (s.crisis)
    return `Experienced readers tend not to soften crisis pairs. They name the ending honestly, then ask the harder question: what was the querent loyal to that prevented earlier exit? That loyalty — to a vow, an image, a sunk cost — is usually the real subject of the reading.`
  if (s.commitment)
    return `Commitment combinations usually ask 'what would honesty cost you here'. The cards are not anti-commitment; they are anti-rote commitment. A working practitioner reading ${c1.name} and ${c2.name} is listening for what the querent has stopped saying out loud.`
  if (s.shadow)
    return `Readers seeing shadow-cluster pairs check first whether the querent is asking the same question repeatedly across sessions. If so, the cards have likely already answered it, and the work has shifted from clarification to confrontation.`
  if (s.healing)
    return `A working practitioner reads healing pairs like ${c1.name} and ${c2.name} as orientation, not arrival. The pair confirms the direction; the timing belongs to the querent's life, not the cards.`
  if (s.transition)
    return `Transition combinations reward patience in the reading itself. ${c1.name} and ${c2.name} are describing a process; compressing it into a single sentence delivers less value than naming the stages the querent is moving through.`
  if (s.willpower)
    return `Readers with experience know willpower pairs are usually a check on application — is the querent pushing where patience was required, or waiting where action was overdue. ${c1.name} and ${c2.name} sharpen the diagnostic; the choice remains the querent's.`
  if (s.archetype === 'two-majors')
    return `Two-Major pairs like ${c1.name} and ${c2.name} tend to invite the practitioner to slow down. The reading is usually about a life phase, not a single decision; treat it as a phase reading and the cards will give more useful detail.`
  if (s.intuition)
    return `Intuition-heavy pairs reward attention to what the querent already half-knows. ${c1.name} and ${c2.name} are rarely delivering new information; more often they are giving the existing intuition a structure clear enough to act on.`
  return `The most useful question to bring to ${c1.name} and ${c2.name} is what the querent has been avoiding asking themselves about the situation. The cards are not refusing to answer; they are pointing toward the question that has not been articulated yet.`
}

function buildFaqs(c1: Card, c2: Card, s: ComboSignals, mainText: string, loveText: string, careerText: string): Array<{q: string; a: string}> {
  const valenceAnswer = (() => {
    if (s.crisis && !s.healing)
      return `Neither, in the polarised sense. ${c1.name} and ${c2.name} together describe upheaval or ending, which feels negative in the moment but is rarely the full story. Many querents look back on this pair as the moment a stuck situation finally moved.`
    if (s.healing && !s.crisis)
      return `On balance, supportive. ${c1.name} and ${c2.name} carry a healing or completion signal, though the cards do not promise that the work is finished — only that the direction is sound.`
    if (s.commitment)
      return `Constructive but conditional. The pair rewards honest commitment and punishes inertial commitment; the reading depends on which one the querent is actually offering.`
    if (s.transition)
      return `Transitional. ${c1.name} and ${c2.name} describe a moving situation, neither stable enough to call good nor finished enough to call bad. The reading is about the direction of motion, not a verdict on the outcome.`
    return `Tarot pairs do not divide neatly into positive and negative. ${c1.name} and ${c2.name} describe a dynamic with both shadow and light; what the querent does with the energy determines which side the reading falls on.`
  })()

  const contextFocus = (s.commitment || s.shadow || c1.suit === 'cups' || c2.suit === 'cups') ? 'love' : 'career'

  return [
    {
      q: `What does ${c1.name} and ${c2.name} mean in tarot?`,
      a: mainText,
    },
    {
      q: `Is ${c1.name} and ${c2.name} a positive or negative combination?`,
      a: valenceAnswer,
    },
    {
      q: `What does the ${s.elementalRelation} energy between ${c1.name} and ${c2.name} mean?`,
      a: `${s.elementalDesc} In practice this means readings with ${c1.name} and ${c2.name} tend to move ${s.elementalRelation === 'amplifying' ? 'quickly and reward decisive action' : s.elementalRelation === 'nurturing' ? 'slowly and reward patience' : s.elementalRelation === 'tension' ? 'with complexity that resists tidy resolution' : s.elementalRelation === 'grounding' ? 'with practical follow-through over speculation' : s.elementalRelation === 'resonant' ? 'with concentrated, single-themed clarity' : 'across several interpretive layers that benefit from re-reading'}.`,
    },
    contextFocus === 'love'
      ? {
          q: `How should I read ${c1.name} and ${c2.name} in a relationship question?`,
          a: loveText,
        }
      : {
          q: `How should I read ${c1.name} and ${c2.name} in a career question?`,
          a: careerText,
        },
  ]
}

// ---------------------------------------------------------------------------
// Main interpretation — backward-compatible, plus new signal-driven fields
// ---------------------------------------------------------------------------

export function interpret(c1: Card, c2: Card) {
  const rel = getElementRel(c1.element, c2.element)
  const signals = detectSignals(c1, c2)
  const kw1 = c1.kw_up.slice(0, 2).join(' and ')
  const kw2 = c2.kw_up.slice(0, 2).join(' and ')
  const mains: Record<string, string> = {
    amplifying: `The pairing of ${c1.name} and ${c2.name} creates a powerfully amplified current. ${c1.name} brings ${c1.kw_up[0]} and ${c1.kw_up[1]}, while ${c2.name} adds ${c2.kw_up[0]} and ${c2.kw_up[1]}. ${rel.desc} Together they ignite momentum — ideas and actions move fast. The core themes running through this combination are ${kw1} meeting ${kw2}. Something is accelerating: you are being called to act with both awareness and drive.`,
    nurturing: `${c1.name} and ${c2.name} create a deeply supportive pairing. ${c1.name} carries ${kw1}, and ${c2.name} holds ${kw2}. ${rel.desc} Together they ask you to be patient, tend to what is growing, and trust the process. This combination rewards steadiness, care and long-term thinking over quick wins.`,
    tension: `${c1.name} and ${c2.name} create a dynamic, charged tension. ${kw1} from ${c1.name} and ${kw2} from ${c2.name} — these are not opposing forces so much as complementary polarities. ${rel.desc} The pull between them is the heart of this combination's message: both energies are valid; the work is in holding them together.`,
    grounding: `${c1.name} and ${c2.name} bridge vision with reality. ${kw1} meets ${kw2}. ${rel.desc} This combination rewards those who can think clearly and follow through methodically. The ideas must become actions.`,
    resonant: `When ${c1.name} meets ${c2.name}, their shared elemental nature creates deep resonance. ${kw1} and ${kw2} weave into a unified message — a combination of reinforcement and depth. What each card suggests alone becomes more certain and more important together.`,
    complex: `${c1.name} and ${c2.name} bring together two distinct archetypal currents. ${kw1} exists in dialogue with ${kw2}. ${rel.desc} Reading this combination requires holding both energies — each brings its own wisdom, and the message emerges in the space between them.`,
  }
  const main = mains[rel.type]
  const love = `In love, ${c1.name} and ${c2.name} suggest a relationship shaped by ${c1.kw_up[0]} and ${c2.kw_up[0]}. ${signals.commitment ? 'Commitment is part of the reading — either tested, offered, or asked for.' : signals.shadow ? 'Watch for projections; the relationship may carry more imagination than verified fact.' : 'Both emotional truth and personal growth are central themes.'}`
  const career = `Professionally, the meeting of ${c1.name}'s ${c1.kw_up[0]} with ${c2.name}'s ${c2.kw_up[0]} describes a dynamic where ${rel.type === 'amplifying' ? 'bold moves and fast decisions lead to breakthroughs' : rel.type === 'grounding' ? 'careful planning and steady effort produce the best results' : signals.crisis ? 'an ending or restructuring is in motion — resist the urge to rebuild the previous form' : 'genuine collaboration and honest assessment are your greatest assets'}.`
  const spirit = `For personal growth, ${c1.name} and ${c2.name} point at the relationship between ${c1.kw_up[0]} and ${c2.kw_up[0]}. ${signals.transition ? 'A phase is closing or has just closed; the spiritual task is not rushing the next phase into being.' : signals.intuition ? 'Inner knowing is the operative faculty here — quiet enough to hear it requires deliberately reducing input.' : `${c1.name} has prepared you; ${c2.name} shows you where to go next. The lesson is integration.`}`

  return {
    relType: rel.type,
    relDesc: rel.desc,
    main,
    love,
    career,
    spirit,
    signals,
    shadowForm: buildShadowForm(c1, c2, signals),
    edgeCase: buildEdgeCase(c1, c2, signals),
    readerNote: buildReaderNote(c1, c2, signals),
    faqs: buildFaqs(c1, c2, signals, main, love, career),
  }
}

/** Canonical slug: lower card ID always first */
export function makeComboSlug(slug1: string, slug2: string): string {
  const c1 = CARDS_BY_SLUG[slug1]
  const c2 = CARDS_BY_SLUG[slug2]
  if (!c1 || !c2) return `${slug1}-and-${slug2}`
  return c1.id <= c2.id
    ? `${slug1}-and-${slug2}`
    : `${slug2}-and-${slug1}`
}

/**
 * Parse a combo slug like "death-and-the-tower" into two card slugs.
 * Tries all possible "-and-" split points to find two valid cards.
 * Returns null if no valid pair found.
 */
export function parseComboSlug(comboSlug: string): [string, string] | null {
  const parts = comboSlug.split('-and-')
  for (let i = 1; i < parts.length; i++) {
    const slug1 = parts.slice(0, i).join('-and-')
    const slug2 = parts.slice(i).join('-and-')
    if (CARDS_BY_SLUG[slug1] && CARDS_BY_SLUG[slug2]) {
      return [slug1, slug2]
    }
  }
  return null
}

/** All Major Arcana slugs in deck order */
export const MAJOR_SLUGS = CARDS
  .filter(c => c.suit === 'major')
  .map(c => c.slug)

/** All unique Major × Major combo slugs (canonical, 231 pairs) */
export const MAJOR_COMBOS: string[] = []
for (let i = 0; i < MAJOR_SLUGS.length; i++) {
  for (let j = i + 1; j < MAJOR_SLUGS.length; j++) {
    MAJOR_COMBOS.push(`${MAJOR_SLUGS[i]}-and-${MAJOR_SLUGS[j]}`)
  }
}

/** High-priority Minor Arcana combos with proven search volume */
export const PRIORITY_MINOR_COMBOS = [
  'the-high-priestess-and-page-of-swords',
  'the-fool-and-ace-of-wands',
  'the-magician-and-ace-of-wands',
  'the-high-priestess-and-ace-of-wands',
  'the-empress-and-ace-of-wands',
  'the-emperor-and-ace-of-wands',
  'the-hierophant-and-ace-of-wands',
  'the-lovers-and-ace-of-wands',
  'the-chariot-and-ace-of-wands',
  'strength-and-ace-of-wands',
  'the-hermit-and-ace-of-wands',
  'wheel-of-fortune-and-ace-of-wands',
  'justice-and-ace-of-wands',
  'the-hanged-man-and-ace-of-wands',
  'death-and-ace-of-wands',
  'temperance-and-ace-of-wands',
  'the-devil-and-ace-of-wands',
  'the-tower-and-ace-of-wands',
  'the-star-and-ace-of-wands',
  'the-moon-and-ace-of-wands',
  'the-sun-and-ace-of-wands',
  'judgement-and-ace-of-wands',
  'the-world-and-ace-of-wands',
  'the-fool-and-three-of-wands',
  'the-magician-and-three-of-wands',
  'the-high-priestess-and-three-of-wands',
  'the-empress-and-three-of-wands',
  'the-emperor-and-three-of-wands',
  'the-hierophant-and-three-of-wands',
  'the-lovers-and-three-of-wands',
  'the-chariot-and-three-of-wands',
  'strength-and-three-of-wands',
  'the-hermit-and-three-of-wands',
  'wheel-of-fortune-and-three-of-wands',
  'justice-and-three-of-wands',
  'the-hanged-man-and-three-of-wands',
  'death-and-three-of-wands',
  'temperance-and-three-of-wands',
  'the-devil-and-three-of-wands',
  'the-tower-and-three-of-wands',
  'the-star-and-three-of-wands',
  'the-moon-and-three-of-wands',
  'the-sun-and-three-of-wands',
  'judgement-and-three-of-wands',
  'the-world-and-three-of-wands',
  'the-fool-and-five-of-wands',
  'the-magician-and-five-of-wands',
  'the-high-priestess-and-five-of-wands',
  'the-empress-and-five-of-wands',
  'the-emperor-and-five-of-wands',
  'the-hierophant-and-five-of-wands',
  'the-lovers-and-five-of-wands',
  'the-chariot-and-five-of-wands',
  'strength-and-five-of-wands',
  'the-hermit-and-five-of-wands',
  'wheel-of-fortune-and-five-of-wands',
  'justice-and-five-of-wands',
  'the-hanged-man-and-five-of-wands',
  'death-and-five-of-wands',
  'temperance-and-five-of-wands',
  'the-devil-and-five-of-wands',
  'the-tower-and-five-of-wands',
  'the-star-and-five-of-wands',
  'the-moon-and-five-of-wands',
  'the-sun-and-five-of-wands',
  'judgement-and-five-of-wands',
  'the-world-and-five-of-wands',
  'the-fool-and-seven-of-wands',
  'the-magician-and-seven-of-wands',
  'the-high-priestess-and-seven-of-wands',
  'the-empress-and-seven-of-wands',
  'the-emperor-and-seven-of-wands',
  'the-hierophant-and-seven-of-wands',
  'the-lovers-and-seven-of-wands',
  'the-chariot-and-seven-of-wands',
  'strength-and-seven-of-wands',
  'the-hermit-and-seven-of-wands',
  'wheel-of-fortune-and-seven-of-wands',
  'justice-and-seven-of-wands',
  'the-hanged-man-and-seven-of-wands',
  'death-and-seven-of-wands',
  'temperance-and-seven-of-wands',
  'the-devil-and-seven-of-wands',
  'the-tower-and-seven-of-wands',
  'the-star-and-seven-of-wands',
  'the-moon-and-seven-of-wands',
  'the-sun-and-seven-of-wands',
  'judgement-and-seven-of-wands',
  'the-world-and-seven-of-wands',
  'the-fool-and-eight-of-wands',
  'the-magician-and-eight-of-wands',
  'the-high-priestess-and-eight-of-wands',
  'the-empress-and-eight-of-wands',
  'the-emperor-and-eight-of-wands',
  'the-hierophant-and-eight-of-wands',
  'the-lovers-and-eight-of-wands',
  'the-chariot-and-eight-of-wands',
  'strength-and-eight-of-wands',
  'the-hermit-and-eight-of-wands',
  'wheel-of-fortune-and-eight-of-wands',
  'justice-and-eight-of-wands',
  'the-hanged-man-and-eight-of-wands',
  'death-and-eight-of-wands',
  'temperance-and-eight-of-wands',
  'the-devil-and-eight-of-wands',
  'the-tower-and-eight-of-wands',
  'the-star-and-eight-of-wands',
  'the-moon-and-eight-of-wands',
  'the-sun-and-eight-of-wands',
  'judgement-and-eight-of-wands',
  'the-world-and-eight-of-wands',
  'the-fool-and-ten-of-wands',
  'the-magician-and-ten-of-wands',
  'the-high-priestess-and-ten-of-wands',
  'the-empress-and-ten-of-wands',
  'the-emperor-and-ten-of-wands',
  'the-hierophant-and-ten-of-wands',
  'the-lovers-and-ten-of-wands',
  'the-chariot-and-ten-of-wands',
  'strength-and-ten-of-wands',
  'the-hermit-and-ten-of-wands',
  'wheel-of-fortune-and-ten-of-wands',
  'justice-and-ten-of-wands',
  'the-hanged-man-and-ten-of-wands',
  'death-and-ten-of-wands',
  'temperance-and-ten-of-wands',
  'the-devil-and-ten-of-wands',
  'the-tower-and-ten-of-wands',
  'the-star-and-ten-of-wands',
  'the-moon-and-ten-of-wands',
  'the-sun-and-ten-of-wands',
  'judgement-and-ten-of-wands',
  'the-world-and-ten-of-wands',
  'the-fool-and-page-of-wands',
  'the-magician-and-page-of-wands',
  'the-high-priestess-and-page-of-wands',
  'the-empress-and-page-of-wands',
  'the-emperor-and-page-of-wands',
  'the-hierophant-and-page-of-wands',
  'the-lovers-and-page-of-wands',
  'the-chariot-and-page-of-wands',
  'strength-and-page-of-wands',
  'the-hermit-and-page-of-wands',
  'wheel-of-fortune-and-page-of-wands',
  'justice-and-page-of-wands',
  'the-hanged-man-and-page-of-wands',
  'death-and-page-of-wands',
  'temperance-and-page-of-wands',
  'the-devil-and-page-of-wands',
  'the-tower-and-page-of-wands',
  'the-star-and-page-of-wands',
  'the-moon-and-page-of-wands',
  'the-sun-and-page-of-wands',
  'judgement-and-page-of-wands',
  'the-world-and-page-of-wands',
  'the-fool-and-knight-of-wands',
  'the-magician-and-knight-of-wands',
  'the-high-priestess-and-knight-of-wands',
  'the-empress-and-knight-of-wands',
  'the-emperor-and-knight-of-wands',
  'the-hierophant-and-knight-of-wands',
  'the-lovers-and-knight-of-wands',
  'the-chariot-and-knight-of-wands',
  'strength-and-knight-of-wands',
  'the-hermit-and-knight-of-wands',
  'wheel-of-fortune-and-knight-of-wands',
  'justice-and-knight-of-wands',
  'the-hanged-man-and-knight-of-wands',
  'death-and-knight-of-wands',
  'temperance-and-knight-of-wands',
  'the-devil-and-knight-of-wands',
  'the-tower-and-knight-of-wands',
  'the-star-and-knight-of-wands',
  'the-moon-and-knight-of-wands',
  'the-sun-and-knight-of-wands',
  'judgement-and-knight-of-wands',
  'the-world-and-knight-of-wands',
  'the-fool-and-queen-of-wands',
  'the-magician-and-queen-of-wands',
  'the-high-priestess-and-queen-of-wands',
  'the-empress-and-queen-of-wands',
  'the-emperor-and-queen-of-wands',
  'the-hierophant-and-queen-of-wands',
  'the-lovers-and-queen-of-wands',
  'the-chariot-and-queen-of-wands',
  'strength-and-queen-of-wands',
  'the-hermit-and-queen-of-wands',
  'wheel-of-fortune-and-queen-of-wands',
  'justice-and-queen-of-wands',
  'the-hanged-man-and-queen-of-wands',
  'death-and-queen-of-wands',
  'temperance-and-queen-of-wands',
  'the-devil-and-queen-of-wands',
  'the-tower-and-queen-of-wands',
  'the-star-and-queen-of-wands',
  'the-moon-and-queen-of-wands',
  'the-sun-and-queen-of-wands',
  'judgement-and-queen-of-wands',
  'the-world-and-queen-of-wands',
  'the-fool-and-king-of-wands',
  'the-magician-and-king-of-wands',
  'the-high-priestess-and-king-of-wands',
  'the-empress-and-king-of-wands',
  'the-emperor-and-king-of-wands',
  'the-hierophant-and-king-of-wands',
  'the-lovers-and-king-of-wands',
  'the-chariot-and-king-of-wands',
  'strength-and-king-of-wands',
  'the-hermit-and-king-of-wands',
  'wheel-of-fortune-and-king-of-wands',
  'justice-and-king-of-wands',
  'the-hanged-man-and-king-of-wands',
  'death-and-king-of-wands',
  'temperance-and-king-of-wands',
  'the-devil-and-king-of-wands',
  'the-tower-and-king-of-wands',
  'the-star-and-king-of-wands',
  'the-moon-and-king-of-wands',
  'the-sun-and-king-of-wands',
  'judgement-and-king-of-wands',
  'the-world-and-king-of-wands',
  'the-fool-and-ace-of-cups',
  'the-magician-and-ace-of-cups',
  'the-high-priestess-and-ace-of-cups',
  'the-empress-and-ace-of-cups',
  'the-emperor-and-ace-of-cups',
  'the-hierophant-and-ace-of-cups',
  'the-lovers-and-ace-of-cups',
  'the-chariot-and-ace-of-cups',
  'strength-and-ace-of-cups',
  'the-hermit-and-ace-of-cups',
  'wheel-of-fortune-and-ace-of-cups',
  'justice-and-ace-of-cups',
  'the-hanged-man-and-ace-of-cups',
  'death-and-ace-of-cups',
  'temperance-and-ace-of-cups',
  'the-devil-and-ace-of-cups',
  'the-tower-and-ace-of-cups',
  'the-star-and-ace-of-cups',
  'the-moon-and-ace-of-cups',
  'the-sun-and-ace-of-cups',
  'judgement-and-ace-of-cups',
  'the-world-and-ace-of-cups',
  'the-fool-and-two-of-cups',
  'the-magician-and-two-of-cups',
  'the-high-priestess-and-two-of-cups',
  'the-empress-and-two-of-cups',
  'the-emperor-and-two-of-cups',
  'the-hierophant-and-two-of-cups',
  'the-lovers-and-two-of-cups',
  'the-chariot-and-two-of-cups',
  'strength-and-two-of-cups',
  'the-hermit-and-two-of-cups',
  'wheel-of-fortune-and-two-of-cups',
  'justice-and-two-of-cups',
  'the-hanged-man-and-two-of-cups',
  'death-and-two-of-cups',
  'temperance-and-two-of-cups',
  'the-devil-and-two-of-cups',
  'the-tower-and-two-of-cups',
  'the-star-and-two-of-cups',
  'the-moon-and-two-of-cups',
  'the-sun-and-two-of-cups',
  'judgement-and-two-of-cups',
  'the-world-and-two-of-cups',
  'the-fool-and-three-of-cups',
  'the-magician-and-three-of-cups',
  'the-high-priestess-and-three-of-cups',
  'the-empress-and-three-of-cups',
  'the-emperor-and-three-of-cups',
  'the-hierophant-and-three-of-cups',
  'the-lovers-and-three-of-cups',
  'the-chariot-and-three-of-cups',
  'strength-and-three-of-cups',
  'the-hermit-and-three-of-cups',
  'wheel-of-fortune-and-three-of-cups',
  'justice-and-three-of-cups',
  'the-hanged-man-and-three-of-cups',
  'death-and-three-of-cups',
  'temperance-and-three-of-cups',
  'the-devil-and-three-of-cups',
  'the-tower-and-three-of-cups',
  'the-star-and-three-of-cups',
  'the-moon-and-three-of-cups',
  'the-sun-and-three-of-cups',
  'judgement-and-three-of-cups',
  'the-world-and-three-of-cups',
  'the-fool-and-five-of-cups',
  'the-magician-and-five-of-cups',
  'the-high-priestess-and-five-of-cups',
  'the-empress-and-five-of-cups',
  'the-emperor-and-five-of-cups',
  'the-hierophant-and-five-of-cups',
  'the-lovers-and-five-of-cups',
  'the-chariot-and-five-of-cups',
  'strength-and-five-of-cups',
  'the-hermit-and-five-of-cups',
  'wheel-of-fortune-and-five-of-cups',
  'justice-and-five-of-cups',
  'the-hanged-man-and-five-of-cups',
  'death-and-five-of-cups',
  'temperance-and-five-of-cups',
  'the-devil-and-five-of-cups',
  'the-tower-and-five-of-cups',
  'the-star-and-five-of-cups',
  'the-moon-and-five-of-cups',
  'the-sun-and-five-of-cups',
  'judgement-and-five-of-cups',
  'the-world-and-five-of-cups',
  'the-fool-and-six-of-cups',
  'the-magician-and-six-of-cups',
  'the-high-priestess-and-six-of-cups',
  'the-empress-and-six-of-cups',
  'the-emperor-and-six-of-cups',
  'the-hierophant-and-six-of-cups',
  'the-lovers-and-six-of-cups',
  'the-chariot-and-six-of-cups',
  'strength-and-six-of-cups',
  'the-hermit-and-six-of-cups',
  'wheel-of-fortune-and-six-of-cups',
  'justice-and-six-of-cups',
  'the-hanged-man-and-six-of-cups',
  'death-and-six-of-cups',
  'temperance-and-six-of-cups',
  'the-devil-and-six-of-cups',
  'the-tower-and-six-of-cups',
  'the-star-and-six-of-cups',
  'the-moon-and-six-of-cups',
  'the-sun-and-six-of-cups',
  'judgement-and-six-of-cups',
  'the-world-and-six-of-cups',
  'the-fool-and-seven-of-cups',
  'the-magician-and-seven-of-cups',
  'the-high-priestess-and-seven-of-cups',
  'the-empress-and-seven-of-cups',
  'the-emperor-and-seven-of-cups',
  'the-hierophant-and-seven-of-cups',
  'the-lovers-and-seven-of-cups',
  'the-chariot-and-seven-of-cups',
  'strength-and-seven-of-cups',
  'the-hermit-and-seven-of-cups',
  'wheel-of-fortune-and-seven-of-cups',
  'justice-and-seven-of-cups',
  'the-hanged-man-and-seven-of-cups',
  'death-and-seven-of-cups',
  'temperance-and-seven-of-cups',
  'the-devil-and-seven-of-cups',
  'the-tower-and-seven-of-cups',
  'the-star-and-seven-of-cups',
  'the-moon-and-seven-of-cups',
  'the-sun-and-seven-of-cups',
  'judgement-and-seven-of-cups',
  'the-world-and-seven-of-cups',
  'the-fool-and-eight-of-cups',
  'the-magician-and-eight-of-cups',
  'the-high-priestess-and-eight-of-cups',
  'the-empress-and-eight-of-cups',
  'the-emperor-and-eight-of-cups',
  'the-hierophant-and-eight-of-cups',
  'the-lovers-and-eight-of-cups',
  'the-chariot-and-eight-of-cups',
  'strength-and-eight-of-cups',
  'the-hermit-and-eight-of-cups',
  'wheel-of-fortune-and-eight-of-cups',
  'justice-and-eight-of-cups',
  'the-hanged-man-and-eight-of-cups',
  'death-and-eight-of-cups',
  'temperance-and-eight-of-cups',
  'the-devil-and-eight-of-cups',
  'the-tower-and-eight-of-cups',
  'the-star-and-eight-of-cups',
  'the-moon-and-eight-of-cups',
  'the-sun-and-eight-of-cups',
  'judgement-and-eight-of-cups',
  'the-world-and-eight-of-cups',
  'the-fool-and-nine-of-cups',
  'the-magician-and-nine-of-cups',
  'the-high-priestess-and-nine-of-cups',
  'the-empress-and-nine-of-cups',
  'the-emperor-and-nine-of-cups',
  'the-hierophant-and-nine-of-cups',
  'the-lovers-and-nine-of-cups',
  'the-chariot-and-nine-of-cups',
  'strength-and-nine-of-cups',
  'the-hermit-and-nine-of-cups',
  'wheel-of-fortune-and-nine-of-cups',
  'justice-and-nine-of-cups',
  'the-hanged-man-and-nine-of-cups',
  'death-and-nine-of-cups',
  'temperance-and-nine-of-cups',
  'the-devil-and-nine-of-cups',
  'the-tower-and-nine-of-cups',
  'the-star-and-nine-of-cups',
  'the-moon-and-nine-of-cups',
  'the-sun-and-nine-of-cups',
  'judgement-and-nine-of-cups',
  'the-world-and-nine-of-cups',
  'the-fool-and-ten-of-cups',
  'the-magician-and-ten-of-cups',
  'the-high-priestess-and-ten-of-cups',
  'the-empress-and-ten-of-cups',
  'the-emperor-and-ten-of-cups',
  'the-hierophant-and-ten-of-cups',
  'the-lovers-and-ten-of-cups',
  'the-chariot-and-ten-of-cups',
  'strength-and-ten-of-cups',
  'the-hermit-and-ten-of-cups',
  'wheel-of-fortune-and-ten-of-cups',
  'justice-and-ten-of-cups',
  'the-hanged-man-and-ten-of-cups',
  'death-and-ten-of-cups',
  'temperance-and-ten-of-cups',
  'the-devil-and-ten-of-cups',
  'the-tower-and-ten-of-cups',
  'the-star-and-ten-of-cups',
  'the-moon-and-ten-of-cups',
  'the-sun-and-ten-of-cups',
  'judgement-and-ten-of-cups',
  'the-world-and-ten-of-cups',
  'the-fool-and-page-of-cups',
  'the-magician-and-page-of-cups',
  'the-high-priestess-and-page-of-cups',
  'the-empress-and-page-of-cups',
  'the-emperor-and-page-of-cups',
  'the-hierophant-and-page-of-cups',
  'the-lovers-and-page-of-cups',
  'the-chariot-and-page-of-cups',
  'strength-and-page-of-cups',
  'the-hermit-and-page-of-cups',
  'wheel-of-fortune-and-page-of-cups',
  'justice-and-page-of-cups',
  'the-hanged-man-and-page-of-cups',
  'death-and-page-of-cups',
  'temperance-and-page-of-cups',
  'the-devil-and-page-of-cups',
  'the-tower-and-page-of-cups',
  'the-star-and-page-of-cups',
  'the-moon-and-page-of-cups',
  'the-sun-and-page-of-cups',
  'judgement-and-page-of-cups',
  'the-world-and-page-of-cups',
  'the-fool-and-knight-of-cups',
  'the-magician-and-knight-of-cups',
  'the-high-priestess-and-knight-of-cups',
  'the-empress-and-knight-of-cups',
  'the-emperor-and-knight-of-cups',
  'the-hierophant-and-knight-of-cups',
  'the-lovers-and-knight-of-cups',
  'the-chariot-and-knight-of-cups',
  'strength-and-knight-of-cups',
  'the-hermit-and-knight-of-cups',
  'wheel-of-fortune-and-knight-of-cups',
  'justice-and-knight-of-cups',
  'the-hanged-man-and-knight-of-cups',
  'death-and-knight-of-cups',
  'temperance-and-knight-of-cups',
  'the-devil-and-knight-of-cups',
  'the-tower-and-knight-of-cups',
  'the-star-and-knight-of-cups',
  'the-moon-and-knight-of-cups',
  'the-sun-and-knight-of-cups',
  'judgement-and-knight-of-cups',
  'the-world-and-knight-of-cups',
  'the-fool-and-queen-of-cups',
  'the-magician-and-queen-of-cups',
  'the-high-priestess-and-queen-of-cups',
  'the-empress-and-queen-of-cups',
  'the-emperor-and-queen-of-cups',
  'the-hierophant-and-queen-of-cups',
  'the-lovers-and-queen-of-cups',
  'the-chariot-and-queen-of-cups',
  'strength-and-queen-of-cups',
  'the-hermit-and-queen-of-cups',
  'wheel-of-fortune-and-queen-of-cups',
  'justice-and-queen-of-cups',
  'the-hanged-man-and-queen-of-cups',
  'death-and-queen-of-cups',
  'temperance-and-queen-of-cups',
  'the-devil-and-queen-of-cups',
  'the-tower-and-queen-of-cups',
  'the-star-and-queen-of-cups',
  'the-moon-and-queen-of-cups',
  'the-sun-and-queen-of-cups',
  'judgement-and-queen-of-cups',
  'the-world-and-queen-of-cups',
  'the-fool-and-king-of-cups',
  'the-magician-and-king-of-cups',
  'the-high-priestess-and-king-of-cups',
  'the-empress-and-king-of-cups',
  'the-emperor-and-king-of-cups',
  'the-hierophant-and-king-of-cups',
  'the-lovers-and-king-of-cups',
  'the-chariot-and-king-of-cups',
  'strength-and-king-of-cups',
  'the-hermit-and-king-of-cups',
  'wheel-of-fortune-and-king-of-cups',
  'justice-and-king-of-cups',
  'the-hanged-man-and-king-of-cups',
  'death-and-king-of-cups',
  'temperance-and-king-of-cups',
  'the-devil-and-king-of-cups',
  'the-tower-and-king-of-cups',
  'the-star-and-king-of-cups',
  'the-moon-and-king-of-cups',
  'the-sun-and-king-of-cups',
  'judgement-and-king-of-cups',
  'the-world-and-king-of-cups',
  'the-fool-and-ace-of-swords',
  'the-magician-and-ace-of-swords',
  'the-high-priestess-and-ace-of-swords',
  'the-empress-and-ace-of-swords',
  'the-emperor-and-ace-of-swords',
  'the-hierophant-and-ace-of-swords',
  'the-lovers-and-ace-of-swords',
  'the-chariot-and-ace-of-swords',
  'strength-and-ace-of-swords',
  'the-hermit-and-ace-of-swords',
  'wheel-of-fortune-and-ace-of-swords',
  'justice-and-ace-of-swords',
  'the-hanged-man-and-ace-of-swords',
  'death-and-ace-of-swords',
  'temperance-and-ace-of-swords',
  'the-devil-and-ace-of-swords',
  'the-tower-and-ace-of-swords',
  'the-star-and-ace-of-swords',
  'the-moon-and-ace-of-swords',
  'the-sun-and-ace-of-swords',
  'judgement-and-ace-of-swords',
  'the-world-and-ace-of-swords',
  'the-fool-and-two-of-swords',
  'the-magician-and-two-of-swords',
  'the-high-priestess-and-two-of-swords',
  'the-empress-and-two-of-swords',
  'the-emperor-and-two-of-swords',
  'the-hierophant-and-two-of-swords',
  'the-lovers-and-two-of-swords',
  'the-chariot-and-two-of-swords',
  'strength-and-two-of-swords',
  'the-hermit-and-two-of-swords',
  'wheel-of-fortune-and-two-of-swords',
  'justice-and-two-of-swords',
  'the-hanged-man-and-two-of-swords',
  'death-and-two-of-swords',
  'temperance-and-two-of-swords',
  'the-devil-and-two-of-swords',
  'the-tower-and-two-of-swords',
  'the-star-and-two-of-swords',
  'the-moon-and-two-of-swords',
  'the-sun-and-two-of-swords',
  'judgement-and-two-of-swords',
  'the-world-and-two-of-swords',
  'the-fool-and-three-of-swords',
  'the-magician-and-three-of-swords',
  'the-high-priestess-and-three-of-swords',
  'the-empress-and-three-of-swords',
  'the-emperor-and-three-of-swords',
  'the-hierophant-and-three-of-swords',
  'the-lovers-and-three-of-swords',
  'the-chariot-and-three-of-swords',
  'strength-and-three-of-swords',
  'the-hermit-and-three-of-swords',
  'wheel-of-fortune-and-three-of-swords',
  'justice-and-three-of-swords',
  'the-hanged-man-and-three-of-swords',
  'death-and-three-of-swords',
  'temperance-and-three-of-swords',
  'the-devil-and-three-of-swords',
  'the-tower-and-three-of-swords',
  'the-star-and-three-of-swords',
  'the-moon-and-three-of-swords',
  'the-sun-and-three-of-swords',
  'judgement-and-three-of-swords',
  'the-world-and-three-of-swords',
  'the-fool-and-five-of-swords',
  'the-magician-and-five-of-swords',
  'the-high-priestess-and-five-of-swords',
  'the-empress-and-five-of-swords',
  'the-emperor-and-five-of-swords',
  'the-hierophant-and-five-of-swords',
  'the-lovers-and-five-of-swords',
  'the-chariot-and-five-of-swords',
  'strength-and-five-of-swords',
  'the-hermit-and-five-of-swords',
  'wheel-of-fortune-and-five-of-swords',
  'justice-and-five-of-swords',
  'the-hanged-man-and-five-of-swords',
  'death-and-five-of-swords',
  'temperance-and-five-of-swords',
  'the-devil-and-five-of-swords',
  'the-tower-and-five-of-swords',
  'the-star-and-five-of-swords',
  'the-moon-and-five-of-swords',
  'the-sun-and-five-of-swords',
  'judgement-and-five-of-swords',
  'the-world-and-five-of-swords',
  'the-fool-and-eight-of-swords',
  'the-magician-and-eight-of-swords',
  'the-high-priestess-and-eight-of-swords',
  'the-empress-and-eight-of-swords',
  'the-emperor-and-eight-of-swords',
  'the-hierophant-and-eight-of-swords',
  'the-lovers-and-eight-of-swords',
  'the-chariot-and-eight-of-swords',
  'strength-and-eight-of-swords',
  'the-hermit-and-eight-of-swords',
  'wheel-of-fortune-and-eight-of-swords',
  'justice-and-eight-of-swords',
  'the-hanged-man-and-eight-of-swords',
  'death-and-eight-of-swords',
  'temperance-and-eight-of-swords',
  'the-devil-and-eight-of-swords',
  'the-tower-and-eight-of-swords',
  'the-star-and-eight-of-swords',
  'the-moon-and-eight-of-swords',
  'the-sun-and-eight-of-swords',
  'judgement-and-eight-of-swords',
  'the-world-and-eight-of-swords',
  'the-fool-and-nine-of-swords',
  'the-magician-and-nine-of-swords',
  'the-high-priestess-and-nine-of-swords',
  'the-empress-and-nine-of-swords',
  'the-emperor-and-nine-of-swords',
  'the-hierophant-and-nine-of-swords',
  'the-lovers-and-nine-of-swords',
  'the-chariot-and-nine-of-swords',
  'strength-and-nine-of-swords',
  'the-hermit-and-nine-of-swords',
  'wheel-of-fortune-and-nine-of-swords',
  'justice-and-nine-of-swords',
  'the-hanged-man-and-nine-of-swords',
  'death-and-nine-of-swords',
  'temperance-and-nine-of-swords',
  'the-devil-and-nine-of-swords',
  'the-tower-and-nine-of-swords',
  'the-star-and-nine-of-swords',
  'the-moon-and-nine-of-swords',
  'the-sun-and-nine-of-swords',
  'judgement-and-nine-of-swords',
  'the-world-and-nine-of-swords',
  'the-fool-and-ten-of-swords',
  'the-magician-and-ten-of-swords',
  'the-high-priestess-and-ten-of-swords',
  'the-empress-and-ten-of-swords',
  'the-emperor-and-ten-of-swords',
  'the-hierophant-and-ten-of-swords',
  'the-lovers-and-ten-of-swords',
  'the-chariot-and-ten-of-swords',
  'strength-and-ten-of-swords',
  'the-hermit-and-ten-of-swords',
  'wheel-of-fortune-and-ten-of-swords',
  'justice-and-ten-of-swords',
  'the-hanged-man-and-ten-of-swords',
  'death-and-ten-of-swords',
  'temperance-and-ten-of-swords',
  'the-devil-and-ten-of-swords',
  'the-tower-and-ten-of-swords',
  'the-star-and-ten-of-swords',
  'the-moon-and-ten-of-swords',
  'the-sun-and-ten-of-swords',
  'judgement-and-ten-of-swords',
  'the-world-and-ten-of-swords',
  'the-fool-and-page-of-swords',
  'the-magician-and-page-of-swords',
  'the-empress-and-page-of-swords',
  'the-emperor-and-page-of-swords',
  'the-hierophant-and-page-of-swords',
  'the-lovers-and-page-of-swords',
  'the-chariot-and-page-of-swords',
  'strength-and-page-of-swords',
  'the-hermit-and-page-of-swords',
  'wheel-of-fortune-and-page-of-swords',
  'justice-and-page-of-swords',
  'the-hanged-man-and-page-of-swords',
  'death-and-page-of-swords',
  'temperance-and-page-of-swords',
  'the-devil-and-page-of-swords',
  'the-tower-and-page-of-swords',
  'the-star-and-page-of-swords',
  'the-moon-and-page-of-swords',
  'the-sun-and-page-of-swords',
  'judgement-and-page-of-swords',
  'the-world-and-page-of-swords',
  'the-fool-and-knight-of-swords',
  'the-magician-and-knight-of-swords',
  'the-high-priestess-and-knight-of-swords',
  'the-empress-and-knight-of-swords',
  'the-emperor-and-knight-of-swords',
  'the-hierophant-and-knight-of-swords',
  'the-lovers-and-knight-of-swords',
  'the-chariot-and-knight-of-swords',
  'strength-and-knight-of-swords',
  'the-hermit-and-knight-of-swords',
  'wheel-of-fortune-and-knight-of-swords',
  'justice-and-knight-of-swords',
  'the-hanged-man-and-knight-of-swords',
  'death-and-knight-of-swords',
  'temperance-and-knight-of-swords',
  'the-devil-and-knight-of-swords',
  'the-tower-and-knight-of-swords',
  'the-star-and-knight-of-swords',
  'the-moon-and-knight-of-swords',
  'the-sun-and-knight-of-swords',
  'judgement-and-knight-of-swords',
  'the-world-and-knight-of-swords',
  'the-fool-and-queen-of-swords',
  'the-magician-and-queen-of-swords',
  'the-high-priestess-and-queen-of-swords',
  'the-empress-and-queen-of-swords',
  'the-emperor-and-queen-of-swords',
  'the-hierophant-and-queen-of-swords',
  'the-lovers-and-queen-of-swords',
  'the-chariot-and-queen-of-swords',
  'strength-and-queen-of-swords',
  'the-hermit-and-queen-of-swords',
  'wheel-of-fortune-and-queen-of-swords',
  'justice-and-queen-of-swords',
  'the-hanged-man-and-queen-of-swords',
  'death-and-queen-of-swords',
  'temperance-and-queen-of-swords',
  'the-devil-and-queen-of-swords',
  'the-tower-and-queen-of-swords',
  'the-star-and-queen-of-swords',
  'the-moon-and-queen-of-swords',
  'the-sun-and-queen-of-swords',
  'judgement-and-queen-of-swords',
  'the-world-and-queen-of-swords',
  'the-fool-and-king-of-swords',
  'the-magician-and-king-of-swords',
  'the-high-priestess-and-king-of-swords',
  'the-empress-and-king-of-swords',
  'the-emperor-and-king-of-swords',
  'the-hierophant-and-king-of-swords',
  'the-lovers-and-king-of-swords',
  'the-chariot-and-king-of-swords',
  'strength-and-king-of-swords',
  'the-hermit-and-king-of-swords',
  'wheel-of-fortune-and-king-of-swords',
  'justice-and-king-of-swords',
  'the-hanged-man-and-king-of-swords',
  'death-and-king-of-swords',
  'temperance-and-king-of-swords',
  'the-devil-and-king-of-swords',
  'the-tower-and-king-of-swords',
  'the-star-and-king-of-swords',
  'the-moon-and-king-of-swords',
  'the-sun-and-king-of-swords',
  'judgement-and-king-of-swords',
  'the-world-and-king-of-swords',
  'the-fool-and-ace-of-pentacles',
  'the-magician-and-ace-of-pentacles',
  'the-high-priestess-and-ace-of-pentacles',
  'the-empress-and-ace-of-pentacles',
  'the-emperor-and-ace-of-pentacles',
  'the-hierophant-and-ace-of-pentacles',
  'the-lovers-and-ace-of-pentacles',
  'the-chariot-and-ace-of-pentacles',
  'strength-and-ace-of-pentacles',
  'the-hermit-and-ace-of-pentacles',
  'wheel-of-fortune-and-ace-of-pentacles',
  'justice-and-ace-of-pentacles',
  'the-hanged-man-and-ace-of-pentacles',
  'death-and-ace-of-pentacles',
  'temperance-and-ace-of-pentacles',
  'the-devil-and-ace-of-pentacles',
  'the-tower-and-ace-of-pentacles',
  'the-star-and-ace-of-pentacles',
  'the-moon-and-ace-of-pentacles',
  'the-sun-and-ace-of-pentacles',
  'judgement-and-ace-of-pentacles',
  'the-world-and-ace-of-pentacles',
  'the-fool-and-five-of-pentacles',
  'the-magician-and-five-of-pentacles',
  'the-high-priestess-and-five-of-pentacles',
  'the-empress-and-five-of-pentacles',
  'the-emperor-and-five-of-pentacles',
  'the-hierophant-and-five-of-pentacles',
  'the-lovers-and-five-of-pentacles',
  'the-chariot-and-five-of-pentacles',
  'strength-and-five-of-pentacles',
  'the-hermit-and-five-of-pentacles',
  'wheel-of-fortune-and-five-of-pentacles',
  'justice-and-five-of-pentacles',
  'the-hanged-man-and-five-of-pentacles',
  'death-and-five-of-pentacles',
  'temperance-and-five-of-pentacles',
  'the-devil-and-five-of-pentacles',
  'the-tower-and-five-of-pentacles',
  'the-star-and-five-of-pentacles',
  'the-moon-and-five-of-pentacles',
  'the-sun-and-five-of-pentacles',
  'judgement-and-five-of-pentacles',
  'the-world-and-five-of-pentacles',
  'the-fool-and-eight-of-pentacles',
  'the-magician-and-eight-of-pentacles',
  'the-high-priestess-and-eight-of-pentacles',
  'the-empress-and-eight-of-pentacles',
  'the-emperor-and-eight-of-pentacles',
  'the-hierophant-and-eight-of-pentacles',
  'the-lovers-and-eight-of-pentacles',
  'the-chariot-and-eight-of-pentacles',
  'strength-and-eight-of-pentacles',
  'the-hermit-and-eight-of-pentacles',
  'wheel-of-fortune-and-eight-of-pentacles',
  'justice-and-eight-of-pentacles',
  'the-hanged-man-and-eight-of-pentacles',
  'death-and-eight-of-pentacles',
  'temperance-and-eight-of-pentacles',
  'the-devil-and-eight-of-pentacles',
  'the-tower-and-eight-of-pentacles',
  'the-star-and-eight-of-pentacles',
  'the-moon-and-eight-of-pentacles',
  'the-sun-and-eight-of-pentacles',
  'judgement-and-eight-of-pentacles',
  'the-world-and-eight-of-pentacles',
  'the-fool-and-nine-of-pentacles',
  'the-magician-and-nine-of-pentacles',
  'the-high-priestess-and-nine-of-pentacles',
  'the-empress-and-nine-of-pentacles',
  'the-emperor-and-nine-of-pentacles',
  'the-hierophant-and-nine-of-pentacles',
  'the-lovers-and-nine-of-pentacles',
  'the-chariot-and-nine-of-pentacles',
  'strength-and-nine-of-pentacles',
  'the-hermit-and-nine-of-pentacles',
  'wheel-of-fortune-and-nine-of-pentacles',
  'justice-and-nine-of-pentacles',
  'the-hanged-man-and-nine-of-pentacles',
  'death-and-nine-of-pentacles',
  'temperance-and-nine-of-pentacles',
  'the-devil-and-nine-of-pentacles',
  'the-tower-and-nine-of-pentacles',
  'the-star-and-nine-of-pentacles',
  'the-moon-and-nine-of-pentacles',
  'the-sun-and-nine-of-pentacles',
  'judgement-and-nine-of-pentacles',
  'the-world-and-nine-of-pentacles',
  'the-fool-and-ten-of-pentacles',
  'the-magician-and-ten-of-pentacles',
  'the-high-priestess-and-ten-of-pentacles',
  'the-empress-and-ten-of-pentacles',
  'the-emperor-and-ten-of-pentacles',
  'the-hierophant-and-ten-of-pentacles',
  'the-lovers-and-ten-of-pentacles',
  'the-chariot-and-ten-of-pentacles',
  'strength-and-ten-of-pentacles',
  'the-hermit-and-ten-of-pentacles',
  'wheel-of-fortune-and-ten-of-pentacles',
  'justice-and-ten-of-pentacles',
  'the-hanged-man-and-ten-of-pentacles',
  'death-and-ten-of-pentacles',
  'temperance-and-ten-of-pentacles',
  'the-devil-and-ten-of-pentacles',
  'the-tower-and-ten-of-pentacles',
  'the-star-and-ten-of-pentacles',
  'the-moon-and-ten-of-pentacles',
  'the-sun-and-ten-of-pentacles',
  'judgement-and-ten-of-pentacles',
  'the-world-and-ten-of-pentacles',
  'the-fool-and-page-of-pentacles',
  'the-magician-and-page-of-pentacles',
  'the-high-priestess-and-page-of-pentacles',
  'the-empress-and-page-of-pentacles',
  'the-emperor-and-page-of-pentacles',
  'the-hierophant-and-page-of-pentacles',
  'the-lovers-and-page-of-pentacles',
  'the-chariot-and-page-of-pentacles',
  'strength-and-page-of-pentacles',
  'the-hermit-and-page-of-pentacles',
  'wheel-of-fortune-and-page-of-pentacles',
  'justice-and-page-of-pentacles',
  'the-hanged-man-and-page-of-pentacles',
  'death-and-page-of-pentacles',
  'temperance-and-page-of-pentacles',
  'the-devil-and-page-of-pentacles',
  'the-tower-and-page-of-pentacles',
  'the-star-and-page-of-pentacles',
  'the-moon-and-page-of-pentacles',
  'the-sun-and-page-of-pentacles',
  'judgement-and-page-of-pentacles',
  'the-world-and-page-of-pentacles',
  'the-fool-and-knight-of-pentacles',
  'the-magician-and-knight-of-pentacles',
  'the-high-priestess-and-knight-of-pentacles',
  'the-empress-and-knight-of-pentacles',
  'the-emperor-and-knight-of-pentacles',
  'the-hierophant-and-knight-of-pentacles',
  'the-lovers-and-knight-of-pentacles',
  'the-chariot-and-knight-of-pentacles',
  'strength-and-knight-of-pentacles',
  'the-hermit-and-knight-of-pentacles',
  'wheel-of-fortune-and-knight-of-pentacles',
  'justice-and-knight-of-pentacles',
  'the-hanged-man-and-knight-of-pentacles',
  'death-and-knight-of-pentacles',
  'temperance-and-knight-of-pentacles',
  'the-devil-and-knight-of-pentacles',
  'the-tower-and-knight-of-pentacles',
  'the-star-and-knight-of-pentacles',
  'the-moon-and-knight-of-pentacles',
  'the-sun-and-knight-of-pentacles',
  'judgement-and-knight-of-pentacles',
  'the-world-and-knight-of-pentacles',
  'the-fool-and-queen-of-pentacles',
  'the-magician-and-queen-of-pentacles',
  'the-high-priestess-and-queen-of-pentacles',
  'the-empress-and-queen-of-pentacles',
  'the-emperor-and-queen-of-pentacles',
  'the-hierophant-and-queen-of-pentacles',
  'the-lovers-and-queen-of-pentacles',
  'the-chariot-and-queen-of-pentacles',
  'strength-and-queen-of-pentacles',
  'the-hermit-and-queen-of-pentacles',
  'wheel-of-fortune-and-queen-of-pentacles',
  'justice-and-queen-of-pentacles',
  'the-hanged-man-and-queen-of-pentacles',
  'death-and-queen-of-pentacles',
  'temperance-and-queen-of-pentacles',
  'the-devil-and-queen-of-pentacles',
  'the-tower-and-queen-of-pentacles',
  'the-star-and-queen-of-pentacles',
  'the-moon-and-queen-of-pentacles',
  'the-sun-and-queen-of-pentacles',
  'judgement-and-queen-of-pentacles',
  'the-world-and-queen-of-pentacles',
  'the-fool-and-king-of-pentacles',
  'the-magician-and-king-of-pentacles',
  'the-high-priestess-and-king-of-pentacles',
  'the-empress-and-king-of-pentacles',
  'the-emperor-and-king-of-pentacles',
  'the-hierophant-and-king-of-pentacles',
  'the-lovers-and-king-of-pentacles',
  'the-chariot-and-king-of-pentacles',
  'strength-and-king-of-pentacles',
  'the-hermit-and-king-of-pentacles',
  'wheel-of-fortune-and-king-of-pentacles',
  'justice-and-king-of-pentacles',
  'the-hanged-man-and-king-of-pentacles',
  'death-and-king-of-pentacles',
  'temperance-and-king-of-pentacles',
  'the-devil-and-king-of-pentacles',
  'the-tower-and-king-of-pentacles',
  'the-star-and-king-of-pentacles',
  'the-moon-and-king-of-pentacles',
  'the-sun-and-king-of-pentacles',
  'judgement-and-king-of-pentacles',
  'the-world-and-king-of-pentacles',
]
