import type { LoveContext } from '../card-love-extended'

export const SWORDS: Record<string, LoveContext> = {
  'ace-of-swords': {
    loveLong: `The Ace of Swords in love is the moment something becomes unmistakably clear. A truth that has been forming under the surface — about who someone is to you, about what you actually want from a relationship, about what is no longer working — breaks through into language. The blade is sharp because the insight is sharp. Once seen, it cannot easily be unseen, and the card asks what you intend to do with what you now know.

For some this lands as a breakthrough conversation. The words you could not find for months arrive whole, and you say the thing that has needed saying. For others it is a single private moment of recognition — you realise you have been holding back, or that the person you have been trying to fit yourself around is not actually offering what you need. New connections under the Ace of Swords often begin with an unusually honest first conversation, the kind where small talk runs out quickly and something real takes its place.

The growth edge here is delivery. Clarity is a gift, but truth told carelessly cuts the wrong things. Take a beat between insight and speech. Choose words that name what is real without weaponising it. The Ace of Swords does not reward cruelty disguised as honesty; it rewards precision, the kind that opens a door rather than slams one. If the clarity is asking you to act — to commit, to leave, to speak — let yourself trust it, but bring care with you when you move. Sharp things handled well shape something better. Handled badly, they simply wound.`,
    loveFaqs: [
      { q: 'What does the Ace of Swords mean in love?', a: `It marks a moment of genuine clarity arriving in a relationship or in your own thinking about love. A truth you have been circling becomes clearly visible — sometimes through a conversation, sometimes through a quiet private realisation. You may suddenly know what you want, what you no longer accept, or what you need to say. The card favours honest communication and clean decisions over polite avoidance. New connections under this card often begin with a refreshingly direct exchange. The growth edge is in how you deliver the clarity: with precision and care rather than as a blunt weapon.` },
      { q: 'Is the Ace of Swords a good love card?', a: `It is a powerful card rather than a sweetly romantic one. The Ace of Swords does not promise candlelight; it promises truth, and truth is genuinely good news when you have been living with confusion. Couples receive it as the conversation that finally cuts through the fog. Singles often receive it as a sharp recognition of what they actually want, which then makes the next choice obvious. The card rewards those willing to honour what they have understood. If you can speak and act from that clarity with care, the Ace of Swords becomes one of the most constructive cards you can draw in love.` },
      { q: 'What does the Ace of Swords mean for clarity in a relationship?', a: `It signals that genuine clarity is available now, even if previous attempts to find it have failed. You will likely be able to see the shape of the connection plainly — what is working, what is not, what has been unspoken. The card favours the conversation where both people can finally name what has been hovering. Write things down before you speak; precision matters here. Ask the simple, unflattering questions and let the answers land. The clarity may be uncomfortable, but it ends the exhausting work of pretending you do not already half-know what is true.` },
      { q: 'What does the Ace of Swords say about how someone feels?', a: `Their feelings are unusually clear to them right now, and probably more direct than you are used to. Expect honesty rather than hedging. If they care for you, they are likely to say so plainly; if they have doubts, those will also surface in language rather than silence. This card is rarely about hidden emotion — it is about emotion being named. Whatever they tell you, treat it as accurate rather than rehearsed. The Ace of Swords does not favour vague reassurance or polite half-truths; it brings the conversation that establishes where each of you actually stands.` },
    ],
  },

  'two-of-swords': {
    loveLong: `The Two of Swords in love is the held breath of indecision. You are sitting between two options — stay or go, speak or stay silent, choose this person or hold out for someone else — and you have managed, through real effort, to avoid choosing. The blindfold is the giveaway. You have stopped looking at the situation directly because looking would require you to act on what you saw. So the scales stay balanced, the swords stay crossed, and nothing moves.

There is often a relational version of this where two people are both unwilling to make the first move. One of you is waiting for the other to bring up the difficult subject, define the relationship, or break the tension that has been quietly building. The Two of Swords describes that exact standoff. It is not malicious — neither of you is trying to hurt the other — but the stillness has its own cost. Connection cannot deepen while everyone is hovering politely at the threshold.

The growth edge here is the willingness to look. Take the blindfold off, even just in private. Ask yourself the question you have been refusing to ask: which way does your heart actually lean when you stop performing fairness? You usually know. Underneath the careful weighing there is a quiet preference, and your job is to admit it to yourself before it can become a real choice in the world. The card does not demand a dramatic decision in the next hour, only an honest look. Once you can see, the path forward almost always becomes walkable. The blindfold was the obstacle. The choice itself is often smaller than the avoiding of it.`,
    loveFaqs: [
      { q: 'What does the Two of Swords mean in love?', a: `It points to a stalemate — either inside you or between you and someone else. A decision is hovering and is being deferred, usually because making it feels too costly. You may be balancing two possible relationships, holding back from defining the one you are in, or waiting silently for the other person to move first. The card honours how hard the choice is, but it also notes that the suspension has its own price. Connection cannot grow while everyone is refusing to look. Be willing to take the blindfold off, even just in your own private thinking.` },
      { q: 'Is the Two of Swords a yes for love?', a: `Not directly. It is more of a pause than a yes or a no — a card about not-yet-deciding rather than about the outcome of the decision. For a yes-or-no question, the Two of Swords usually means the answer is being avoided rather than absent. If you have asked the cards whether to stay, leave, commit, or speak, this card invites you to admit that you already half-know and have been postponing the responsibility of acting on it. The honest yes or no is available; you just have to be willing to see it.` },
      { q: 'What does the Two of Swords mean for a new relationship?', a: `Early connections under this card often plateau at a careful, cordial distance. Both of you may be uncertain whether to invest, and rather than name the uncertainty, you politely keep things light. Nothing breaks, but nothing deepens either. The card invites the slightly braver conversation about where each of you stands and what you are actually looking for. Even a small honest exchange usually shifts the dynamic. If you would rather not have that conversation, ask yourself why; the answer often tells you more about the connection than the conversation itself would have.` },
      { q: 'What does the Two of Swords say about how someone feels about me?', a: `Their feelings are likely real but held in suspension. They have not allowed themselves to fully look at what they feel, often because doing so would require them to act, and acting feels too risky right now. This is not the same as indifference; it is more like a careful refusal to commit even internally. They may be weighing you against another option, against their fear, or against a version of life they are not ready to let go of. Do not interpret the stillness as your answer. Ask, gently and directly, and let them practise honesty.` },
    ],
  },

  'three-of-swords': {
    loveLong: `The Three of Swords in love is the heartbreak card, and there is no comfortable way around that. It speaks to the kind of pain that comes from a relationship — a separation, a betrayal, a truth that arrived and changed everything, the slow recognition that someone you loved is not who you thought they were. The image is direct because the feeling is direct. The card is not predicting future pain so much as honouring pain that is real now, or grief that is finally being allowed into conscious view.

This card can also mark a difficult truth being spoken or received. The conversation you have been dreading happens. The thing you suspected is confirmed. The story you were telling yourself collapses. There is grief in the collapse even when the truth was needed. You may be the one breaking the news or the one hearing it; either way, the cleanness of the cut does not soften what it costs.

The growth edge with the Three of Swords is to let yourself feel what is here rather than rushing to recover. Heartbreak treated like an inconvenience does not actually heal; it just goes underground and shapes the next relationship from the shadows. Cry when you need to. Cancel things. Let trusted people in. Resist the urge to leap into the lesson before the feeling has finished speaking. Practical guidance is simple: name what hurts, share it with someone safe, and give yourself an honest amount of time. The pain will not be permanent, but pretending you are fine will lengthen rather than shorten it. The Three of Swords is also, quietly, a card of release. Something needed to leave so that something truer could one day take its place.`,
    loveFaqs: [
      { q: 'What does the Three of Swords mean in love?', a: `It marks heartbreak in some form — a separation, a betrayal, a painful truth, the loss of an illusion you had been protecting. The pain is real and the card does not ask you to minimise it. Sometimes the heartbreak is acute and recent; sometimes it is grief that has been waiting under the surface and is finally being allowed in. The card asks for honesty about what is hurting and for the courage to feel it rather than perform recovery. There is release inside the wound. Something needed to leave so that something truer could eventually grow.` },
      { q: 'Is the Three of Swords a warning in love?', a: `It can be, particularly when it appears before a difficult conversation, a discovery, or a decision. The card warns that pain is part of what is approaching, but it does not advise avoidance. Avoiding the Three of Swords usually just delays it and makes it heavier when it arrives. If you are heading toward a hard truth, prepare yourself rather than dodge it: choose supportive people to be near, lower other commitments, and remind yourself that pain you walk through honestly hurts less in the long run than pain you keep dressing up. The card is severe, not punitive.` },
      { q: 'What does the Three of Swords mean for ending a relationship?', a: `It often accompanies endings, but it does not require them. Sometimes the card describes a wound a relationship can heal from with honest work; sometimes it describes the final clarity that the relationship cannot continue. The difference is usually whether both people are willing to face what is in the open. If the Three of Swords is showing you the end, treat the ending with the gravity it deserves. There may be grief even when leaving is right. Allow time for mourning, do not rush into the next thing, and do not weaponise the pain against the person who shared it.` },
      { q: 'What does the Three of Swords say about how someone feels about me?', a: `Their feelings are likely pained right now, whether toward you or about the situation you share. They may be hurt, grieving, or sitting with a truth that has been hard to hold. This is not the same as them no longer caring; sorrow is often a sign of how much someone has been invested. They may also need space to process before they can speak clearly. Do not pursue a clean resolution while the wound is still bleeding. Give time and gentleness, and trust that whatever conversation needs to happen will be more honest when both of you have steadied.` },
    ],
  },

  'four-of-swords': {
    loveLong: `The Four of Swords in love is the call to rest. Something in your romantic life has been demanding — a difficult breakup, a long stretch of dating that drained more than it gave, a relationship going through a hard season — and the card is telling you to stop pushing for a moment and let yourself recover. This is not the same as giving up. It is the deliberate, healing pause that makes everything else possible afterward.

For singles, the card often counsels a deliberate withdrawal from dating apps, from the search, from the pressure to keep producing romantic effort while your reserves are empty. Trying to meet someone while exhausted and unhealed rarely brings in the person you actually want; it brings in whoever fits the shape of your current depletion. Step back. Do the dull, unglamorous work of resting properly. The right re-entry will come on its own once you are no longer running on fumes.

For couples, the Four of Swords can mark a quieter phase where the relationship needs less intensity and more peace. After a difficult patch, this might look like deliberately calm evenings, fewer hard conversations for a little while, more practical care and less analysis. It is not stagnation. It is the convalescence period that lets the connection knit back together. The growth edge here is to trust that rest is doing real work even when nothing appears to be happening on the surface. Do not interrupt the recovery with new dramas. Honour the quiet. The card is reminding you that the strongest love lives need genuine pauses, and that the pause you take now will pay back generously once you are ready to re-engage.`,
    loveFaqs: [
      { q: 'What does the Four of Swords mean in love?', a: `It is the card of rest and recovery in a romantic context. Something has been demanding — a breakup, a draining dating phase, a hard chapter in a relationship — and the card is telling you to pause and let yourself heal. For singles this often means stepping back from active pursuit. For couples it can mean a deliberately quieter phase with less intensity and more practical care. The pause is not stagnation; it is the work that makes everything afterward possible. Trust that genuine rest is doing its job even when nothing dramatic appears on the surface.` },
      { q: 'Is the Four of Swords a good love card?', a: `It is a wise card rather than an exciting one. The Four of Swords does not bring fireworks; it brings the steadying breath you have been postponing. For anyone tired, hurt, or recently come through something heavy, this is genuinely good news. The card honours what you have been carrying and gives you permission to set it down for a while. Couples find it strengthening in the longer view: a relationship that learns to rest together becomes more durable than one constantly chasing intensity. Take the slower pace seriously. It is not a delay; it is the foundation for what follows.` },
      { q: 'What does the Four of Swords mean for healing after heartbreak?', a: `It is one of the most supportive cards you can draw at this stage. The Four of Swords confirms that what you need now is genuine rest, not more processing, not more analysing, not another conversation about what went wrong. Cancel the optional commitments. Sleep more. Take walks. Let trusted people be near without asking them to fix anything. Healing happens in the dull, repeated days of letting your nervous system settle. Resist the urge to date your way out of the grief. The card promises that the recovery you give yourself now will return strength when you are ready to open again.` },
      { q: 'What does the Four of Swords mean for being single?', a: `It often advises a deliberate, chosen period of stepping back from the search. Not forever — just for long enough to remember who you are without the dating noise. Delete the apps for a while if they have been draining you. Spend the time on rest, friendship, and the parts of your life that have been quietly neglected while you were trying to meet someone. The Four of Swords promises that the right re-entry will come more easily from a rested place than from a frantic one. Singleness here is not a problem to solve; it is a window to honour.` },
    ],
  },

  'five-of-swords': {
    loveLong: `The Five of Swords in love is the card of conflict, and specifically of the kind of conflict where winning costs more than losing would have. An argument has happened, or is happening, and someone is determined to be right. Pride has taken the wheel. Cutting words have been used. The other person may have walked away — physically, emotionally, or both — leaving the victor standing alone among the dropped swords, wondering whether the point that was defended was actually worth what defending it has just cost.

This card sometimes describes a relationship that has become hostile in subtler ways: small daily disagreements where each person is keeping score, sarcasm that pretends to be humour, the constant low pressure of someone trying to come out on top. That climate erodes love faster than almost anything else. The Five of Swords names it honestly so it can be addressed before more damage is done.

The growth edge is the willingness to ask whether being right is what you actually want here. Often the honest answer is no — what you want is to be heard, or respected, or to stop feeling small in the relationship. Those needs deserve to be named, but they cannot be met by winning arguments. Step out of the fight long enough to see what you are really fighting for. If you owe an apology, give it cleanly, without bundling in a counter-grievance. If the other person is the one with the sword raised, decide what you are willing to keep absorbing. The Five of Swords does not always advise leaving, but it asks you to stop pretending that this dynamic is sustainable. Pride is heavy. Put it down and see what the relationship looks like underneath.`,
    loveFaqs: [
      { q: 'What does the Five of Swords mean in love?', a: `It marks conflict, particularly the kind where pride has taken over and someone is determined to win regardless of cost. The card describes hollow victories — being right at the expense of the connection, scoring points that leave the relationship weaker, hostility that has crept into the daily climate. It asks you to look honestly at what you are actually defending. Often beneath the position there is a real need — to be heard, respected, or treated more gently — that cannot be met by winning the argument. Name the underlying need instead. The fight is rarely about what it appears to be about.` },
      { q: 'Is the Five of Swords a warning in love?', a: `Yes, and it is worth taking seriously. The card warns that the current pattern of conflict is corrosive and that continuing it will cost more than either of you currently sees. It is not predicting the end of the relationship; it is showing the dynamic that will end it if unaddressed. Take the warning as useful information rather than doom. The path forward involves at least one of you setting down the sword first — not as surrender but as a refusal to keep fighting on these terms. The longer the climate of hostility runs, the harder repair becomes.` },
      { q: 'What does the Five of Swords mean for ending a relationship?', a: `It often accompanies endings, especially the kind that arrive through accumulated conflict rather than a single decisive event. If the relationship is ending under this card, try to end it cleanly. The temptation will be to fire one last cutting truth on the way out, to make sure they know exactly what you think. Resist it. Endings handled with dignity heal faster than endings won. You will carry whatever you said last for longer than you imagine. Say the things that need saying, but say them without the urge to wound. Walk away whole rather than triumphant.` },
      { q: 'What does the Five of Swords say about how someone feels about me?', a: `They are likely feeling defensive, wounded, or oriented toward winning rather than toward the connection right now. Something has activated their pride, and they are not currently able to meet you in a soft place. This is rarely permanent — the Five of Swords is a phase rather than a verdict — but it does describe their current state. Pushing for resolution while they are in this mode tends to escalate rather than help. Give some space. When you do return to the conversation, lead with what you got wrong rather than what they did. That move often unlocks more than another round of arguing the case.` },
    ],
  },

  'six-of-swords': {
    loveLong: `The Six of Swords in love is the slow, hopeful card of moving on. After difficulty — a hard relationship, a painful chapter, a long stretch of feeling stuck — you are finally beginning to leave the rough water behind. The boat is small, the journey is quiet, and the far shore is not yet visible, but you are unmistakably in motion. This is the card of transition, not of arrival. The work now is the patient act of crossing.

For couples, the Six of Swords often describes a relationship moving past a hard season together — perhaps after grief, conflict, a health crisis, or a long-distance stretch. The intensity is dropping. You are still tender, but you are heading somewhere calmer, and the trip is something you are doing together. There is a quiet intimacy to this phase. It does not look dramatic, but it is genuine.

For singles or those leaving a relationship, the card honours the dignity of the in-between. You have made the decision to go. You have stepped onto the boat. Now you are in the part of the journey where you cannot yet see what comes next, and that uncertainty has its own ache. The growth edge is to keep rowing without constantly looking back. Each backward glance restarts grief from an earlier point. Each fantasy of returning to the dock costs energy you need for the crossing. Be honest with yourself about what you are still hoping the past will hand you — usually closure that, in truth, will form inside you rather than arrive from there. Trust the movement. Calmer water is real, and you are heading toward it even on the days when it does not feel like progress.`,
    loveFaqs: [
      { q: 'What does the Six of Swords mean in love?', a: `It is the card of moving on after a difficult phase. You may be leaving a relationship behind, leaving a hard chapter inside one, or simply rowing out of a long stretch of romantic difficulty. The journey is quiet rather than dramatic. The far shore is not yet visible, but the movement is real. The card asks you to keep going gently rather than rush. Resist the pull to look back too often; each backward glance restarts the grief. Calmer water is genuinely ahead, and you are closer to it than you can feel on any given day.` },
      { q: 'Is the Six of Swords a good love card?', a: `It is a quietly hopeful card. The Six of Swords does not promise the new shore in the next chapter, but it confirms that the worst of what you were in is behind you. For people in recovery from a hard relationship or a draining season, this is genuinely good news. The card honours the slowness of the transition without minimising it. It rewards patience, gentle companionship, and the steady act of continuing to row. Read it as confirmation that you are heading in the right direction, even if the present moment still feels uncertain or in-between.` },
      { q: 'What does the Six of Swords mean for healing after heartbreak?', a: `It describes the post-acute phase of healing, where the sharpest pain has settled and the slow work of moving forward has begun. You are not yet whole, but you are not in the storm anymore. The card supports careful re-engagement with life — small social outings, returning to interests you let lapse, sleeping in your own bed without dread. Avoid the temptation to rush back into the dating world to prove you are over it. The crossing is its own important phase. Honour the in-between rather than skipping it. The next shore will be more sustainable for arriving on it slowly.` },
      { q: 'What does the Six of Swords mean for an existing relationship?', a: `It often shows a couple moving together out of a hard season. You may have been through grief, conflict, a health crisis, or a stretch of practical difficulty, and the intensity is finally beginning to lower. The card describes a quiet, tender phase rather than a dramatic one. Use it to rebuild gently. Small rituals matter more than grand gestures here. Be patient with one another; both of you may still be carrying residue from what you came through. The card promises that calmer waters are ahead and that you are crossing together, which is itself a kind of intimacy.` },
    ],
  },

  'seven-of-swords': {
    loveLong: `The Seven of Swords in love asks an uncomfortable question about honesty. Something is being hidden, withheld, or strategically managed in a way that is not quite straight. The hiding may be small — a half-truth told to avoid conflict, a feeling tucked out of sight, a part of your life kept neatly compartmentalised — or it may be larger, the kind of secret that, once seen, will change everything. The card does not always specify which. It simply names that something is not as transparent as it looks.

This card sometimes describes you. You may be the one quietly avoiding a conversation, omitting a detail that feels safer left unsaid, or planning a private exit from a situation you have not yet been honest about. There are reasons for this — fear of conflict, fear of consequence, genuine uncertainty about what you want — but the strategy of half-truth tends to cost more than it saves. Sooner or later the hidden thing surfaces, and what was withheld weighs more than what was originally feared.

The card sometimes describes someone else. If you have been feeling that the story does not quite add up, that instinct deserves attention. The Seven of Swords is rarely paranoia; it is usually pattern recognition. Without leaping to confrontation, gather your own information quietly. Trust what you observe over what you are told. The growth edge here is the willingness to live in the truth of the situation, whichever side of it you are on. If you are the one hiding, consider what it would take to come clean while it is still on your own terms. If you are the one being managed, consider how much of yourself is going into convincing yourself everything is fine. Honesty is heavier than it looks, but it is the only foundation a love life can hold.`,
    loveFaqs: [
      { q: 'What does the Seven of Swords mean in love?', a: `It points to something hidden, withheld, or strategically managed in a relationship — sometimes by you, sometimes by the other person. The hidden thing may be small or significant; the card does not always specify. What it does say is that the current dynamic is not as transparent as it appears, and that the gap between what is happening and what is being acknowledged is becoming costly. The card asks for honesty, gently or bluntly as the situation requires. Truth handled directly nearly always weighs less, in the end, than the strategy of avoidance.` },
      { q: 'Is the Seven of Swords a warning in love?', a: `Yes. The card warns about deception, evasion, or strategic distance — including the kind you may be practising on yourself. It is not automatically predicting cheating, though it can describe that; more often it is the smaller daily dishonesties that compound. Take the warning seriously without leaping straight to accusation. Notice what is being unsaid. Watch what does not match up. If your instinct has been telling you something is off, the Seven of Swords is usually confirming that instinct rather than feeding paranoia. Pay attention to the gap between words and behaviour.` },
      { q: 'What does the Seven of Swords say about how someone feels about me?', a: `Their feelings may be more guarded or strategic than they are showing. They may be keeping part of themselves out of view — past hurts they have not disclosed, doubts they have not voiced, other connections they have not mentioned — not necessarily because they are malicious, but because vulnerability feels risky to them. This does not always mean dishonesty in the dramatic sense; sometimes it just means they are managing the impression they make on you. Take what you are told as partial information rather than the full picture, and let trust build slowly enough to test what is real.` },
      { q: 'What does the Seven of Swords mean about communication in a relationship?', a: `Communication under this card tends to be incomplete. Things are being implied rather than said, edited rather than shared, or routed through other people instead of direct conversation. The card invites you to name the gap. You do not have to confront, only to bring more of the actual truth into the open — your truth first. Modelling honest, non-strategic speech often invites the other person to follow. If they cannot, that itself is information. Communication in the Seven of Swords improves the moment someone stops playing the careful game and simply tells the truth.` },
    ],
  },

  'eight-of-swords': {
    loveLong: `The Eight of Swords in love is the experience of feeling trapped in a romantic situation that, on closer look, is far less locked than it feels. The figure is bound and blindfolded, but the ropes are loose and the path out is open if she would only test it. That is the heart of this card: a sense of helplessness that is shaped more by belief than by reality. You may feel you cannot leave, cannot speak up, cannot ask for what you need, cannot start over — and the card is asking you to examine, gently but firmly, where that conviction actually comes from.

For some, the Eight of Swords describes staying in a relationship long after it stopped serving them, paralysed by stories about what leaving would mean. For others it is feeling unable to express a need inside a relationship that would probably honour it, if asked. For singles it can describe the belief that no one is out there, that you are too much or too little, that the romantic life of other people simply does not apply to you. The bondage in each case is largely internal.

The growth edge is to notice the story and test it. What specifically do you believe you cannot do? What would happen if you did? Often, when the question is asked plainly, the worst-case scenario shrinks dramatically. The card does not minimise real constraints — there are situations where leaving genuinely is hard, where speaking up has real cost — but it insists that you are probably underestimating your agency. Begin with one small move. Send the message you have been avoiding. Sit with the discomfort of an honest sentence. The blindfold loosens the moment you stop pretending it cannot.`,
    loveFaqs: [
      { q: 'What does the Eight of Swords mean in love?', a: `It marks feeling trapped in a romantic situation that has more give than you currently see. The card describes the experience of helplessness — that you cannot leave, cannot speak, cannot ask, cannot start over — and gently challenges how true that actually is. Most of the binding is internal: stories about what would happen if you acted, fears that have not been tested for years, identities that have outgrown their usefulness. The card does not minimise real constraints, but it asks you to look carefully at which of your limits are imposed and which are quietly chosen. Test the rope.` },
      { q: 'Is the Eight of Swords a bad love card?', a: `It is uncomfortable rather than catastrophic. The Eight of Swords describes a state of mind that is painful and that often outlasts the situation that triggered it, but it does not predict permanent imprisonment. The card is essentially diagnostic: it tells you where the trap is, and it points out that the door is closer than it looks. Once seen, the situation usually starts to shift. Read it as encouragement to act in a small specific way rather than as confirmation that you are stuck. The card rewards the first concrete step, even when that step is tiny.` },
      { q: 'What does the Eight of Swords mean for being single?', a: `It often describes a stuck story about romantic life — that you are unlovable, too late, too much, too little, too tired, too unlike other people. The story feels factual but is usually outdated. The card invites you to test it gently. Make one small move that contradicts the narrative: send a message, accept an invitation, sign up for the thing you keep putting off. You are not required to overhaul your dating life in a weekend. You are asked to notice that the bondage is largely in the telling and that the path out begins the moment you stop reciting the story as if it were destiny.` },
      { q: 'What does the Eight of Swords mean for healing after heartbreak?', a: `It can describe the part of recovery where you feel permanently changed by what happened — as if love itself has become inaccessible to you, as if the door to other relationships is closed. The card sits with this honestly while also pointing out that the closure is not as total as the grief is telling you it is. Healing here looks like loosening one belief at a time. The thought "I will never trust again" softens, gradually, into "I am not ready yet". That small shift is real progress. Be patient with yourself. The ropes are looser than they feel today.` },
    ],
  },

  'nine-of-swords': {
    loveLong: `The Nine of Swords in love is the card of late-night anxiety — the worry that wakes you at three in the morning, the conversation you rehearse over and over without ever having it, the catastrophic story your mind tells about a relationship when the lights are off. The image is direct: someone sitting up in bed, head in hands, the swords above them representing thoughts rather than enemies. The crisis is largely internal. The actual situation may be much smaller than the dread surrounding it.

This card does not say your fears are baseless. Sometimes they accurately reflect something real that needs addressing — a relationship that has lost its safety, a partner whose behaviour is destabilising, a decision you have been avoiding. But more often the Nine of Swords describes anxiety that has outgrown its trigger, where your mind has constructed an elaborate worst case from a thread of information and is now treating the construction as reality. The card invites you to test the story by daylight. What of it would survive direct examination?

The growth edge is twofold. First, get the worry out of your head and into the world: write it down, share it with someone safe, ask the question directly rather than rehearse the catastrophe alone. Most fears shrink dramatically once they leave the echo chamber of late-night thought. Second, take seriously the part of the anxiety that is signal rather than noise. If the worry keeps returning to one specific thing, that thing probably needs to be addressed in waking life. Address it, gently. The Nine of Swords does not ask you to dismiss your fear; it asks you to bring it into the light, where most of it dissolves and the real piece can be handled.`,
    loveFaqs: [
      { q: 'What does the Nine of Swords mean in love?', a: `It points to anxiety, worry, and the late-night spiral around a romantic situation. You may be catastrophising a conversation that has not happened, replaying a small comment until it feels enormous, or lying awake imagining the worst version of where things are heading. The card honours that the suffering is real while quietly noting that the situation is often smaller than the dread. Get the worries out of your head and into the world — write them, speak them, test them. Most of the fear loses its grip in daylight; what survives examination is the real thing to address.` },
      { q: 'Is the Nine of Swords a bad love card?', a: `It is a difficult card emotionally, but it is rarely a verdict on the relationship itself. The Nine of Swords is largely about the state of your mind around a romantic situation rather than the situation as it actually is. That means the suffering can ease significantly even before the external circumstances change. Naming what you are afraid of, sharing it with someone safe, and asking direct questions in daylight all loosen the card's grip quickly. Read it as a call to bring your fears into the open rather than as confirmation that everything is as bad as your mind says it is.` },
      { q: 'What does the Nine of Swords mean about communication in a relationship?', a: `It often describes communication that is happening entirely inside your head rather than between you and your partner. You are rehearsing the conversation, predicting their responses, drafting and discarding messages, and never actually saying the thing. The card invites you to break the loop with a real sentence in real life. The conversation you are dreading is almost always lighter than the version your anxiety has built. Ask the question, share the worry, name what you are scared of. Most of the time the response is more manageable than the rehearsal predicted, and the relief is immediate.` },
      { q: 'What does the Nine of Swords say about how someone feels about me?', a: `It often says more about your fears than about their actual feelings. The Nine of Swords describes a mind that is constructing its worst-case interpretation of partial information, and the construction usually exaggerates. Rather than trying to read their feelings through your anxiety, ask. A direct question delivered without accusation is more reliable than any amount of internal analysis. They may also be feeling some form of worry themselves; this card sometimes describes mutual anxiety that neither person has named. Speaking it aloud, gently, often dissolves a surprising amount of it on both sides.` },
    ],
  },

  'ten-of-swords': {
    loveLong: `The Ten of Swords in love is the rock bottom of an ending. It is not the looming threat of an end; it is the end having arrived, the worst already happened, the wound complete. There is a strange, severe relief in the image — the figure has fallen, the swords are in, there is nothing left to fear because the feared thing has already taken place. Whatever you were bracing for is over. The bracing itself can finally stop.

For many, this card marks a relationship that is undeniably finished. The denial has run out; the door has closed; the story is no longer salvageable on its old terms. Some readers will draw it during a relationship's final breakdown, others after a betrayal that cannot be unsaid or undone. The card does not promise the pain is small. It does, however, promise that you are at the floor rather than still falling, which is itself a kind of mercy.

The growth edge is the surrender that the card insists on. Fighting the ending — strategising returns, replaying conversations to find the loophole, treating the death of the relationship as a problem to solve — only prolongs the suffering. The dawn in the background of many versions of this card is the point. After full ending comes genuine renewal, but only if you stop trying to revive what is gone. Practical guidance: let yourself grieve without performance, take care of the body, lean on chosen people, and resist any urgent decision-making in the immediate aftermath. The path forward will become visible once you have stopped trying to walk backward. The Ten of Swords is severe, but it is also the card that promises this part is over.`,
    loveFaqs: [
      { q: 'What does the Ten of Swords mean in love?', a: `It marks the complete ending of a relationship, dynamic, or chapter — the bottom rather than the fall. The worst has already happened. The fear of losing this version of love is now the fact of having lost it. The card is severe but also strangely merciful: you are no longer bracing, no longer suspended, no longer suspended in the agony of not-knowing. Grief is real here, and the work is to let it move through you honestly rather than push it away. The card promises that after a true ending, genuine renewal becomes possible, but not before.` },
      { q: 'Is the Ten of Swords a warning in love?', a: `It is more an acknowledgement than a warning. By the time the Ten of Swords appears, the situation is usually already past the point where prevention is possible. The card is honest about that. Read it not as a threat of what might happen but as a clean confirmation of what is. The mercy in this card is the end of denial. You do not have to keep trying to save what has already left. Stop bracing and start grieving. The card is severe in its clarity, but it is also the card that ends the worst phase of suspended dread.` },
      { q: 'What does the Ten of Swords mean for ending a relationship?', a: `It often confirms an ending that is already in motion. The relationship is finished, the door has closed, the story cannot continue in its previous form. The card asks for surrender — not as defeat but as the willingness to stop fighting what is already over. Trying to revive the relationship from this place tends to deepen the wound rather than heal it. Allow the ending. Take care of the body. Lean on the people who love you outside the relationship. Resist big decisions for a little while. The renewal the card promises will form on its own once you stop trying to walk backward.` },
      { q: 'What does the Ten of Swords mean for healing after heartbreak?', a: `It describes the deepest part of the descent and, paradoxically, the turning point. You are at the bottom rather than still falling, which means the work of healing can actually begin. The card asks you to be honest about how bad it has been rather than minimise it for the comfort of others. Real grief, allowed fully, moves through faster than grief that is performed away. Take care of basic things — sleep, food, water, gentle movement, trusted people. The dawn is in the background of the card for a reason. After a complete ending, genuine renewal becomes possible, but the renewal cannot be hurried.` },
    ],
  },

  'page-of-swords': {
    loveLong: `The Page of Swords in love is the curious, restless mind in a romantic context. There is intellectual energy here — questions being asked, ideas being tested, conversations that run late because both people are finding the exchange more interesting than they expected. New connections under this card often begin with a striking mental spark. You find yourself sending long messages, picking apart how the other person thinks, comparing notes on the world. The attraction is partly cerebral, and that gives it a particular brightness.

The Page also carries the energy of immaturity, in the gentle developmental sense rather than the insulting one. The mind is keen but the experience is light. You or the other person may be new to relationships, new to expressing yourselves clearly, or simply still in the phase where you are working out who you are romantically. There can be a tendency to talk about feelings rather than feel them, to analyse the connection rather than inhabit it, to test the other person with sharp questions to see how they respond. None of this is fatal; it is part of how this card learns.

The growth edge is to keep the curiosity and add a little more care. Watch for gossip, for clever-but-cutting words, for the urge to win small intellectual victories over someone you actually like. The Page of Swords can hurt without meaning to, simply because it has not yet learned how heavy its own words are. Slow the speech down a little. Choose precision rather than performance. If someone is showing up as this Page, give them honest patience rather than scorn — they are working it out. New ideas about love arriving under this card are worth taking seriously, but worth testing too. Not every clever theory survives contact with a real person.`,
    loveFaqs: [
      { q: 'What does the Page of Swords mean in love?', a: `It marks a curious, mentally alive phase of romantic life. New ideas are arriving, conversations are interesting, and an exchange of minds is happening — sometimes with a new person, sometimes within an existing relationship that is rediscovering how to talk. The card can also signal someone who is young in their romantic development, eager to think and talk about love but still learning what to do with what they feel. The growth edge is to add care to the cleverness. Keep the curiosity, but slow the speech down enough that the sharp words do not nick the people you actually care about.` },
      { q: 'Is the Page of Swords a good love card?', a: `It is a bright and interesting card more than a deeply tender one. The Page of Swords lights up the mental side of connection — the conversations, the shared ideas, the genuine intellectual attraction — and that is genuinely valuable. What it does not yet bring is depth of feeling or emotional maturity. Take it as encouragement for the early or curious stages of a connection, but do not expect it to carry the weight of long-term commitment without growing further. The card is most positive when its energy is balanced by other softer cards in the spread.` },
      { q: 'What does the Page of Swords mean for a new relationship?', a: `Early connections under this card often start with vivid, late-running conversations and a noticeable mental spark. You find each other interesting. The exchange is quick and curious. Watch for two patterns: one is talking about the connection so much that you forget to actually experience it; the other is using sharp humour or pointed questions that land harder than intended. Both are common with this Page. Keep the playfulness, but add gentleness. The new relationship will deepen most readily if you let yourselves be impressed by each other rather than competing to be the cleverer one.` },
      { q: 'What kind of partner does the Page of Swords represent?', a: `Usually a younger or developmentally lighter partner — curious, articulate, often funny, often opinionated, still finding their feet emotionally. They are quick to think but slower to feel. Conversations with them tend to be stimulating and a little wired. They may gossip more than is wise, leap to conclusions, or test you with pointed questions when they actually mean to compliment you. None of this is malicious. With patience and clear communication, the Page grows into a more grounded partner. With criticism, they tend to spiral or pull away. Encourage their best while gently naming the costs of their sharper edges.` },
    ],
  },

  'knight-of-swords': {
    loveLong: `The Knight of Swords in love is the gallop. There is decisive, single-minded romantic energy here — someone moving toward what they want without much pause for nuance. Under this card, things happen fast. Declarations are made. Plans are proposed. The "let's just do this" energy is strong, and if you have been in a slow-moving connection, the speed can feel exhilarating after the long quiet.

The shadow of this card is exactly its strength. The Knight is so focused on the goal that he does not always notice what he is trampling on the way. Subtleties get missed. The other person's pace is overridden. Feelings that need delicacy get bulldozed by certainty. New connections that begin with this Knight often burn very bright and then either crystallise quickly into something real or burn out almost as fast as they started. Inside existing relationships, this card can describe one partner suddenly pushing hard for a decision the other has not had time to consider.

The growth edge is to slow the pace just enough to let the other person travel with you. Decisive energy is genuinely a gift — the Knight gets things done where others get stuck — but love requires checking in. Ask before assuming. Notice when the other person has gone quiet, and treat that quiet as data rather than as an obstacle to ride past. If you are the one receiving this Knight, you do not have to match his pace. Honest information is the best protection: tell him plainly where you are and what speed you can move at. The Knight of Swords respects directness more than he respects polite slowing down. Honesty travels better at this pace than hedging ever will.`,
    loveFaqs: [
      { q: 'What does the Knight of Swords mean in love?', a: `It marks fast, decisive romantic energy — someone moving toward what they want without much patience for slow rituals. Declarations, plans, big moves, and ultimatums all fit this card. The pace can feel exhilarating or destabilising depending on which side of it you are on. The card is not careless on purpose, but it is single-minded, and single-mindedness has a way of overriding nuance. The growth edge is to slow just enough to let the other person move with you. Speed paired with genuine attention becomes powerful; speed alone tends to leave casualties.` },
      { q: 'Is the Knight of Swords a good love card?', a: `It is a high-energy card rather than an automatically positive one. The Knight gets things moving, which is genuinely useful when a connection has been stalled. He cuts through indecision, pushes for clarity, and forces decisions. What he does not bring is patience or emotional subtlety. Whether he is good for the situation depends on whether the situation actually needs his speed. For a frozen conversation, he is a gift; for a delicate negotiation, he is a wrecking ball. Read him as a force you can welcome or steer rather than as a verdict on the relationship.` },
      { q: 'What does the Knight of Swords mean for a new relationship?', a: `Early connections under this card move very quickly. Big conversations happen on the second date. Plans skip ahead. Sometimes this leads to a fast, genuine recognition of fit; sometimes it leads to a crash when the pace outruns the actual foundation. Pay attention to whether the speed is shared or whether one of you is being swept along. Honest communication about pace matters more than usual here. If you need slower, say so directly — this Knight respects clarity far more than polite hedging. If you are the Knight, slow your stride just enough to check whether they are still beside you.` },
      { q: 'What kind of partner does the Knight of Swords represent?', a: `Usually a decisive, intellectually sharp partner who moves fast and speaks plainly. They are often refreshing after a long stretch of indecisive connections — they say what they mean, propose what they want, and follow through. They can also be impatient, prone to ultimatums, and inclined to ride past softness when there is a goal in sight. Conflict with them tends to be direct rather than passive-aggressive, which is a mixed blessing. At their best, they are a fierce ally who will not let things drift. At their worst, they leave bruises by moving faster than the relationship can absorb. Speak plainly back; they hear it.` },
    ],
  },

  'queen-of-swords': {
    loveLong: `The Queen of Swords in love is the partner — or the self — who has chosen clear-headed honesty as a way of life. She has lived enough to know what she will and will not accept. She speaks plainly. She prefers truth, even uncomfortable truth, over reassurance that has not been earned. There is genuine warmth here, though it is not always the soft warmth people expect from a love card. Her affection arrives in clean sentences, fair treatment, and the absence of game-playing.

This card can describe you or someone you are involved with. If she is you, you may notice that you are finally done with the indirect kind of dating — the unanswered texts, the people who cannot say what they mean, the relationships that require translation. You want directness now, and you are willing to risk being seen as too much in exchange for the simplicity of being honest. That trade tends to be worth it. The people who can match you will arrive more steadily once you have stopped performing softness you do not feel.

If the Queen is someone in your life, expect her to tell you the truth even when it is hard. She is not cruel, but she is unguarded with reality. Lean into her clarity rather than punishing her for it. Her gift in a relationship is that you never have to guess where you stand. The growth edge for this Queen, and for anyone embodying her, is to remember that warmth and clarity can coexist — that a true thing said gently is still true, and that softness is not the same as weakness. Hold the sword and the heart together. The combination is rare and steadying, and it is what this Queen, at her fullest, brings to love.`,
    loveFaqs: [
      { q: 'What does the Queen of Swords mean in love?', a: `It marks clear-headed, honest energy in a romantic context. The Queen has done enough living to know what she will and will not tolerate, and she speaks plainly about it. There is warmth here, but the warmth arrives through truth-telling and fair treatment rather than through softness for its own sake. The card can describe you stepping into this clarity yourself, or a partner who carries it. The growth edge is to pair the directness with kindness so that the honesty opens connection rather than closes it. Truth and warmth are allies, not opposites.` },
      { q: 'Is the Queen of Swords a good love card?', a: `Yes, though her gifts are mature rather than sparkly. The Queen of Swords does not promise romance-novel intensity; she promises the steadying experience of being with someone who tells you the truth and expects the same. For people who have been through enough indirect or game-heavy dating, this card is genuinely good news. The clarity becomes its own form of intimacy. Lean into it rather than read it as cold. The warmth here is real — it just arrives in plain language and fair behaviour rather than in performance.` },
      { q: 'What does the Queen of Swords mean for being single?', a: `It often describes a season of being single during which you sharpen what you actually want. You stop apologising for your standards. You become less interested in connections that require translation or constant management. The card supports a more discerning, less anxious approach to dating. You will likely date less but date better. Be willing to be perceived as direct or particular; the people who match this energy will find that quality attractive rather than off-putting. The Queen of Swords single is rarely lonely in the way the dating-app spiral is lonely. Her solitude is steady.` },
      { q: 'What kind of partner does the Queen of Swords represent?', a: `An independent, honest, often funny partner who values truth and fair treatment. They have usually been through something difficult and emerged with sharper discernment for it. They do not play games and do not respond well to people who do. Conversations with them are direct, sometimes startlingly so, and the absence of guessing is a relief once you adjust to it. Their potential edge is being read as cold or guarded; in truth, they reserve their warmth for those who have earned it. With them, you always know where you stand. That clarity is their love language.` },
    ],
  },

  'king-of-swords': {
    loveLong: `The King of Swords in love is the partner — or the self — who leads with the mind. He is rational, fair, and ethically anchored. His decisions in love are considered. His commitments are made with full awareness of what they require. When he is yours, you feel the steadiness of being with someone who has thought things through and who can be trusted to behave consistently with what he has said. That reliability is itself a form of love, even when it does not look romantic on the surface.

This card can describe you stepping into more grounded, principled territory in your romantic life. You may be making decisions about love that you would have ducked a year ago. You may be applying clearer standards, holding more honest conversations, behaving more like the partner you want to be. The King's strength is that the inner life is in order, which makes the outer relationship far steadier than it would be otherwise.

The shadow of this King, and the growth edge, is emotional distance. The mind that rules so well in difficult decisions can also keep feelings at arm's length, treat intimacy as a problem to be analysed, or solve when the moment calls for being present. If you are with this King, you may need to ask gently for what he is not offering on his own — emotional disclosure, softness, the willingness to sit in feeling rather than fix it. If you are this King, the practice is to let yourself be moved as well as wise. Reason is a gift to a relationship. Reason without warmth is colder than it needs to be. Bring the heart back into the chamber where the mind is already in charge. The combination is what this King, at his best, was always meant to embody.`,
    loveFaqs: [
      { q: 'What does the King of Swords mean in love?', a: `It marks a rational, principled approach to relationship — yours, or a partner's. The King thinks clearly, behaves consistently, and treats love as something serious enough to deserve careful judgement. There is real steadiness here. The card honours the part of love that is built from fair decisions, kept promises, and honest conversations rather than from intensity alone. Its growth edge is emotional warmth. The mind that governs so well can hold feelings at a distance; the work is to let yourself be moved as well as wise. Bring the heart into the room where the mind already presides.` },
      { q: 'Is the King of Swords a good love card?', a: `Yes, though his gifts are mature and steady rather than fiery. The King of Swords does not promise sweeping romance; he promises the slow, dependable kind of partnership where you can trust the other person's word and behaviour. For people who have been through chaotic relationships, this card is genuinely good news. The watch-out is emotional distance — the King can over-think feelings and treat tenderness as inefficient. Read him as supportive of long-term partnership especially when paired with warmer cards. On his own, lean into him while also asking for the softness he may forget to offer.` },
      { q: 'What does the King of Swords mean for an existing relationship?', a: `It often describes a relationship moving into a more mature, principled phase. Hard conversations get had cleanly. Promises are kept rather than performed. Decisions about shared life — money, time, family, future — are made with care and follow-through. The card supports this with one caveat: do not let the management of the relationship replace the experience of it. Keep room for tenderness, play, and unguarded affection alongside the well-run logistics. The King at his best holds both the spreadsheet and the heart. Without that balance, the relationship becomes steady but quietly hungry for warmth.` },
      { q: 'What kind of partner does the King of Swords represent?', a: `An intelligent, fair, often professionally accomplished partner who is reliable to their bones. They say what they will do and they do it. Their judgement is sound; their loyalty, once given, is durable. The trade-off is that emotional expression does not come as easily to them as rational discussion. They may default to problem-solving when you need empathy, or analyse a feeling rather than simply share it. None of this is malicious — it is how they are wired. Tell them clearly when you need emotional presence rather than counsel, and most of these Kings will rise to meet that need with genuine care.` },
    ],
  },
}
