import type { LoveContext } from '../card-love-extended'

export const WANDS: Record<string, LoveContext> = {
  'ace-of-wands': {
    loveLong: `The Ace of Wands in love is the moment the match strikes. Something quickens — a glance held a second longer than necessary, a name on your phone that lights a small fire in your chest, a fresh chapter of attraction that announces itself without warning. The card is pure ignition: not yet a relationship, not yet a story, simply the undeniable evidence that desire is alive in you again. After dry spells, this Ace feels almost shocking. After comfortable years, it can show up as renewed heat with the partner you already share a life with.

For singles, the Ace of Wands often heralds someone who genuinely sparks you — chemistry that registers in the body before the mind has time to vet it. For couples, it points to a chapter where intimacy stops being routine and remembers it is a creative act. The dynamic this card favours is honest appetite: people who can say out loud what they want, who flirt because they enjoy each other, who do not negotiate their desire down to a safer size.

The growth edge is courage. Sparks ask to be acted on quickly while they are still warm. Send the message. Light the candle. Initiate the conversation you have been circling. Aces have a short fuse — they reward the bold and dissolve in the hands of the over-cautious. Practical guidance: do not over-plan the next step. Take the smallest live action your nerve will allow today, and trust the fire to widen from there. The Ace of Wands does not promise a final outcome. It promises that the door has just opened, and standing politely outside it is not the response this card came to reward.`,
    loveFaqs: [
      { q: 'What does the Ace of Wands mean in love?', a: `The Ace of Wands in love is a fresh spark — the start of attraction, renewed passion in an existing bond, or a romantic impulse that suddenly feels alive again after a flat stretch. It is not yet a relationship; it is the kindling that could become one. The card favours bold, embodied desire and asks you to honour it with quick, honest action rather than over-analysis. Aces have short fuses. They reward people who answer the message, accept the date, or initiate the kiss while the heat is still in the room.` },
      { q: 'Is the Ace of Wands a passionate card?', a: `Yes — the Ace of Wands is one of the most passionate cards in the deck. It is the suit of fire at its purest beginning: chemistry, physical magnetism, creative excitement and the sheer will to pursue. In a love reading it almost always points to genuine attraction, not just intellectual interest. The card describes desire you can feel in the body — quickened pulse, restless energy, the wish to be near someone specific. Whether the spark matures into a lasting bond depends on later cards, but the initial heat the Ace promises is unmistakably real.` },
      { q: 'What does the Ace of Wands mean for a new relationship?', a: `For a new relationship, the Ace of Wands describes a beginning with genuine fire underneath it. Chemistry is present, curiosity is mutual, and there is a sense of momentum carrying the early days. This is the card of the first kiss, the first weekend lost in conversation, the first time you notice you cannot stop smiling at your phone. The honest guidance is to let the early intensity be itself without trying to lock it down too quickly. Aces flourish when given room to breathe. Show up, stay playful and let the spark prove itself with time.` },
      { q: 'Does the Ace of Wands mean physical attraction?', a: `Strongly, yes. The Ace of Wands is one of the clearest indicators of physical attraction in tarot. The card belongs to the suit of fire, which governs the body, desire and animal magnetism. When it appears in a love reading, it often signals chemistry you can feel before you can explain — the kind of pull that makes small touches feel charged and ordinary conversations feel electric. Emotional intimacy and shared values will be needed to sustain anything long-term, but the question of whether the attraction is real receives a confident yes from this card.` },
    ],
  },

  'two-of-wands': {
    loveLong: `The Two of Wands in love is the balcony moment — you are standing with the future in your hand, looking out over what could be, weighing where to point the next chapter of your romantic life. The card carries a quieter heat than the Ace; the spark has been struck and now becomes a deliberate decision. Will you commit to this person? Move cities for them? Define the relationship out loud? Or, if you are single, what kind of love are you genuinely building toward rather than passively waiting to receive?

For couples, this card often shows a juncture where casual must become intentional. You have enjoyed each other; now you are being invited to plan together. For singles, it points to a partner you can co-author a future with — someone whose horizon overlaps with yours rather than competes with it. The dynamic favoured here is collaborative ambition. Two of Wands love is not about losing yourself in another; it is about discovering that two visions can be braided into a stronger one.

The growth edge is courage of choice. Two of Wands punishes hedging. Keeping one foot out of the door, running quiet shortlists, refusing to declare yourself — these strategies feel safe but they slowly empty the relationship of fire. Practical guidance: pick the future that asks more of you. Have the conversation about where this is heading. Make the plan that requires you to mean it. The card is generous to people who plant a flag, even an imperfect one. It loses interest in people who treat their own life like a hypothetical.`,
    loveFaqs: [
      { q: 'What does the Two of Wands mean in love?', a: `The Two of Wands in love is the planning card. The early spark has settled into something you can now make decisions about — defining the relationship, planning a shared future, deciding whether to commit fully or keep things casual. The card asks you to look beyond your familiar horizon and choose the version of love that genuinely stretches you. It rewards bold, honest choices and gently punishes prolonged hedging. Where the Ace of Wands lights the match, the Two of Wands invites you to decide where to carry the flame.` },
      { q: 'Is the Two of Wands a soulmate card?', a: `The Two of Wands can carry soulmate energy, but in a very specific flavour: the partner you build a life with on purpose rather than fall into by accident. It points to compatible ambition — two people whose visions for the future overlap enough to plan together. This is not the dreamy, fated soulmate of the Lovers card; it is the more grounded recognition that you and this person could genuinely co-author a chapter. If you are asking whether someone is a long-term partner you can build with, the Two of Wands is a strong yes.` },
      { q: 'What does the Two of Wands mean for a new relationship?', a: `For a new relationship, the Two of Wands signals a moment of choosing how serious to let it become. The chemistry has been established; now you are weighing trajectory. Should you introduce them to friends, plan the trip, define what you are? The card encourages you to choose deliberately rather than drift. Talk about what you each want. Notice whether your horizons align. New relationships under this card tend to move from casual to intentional when both people are willing to name what they are building. Avoid prolonged ambiguity — it costs more here than it saves.` },
      { q: 'What does the Two of Wands mean for being single?', a: `If you are single, the Two of Wands invites you to design the love life you actually want rather than wait for it to happen to you. Get clear on what kind of partner you are building toward — values, lifestyle, ambition, geography. The card favours expansive thinking: do not narrow your search to who is currently nearby if your real horizon is wider. It also rewards small, declarative actions: joining the community, taking the trip, having the conversation that places you closer to the life your future partner is already living. Plan the future, then walk toward it.` },
    ],
  },

  'three-of-wands': {
    loveLong: `The Three of Wands in love is the card of waiting at the shoreline with ships on the horizon. You have done the inner work, set things in motion, and now the returns are arriving. Perhaps a long-distance connection is moving closer. Perhaps someone you took a chance on is finally proving themselves. Perhaps you yourself are returning to dating after a deliberate pause, broader and clearer than the last time you tried. The card carries patient confidence — foresight that has not soured into impatience.

For couples, the Three of Wands often points to a relationship entering its expansion phase: travel, relocation, a shared business, a baby on the horizon, an investment in a life larger than either of you would have built alone. The dynamic favoured here is one of mutual exploration. You and your partner are not just enjoying each other; you are pointing the same direction together and waiting for the next part of the journey to dock. For singles, it can mean a connection that began far away — different city, different chapter — is now drawing close enough to matter.

The growth edge is staying at the shore. Three of Wands rewards the people who keep watching for the ships even when impatience tempts them to wander off. Romance under this card asks for follow-through: send the second message, plan the visit, keep showing up to the things future-you will be glad you attended. Practical guidance: trust your long view but back it up with steady, embodied action this week. The opportunities you set in motion months ago are arriving now. Be near the water when they do.`,
    loveFaqs: [
      { q: 'What does the Three of Wands mean in love?', a: `The Three of Wands in love is the card of expansion and patient anticipation. Things you set in motion are coming back to you — a long-distance connection drawing closer, a relationship moving into a bigger chapter, or the romantic returns of inner work you did months ago. The card favours people with foresight: those who can see where love is heading and stay steady while it arrives. It rewards travel, exploration and the willingness to widen your romantic horizons. Stay at the shore, keep watching, and back your vision with consistent small actions.` },
      { q: 'What does the Three of Wands mean for long-distance love?', a: `The Three of Wands is one of the most encouraging cards for long-distance relationships. It belongs to ships, horizons, foresight and ventures that span distance, and it points to a connection that is genuinely worth the wait. The card often signals that the gap is closing — visits, plans, a future move — or that the patient investment you have made in someone far away is beginning to pay off. Communication and shared vision matter under this card. If you and your partner are still pointing the same direction, the distance is a chapter rather than a verdict.` },
      { q: 'Is the Three of Wands a good love card?', a: `Yes, the Three of Wands is a favourable card in love readings, especially for people with patience and a clear sense of where they are heading. It promises returns on earlier romantic investment, expansion of the relationship into a bigger chapter, and the arrival of opportunities you have been quietly preparing for. The card asks you to trust the long view rather than chase short-term reassurance. It is not a card of instant fireworks; it is the slower satisfaction of watching a chosen direction begin to bear fruit. Stay the course.` },
      { q: 'What does the Three of Wands mean for dating?', a: `For dating, the Three of Wands encourages you to broaden your horizon. Do not limit your search to who is immediately nearby if your real life is pointing somewhere wider. The card favours people who travel, who use apps with intention rather than habit, who follow curiosity into unfamiliar rooms. It also rewards follow-through: the second date, the visit, the message that keeps a slow-burn connection warm. Romantic returns under this card arrive on a slightly longer timeline than the Ace promises, but they tend to arrive more substantially. Stay patient and stay visible.` },
    ],
  },

  'four-of-wands': {
    loveLong: `The Four of Wands in love is the celebration card — the wedding arch, the housewarming, the milestone where private love becomes publicly shared. The card carries warm, settled fire: the kind of relationship strong enough to invite a crowd into. Engagements, weddings, anniversaries, moving in together, meeting the family, choosing to build a home — any threshold where two people declare themselves to their wider world lives under this card. There is genuine joy here, not performance, and the celebration is earned.

For couples, this is one of the most affirming cards in the deck. It points to a relationship that has matured into something stable and visible, where the early spark of the Ace has become a steady hearth. The dynamic favoured here is one of shared belonging — a partner who feels like home, a household that genuinely functions, families on both sides who can hold the union with goodwill. For singles, the Four of Wands often signals a chapter of being welcomed back into your own life, sometimes through a community or a homecoming that becomes the unexpected setting for a meaningful meeting.

The growth edge is letting yourself be celebrated. Many people can build a beautiful relationship and still flinch when it is time to mark it publicly. The Four of Wands invites you to soften that reflex — to host the gathering, post the photo, accept the toast, wear the ring. Practical guidance: schedule the celebration on the calendar. Honour the milestone you have already reached rather than minimising it while you eye the next one. Love this card describes does not need to be performed; it does, however, deserve to be witnessed.`,
    loveFaqs: [
      { q: 'What does the Four of Wands mean in love?', a: `The Four of Wands in love is the card of celebration, milestone and shared belonging. It points to engagements, weddings, moving in together, anniversaries and the kind of stable, joyful chapter where private love becomes publicly recognised. The card carries warm, settled fire: a relationship that has matured beyond the early spark into genuine partnership. It also describes home — the household two people build together, the community that surrounds them, the family on both sides. Few cards in the deck are more affirming for committed love.` },
      { q: 'What does the Four of Wands mean for marriage?', a: `The Four of Wands is one of the strongest marriage cards in the deck. It is literally the wedding-arch card, depicting four staves wreathed in flowers under which a celebration takes place. In a reading about marriage, it points to engagement, the wedding itself, or the milestone of a deeply settled long-term commitment. It also affirms that the relationship has the kind of stable foundation worth marking publicly. If you are asking whether marriage is on the horizon, the Four of Wands is one of the clearest yes answers tarot offers.` },
      { q: 'Is the Four of Wands a soulmate card?', a: `The Four of Wands can carry soulmate energy in its most domestic, settled form. It is less about cosmic fated connection and more about the partner who genuinely feels like home — the person you build a household with, host gatherings beside, welcome family through. If you believe in soulmates as the people you grow alongside over decades rather than meet in a single thunderclap, this card is one of the strongest indicators. It points to belonging that is mutual, witnessed and built rather than merely felt.` },
      { q: 'What does the Four of Wands mean for an existing relationship?', a: `For an existing relationship, the Four of Wands signals a milestone moment — engagement, moving in, anniversary, the introduction to family, the choice to make the partnership more visible to the outside world. It also describes a chapter of genuine domestic harmony, where the relationship has settled into a stable, joyful rhythm. The card encourages you to celebrate what you have built rather than rush past it. Honour the milestone. Host the gathering. Mark the threshold. Love that is not witnessed sometimes forgets how solid it has become.` },
    ],
  },

  'five-of-wands': {
    loveLong: `The Five of Wands in love is the friction card — small fights, mismatched timing, competing wants, the bickering that erupts when two people who genuinely care still cannot agree on which film to watch. The card carries hot, restless fire, not the steady heat of intimacy. It is rarely catastrophic; more often it describes the squabbling phase of a relationship where everyone is jostling for position and nobody has yet remembered they are on the same team. For singles, it can show the chaos of dating multiple people, the jostle of a love triangle, or the romantic equivalent of being in a too-crowded room.

For couples, this card often points to disagreements over direction — money, family, division of labour, how often you see each other's people. None of these are unsolvable; all of them feel disproportionately heated while you are inside them. The dynamic favoured here is one of fair fighting. The Five of Wands does not ask you to suppress disagreement; it asks you to disagree better, with rules of engagement that keep the relationship intact while the argument runs its course. Avoidance is not the remedy. Skilful conflict is.

The growth edge is recognising which battles are worth lighting. Five of Wands energy tempts you to take every disagreement personally and to escalate small frictions into territorial wars. Practical guidance: name the actual issue underneath the surface squabble. Often it is one larger unsaid thing — feeling unappreciated, scared, unseen — wearing the costume of a minor grievance. Defuse that, and the petty fights stop multiplying. Love this card describes is not doomed; it is just learning to share a room. Most couples worth keeping have a Five of Wands chapter somewhere.`,
    loveFaqs: [
      { q: 'What does the Five of Wands mean in love?', a: `The Five of Wands in love is the card of friction and minor conflict — bickering, mismatched timing, competing wants, the small fights that erupt when two people care but cannot quite coordinate. It is rarely catastrophic; more often it describes a noisy phase rather than a doomed one. For couples it can point to disagreements about direction, money or family. For singles it can show the jostle of dating multiple people or a chaotic dating-app season. The remedy is not avoidance; it is learning to disagree more skilfully.` },
      { q: 'Is the Five of Wands a bad love card?', a: `Not bad, but uncomfortable. The Five of Wands describes friction, not failure, and most healthy relationships pass through chapters that look exactly like this card. The danger is not the conflict itself but how it is handled: contempt, escalation and stonewalling are corrosive, while honest, fair disagreement can actually deepen a bond. Treat the card as a diagnostic. Identify the larger unsaid thing underneath the petty squabbles and address it directly. Many Five of Wands chapters resolve into stronger partnerships once the actual issue is named.` },
      { q: 'What does the Five of Wands mean for an existing relationship?', a: `For an existing relationship, the Five of Wands describes a chapter of frequent low-grade conflict. You and your partner are snapping at each other, disagreeing about small things that feel suspiciously large, or jostling over decisions that should be straightforward. The card asks you to look beneath the surface — usually one bigger unspoken issue is wearing the costume of many smaller ones. Have the harder, calmer conversation. Set rules of fair fighting if you need to. The relationship is not necessarily in trouble, but the way you handle this chapter will decide what comes next.` },
      { q: 'What does the Five of Wands mean for dating?', a: `For dating, the Five of Wands often describes a crowded, competitive or chaotic chapter. You may be juggling several connections, navigating mixed signals, or dealing with the friction of a romantic landscape that feels noisier than it is rewarding. The card asks you to bring more focus and less reactivity to the field. Decide who is genuinely worth your attention and let the rest fall away. Healthy dating involves some friction — disagreement is not automatically a red flag — but constant low-grade conflict is a sign that the match itself, or your approach to the field, needs recalibrating.` },
    ],
  },

  'six-of-wands': {
    loveLong: `The Six of Wands in love is the recognition card — the moment when your effort, your patience, or your willingness to risk being seen finally pays off in a visible way. Someone says yes. A relationship goes public. A partner introduces you with pride. The shy hope you carried privately turns out to be returned. There is a parade quality to this card: love that does not need to hide, attraction that is acknowledged, the small triumph of being chosen out loud.

For couples, the Six of Wands often points to a chapter of mutual pride — going through a difficult passage together and emerging visibly stronger, celebrating a milestone the wider world can witness, feeling genuinely admired by your partner. The dynamic favoured here is reciprocal honouring. You see them well; they see you well; both of you are willing to show that publicly. For singles, this card can describe attention from someone you respect, an admirer who is not afraid to make their interest plain, or a confident return to dating after a chapter of self-doubt.

The growth edge is letting yourself be celebrated without immediately deflecting. Many people can do the unseen work of becoming worthy of love and then flinch when love actually arrives with applause. Practical guidance: receive the compliment, accept the introduction, post the photo if you want to, say yes to the public version of the connection. The Six of Wands rewards confidence that is earned rather than performed. Love under this card asks you to occupy your own life with a little more height. The fire here is warm, visible and shared.`,
    loveFaqs: [
      { q: 'What does the Six of Wands mean in love?', a: `The Six of Wands in love is the card of recognition and visible reward. Someone says yes, a relationship goes public, a partner introduces you with pride, or your patient effort in love is finally honoured out loud. It carries triumphant fire: confidence, mutual respect and the small but meaningful parade of being chosen. For couples it often signals a chapter of shared pride. For singles it can describe attention from someone you respect, or a confident return to dating after self-doubt. Receive the recognition without deflecting.` },
      { q: 'Is the Six of Wands a yes for love?', a: `Yes — the Six of Wands is one of the clearer yes cards in a love reading. It points to public recognition, mutual pride and the visible reward of romantic effort. If you are asking whether someone reciprocates, whether a relationship will be acknowledged, or whether the partnership will reach a milestone worth celebrating, this card answers in your favour. The only caveat is that the yes asks something of you in return: you must be willing to receive the recognition, occupy your own life confidently, and let love be seen rather than hidden.` },
      { q: 'What does the Six of Wands say about how someone feels about me?', a: `If you are asking about another person's feelings, the Six of Wands suggests they hold you in genuine high regard. There is admiration here, possibly pride at being associated with you, and a willingness to acknowledge the connection publicly rather than keep it private. Their feelings are not shy. The card describes someone who respects you and is not embarrassed to let it show. If they have been hesitant, the Six of Wands often signals a turning point where they are ready to make their interest visible, sometimes more publicly than you expected.` },
      { q: 'What does the Six of Wands mean for an existing relationship?', a: `For an existing relationship, the Six of Wands signals a chapter of shared triumph — emerging stronger from a difficult passage, celebrating a milestone the wider world can see, or simply enjoying mutual pride in the life you have built together. The card encourages public recognition: introduce your partner with warmth, post the photo, accept the toast. It also rewards reciprocity. Make sure the admiration flows both ways. The relationship under this card is not just functional; it is something you and your partner can both feel quietly proud of, and that pride deserves to be expressed.` },
    ],
  },

  'seven-of-wands': {
    loveLong: `The Seven of Wands in love is the defending-your-ground card. You are protecting something — your standards, your boundaries, your version of the relationship, your right to choose this particular partner against louder opinions. The card carries embattled but determined fire. There is a sense of being slightly outnumbered and yet still holding firm. This can show up as defending the relationship against disapproving family, defending your boundaries against a partner who pushes them, or defending yourself against your own self-doubt in a romantic landscape that keeps testing your resolve.

For couples, this card often points to a chapter where the relationship is under external pressure — in-laws, exes, judgemental friends, social media commentary — and the two of you are deciding whether to stand together or let the noise divide you. The dynamic favoured here is solidarity under fire. For singles, it can describe holding your standards against the temptation of settling, defending your dating boundaries from people who want you to lower them, or staying with your own values when the field would prefer you to compromise.

The growth edge is choosing your battles wisely. Seven of Wands energy can tip into chronic defensiveness — fighting every challenge as if it were existential, treating every difference of opinion as an attack. Practical guidance: know what you are actually defending and why. The card rewards conviction backed by clarity, not stubbornness for its own sake. Love this card describes is not paranoid; it is principled. If something genuinely matters to you in the relationship, hold the line with calm confidence. If something does not, let it go and save your fire for what does.`,
    loveFaqs: [
      { q: 'What does the Seven of Wands mean in love?', a: `The Seven of Wands in love is the card of defending your ground — your standards, your boundaries, your right to be with the partner you have chosen against louder external opinions. It carries embattled but determined fire. For couples it can describe weathering disapproval from family, friends or social pressure together. For singles it often points to holding your standards against the temptation to settle. The card rewards principled conviction backed by clarity, not chronic defensiveness. Know what you are defending and why, and hold the line with calm confidence.` },
      { q: 'Is the Seven of Wands a good love card?', a: `It is a difficult but ultimately strengthening card. The Seven of Wands describes pressure and the need to defend something, which is rarely comfortable in a love context. But it is not a failure card. It points to a relationship or standard worth holding, and to the maturity required to protect it. Couples who navigate this chapter together often emerge with a stronger sense of solidarity. Singles who stay true to their values rather than compromise under social pressure usually find a better match for it. The card honours conviction.` },
      { q: 'What does the Seven of Wands mean for an existing relationship?', a: `For an existing relationship, the Seven of Wands describes a chapter where you and your partner must defend the relationship against external pressure or internal friction. This could be disapproving family, complicated exes, judgemental friends, or stress from work and life that keeps testing your bond. The card asks the two of you to stand together rather than let the noise create distance. It also rewards healthy boundaries — defending the relationship from forces that drain it. Couples who hold the line as a team during a Seven of Wands chapter often come out closer than they went in.` },
      { q: 'What does the Seven of Wands mean for being single?', a: `If you are single, the Seven of Wands urges you to hold your standards in a romantic landscape that keeps testing them. Friends may pressure you to lower the bar, dating apps may erode your patience, family may ask why you are still alone. The card affirms your right to be selective. It also rewards you for defending the version of love you actually want rather than the convenient version others want for you. Just make sure your standards are about substance, not perfectionism. Hold the line where it matters; release the rules that have become merely defensive.` },
    ],
  },

  'eight-of-wands': {
    loveLong: `The Eight of Wands in love is the card of fast, aligned movement. Things accelerate. Messages fly back and forth. Plans come together quickly. A connection that has been simmering suddenly takes off — flights booked, dates confirmed, declarations made. There is a sense of momentum that feels almost inevitable, as if the universe has cleared the runway and several pieces are landing at once. The card carries swift, clean fire: not chaotic heat, but coordinated movement in the same direction.

For couples, the Eight of Wands often points to a phase of rapid progress — moving in, getting engaged, planning travel, deciding to have a child, or simply a chapter of effortless communication after a stretch of friction. The dynamic favoured here is speed paired with mutual willingness. Both people are saying yes at the same time. For singles, this card frequently signals a flurry of romantic activity: a message that lands, a date that turns into many, a long-distance connection that suddenly becomes geographically possible. The Knight of Wands energy is close by here, but more focused, more arrival-shaped.

The growth edge is keeping pace without losing yourself. When everything is moving fast, it can be tempting to skip the conversations that matter or to assume that speed equals certainty. Practical guidance: ride the momentum but check in honestly along the way. Reply to the messages. Make the plans. Accept the date. But also pause occasionally to ask whether the direction still genuinely fits you, not just whether you can keep up. Love this card describes rewards alignment far more than acceleration alone. When both speed and direction are right, this is one of the most exhilarating cards in a love reading.`,
    loveFaqs: [
      { q: 'What does the Eight of Wands mean in love?', a: `The Eight of Wands in love is the card of swift, aligned movement. Messages fly back and forth, plans come together quickly, and a connection that was simmering suddenly takes off. It often signals a flurry of romantic activity — flights booked, declarations made, decisions accelerated. The card favours mutual willingness and clear communication. For couples it can point to rapid progress: moving in, getting engaged, planning travel. For singles it often heralds a date, message or meeting that arrives faster than you expected. Ride the momentum and check in honestly along the way.` },
      { q: 'Does the Eight of Wands mean a message is coming?', a: `Yes — the Eight of Wands is one of the strongest message cards in tarot, especially in love readings. It often describes texts, calls, emails or DMs arriving quickly, sometimes after a stretch of silence. If you are asking whether someone will reach out, the card answers strongly in the affirmative and suggests it will happen sooner rather than later. The message tends to be honest and forward-moving rather than vague or hesitant. Have your response ready. Eight of Wands communication usually expects momentum, not delay.` },
      { q: 'What does the Eight of Wands mean for a new relationship?', a: `For a new relationship, the Eight of Wands describes a chapter of accelerated development. The early days are moving fast: frequent contact, plans being made, both people saying yes in roughly the same rhythm. The card favours alignment over hesitation. It is a strong sign that the connection is mutual and that the timing is genuinely right. The honest caveat is to maintain the conversations that matter even when everything feels exhilarating. Speed paired with substance is the magic of this card. Speed without substance becomes burnout. Keep checking that the direction still fits, not just the pace.` },
      { q: 'Is the Eight of Wands a good love card?', a: `Yes — the Eight of Wands is generally one of the most favourable love cards. It points to momentum, clear communication, aligned timing and the rapid forward movement of a connection that wants to develop. For people stuck in romantic limbo, this card almost always signals relief: silence breaks, messages arrive, plans materialise. The only thing it asks of you in return is willingness to match the pace. Hesitation under this card costs you the window. When the Eight of Wands shows up, respond quickly, decide bravely and let the connection move.` },
    ],
  },

  'nine-of-wands': {
    loveLong: `The Nine of Wands in love is the card of weary perseverance. You have been through a lot in love — heartbreak, near-misses, relationships that drained more than they returned — and you are still standing, but you are guarded. The card depicts a figure leaning on one staff while watching for the next challenge, bandaged but unbowed. In romance, this often shows up as someone who genuinely wants connection but is exhausted by the work of pursuing it, or as a partnered person who is tired from a long stretch of difficulty and bracing for whatever comes next.

For couples, this card frequently appears in chapters where the relationship has weathered real challenges and both partners are running on fumes. The dynamic favoured here is mutual recognition of effort: acknowledging that you have both been through it, that you have not given up, and that the persistence has counted for something even when it has been invisible. For singles, the Nine of Wands often points to dating fatigue — apps deleted, hopes managed downward, a tired but principled refusal to settle. The wariness is earned. So is the strength underneath it.

The growth edge is distinguishing useful guardedness from chronic defensiveness. Wariness has kept you safe; left unexamined, it now keeps you alone. Practical guidance: name the specific scars that are doing the watching. Most are doing important work; some have outstayed their welcome. Lower one well-chosen guard this season and see what becomes possible. The Nine of Wands rewards people who can be both protected and open — who have learned from past hurt without letting it become the only voice in the room. You are closer than you feel. The card knows.`,
    loveFaqs: [
      { q: 'What does the Nine of Wands mean in love?', a: `The Nine of Wands in love describes weary perseverance. You have been through a lot — heartbreak, near-misses, exhausting relationships — and you are still standing but guarded. The card honours your resilience and the strength you have built through difficult chapters. It also gently questions whether some of your defences are still earning their keep. For couples it can describe surviving a hard stretch together. For singles it often points to dating fatigue and the principled refusal to settle. Lower one well-chosen guard and see what becomes possible.` },
      { q: 'Is the Nine of Wands a good sign for love?', a: `It is a mixed but ultimately hopeful sign. The Nine of Wands acknowledges genuine difficulty: you have been hurt, you are tired, and your defences are up for reasons that have earned their place. But the card also affirms that you are still in the game, still capable of love, and closer to resolution than you feel. It is rarely a hopeless card. More often it marks the chapter just before things ease — the last stretch of vigilance before the connection arrives or the relationship steadies. Hold on; rest where you can.` },
      { q: 'What does the Nine of Wands mean for an existing relationship?', a: `For an existing relationship, the Nine of Wands describes a chapter of survival fatigue. You and your partner have weathered real challenges — illness, distance, family stress, a hard year — and you are tired but still together. The card asks you to acknowledge what you have come through and to recognise each other's effort honestly. Resentment can build under this card if either partner feels unseen. Speak the gratitude out loud. Take the rest you need. Lower one or two of the defences you both built during the hard chapter. The worst is usually behind you under this card, not ahead.` },
      { q: 'What does the Nine of Wands mean for being single?', a: `If you are single, the Nine of Wands describes dating fatigue and the wary, principled refusal to settle. You have tried apps, swiped through people, perhaps invested in connections that did not return what you gave. You are tired but not defeated. The card honours your standards and your strength. It also encourages you to soften one specific guard this season — not all of them, just one — and to let yourself be more visible than fear would otherwise allow. Real love often arrives at the end of a Nine of Wands chapter, when the worst of the bracing is finally behind you.` },
    ],
  },

  'ten-of-wands': {
    loveLong: `The Ten of Wands in love is the burden card. The relationship has become heavy. You are carrying responsibilities that should be shared, or you are over-functioning to keep everything afloat, or the partnership has accumulated so much practical weight — bills, logistics, family obligations, household labour — that the romance underneath has been quietly buried. The card carries strained fire: still burning, but doing too much work for its size. It is rarely a dramatic card. It is the slow exhaustion of love that has forgotten how to be light.

For couples, the Ten of Wands often points to an imbalance in domestic load. One partner is carrying significantly more — emotional labour, planning, parenting, household management — and the other is either oblivious or quietly enabling the imbalance. The dynamic favoured here is honest renegotiation. The card asks you to put down what is not yours, ask for help with what is too much for one person, and let the relationship contribute to your life rather than just consume it. For singles, this card can describe being burdened by past relationships or by the unpaid emotional labour you do for others in your life that leaves you nothing for romance.

The growth edge is permission to put bundles down. Many Ten of Wands people pride themselves on carrying everything; the pride itself becomes part of the trap. Practical guidance: list what you are carrying. Identify what is genuinely yours, what should be shared, and what was never yours to begin with. Have the conversation that redistributes the load. Love this card describes is not doomed, but it cannot be saved by adding more weight. The fire under all that wood is still alive. Clear some of the wood and you will see it again.`,
    loveFaqs: [
      { q: 'What does the Ten of Wands mean in love?', a: `The Ten of Wands in love describes burden — a relationship weighed down by responsibilities, imbalanced labour or the slow accumulation of practical weight that has buried the romance underneath. The card asks you to put down what is not yours, ask for help with what is too much for one person, and renegotiate the load honestly. For couples it often points to one partner over-functioning while the other coasts. For singles it can describe being so depleted by other obligations that romance feels impossible. Lighten the load and the fire returns.` },
      { q: 'Is the Ten of Wands a bad love card?', a: `It is a difficult card but not a fatal one. The Ten of Wands describes a relationship that has become heavy with practical and emotional labour, not one that is necessarily wrong. The fire underneath is often still alive; it is simply buried under too much wood. The card asks for honest renegotiation rather than departure. Many Ten of Wands chapters lift dramatically once the imbalance is named and addressed. The danger is staying silent and letting resentment compound. Speak up, redistribute the load, and the relationship usually breathes again.` },
      { q: 'What does the Ten of Wands mean for an existing relationship?', a: `For an existing relationship, the Ten of Wands describes a chapter of strain. One or both of you are carrying more than is sustainable — domestic labour, childcare, financial pressure, caregiving for ageing parents, the endless logistics of modern adult life. Romance has slipped down the priority list because there is no oxygen left for it. The card asks you to renegotiate honestly. Name the imbalance. Ask for the help you need. Put down what was never yours. The relationship is not doomed; it is simply exhausted. Lighten the load and most of what you miss will return.` },
      { q: 'What does the Ten of Wands mean for being single?', a: `If you are single, the Ten of Wands often describes being so weighed down by other responsibilities that romance feels impossible to fit in. Work, family obligations, caregiving, financial pressure — your time and energy are spoken for, and the idea of dating feels like one more burden rather than a pleasure. The card asks you to examine what you are carrying that is not genuinely yours, and to lighten the load before adding anything new. Love will not flourish on top of an already buried life. Put some bundles down first; then look up.` },
    ],
  },

  'page-of-wands': {
    loveLong: `The Page of Wands in love is the card of fresh enthusiasm and exploratory desire. Something has caught your attention — a new person, a new chapter of attraction, a sudden curiosity about a kind of love you have not yet tried. The Page carries kindled fire, not yet a full blaze: the beginner's spirit of being genuinely excited to discover what this could become. There is innocence here, in the best sense: the willingness to be a learner in love rather than performing a role you have outgrown.

For singles, this card often points to a playful, curious chapter of dating — someone younger or younger-in-spirit may appear, or you may find yourself approaching the field with the unguarded enthusiasm you had not felt in years. For couples, the Page of Wands can signal a return to playfulness — date nights that are actually fun, flirtation rekindled, a shared willingness to try something new together. It can also describe news: a message from a fresh romantic prospect, an unexpected invitation, an idea that lights up the relationship.

The growth edge is letting yourself be a beginner. Many people who have been in love before resist the Page's energy because they think they should be past it — too sophisticated for crushes, too experienced for butterflies. The card disagrees. Practical guidance: follow the small flicker of curiosity even when you cannot yet see where it leads. Send the message that feels slightly silly to send. Ask the question that sounds naive. Try the date format you have never tried. Love this card describes does not yet know what it will become — and that uncertainty is exactly the point. Pages explore; verdicts come later.`,
    loveFaqs: [
      { q: 'What does the Page of Wands mean in love?', a: `The Page of Wands in love is the card of fresh enthusiasm and exploratory desire. Something new has caught your attention — a person, a chapter of attraction, a curiosity about a kind of love you have not yet tried. The card carries kindled fire and beginner's spirit: the willingness to be a learner in love rather than performing a role you have outgrown. It can also signal romantic news, an unexpected invitation, or a playful idea that lights up an existing relationship. Follow the flicker of curiosity.` },
      { q: 'What kind of partner does the Page of Wands represent?', a: `The Page of Wands as a partner represents someone enthusiastic, curious and full of fresh energy. They may be younger, younger-in-spirit, or simply newer to serious dating. They light up rooms, follow their interests with genuine excitement and bring a sense of play to the connection. The honest caveat is that Pages are still in the exploratory phase of life — they may not yet be ready for the depth or stability you want long-term. The connection can be wonderful in its season but ask itself harder questions later about whether you are at the same stage.` },
      { q: 'What does the Page of Wands mean for a new relationship?', a: `For a new relationship, the Page of Wands describes a chapter of playful discovery. There is genuine spark, but it is still finding its shape. Both of you are exploring: what do we like together, what makes us laugh, what kind of connection are we actually building? The card favours curiosity over premature definition. Resist the urge to lock things down too quickly. Try new things together, ask each other unguarded questions, let the relationship be allowed to surprise you. Pages reward people who treat the early days as an adventure rather than an audition.` },
      { q: 'What does the Page of Wands mean for dating?', a: `For dating, the Page of Wands invites you to bring fresh enthusiasm and beginner's curiosity back into the field. Approach apps and meetings with playfulness rather than weary calculation. Be willing to try new venues, new formats, new types of person who fall slightly outside your usual list. The card also often signals encouraging news — a message that surprises you, a match that turns into a real plan. Lean into the exploratory energy. Pages succeed in dating not by being polished but by being genuinely interested. Stay open; stay curious; let the field surprise you.` },
    ],
  },

  'knight-of-wands': {
    loveLong: `The Knight of Wands in love is the card of passionate pursuit. Someone is chasing — charismatic, magnetic, full of fire — and the energy is hard to ignore. Where the Page explores, the Knight commits to the charge. This is the partner who books the flight, sends the grand text, plans the spontaneous weekend, kisses you in the middle of the street because waiting another moment is unbearable. The card carries thrilling, restless fire. It is exhilarating to be on the receiving end of, and equally exhilarating to embody.

For singles, the Knight of Wands often heralds a whirlwind connection — someone who arrives quickly, courts boldly and makes their interest unmistakable. The dynamic favoured is mutual heat: two people willing to feel the pull and act on it rather than play it cool. For couples, the card can signal a chapter of renewed pursuit, where one or both partners remember to actively want each other rather than coast on familiarity. It can also point to travel, adventure or a shared project that reignites the fire between you.

The growth edge is consistency. Knights of Wands are famous for blazing in and burning out — passionate at the start, distractible later, sometimes vanishing when the next horizon catches their eye. Practical guidance: enjoy the heat, but watch for follow-through over time. Honest, sustained interest matters more than spectacular opening moves. If you are the Knight in this story, ask whether you are pursuing because you want this person or because you want the chase. If you are receiving the Knight, let yourself feel it fully, and then notice whether the substance grows or stays superficial as weeks pass. Fire that is real lasts past the first weekend.`,
    loveFaqs: [
      { q: 'What does the Knight of Wands mean in love?', a: `The Knight of Wands in love is the card of passionate pursuit. Someone is chasing — charismatic, magnetic, full of fire and unmistakable about their interest. The card carries thrilling, restless heat: spontaneous trips, bold declarations, the kiss that does not wait politely for permission. It can describe a whirlwind connection arriving in your life, a partner remembering to actively pursue you again, or your own willingness to court someone with full enthusiasm. The honest caveat is consistency — Knights are famous for blazing in, so watch for sustained follow-through.` },
      { q: 'What kind of partner does the Knight of Wands represent?', a: `The Knight of Wands as a partner represents someone passionate, adventurous, charming and bold. They pursue you openly, make you feel desired, and bring a sense of momentum and excitement to the connection. They are often charismatic in groups and confident in their own appetites. The shadow side is inconsistency: they can lose interest when novelty fades, get distracted by the next bright thing, or struggle to settle into routine intimacy. The relationship is thrilling but asks honest questions about whether the heat translates into reliability over time.` },
      { q: 'Does the Knight of Wands mean an ex coming back?', a: `It can — the Knight of Wands is one of the few Wands cards that sometimes describes an ex returning, particularly an ex who left in a hurry and may now be circling back with passionate energy. Expect bold gestures: a long message, an unexpected visit, a grand attempt to win you back. The card is honest about whether this is a good idea: Knights can be sincere but they can also repeat their patterns. If you are tempted, ask whether the substance has actually changed or only the volume of pursuit. Heat is not the same as growth.` },
      { q: 'Does the Knight of Wands mean physical attraction?', a: `Strongly, yes. The Knight of Wands is one of the most physically charged cards in the deck. It belongs to the suit of fire and describes desire that does not hide itself — eye contact, touch, sexual chemistry, the unmistakable feeling of being wanted. For singles it often points to a connection where the physical pull is immediate and powerful. For couples it can describe a chapter of renewed sexual heat after a stretch of routine. The card answers the question of attraction with a confident yes. Whether that attraction matures into something lasting is a separate, longer question.` },
    ],
  },

  'queen-of-wands': {
    loveLong: `The Queen of Wands in love is the card of magnetic, confident partnership. She is warm, vivacious, independent, sexy in a way that has nothing to do with effort. She does not need a relationship to feel whole, which is precisely why she attracts good ones. The card carries radiant fire — generous, grounded heat, the kind that draws people in without chasing them. When this Queen appears in love readings, she points either to a partner with these qualities or to the version of yourself that magnetises healthy love into your life.

For singles, the Queen of Wands often heralds a confident, charismatic woman entering your story — or invites you to embody those qualities yourself. The dynamic favoured here is self-possession. The card rewards people who have built genuinely full lives and choose partners as additions rather than rescues. For couples, the Queen can describe a partner who brings warmth, confidence and creative energy to the relationship, or a chapter where you reconnect with your own magnetism and remember what you bring to the partnership.

The growth edge is balancing fire with steadiness. Queen of Wands energy can tip into pride, jealousy or a need to be the brightest light in the room. Practical guidance: let the people you love also shine. Welcome their successes without competing with them. Share the warmth rather than monopolise it. Love this card describes is generous, sexually alive, and fiercely loyal when the loyalty is mutual. It rewards partners who can hold their own without trying to dim her — and equally, it asks her not to dim them. The fire here is most beautiful when it lights others up rather than burning alone.`,
    loveFaqs: [
      { q: 'What does the Queen of Wands mean in love?', a: `The Queen of Wands in love is the card of magnetic, confident partnership. She is warm, vivacious, independent and sexually alive — the partner who draws people in without chasing them. The card points either to such a person in your life or to the version of yourself that attracts healthy love. It favours self-possession over neediness, generosity over jealousy, and partnerships where both people maintain their own light. For couples it can describe a chapter of renewed confidence and creative energy in the relationship.` },
      { q: 'What kind of partner does the Queen of Wands represent?', a: `The Queen of Wands as a partner represents someone confident, warm, independent and magnetic. She is socially gifted, creatively alive, often the centre of a room without needing to be. In love she is generous and passionate when respected, but she will not shrink herself for anyone. She values partners who have their own light and who can match her confidence rather than feel threatened by it. The shadow side is occasional jealousy or pride. At her best, she is fiercely loyal, sexually alive, and one of the most rewarding partners in the deck.` },
      { q: 'Is the Queen of Wands a good love card?', a: `Yes — the Queen of Wands is a strongly favourable love card, particularly for people who value passion paired with independence. She points to magnetic partnership, sexual confidence, mutual respect and the kind of love that does not require either person to shrink. The card affirms relationships built between two whole lives rather than two halves seeking completion. For singles, she signals either an incoming partner with these qualities or an invitation to embody them yourself. The fire she carries is generous and warm rather than competitive when she is honoured properly.` },
      { q: 'Does the Queen of Wands mean physical attraction?', a: `Yes — the Queen of Wands is one of the most sexually confident cards in the tarot. She represents embodied magnetism: attraction that comes from how someone occupies their own skin rather than from performance. For singles she often points to a partner who is physically expressive and unashamed of desire. For couples she can describe a chapter of renewed sexual chemistry, often initiated by remembering your own attractiveness rather than waiting for it to be reflected back. The card answers questions about chemistry with a generous and confident yes.` },
    ],
  },

  'king-of-wands': {
    loveLong: `The King of Wands in love is the card of visionary, charismatic partnership. He is bold, generous, sexually confident and ambitious — the partner who knows what he wants, including you. The card carries commanding fire: not pursuit for its own sake, but the steady authority of someone who has built his life on purpose and is now choosing a partner with equal intention. When this King appears, he points either to a partner with these qualities or to the version of yourself that loves from a place of confident leadership.

For singles, the King of Wands often heralds a successful, charismatic partner entering the field — someone older or simply more established, who pursues clearly and commits openly when convinced. The dynamic favoured here is mutual ambition. The card rewards relationships where both people are building something larger than the partnership itself and bringing each other into that creative life. For couples, the King can describe a partner who provides strong, generous leadership in the relationship or a chapter of renewed direction and shared vision.

The growth edge is humility. King of Wands energy can tip into ego, controlling tendencies, or the assumption that his vision should automatically be everyone else's. Practical guidance: lead with influence rather than dominance. Listen to your partner's vision as carefully as you expect them to listen to yours. Be generous with credit. Love this card describes is magnificent when the King remembers that real authority is earned through service to the people he loves, not asserted over them. Romantic partnerships under this card can be powerful, creative and deeply expansive — provided neither partner is reduced to a supporting role in the other's life.`,
    loveFaqs: [
      { q: 'What does the King of Wands mean in love?', a: `The King of Wands in love is the card of visionary, charismatic partnership. He is bold, generous, sexually confident and ambitious — the partner who knows what he wants and is willing to commit when he has chosen. The card points either to such a person in your life or to the version of yourself that loves from confident leadership. It favours mutual ambition, shared vision and partnerships where both people are building larger lives together. The growth edge is humility: leading with influence rather than ego, and welcoming a partner's vision as fully as your own.` },
      { q: 'What kind of partner does the King of Wands represent?', a: `The King of Wands as a partner represents someone successful, charismatic, generous and direct. He often has built a substantial life already — career, creative work, public role — and is now ready to choose a partner with equal intention. He commits openly when convinced, leads with warmth, and is sexually confident. The shadow side is occasional ego, control or impatience with anyone who challenges his vision. At his best he is an inspiring, generous partner who brings his whole life to the relationship rather than fragments. He needs a partner who can hold their own.` },
      { q: 'Is the King of Wands a good love card?', a: `Yes — the King of Wands is a strong love card, particularly for people seeking committed, ambitious partnership. He brings clarity of intention, sexual confidence and a willingness to commit publicly. The card favours relationships built on shared vision and mutual respect, where both partners contribute to a life larger than the romance itself. The caveat is the King's occasional ego: the partnership thrives when both people lead and listen, and struggles when one tries to dominate the other. Treated as equals, this is one of the most rewarding cards in a love reading.` },
      { q: 'What does the King of Wands say about how someone feels about me?', a: `If you are asking about another person's feelings, the King of Wands suggests they hold you in genuine high regard and are likely considering serious commitment. Their feelings are not hesitant or shy. This is someone who, once decided, communicates clearly, pursues openly and is willing to make the relationship visible to their wider life. The card describes confidence and intention rather than vague interest. If they have been moving slowly, it is more often because they are deliberate by nature than because they are unsure. When the King of Wands chooses, he tends to choose decisively.` },
    ],
  },
}
